### ISSUE TITLE
intellij idea right click popup menu window looses focus and dissapears

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#1436]
*Issue migrated from trac ticket # 1436*

**component:** client | **priority:** major | **resolution:** needinfo

#### 2017-02-13 13:44:34: pawelpanasewicz created the issue

___
> Right click in Intellij Idea (java awt application) should show menu popup window.
> 
> It doesn't work when running this program in server (ubuntu in docker) and displaying it in client (windows 10). Popup window immediately disappears.
> 
> 
> == How do I run program:
> 
> 1. In Server:
> 
> ```
> docker@7568603c3dc7:/devstation/idea-IU-163.12024.16$ xpra start :10
> docker@7568603c3dc7:/devstation/idea-IU-163.12024.16$ Entering daemon mode; any further errors will be reported to:
>   /home/docker/.xpra/:10.log
> 
> docker@7568603c3dc7:/devstation/idea-IU-163.12024.16$ cd bin/
> docker@7568603c3dc7:/devstation/idea-IU-163.12024.16/bin$ DISPLAY=:10 ./idea.sh
> Xlib:  extension "RANDR" missing on display ":10".
> ...
> ```
> 
> Content of  /home/docker/.xpra/:10.log 
> ```
> _XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root                                                                                                                            
> Initializing built-in extension Generic Event Extension                                                                                                                                    
> Initializing built-in extension SHAPE                                                                                                                                                      
> Initializing built-in extension MIT-SHM                                                                                                                                                    
> Initializing built-in extension XInputExtension                                                                                                                                            
> Initializing built-in extension XTEST                                                                                                                                                      
> Initializing built-in extension BIG-REQUESTS                                                                                                                                               
> Initializing built-in extension SYNC                                                                                                                                                       
> Initializing built-in extension XKEYBOARD                                                                                                                                                  
> Initializing built-in extension XC-MISC                                                                                                                                                    
> Initializing built-in extension SECURITY                                                                                                                                                   
> Initializing built-in extension XINERAMA                                                                                                                                                   
> Initializing built-in extension XFIXES                                                                                                                                                     
> Initializing built-in extension RENDER                                                                                                                                                     
> Initializing built-in extension RANDR                                                                                                                                                      
> Initializing built-in extension COMPOSITE                                                                                                                                                  
> Initializing built-in extension DAMAGE                                                                                                                                                     
> Initializing built-in extension MIT-SCREEN-SAVER                                                                                                                                           
> Initializing built-in extension DOUBLE-BUFFER                                                                                                                                              
> Initializing built-in extension RECORD                                                                                                                                                     
> Initializing built-in extension DPMS                                                                                                                                                       
> Initializing built-in extension Present                                                                                                                                                    
> Initializing built-in extension DRI3                                                                                                                                                       
> Initializing built-in extension X-Resource                                                                                                                                                 
> Initializing built-in extension XVideo                                                                                                                                                     
> Initializing built-in extension XVideo-MotionCompensation                                                                                                                                  
> Initializing built-in extension SELinux                                                                                                                                                    
> Initializing built-in extension GLX                                                                                                                                                        
> [dix] Could not init font path element /usr/share/fonts/X11/cyrillic, removing from list!                                                                                                  
> [dix] Could not init font path element /usr/share/fonts/X11/100dpi/:unscaled, removing from list!                                                                                          
> [dix] Could not init font path element /usr/share/fonts/X11/75dpi/:unscaled, removing from list!                                                                                           
> [dix] Could not init font path element /usr/share/fonts/X11/Type1, removing from list!                                                                                                     
> [dix] Could not init font path element /usr/share/fonts/X11/100dpi, removing from list!                                                                                                    
> [dix] Could not init font path element /usr/share/fonts/X11/75dpi, removing from list!                                                                                                     
> Xlib:  extension "RANDR" missing on display ":10".                                                                                                                                         
> Xlib:  extension "RANDR" missing on display ":10".                                                                                                                                         
> 2017-02-13 14:28:09,166 created unix domain socket: /home/docker/.xpra/7568603c3dc7-10ESC[0m                                                                                               
> ESC[33m2017-02-13 14:28:09,167 Warning: failed to create socket directory '/var/run/xpra'ESC[0m                                                                                            
> ESC[33m2017-02-13 14:28:09,167  [Errno 13] Permission denied: '/var/run/xpra'ESC[0m                                                                                                        
> ESC[33m2017-02-13 14:28:09,167 Warning: cannot create socket '/var/run/xpra/7568603c3dc7-10'ESC[0m                                                                                         
> ESC[33m2017-02-13 14:28:09,167  [Errno 2] No such file or directoryESC[0m                                                                                                                  
> ESC[33m2017-02-13 14:28:09,167  /var/run/xpra does not existESC[0m                                                                                                                         
> ESC[33m2017-02-13 14:28:09,167  user 'docker' is a member of groups: sudoESC[0m                                                                                                            
> ESC[33m2017-02-13 14:28:09,167   (missing 'xpra' group membership?)ESC[0m                                                                                                                  
> /bin/sh: 1: dbus-launch: not found                                                                                                                                                         
> dbus-launch failed to start using command 'dbus-launch --close-stderr':                                                                                                                    
>  exit code is 127                                                                                                                                                                          
> ESC[33m2017-02-13 14:28:10,386 Warning: menu forwarding is disabled:ESC[0m                                                                                                                 
> ESC[33m2017-02-13 14:28:10,386  cannot load dbus helper: org.freedesktop.DBus.Error.Spawn.ExecFailed: //bin/dbus-launch terminated abnormally without any error messageESC[0m              
> ESC[33m2017-02-13 14:28:10,615 Warning: libvpx ABI version 5 is too old:ESC[0m                                                                                                             
> ESC[33m2017-02-13 14:28:10,615  disabling YUV444P support with VP9ESC[0m                                                                                                                   
> ESC[33m2017-02-13 14:28:11,750 Warning: failed to load the mdns avahi publisher:ESC[0m                                                                                                     
> ESC[33m2017-02-13 14:28:11,750  No module named avahiESC[0m                                                                                                                                
> ESC[33m2017-02-13 14:28:11,750  either fix your installation or use the 'mdns=no' optionESC[0m                                                                                             
> ESC[33m2017-02-13 14:28:11,756 Warning: no X11 RandR support on :10ESC[0m                                                                                                                  
> ESC[33m2017-02-13 14:28:12,770 Warning: webcam forwarding is disabledESC[0m                                                                                                                
> ESC[33m2017-02-13 14:28:12,770  the virtual video directory '/sys/devices/virtual/video4linux' was not foundESC[0m                                                                         
> ESC[33m2017-02-13 14:28:12,770  make sure that the 'v4l2loopback' kernel module is installed and loadedESC[0m                                                                              
> 2017-02-13 14:28:12,770 found 0 virtual video devices for webcam forwardingESC[0m                                                                                                          
> 2017-02-13 14:28:12,930 pulseaudio server started with pid 152ESC[0m                                                                                                                       
> /bin/sh: 1: pulseaudio: not found
> Warning: failed to import GStreamer:
>  GStreamer 1.0: Namespace Gst not available
>  GStreamer 0.10: No module named pygst
> ESC[31m2017-02-13 14:28:13,393 Error: failed to query sound subsystem:ESC[0m
> ESC[31m2017-02-13 14:28:13,393  query did not return any dataESC[0m
> ESC[33m2017-02-13 14:28:13,400 Warning: failed to load or register our dbus notifications forwarder:ESC[0m
> ESC[33m2017-02-13 14:28:13,400  org.freedesktop.DBus.Error.Spawn.ExecFailed: //bin/dbus-launch terminated abnormally without any error messageESC[0m
> ESC[33m2017-02-13 14:28:13,400  if you do not have a dedicated dbus session for this xpra instance,ESC[0m
> ESC[33m2017-02-13 14:28:13,400  use the 'notifications=no' optionESC[0m
> ESC[33m2017-02-13 14:28:13,403 Warning: cannot load dbus helper:ESC[0m
> ESC[33m2017-02-13 14:28:13,403  org.freedesktop.DBus.Error.Spawn.ExecFailed: //bin/dbus-launch terminated abnormally without any error messageESC[0m
> ESC[31m2017-02-13 14:28:13,410 dbus server error
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/xpra/server/dbus/dbus_common.py", line 12, in dbus_exception_wrap
>     v = fn()
>   File "/usr/lib/python2.7/dist-packages/xpra/x11/server.py", line 1350, in make_dbus_server
>     return X11_DBUS_Server(self, os.environ.get("DISPLAY", "").lstrip(":"))
>   File "/usr/lib/python2.7/dist-packages/xpra/server/dbus/dbus_server.py", line 38, in __init__
>     session_bus = init_session_bus()
>   File "/usr/lib/python2.7/dist-packages/xpra/dbus/common.py", line 22, in init_session_bus
>     _session_bus = dbus.SessionBus(private=private)
>   File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 211, in __new__
>     mainloop=mainloop)
>   File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 100, in __new__
>     bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
>   File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 122, in __new__
>     bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
> DBusException: org.freedesktop.DBus.Error.Spawn.ExecFailed: //bin/dbus-launch terminated abnormally without any error messageESC[0m
> ESC[31m2017-02-13 14:28:13,413 Error setting up server dbus instance:ESC[0m
> ESC[31m2017-02-13 14:28:13,413   org.freedesktop.DBus.Error.Spawn.ExecFailedESC[0m
> ESC[31m2017-02-13 14:28:13,413   //bin/dbus-launch terminated abnormally without any error messageESC[0m
> 2017-02-13 14:28:13,416 xpra X11 version 1.0.2-[r14944](../commit/e3fb0bf5bd982c486f988040abb4b63ad63c536d) 64-bitESC[0m
> 2017-02-13 14:28:13,416  uid=1000 (docker), gid=1000 (docker)ESC[0m
> 2017-02-13 14:28:13,416  running with pid 101 on Linux Ubuntu 14.04 trustyESC[0m
> 2017-02-13 14:28:13,416  connected to X11 display :10ESC[0m
> 2017-02-13 14:28:13,487 xpra is ready.ESC[0m
> ESC[33m2017-02-13 14:28:13,683 Warning: lpinfo command failed and returned 1ESC[0m
> ESC[33m2017-02-13 14:28:13,683  command used: '/usr/sbin/lpinfo --make-and-model Generic PDF Printer -m'ESC[0m
> ESC[33m2017-02-13 14:28:13,844 Warning: lpinfo command failed and returned 1ESC[0m
> ESC[33m2017-02-13 14:28:13,844  command used: '/usr/sbin/lpinfo --make-and-model Generic PostScript Printer -m'ESC[0m
> 2017-02-13 14:28:13,845 printer forwarding enabled using postscript and pdfESC[0m
> 2017-02-13 14:28:13,845 7.8GB of system memoryESC[0m
> ESC[33m2017-02-13 14:28:14,417 Warning: pulseaudio has terminated shortly after startup.ESC[0m
> ESC[33m2017-02-13 14:28:14,417  pulseaudio is limited to a single instance per user account,ESC[0m
> ESC[33m2017-02-13 14:28:14,418  and one may be running already for user 'docker'ESC[0m
> ESC[33m2017-02-13 14:28:14,418  to avoid this warning, either fix the pulseaudio command lineESC[0m
> ESC[33m2017-02-13 14:28:14,418  or use the 'pulseaudio=no' optionESC[0m
> 2017-02-13 14:31:37,817 New unix-domain connection received on /home/docker/.xpra/7568603c3dc7-10ESC[0m
> 2017-02-13 14:31:37,819 New unix-domain connection received on /home/docker/.xpra/7568603c3dc7-10ESC[0m
> 2017-02-13 14:31:37,821 Handshake complete; enabling connectionESC[0m
> ESC[33m2017-02-13 14:31:37,871 Warning: xxhash python bindings not foundESC[0m
> ESC[33m2017-02-13 14:31:37,872  no scrolling detectionESC[0m
> ESC[31m2017-02-13 14:31:37,878 dbus server error
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/xpra/server/dbus/dbus_common.py", line 12, in dbus_exception_wrap
>     v = fn()
>   File "/usr/lib/python2.7/dist-packages/xpra/server/source.py", line 356, in make_dbus_server
>     return DBUS_Source(self, os.environ.get("DISPLAY", "").lstrip(":"))
>   File "/usr/lib/python2.7/dist-packages/xpra/server/dbus/dbus_source.py", line 36, in __init__
>     session_bus = init_session_bus()
>   File "/usr/lib/python2.7/dist-packages/xpra/dbus/common.py", line 22, in init_session_bus
>     _session_bus = dbus.SessionBus(private=private)
>   File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 211, in __new__
>     mainloop=mainloop)
>   File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 100, in __new__
>     bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
>   File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 122, in __new__
>     bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
> DBusException: org.freedesktop.DBus.Error.Spawn.ExecFailed: //bin/dbus-launch terminated abnormally without any error messageESC[0m
> ESC[31m2017-02-13 14:31:37,880 Error setting up client dbus instance:ESC[0m
> ESC[31m2017-02-13 14:31:37,880   org.freedesktop.DBus.Error.Spawn.ExecFailedESC[0m
> ESC[31m2017-02-13 14:31:37,880   //bin/dbus-launch terminated abnormally without any error messageESC[0m
> 2017-02-13 14:31:37,881 Python/Gtk2 Microsoft Windows 10 aero client version 1.0.2-14941 32-bitESC[0m
> 2017-02-13 14:31:37,881  connected from 'Lenovoid' as 'docker' - 'W541'ESC[0m
> 2017-02-13 14:31:37,882  automatic picture encoding enabledESC[0m
> 2017-02-13 14:31:37,882  also available:ESC[0m
> 2017-02-13 14:31:37,882   h264, vp9, vp8, png, png/P, png/L, rgb24, jpeg, rgb32ESC[0m
> 2017-02-13 14:31:37,891  client root window size is 3840x1526 with 1 display:ESC[0m
> 2017-02-13 14:31:37,891   Default (1016x403 mm - DPI: 96x96) workarea: 3840x1486ESC[0m
> 2017-02-13 14:31:37,891     DISPLAY2 1920x1200 at 1920x0 (550x343 mm - DPI: 88x88) workarea: 1920x1160ESC[0m
> 2017-02-13 14:31:37,891     DISPLAY1 1920x1080 at 0x446 (344x193 mm - DPI: 141x142) workarea: 1920x1040ESC[0m
> 2017-02-13 14:31:37,926 setting key repeat rate from client: 500ms delay / 33ms intervalESC[0m
> 2017-02-13 14:31:37,927 setting keyboard layout to 'gb'ESC[0m
> 2017-02-13 14:31:37,972 client 1: Attached to ssh:docker@127.0.0.1:10 (press Control-C to detach)ESC[0m
> ESC[33m2017-02-13 14:31:38,028 python netifaces package is missingESC[0m
> lpadmin: Unable to connect to server: Bad file descriptor
> ESC[33m2017-02-13 14:31:39,151 lpadmin failed and returned error code: 1ESC[0m
> ESC[33m2017-02-13 14:31:39,152  verify that user 'docker' has all the required permissionsESC[0m
> ESC[33m2017-02-13 14:31:39,152  for running: '/usr/sbin/lpadmin'ESC[0m
> ESC[33m2017-02-13 14:31:39,152  full command: '/usr/sbin/lpadmin' '-p' 'EPSON-AL-C1750W' '-v' 'xpraforwarder:/tmp?mimetype=application%2Fpdf&socket-path=%2Fhome%2Fdocker%2F.xpra%2F7568603c3dc7-10&remote-printer=EPSON+AL-C1750W&remote-device-uri=None&source=7cfe6a4639eceb031341311bf3f718b747295acd&display=%3A10' '-D' 'EPSON AL-C1750W' '-L' 'on Lenovoid (via xpra)' '-E' '-o' 'printer-is-shared=false' '-u' 'allow:docker' '-P' '/usr/share/ppd/cupsfilters/Generic-PDF_Printer-PDF.ppd'ESC[0m
> lpadmin: Unable to connect to server: Bad file descriptor
> ESC[33m2017-02-13 14:31:39,324 lpadmin failed and returned error code: 1ESC[0m
> ESC[33m2017-02-13 14:31:39,324  verify that user 'docker' has all the required permissionsESC[0m
> ESC[33m2017-02-13 14:31:39,325  for running: '/usr/sbin/lpadmin'ESC[0m
> ESC[33m2017-02-13 14:31:39,325  full command: '/usr/sbin/lpadmin' '-p' 'Microsoft-Print-to-PDF' '-v' 'xpraforwarder:/tmp?mimetype=application%2Fpdf&socket-path=%2Fhome%2Fdocker%2F.xpra%2F7568603c3dc7-10&remote-printer=Microsoft+Print+to+PDF&remote-device-uri=None&source=7cfe6a4639eceb031341311bf3f718b747295acd&display=%3A10' '-D' 'Microsoft Print to PDF,Microsoft Print To PDF' '-L' 'on Lenovoid (via xpra)' '-E' '-o' 'printer-is-shared=false' '-u' 'allow:docker' '-P' '/usr/share/ppd/cupsfilters/Generic-PDF_Printer-PDF.ppd'ESC[0m
> ESC[33m2017-02-13 14:35:47,098 clipboard disabled: more than 20 clipboard requests per second!ESC[0m
> 2017-02-13 14:35:47,106 client 1: clipboard toggled to off by the server, reason given:ESC[0m
> 2017-02-13 14:35:47,107 client 1:  more than 20 clipboard requests per second!ESC[0m
> ```
> 
> 
> 2. In Client:
> ```
> Xpra_cmd attach ssh:docker@127.0.0.1:10                                                                                                                                                                                            ~
> 2017-02-13 13:31:10,818 Xpra gtk2 client version 1.0.2-14941 32-bit
> 2017-02-13 13:31:10,822  running on Microsoft Windows 10
> 2017-02-13 13:31:11,528 GStreamer version 1.10.2 for Python 3.4.4 32-bit
> 2017-02-13 13:31:13,355 OpenGL_accelerate module loaded
> 2017-02-13 13:31:13,361 OpenGL enabled with Quadro K1100M/PCIe/SSE2
> 2017-02-13 13:31:13,430  keyboard settings: layout=gb
> 2017-02-13 13:31:13,430  desktop size is 3840x1526 with 1 screen:
> 2017-02-13 13:31:13,431   Default (1016x403 mm - DPI: 96x96) workarea: 3840x1486
> 2017-02-13 13:31:13,431     DISPLAY2 1920x1200 at 1920x0 (550x343 mm - DPI: 88x88) workarea: 1920x1160
> 2017-02-13 13:31:13,431     DISPLAY1 1920x1080 at 0x446 (344x193 mm - DPI: 141x142) workarea: 1920x1040
> 2017-02-13 13:31:13,549 keyboard layouts: pl,gb
> 2017-02-13 13:31:39,221 Xpra X11 server version 1.0.2-[r14944](../commit/e3fb0bf5bd982c486f988040abb4b63ad63c536d) 64-bit
> 2017-02-13 13:31:39,221  running on Linux Ubuntu 14.04 trusty
> 2017-02-13 13:31:39,223 enabled remote logging
> 2017-02-13 13:31:39,229 Attached to ssh:docker@127.0.0.1:10 (press Control-C to detach)
> 
> D:\devstation-workspace\bin\Xpra_1.0.2-14941\library.zip\xpra\gtk_common\gtk_util.py:383: GtkWarning: inner_clipboard_window_procedure: assertion `success' failed
> 
> ...
> ```
> 
> 
> 
> == Server details
> 
> This is linux which is run inside docker. Docker runs on windows 10 host - the same OS as client described below.
> 
> ```
> $ xpra --version
> xpra v1.0.2-[r14944](../commit/e3fb0bf5bd982c486f988040abb4b63ad63c536d)
> ```
> 
> ```
> $ uname -a
> Linux 7568603c3dc7 4.9.8-moby #1 SMP Wed Feb 8 09:56:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
> ```
> 
> ```
> xpra showconfig
> Warning: lpinfo command failed and returned 1
>  command used: 'lpinfo --make-and-model Generic PDF Printer -m'
> Warning: lpinfo command failed and returned 1
>  command used: 'lpinfo --make-and-model Generic PostScript Printer -m'
> add-printer-options            = '-E', '-o printer-is-shared=false', '-u allow:$USER'
> auth                           = ''
> auto-refresh-delay             = 0.15
> av-sync                        = True
> bell                           = True
> bind                           = 'auto'
> bind-ssl                       = []
> bind-tcp                       = []
> bind-vsock                     = []
> border                         = 'auto,5:off'
> clipboard                      = 'yes'
> clipboard-direction            = 'both'
> clipboard-filter-file           = ''
> compression_level              = 1
> compressors                    = 'lz4', 'lzo', 'zlib'
> csc-modules                    = 'swscale', 'cython'
> cursors                        = True
> daemon                         = True
> dbus-control                   = True
> dbus-launch                    = 'dbus-launch --close-stderr'
> dbus-proxy                     = True
> debug                          = ''
> delay-tray                     = False
> desktop-fullscreen             = False
> desktop-scaling                = 'auto'
> display                        = ''
> download-path                  = '~'
> dpi                            = 0
> encoding                       = ''
> encodings                      = 'h264', 'vp9', 'vp8', 'mpeg4', 'mpeg4+mp4', 'h264+mp4', 'mpeg4+mp4', 'vp8+webm', 'vp9+webm', 'png', 'png/P', 'png/L', 'webp', 'rgb', 'rgb24', 'rgb32', 'jpeg', 'h265'
> encryption                     = ''
> encryption-keyfile             = ''
> env                            = []
> exec-wrapper                   = ''
> exit-ssh                       = True
> exit-with-children             = False
> exit-with-client               = False
> fake-xinerama                  = True
> file-size-limit                = 100
> file-transfer                  = True
> global-menus                   = True
> html                           = 'auto'
> idle-timeout                   = 0
> input-method                   = 'none'
> key-shortcut                   = 'Control+Menu:toggle_keyboard_grab', 'Shift+Menu:toggle_pointer_grab', 'Meta+Shift+F1:show_menu', 'Meta+Shift+F2:show_start_new_command', 'Meta+Shift+F3:show_bug_report', 'Meta+Shift+F4:quit', 'Meta+Shift+F5:increase_quality', 'Meta+Shift+F6:decrease_quality', 'Meta+Shift+F7:increase_speed', 'Meta+Shift+F8:decrease_speed', 'Meta+Shift+F10:magic_key', 'Meta+Shift+F11:show_session_info', 'Meta+Shift+F12:toggle_debug', 'Meta+Shift+plus:scaleup', 'Meta+Shift+minus:scaledown', 'Meta+Shift+underscore:scaledown', 'Meta+Shift+KP_Add:scaleup', 'Meta+Shift+KP_Subtract:scaledown', 'Meta+Shift+KP_Multiply:scalereset', 'Meta+Shift+bar:scalereset', 'Meta+Shift+question:scalingoff'
> keyboard-layout                = ''
> keyboard-layouts               = []
> keyboard-options               = ''
> keyboard-raw                   = False
> keyboard-sync                  = True
> keyboard-variant               = ''
> keyboard-variants              = []
> local-clipboard                = 'CLIPBOARD'
> log-dir                        = 'auto'
> log-file                       = '$DISPLAY.log'
> lpadmin                        = '/usr/sbin/lpadmin'
> lpinfo                         = '/usr/sbin/lpinfo'
> max-size                       = ''
> mdns                           = True
> microphone                     = 'off'
> microphone-codec               = []
> min-quality                    = 30
> min-speed                      = 30
> mmap                           = 'yes'
> mmap-group                     = False
> notifications                  = True
> open-command                   = 'xdg-open'
> open-files                     = False
> opengl                         = None
> packet-encoders                = 'rencode', 'bencode', 'yaml'
> password                       = ''
> password-file                  = ''
> pdf-printer           (used)   = ''                                <type 'str'>
> pdf-printer          (default) = '/usr/share/ppd/cupsfilters/Generic-PDF_Printer-PDF.ppd'  <type 'str'>
> pidfile                        = ''
> pings                          = False
> postscript-printer    (used)   = ''                                <type 'str'>
> postscript-printer   (default) = '/usr/share/ppd/cups-pdf/CUPS-PDF.ppd'  <type 'str'>
> printing                       = True
> proxy-start-sessions           = True
> proxy-video-encoders           = []
> pulseaudio                     = True
> pulseaudio-command             = 'pulseaudio --start -n --daemonize=false --system=false --exit-idle-time=-1 --load=module-suspend-on-idle '--load=module-null-sink sink_name="Xpra-Speaker" sink_properties=device.description="Xpra\ Speaker"' '--load=module-null-sink sink_name="Xpra-Microphone" sink_properties=device.description="Xpra\ Microphone"' --load=module-native-protocol-unix --load=module-dbus-protocol --log-level=2 --log-target=stderr'
> pulseaudio-configure-commands           = 'pactl set-default-sink Xpra-Speaker', 'pactl set-default-source Xpra-Microphone.monitor'
> quality                        = 0
> readonly                       = False
> remote-clipboard               = 'CLIPBOARD'
> remote-logging                 = 'both'
> remote-xpra                    = '~/.xpra/run-xpra', '$XDG_RUNTIME_DIR/xpra/run-xpra', 'xpra'
> resize_display                 = True
> server-idle-timeout            = 0
> session-name                   = ''
> sharing                        = False
> socket-dir                     = ''
> socket-dirs                    = '~/.xpra', '/var/run/xpra'
> socket-permissions             = '600'
> sound-source                   = ''
> speaker                        = 'on'
> speaker-codec                  = []
> speed                          = 0
> ssh                            = 'ssh -x'
> ssl                            = 'auto'
> ssl-auth                       = ''
> ssl-ca-certs                   = 'default'
> ssl-ca-data                    = ''
> ssl-cert                       = ''
> ssl-check-hostname             = False
> ssl-ciphers                    = 'DEFAULT'
> ssl-client-verify-mode           = 'optional'
> ssl-key                        = ''
> ssl-options                    = 'ALL,NO_COMPRESSION'
> ssl-protocol                   = 'SSLv23'
> ssl-server-hostname            = 'localhost'
> ssl-server-verify-mode           = 'required'
> ssl-verify-flags               = 'X509_STRICT'
> start                          = []
> start-after-connect            = []
> start-child                    = []
> start-child-after-connect           = []
> start-child-on-connect           = []
> start-env                      = '#avoid Ubuntu's global menu, which is a mess and cannot be forwarded:', 'UBUNTU_MENUPROXY=', 'QT_X11_NO_NATIVE_MENUBAR=1', '#fix for MainSoft's MainWin buggy window management:', 'MWNOCAPTURE=true', 'MWNO_RIT=true', 'MWWM=allwm', '#force GTK3 applications to use X11 so we can intercept them:', 'GDK_BACKEND=x11'
> start-new-commands             = False
> start-on-connect               = []
> sync-xvfb                      = 0
> system-tray                    = True
> systemd-run                    = 'auto'
> systemd-run-args               = ''
> tcp-auth                       = ''
> tcp-encryption                 = ''
> tcp-encryption-keyfile           = ''
> tcp-proxy                      = ''
> title                          = '@title@ on @client-machine@'
> tray                           = True
> tray-icon                      = ''
> use-display                    = False
> username                       = 'docker'
> video-decoders                 = 'avcodec2', 'vpx'
> video-encoders                 = 'x264', 'vpx', 'nvenc', 'ffmpeg'
> video-scaling                  = 1
> vsock-auth                     = ''
> webcam                         = 'auto'
> window-close                   = 'auto'
> window-icon                    = ''
> windows                        = True
> wm-name                        = 'Xpra'
> xsettings                      = True
> xvfb                           = 'Xvfb +extension Composite -screen 0 5760x2560x24+32 -dpi 96 -nolisten tcp -noreset -auth $XAUTHORITY'
> ```
> 
> 
> == Client details
> 
> Windows 10, running docker
> 
> ``` 
> > xpra_cmd --version
> xpra v1.0.2-14941
> ```
> 
> ```
> > xpra_cmd showconfig                                                                                                                                            /cygdrive/d/devstation-workspace/projects/docker-uczesie
> add-printer-options            = '-E', '-o printer-is-shared=false', '-u allow:$USER'
> auth                           = ''
> auto-refresh-delay             = 0.15
> av-sync                        = True
> bell                           = True
> bind                           = 'Main'
> bind-ssl                       = []
> bind-tcp                       = []
> bind-vsock                     = []
> border                         = 'auto,5:off'
> clipboard                      = 'yes'
> clipboard-direction            = 'both'
> clipboard-filter-file           = ''
> compression_level              = 1
> compressors                    = 'lz4', 'lzo', 'zlib'
> csc-modules                    = 'swscale', 'cython', 'libyuv', 'opencv'
> cursors                        = True
> dbus-control                   = False
> dbus-launch                    = 'dbus-launch --close-stderr'
> debug                          = ''
> delay-tray                     = False
> desktop-fullscreen             = False
> desktop-scaling                = 'auto'
> display                        = ''
> download-path                  = 'C:\Users\W541\Downloads'
> dpi                            = 0
> encoding                       = ''
> encodings                      = 'h264', 'vp9', 'vp8', 'mpeg4', 'mpeg4+mp4', 'h264+mp4', 'mpeg4+mp4', 'vp8+webm', 'vp9+webm', 'png', 'png/P', 'png/L', 'webp', 'rgb', 'rgb24', 'rgb32', 'jpeg', 'h265'
> encryption                     = ''
> encryption-keyfile             = ''
> env                            = []
> exec-wrapper                   = ''
> exit-ssh                       = True
> exit-with-client               = False
> file-size-limit                = 100
> file-transfer                  = True
> global-menus                   = True
> html                           = 'auto'
> idle-timeout                   = 0
> key-shortcut                   = 'Control+Menu:toggle_keyboard_grab', 'Shift+Menu:toggle_pointer_grab', 'Meta+Shift+F1:show_menu', 'Meta+Shift+F2:show_start_new_command', 'Meta+Shift+F3:show_bug_report', 'Meta+Shift+F4:quit', 'Meta+Shift+F5:increase_quality', 'Meta+Shift+F6:decrease_quality', 'Meta+Shift+F7:increase_speed', 'Meta+Shift+F8:decrease_speed', 'Meta+Shift+F10:magic_key', 'Meta+Shift+F11:show_session_info', 'Meta+Shift+F12:toggle_debug', 'Meta+Shift+plus:scaleup', 'Meta+Shift+minus:scaledown', 'Meta+Shift+underscore:scaledown', 'Meta+Shift+KP_Add:scaleup', 'Meta+Shift+KP_Subtract:scaledown', 'Meta+Shift+KP_Multiply:scalereset', 'Meta+Shift+bar:scalereset', 'Meta+Shift+question:scalingoff'
> keyboard-layout                = ''
> keyboard-layouts               = []
> keyboard-options               = ''
> keyboard-raw                   = False
> keyboard-sync                  = True
> keyboard-variant               = ''
> keyboard-variants              = []
> local-clipboard                = 'CLIPBOARD'
> log-dir                        = 'auto'
> log-file                       = '$DISPLAY.log'
> lpinfo                         = '/usr/sbin/lpinfo'
> max-size                       = ''
> microphone                     = 'off'
> microphone-codec               = []
> min-quality                    = 30
> min-speed                      = 30
> mmap                           = 'no'
> notifications                  = True
> open-command                   = 'xdg-open'
> open-files                     = False
> opengl                         = None
> packet-encoders                = 'rencode', 'bencode', 'yaml'
> password                       = ''
> password-file                  = ''
> pdf-printer                    = ''
> pidfile                        = ''
> pings                          = False
> postscript-printer    (used)   = ''                                <type 'str'>
> postscript-printer   (default) = 'drv:///sample.drv/generic.ppd'   <type 'str'>
> printing                       = True
> proxy-start-sessions           = True
> proxy-video-encoders           = []
> pulseaudio-configure-commands           = []
> quality                        = 0
> readonly                       = False
> remote-clipboard               = 'CLIPBOARD'
> remote-logging                 = 'both'
> remote-xpra                    = '~/.xpra/run-xpra', '$XDG_RUNTIME_DIR/xpra/run-xpra', 'xpra'
> resize_display                 = False
> server-idle-timeout            = 0
> session-name                   = ''
> sharing                        = False
> sound-source                   = ''
> speaker                        = 'on'
> speaker-codec                  = []
> speed                          = 0
> ssh                            = 'plink -ssh -agent'
> ssl                            = 'auto'
> ssl-auth                       = ''
> ssl-ca-certs                   = 'default'
> ssl-ca-data                    = ''
> ssl-cert                       = ''
> ssl-check-hostname             = False
> ssl-ciphers                    = 'DEFAULT'
> ssl-client-verify-mode           = 'optional'
> ssl-key                        = ''
> ssl-options                    = 'ALL,NO_COMPRESSION'
> ssl-protocol                   = 'TLSv1_2'
> ssl-server-hostname            = 'localhost'
> ssl-server-verify-mode           = 'required'
> ssl-verify-flags               = 'X509_STRICT'
> start-after-connect            = []
> start-child-after-connect           = []
> start-child-on-connect           = []
> start-env                      = []
> start-on-connect               = []
> sync-xvfb                      = 0
> system-tray                    = True
> systemd-run           (used)   = 'no'                              <type 'str'>
> systemd-run          (default) = 'auto'                            <type 'str'>
> systemd-run-args               = ''
> tcp-auth                       = ''
> tcp-encryption                 = ''
> tcp-encryption-keyfile           = ''
> tcp-proxy                      = ''
> title                          = '@title@ on @client-machine@'
> tray                           = True
> tray-icon                      = ''
> username                       = 'W541'
> video-decoders                 = 'avcodec2', 'vpx'
> video-encoders                 = 'x264', 'vpx'
> video-scaling                  = 1
> vsock-auth                     = ''
> webcam                         = 'auto'
> window-close                   = 'auto'
> window-icon                    = ''
> windows                        = True
> 
> ```

**Comment by totaam** [comment]
> As can be seen on this screenshot: [/ticket/1436/ubuntu-firefox-popup.jpeg], I have followed your instructions (just running the docker container on Linux instead) and then connected from a Windows XP test system. I've also tested the same connection without any issues from a windows 7, windows 10 and Linux client.
> I have used the latest 1.0.x clients and I've also tried the 2.0 [beta](http://xpra.org/beta) builds.
 
Whatever you're doing, there must be something different.
Popup menus going missing is something that has happened before, but I am very confident that if it was still happening right now with an application like Firefox, others would have complained by now.

Please make sure that you can reproduce with a clean install of MS Windows (preferably win7) with the latest stable xpra release.

----


Some notes:
* do not start firefox using `DISPLAY=:10 firefox`, use `xpra start --start=firefox` instead
* "--windows" is the default, not needed
* FYI: you can specify your ssh password in the xpra command line, like so: `xpra attach ssh/devbox:asdf@UBUNTUIP:SSHPORT/` (and append DISPLAY to this string only if you run multiple instances)

**Comment by totaam** [comment]
Without further details, I will have to close this ticket as "needinfo".

**Comment by totaam** [comment]
Likely related to #4631
