### ISSUE TITLE
Error in "Session info" (TypeError: 'int' object is not iterable)

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#1993]
*Issue migrated from trac ticket # 1993*

**component:** client | **priority:** major | **resolution:** fixed

#### 2018-10-21 14:19:47: onlyjob created the issue

___
> On 2.4 Information/"Session info" prints the following to the console:
> 
> ```
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/xpra/client/gtk_base/gtk_tray_menu_base.py", line 401, in show_session_info_cb
>     self.show_session_info()
>   File "/usr/lib/python2.7/dist-packages/xpra/client/gtk_base/gtk_tray_menu_base.py", line 265, in show_session_info
>     self.client.show_session_info(*args)
>   File "/usr/lib/python2.7/dist-packages/xpra/client/gtk_base/gtk_client_base.py", line 497, in show_session_info
>     self.session_info = SessionInfo(self, self.session_name, pixbuf, conn, self.get_pixbuf)
>   File "/usr/lib/python2.7/dist-packages/xpra/client/gtk_base/session_info.py", line 449, in __init__
>     self.populate_all()
>   File "/usr/lib/python2.7/dist-packages/xpra/client/gtk_base/session_info.py", line 523, in populate_all
>     p_cb()
>   File "/usr/lib/python2.7/dist-packages/xpra/client/gtk_base/session_info.py", line 951, in populate_statistics
>     setall(self.speed_labels, self.all_values_from_info("speed", "encoding.speed"))
>   File "/usr/lib/python2.7/dist-packages/xpra/client/gtk_base/session_info.py", line 877, in all_values_from_info
>     v = typedict(v)
> TypeError: 'int' object is not iterable
> ```

**Comment by totaam** [comment]
Thanks, fixed in [r20820](../commit/94b46ed32abe9a1997e3b7b7db9d7cf8f518b42b).
