### ISSUE TITLE
"Run command" fails: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#2340]
*Issue migrated from trac ticket # 2340*

**component:** client | **priority:** major | **resolution:** upstream

#### 2019-06-22 13:27:07: tc424 created the issue

___
> Server: 2.5.2-[r22875](../commit/dcdab4fc0ac91d8acae7531111bd4e337651357b)-1 / Ubuntu 16.04.6
> Client: 3.0-20190621-23016-1 / Ubuntu 18.04.2
> 
> ```
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/xpra/client/gtk_base/gtk_client_base.py", line 371, in show_start_new_command
>     self.server_xdg_menu)
>   File "/usr/lib/python3/dist-packages/xpra/client/gtk_base/start_new_command.py", line 36, in getStartNewCommand
>     _instance = StartNewCommand(run_callback, can_share, xdg_menu)
>   File "/usr/lib/python3/dist-packages/xpra/client/gtk_base/start_new_command.py", line 44, in __init__
>     self.xdg_menu = typedict(xdg_menu)
> TypeError: 'NoneType' object is not iterable
> ```
> 
> This is the set-up which previously experienced #2310, so I'm guessing the work-around for that broke things..?

**Comment by totaam** [comment]
Looks like the fix was incorrect: 634763d930b68eee3d551482a61dc2a7ac2c57cf
