### ISSUE TITLE
GTK3 OpenGL win32 window is transparent

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#2466]
Like it's not getting painted at all.

Tried 2.5.3 and 3.0.x on a win7 system with a Quadro M4000.

The code was originally added in [r16993](../commit/eed27ba9296562da861b5b7626bfe54244b74c8c) + [r16964](../commit/01a868a88f199916c2e6600f5c2244f7cbf848b7), see #1569#comment:5.

See also:
* #1569 python3 opengl client
* #1682 transparency with the native opengl backend on win32

**Comment by totaam** [comment]
Turns out that we may be able to use [GTK.GLArea](https://lazka.github.io/pgi-docs/Gtk-3.0/classes/GLArea.html) with legacy contexts: [GTK Bug 756142 - Bring back support for legacy OpenGL contexts](https://bugzilla.gnome.org/show_bug.cgi?id=756142) using the undocumented env var `GDK_GL=legacy`. (patch hooks the widget)

As per [gdkglcontext-win32.c](https://github.com/GNOME/gtk/blob/master/gdk/win32/gdkglcontext-win32.c): OpenGL does not work with WS_EX_LAYERED enabled, so we need to disable WS_EX_LAYERED when we acquire a valid HGLRC
I've tried doing the same thing in the window style fixup code (removing `WS_EX_LAYERED`), but that did not help.

**Comment by totaam** [comment]
The fix is incorrect, it ends up disabling opengl because this now triggers a rendering error:
```
Error presenting FBO
Traceback (most recent call last):
  File "E:\Xpra\trunk\src/xpra/client/gl/gl_window_backing_base.py", line 666, in present_fbo
    self.do_present_fbo()
  File "E:\Xpra\trunk\src/xpra/client/gl/gl_window_backing_base.py", line 691, in do_present_fbo
    glBindFramebuffer(GL_FRAMEBUFFER, 0)
  File "E:\Xpra\trunk\src\dist\lib\library.zip\OpenGL\error.py", line 223, in glCheckError
    raise GLError(
OpenGL.error.GLError: GLError(
        err = 1282,
        description = b'invalid operation',
        baseOperation = glBindFramebuffer,
        cArguments = (GL_FRAMEBUFFER, 0)
)
EndPaint
```
