### ISSUE TITLE
bug in platform/xposix/keyboard.py

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#2494]
*Issue migrated from trac ticket # 2494*

**component:** keyboard | **priority:** blocker | **resolution:** fixed

#### 2019-11-26 15:19:02: rozenkno created the issue

___
> Launching « xpra start »  on Fedora, I get this error :
> ```
> xpra main error:
> Traceback (most recent call last):
>   File "/usr/lib64/python3.7/site-packages/xpra/scripts/main.py", line 110, in main
>     return run_mode(script_file, err, options, args, mode, defaults)
>   File "/usr/lib64/python3.7/site-packages/xpra/scripts/main.py", line 333, in run_mode
>     return run_remote_server(error_cb, options, args, mode, defaults)
>   File "/usr/lib64/python3.7/site-packages/xpra/scripts/main.py", line 1905, in run_remote_server
>     app.init_ui(opts)
>   File "/usr/lib64/python3.7/site-packages/xpra/client/ui_client_base.py", line 189, in init_ui
>     opts.keyboard_raw, *overrides)
>   File "/usr/lib64/python3.7/site-packages/xpra/client/gtk_base/gtk_keyboard_helper.py", line 30, in __init__
>     self.update()
>   File "/usr/lib64/python3.7/site-packages/xpra/client/gtk_base/gtk_keyboard_helper.py", line 63, in update
>     self.query_xkbmap()
>   File "/usr/lib64/python3.7/site-packages/xpra/client/keyboard_helper.py", line 352, in query_xkbmap
>     ) = self.get_layout_spec()
>   File "/usr/lib64/python3.7/site-packages/xpra/client/keyboard_helper.py", line 305, in get_layout_spec
>     layout, layouts, variant, variants, options = self.keyboard.get_layout_spec()
>   File "/usr/lib64/python3.7/site-packages/xpra/platform/xposix/keyboard.py", line 142, in get_layout_spec
>     locale = self.get_locale_status()
>   File "/usr/lib64/python3.7/site-packages/xpra/platform/xposix/keyboard.py", line 89, in get_locale_status
>     parts = line.lstrip(" ").split(": ")
> TypeError: a bytes-like object is required, not 'str'
> ```
> 
> proposed bugfix : replace line 89 in `/usr/lib64/python3.7/site-packages/xpra/platform/xposix/keyboard.py` by :
> ```
>     parts = line.lstrip(b" ").split(b": ")
> ```

**Comment by frankenstein91** [comment]
Looks like the error I got on ArchLinux today:

```
2022-08-21 16:44:48,489 Xpra GTK3 client version 4.3.3-r0 64-bit
2022-08-21 16:44:48,533  running on Linux unknown unknown unknown
2022-08-21 16:44:48,548  window manager is 'Mutter'
2022-08-21 16:44:51,078 GStreamer version 1.20.3 for Python 3.10.5 64-bit
2022-08-21 16:44:51,200 Warning: failed to load the GTK3 notification class
2022-08-21 16:44:51,200  Namespace Notify not available
2022-08-21 16:44:51,210 Error: cannot enable SSH socket upgrades:
2022-08-21 16:44:51,211  No module named 'paramiko'
2022-08-21 16:44:51,222 created unix domain socket '/run/user/1000/xpra/clients/frank-nano-ng-16625'
2022-08-21 16:44:51,434 Warning: Xkb server extension is missing
2022-08-21 16:44:51,436 Warning: no Xkb support
2022-08-21 16:44:51,460 Warning: printer forwarding disabled:
2022-08-21 16:44:51,460  No module named 'cups'
2022-08-21 16:44:51,477 removing unix domain socket '/run/user/1000/xpra/clients/frank-nano-ng-16625'
xpra main error:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/xpra/scripts/main.py", line 142, in main
    return run_mode(script_file, cmdline, err, options, args, mode, defaults)
  File "/usr/lib/python3.10/site-packages/xpra/scripts/main.py", line 424, in run_mode
    return do_run_mode(script_file, cmdline, error_cb, options, args, mode, defaults)
  File "/usr/lib/python3.10/site-packages/xpra/scripts/main.py", line 467, in do_run_mode
    return run_client(script_file, cmdline, error_cb, options, args, mode)
  File "/usr/lib/python3.10/site-packages/xpra/scripts/main.py", line 1165, in run_client
    app = get_client_app(script_file, cmdline, error_cb, opts, extra_args, mode)
  File "/usr/lib/python3.10/site-packages/xpra/scripts/main.py", line 1326, in get_client_app
    app = get_client_gui_app(error_cb, opts, request_mode, extra_args, mode)
  File "/usr/lib/python3.10/site-packages/xpra/scripts/main.py", line 1382, in get_client_gui_app
    app.init_ui(opts)
  File "/usr/lib/python3.10/site-packages/xpra/client/ui_client_base.py", line 201, in init_ui
    self.keyboard_helper = self.keyboard_helper_class(send_keyboard, opts.keyboard_sync,
  File "/usr/lib/python3.10/site-packages/xpra/client/gtk_base/gtk_keyboard_helper.py", line 27, in __init__
    self.update()
  File "/usr/lib/python3.10/site-packages/xpra/client/gtk_base/gtk_keyboard_helper.py", line 60, in update
    super().update()
  File "/usr/lib/python3.10/site-packages/xpra/client/keyboard_helper.py", line 298, in update
    self.query_xkbmap()
  File "/usr/lib/python3.10/site-packages/xpra/client/keyboard_helper.py", line 270, in query_xkbmap
    ) = self.get_layout_spec()
  File "/usr/lib/python3.10/site-packages/xpra/client/keyboard_helper.py", line 223, in get_layout_spec
    layout, layouts, variant, variants, options = self.keyboard.get_layout_spec()
  File "/usr/lib/python3.10/site-packages/xpra/platform/xposix/keyboard.py", line 187, in get_layout_spec
    v = self.get_xkb_rules_names_property()
  File "/usr/lib/python3.10/site-packages/xpra/platform/xposix/keyboard.py", line 130, in get_xkb_rules_names_property
    xkb_rules_names = prop.split("\0")
TypeError: a bytes-like object is required, not 'str'

```

Sorry I'm new to Xpra... maybe it is just me

**Comment by totaam** [comment]
@frankenstein91 the fix is already in 962acb0b86289f05fc68cc93915d4399997d2e9f.
You can apply it by hand.

**Comment by frankenstein91** [comment]
@totaam so it not yet pushed to the repo?

And thank you

**Comment by totaam** [comment]
> @totaam so it not yet pushed to the repo?

@frankenstein91 no, there has not been any new releases since this commit.
