### ISSUE TITLE
xpra/net/udp_protocol.py line 184: AttributeError: 'UDPClientProtocol' object has no attribute 'send_control_failed'

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#2676]
*Issue migrated from trac ticket # 2676*

**component:** network | **priority:** critical | **keywords:** UDP

#### 2020-03-24 10:49:25: nikiwaibel created the issue

___
> hi team, i am new to xpra.
> 
> due to current covid situation, i do require the UDP transport (have a long distant link and somewhat high delay). yes, i've seen the "experimental" note, nevertheless i'd like to report the following:
> 
> if i use the plain tcp transport, things work fine. if i try to use udp, i get
> =#### on windows=
> ```
> Traceback (most recent call last):
>   File "E:\Xpra\tags\v3.0.x\src/xpra/net/udp_protocol.py", line 184, in send_control
> AttributeError: 'UDPClientProtocol' object has no attribute 'send_control_failed'
> ```
> =#### on linux=
> ```
>   File "/usr/lib64/python3.7/site-packages/xpra/net/udp_protocol.py", line 184, in send_control
>     self._add_packet_to_queue(packet, fail_cb=self.send_control_failed, synchronous=False)
> AttributeError: 'UDPClientProtocol' object has no attribute 'send_control_failed'
> ```
> =====
> 
> i think this can be easily fixed, in case python is your native language ;-)
> 
> server: xpra-3.0.7-25627, centos-7.7.1908, kernel-3.10.0-1062.4.1.el7.x86_64
> ```
> $ xpra start --start-child=xterm --bind-udp=0.0.0.0:14567 --exit-with-children=yes --webcam=no
> ```
> clients:
> 1) xpra-3.0.7-25627, win10-1909
> ```
> $ Xpra_cmd.exe attach udp://10.10.11.23:14567
> ```
> 2) xpra-3.0.6-2.fc30.x86_64, fedora-30, kernel-5.5.10-100.fc30.x86_64
> ```
> $ xpra attach udp://10.10.11.23:14567
> ```
> 
> config: no changes

**Comment by totaam** [comment]
UDP has been removed in 2022238ababa40382d2b8d6b019fb2d757ec9955.
