### ISSUE TITLE
create mswindows station and desktop from proxy

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#2756]
The only thing missing from #1527 is the ability to create a new station and desktop once the system proxy has authenticated the user.
We can already launch a shadow server for the user chosen from the proxy system service. (tested when the user is already logged in, works beautifully)

None of the solutions in the links work, at best I get *error 1800*, I believe this means *Your computer could not connect to another console session on the remote computer because you already have a console session in progress* but this user is definitely not logged in, via RDP or via the Logon screen.
And I can use the `rdesktop` command from another computer to connect with the same credentials.

**Comment by totaam** [comment]
Could be tested using free trials: [Windows 10 Enterprise](https://info.microsoft.com/ww-landing-windows-10-enterprise.html) / [Windows 11 Enterprise](https://info.microsoft.com/ww-landing-windows-11-enterprise.html)

**Comment by totaam** [comment]
Some of this existing code had bitrotted:
* ctypes and proxy server: cfe6c55b913661dd84910d8bf04a4c96b8ab1b97 + 77021615d1ce03f3fa4eeb38dcdce84ea1a5c3c0 + 4355f3d1dbfb9db76dfe2364749156beeea7f7ed
* authentication was now too strict: 6d9c96fccd15d6ea9757c2857ae5cd94c02e82e8 + c608440210676021489c2bc7592d34bb4c79979d

Unfortunately, something else isn't quite right:
```py
Traceback (most recent call last):
  File "E:/xpra/xpra/server/proxy/server.py", line 438, in proxy_session
    proc, socket_path, display = self.start_new_session(username, password, uid, gid, sns, displays)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:/xpra/xpra/platform/win32/proxy_server.py", line 63, in start_new_session
    return self.start_win32_shadow(username, password, new_session_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:/xpra/xpra/platform/win32/proxy_server.py", line 113, in start_win32_shadow
    proc = exec_command(username, password, cmd, exe, app_dir, env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:/xpra/xpra/platform/win32/proxy_server.py", line 51, in exec_command
    proc = Popen(args, executable=exe,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:/xpra/xpra/platform/win32/create_process_lib.py", line 433, in __init__
    super().__init__(*args, **kwds)
  File "C:/msys64/mingw64/lib/python3.12/subprocess.py", line 1028, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "E:/xpra/xpra/platform/win32/create_process_lib.py", line 445, in _execute_child
    self._common_execute_child(executable, commandline, shell,
  File "E:/xpra/xpra/platform/win32/create_process_lib.py", line 481, in _common_execute_child
    pi = create_process(creationinfo=ci, startupinfo=si)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:/xpra/xpra/platform/win32/create_process_lib.py", line 410, in create_process
    advapi32.CreateProcessWithTokenW(*args)
  File "E:/xpra/xpra/platform/win32/create_process_lib.py", line 221, in _check_bool
    raise WinError(get_last_error())
PermissionError: [WinError 5] Access is denied.
Error: failed to start server subprocess:
 [WinError 5] Access is denied.
```

**Comment by totaam** [comment]
```
# qwinsta.exe 
 SESSIONNAME               USERNAME                 ID  STATE   TYPE        DEVICE 
>services                                            0  Disc
 console                   Administrator             3  Active
 rdp-tcp                                         65536  Listen
```
```
# PYTHONPATH=. python3 ./xpra/platform/win32/wtsapi.py
WTSGetActiveConsoleSessionId()=3
* 0
  - State                         : Disconnected
  - StationName                   : Services
  - Type                          : console
* 3
  - Display
    - Depth                       : 2
    - Height                      : 480
    - Width                       : 640
  - DomainName                    : WIN-BDO8UM4JI1E
  - State                         : Active
  - StationName                   : Console
  - Type                          : console
  - UserName                      : Administrator
* 65536
  - State                         : listen
  - StationName                   : RDP-Tcp
  - Type                          : console
```

---


More links:
* [`CreateWindowStationA`](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-createwindowstationa) : _Creates a window station object, associates it with the calling process, and assigns it to the current session._
* [Remote Desktop Sessions](https://learn.microsoft.com/en-us/windows/win32/termserv/terminal-services-sessions): _The only supported window station name for an interactive window station is "WinSta0"_
* [Remote Desktop Services Administration](https://learn.microsoft.com/en-us/windows/win32/termserv/terminal-services-administration)
* [Window Stations and Desktops](https://scorpiosoftware.net/2023/06/20/window-stations-and-desktops/)
* [Windows — Window Station](https://medium.com/@boutnaru/windows-window-station-d72198990f32)
* expand a desktop: https://github.com/Xpra-org/xpra/issues/3390#issuecomment-2710823384
* [rdpwrap](https://github.com/stascorp/rdpwrap)
* [indirect-display-driver](https://learn.microsoft.com/en-us/windows-hardware/drivers/display/indirect-display-driver-model-overview) - https://github.com/Microsoft/Windows-driver-samples/tree/main/video/IndirectDisplay

**Comment by totaam** [comment]
Claude analysis:
---

This is a genuinely hard problem on Windows. Let me give you a complete analysis.

---

## The Core Problem

Windows separates **authentication** (who you are) from **interactive sessions** (where your desktop lives). Creating a full interactive session with a visible desktop from SYSTEM is fundamentally different from Linux where you can just set up a display.

The key constraint: **`CreateProcessAsUser` / `CreateProcessWithTokenW` from SYSTEM can create a process *in* a user's token context, but that process still lands in Session 0 (the SYSTEM session) unless you explicitly migrate it to an interactive session.** Session 0 has no display. This is the root cause of your "black screen" issue.

---

## What Actually Works vs. What Doesn't

### The paexec / psexec approach
`paexec -i <SessionID>` works **only if the user already has an active interactive session** (i.e., they're already logged in at the console or via RDP). It uses `WTSQueryUserToken(SessionID)` + `CreateProcessAsUser` to inject into that session. It cannot *create* a new session.

### LSA S4U logon
`LsaLogonUser` with S4U gives you a token, but **not** a session with a desktop. You get an impersonation/batch token. Calling `CreateProcessWithTokenW` with it creates the process in Session 0 unless you call `SetTokenInformation(TokenSessionId)` to reassign the session ID — and that requires `SeTcbPrivilege` (SYSTEM has this, but the reassigned session must already exist and have a desktop ready).

### DesktopLogon.dll / WTSConnectSession
These target *existing* sessions for reconnection or console handoff. Still no help for creating a new one from scratch.

---

## The Actual Windows Way to Create a New Session from SYSTEM

There are only a few legitimate paths:

### Option 1: `WTSStartRemoteControlSession` / Remote Desktop Services API
Requires the RDS role. On a plain Windows desktop (not Server with RDS), you can only have one interactive session at a time (Session 1). This is a Windows licensing constraint, not just an API gap.

### Option 2: `CreateProcessAsUser` + Session 0 isolation workaround
On **Windows Server** (multi-session), you can:
1. Call `LogonUser(user, pass, LOGON32_LOGON_INTERACTIVE)` → get token
2. `CreateEnvironmentBlock` + load user profile
3. **Crucially**: Call `SetTokenInformation(token, TokenSessionId, &sessionId)` to assign to an existing session slot
4. `CreateProcessAsUser` with `lpDesktop = "WinSta0\\Default"` and a `STARTUPINFO` that specifies the window station

But session slots don't appear from nothing — the session must already have been created by Winlogon or the CSRSS subsystem.

### Option 3: Trigger a new logon via `WinLogon` / `MsRdpClient` programmatically
On Server: `WTSCreateVirtualChannel` / `WTSVirtualChannelOpen` is for data channels, not sessions. **There is no public Win32 API to programmatically create a new interactive session from SYSTEM.**

The undocumented path used by some tools:
```
CreateProcessAsUser → csrss.exe involvement → new session
```
... requires hooking into Winlogon's session creation, which is not publicly documented and breaks between Windows versions.

### Option 4: The `runas /savecred` / `WTSLogonSession` path (Windows Server only)
On Server with Remote Desktop Services:
1. Use `WTSConnectSession` to connect a disconnected session
2. Or use the `WTSAPI32` `WTSStartRemoteControlSession`

But again: sessions must be pre-existing or created by an RDP connection.

---

## What Actually Can Work

### Realistic Option A: Require the user to be logged in first
The proxy detects an existing session via `WTSEnumerateSessions`, then uses `WTSQueryUserToken` + `CreateProcessAsUser` to launch the shadow server *in that session*. This is what your paexec path does. The limitation is that the user must already have a session.

For an enterprise deployment, this is often acceptable: users log in via console or RDP first, then xpra shadows that session.

### Realistic Option B: Force a new RDP session (Server only)
On Windows Server with RDS, you can programmatically trigger an RDP connection to `127.0.0.1` using the `MSTSCLib` COM object or `mstsc /v:localhost` as a child process. This creates a real new session. Your existing code seems to have tried this path. The problems:
- Requires RDS CALs
- `mstsc` to localhost is blocked on some configurations
- The session needs credentials (can't be silent)

### Realistic Option C: Virtual Desktop Objects (not the same as sessions)
`CreateDesktop` / `SwitchDesktop` creates an isolated *desktop* within the same *session*, not a new session. A process running on a separate desktop is invisible to the user's main desktop. This could work for running xpra's shadow server on a **separate desktop within an existing session**, but it's not a full isolation boundary and the user wouldn't see it without explicitly switching desktops.

### Realistic Option D: Headless via a virtual display driver
Install a **virtual display adapter** (e.g., `IddSampleDriver`, `parsec-vdd`, or the older `Mirror Driver` API). SYSTEM can create virtual monitors. Then launch the shadow server targeting that virtual display, not a user session. This sidesteps the session problem entirely — the "display" is a kernel-mode device.

This is the most promising path for a true "create on demand" flow:
1. SYSTEM installs/activates a virtual display for the user's session dimensions
2. Launch the shadow server process pointing at that display
3. No RDP, no desktop session needed

---

## Verdict

**It is possible on Windows Server with RDS, but not on Windows desktop without significant compromises.** The fundamental constraint is that Windows does not have a public API to create new interactive sessions from a service. Your existing code is hitting the ceiling of what's publicly possible.

The most promising paths going forward:

| Approach | Works on | Requires | Notes |
|----------|----------|----------|-------|
| Shadow existing session (paexec) | All | User already logged in | Current code, works when session exists |
| Force RDP to localhost | Server + RDS | RDS role + CALs | Fragile, licensing issues |
| Virtual display driver | All | Driver install (one-time) | Best for "create on demand"; bypasses session problem |
| `CreateDesktop` isolation | All | Existing session | Not full isolation; shares session |

The virtual display driver route (Option D) is worth investigating seriously — it's how tools like Parsec and newer remote desktop solutions handle headless/multi-user on Windows without requiring full RDS infrastructure.

**Comment by totaam** [comment]
## Virtual Display Driver for Xpra on Windows

### What Problem It Solves

The session-creation problem is a dead end because Windows won't let a service spawn a new interactive session with a desktop. A virtual display driver sidesteps this entirely: instead of creating a session that has a display, you create a display that a session-less process can capture. The shadow server runs as the user (via `CreateProcessAsUser`), but targets a driver-backed virtual monitor rather than the physical desktop.

---

### How It Works Architecturally

```
SYSTEM service (xpra proxy)
  │
  ├─ 1. Enable virtual display for user X  (driver API / device instance)
  │
  ├─ 2. CreateProcessAsUser(user X token)
  │       └─ xpra shadow server
  │               └─ captures virtual monitor "\\.\DISPLAY2"
  │
  └─ 3. Proxy streams that capture to remote client
```

The user's apps run on the virtual monitor. The shadow server captures it. No physical display needed, no interactive session with a Winlogon desktop needed.

---

### The Driver Landscape

There are three generations of Windows virtual display technology:

#### 1. Mirror Drivers (legacy, dead)
- Kernel-mode drivers that mirrored GDI rendering
- **Removed in Windows 8** — not viable

#### 2. WDDM with Indirect Display Driver (IDD) — current standard
- Introduced in Windows 10 1607
- User-mode driver (runs in UMDF, not kernel ring 0)
- Appears as a real GPU/monitor to `EnumDisplayMonitors` — xpra's existing display enumeration code would pick it up automatically
- Microsoft provides `IddSampleDriver` as a reference implementation on GitHub
- **This is the right path**

#### 3. `usbmmidd` / `usbpdd` (older user-mode virtual display)
- Open-source projects that implement virtual monitors via a USB HID trick
- Work on older Windows (7/8/10), no signing requirements in test mode
- Less clean than IDD but simpler to deploy

---

### Existing Projects You Can Leverage

| Project | Type | Notes |
|---------|------|-------|
| [parsec-vdd](https://github.com/nhan-tam/parsec-vdd) | IDD | Virtual display used by Parsec; stable, well-documented C API |
| [virtual-display-rs](https://github.com/MolotovCherry/virtual-display-rs) | IDD | Rust-based, named pipe control API; actively maintained |
| [usbmmidd](https://github.com/roshkins/usbmmidd) | Legacy UMDF | Older but works down to Win7; no signing needed in test mode |
| [IddSampleDriver](https://github.com/microsoft/Windows-driver-samples/tree/main/video/IndirectDisplay) | IDD reference | Microsoft's own sample; needs modification to add control API |

Parsec-vdd is the most immediately useful — it ships a pre-signed driver and exposes a simple C API (`VddAddMonitor`, `VddRemoveMonitor`) that you could wrap with ctypes.

---

### Integration Points in Xpra

Very little new code needed inside xpra itself:

**1. New module: `xpra/platform/win32/virtual_display.py`**
```python
# ctypes wrapper around parsec-vdd or virtual-display-rs control API
def add_virtual_monitor(width, height, refresh_hz=60) -> str:
    # calls VddAddMonitor() or named pipe command
    # returns device name e.g. "\\.\DISPLAY3"
    ...

def remove_virtual_monitor(device_name: str) -> None:
    ...
```

**2. Modify `proxy_server.py` → `start_win32_shadow()`**
```python
# Instead of: find existing session, inject via paexec
# New flow:
monitor_name = add_virtual_monitor(width, height)
try:
    launch_shadow_for_user(username, token, display=monitor_name)
    ...
finally:
    remove_virtual_monitor(monitor_name)
```

**3. `shadow_server.py` already works** — `get_shadow_monitors()` calls `EnumDisplayMonitors()`, which will naturally enumerate the virtual monitor. No changes needed there.

---

### The Hard Part: Driver Signing

This is the main deployment friction:

- All kernel-mode drivers (and IDD drivers) must be **WHQL-signed** to load on Windows 10/11 with Secure Boot enabled
- **Test signing mode** (`bcdedit /set testsigning on`) bypasses this but must be enabled on each machine and is unsuitable for production
- Parsec-vdd ships a pre-signed `.inf`/`.cat` — this is the easiest path if their license is acceptable
- `virtual-display-rs` requires you to sign it yourself (EV code signing certificate, ~$300/year) or use their pre-built signed release
- Microsoft's own IDD sample is unsigned; you'd need to sign it

For an enterprise deployment where you control the machines, you can push the signed driver via Group Policy or an MSI installer one time, then the xpra service manages monitor creation/destruction at runtime without any further driver interaction.

---

### Per-User Isolation Consideration

One subtlety: virtual monitors created by an IDD driver are **system-wide** — they appear in `EnumDisplayMonitors` for all sessions. If you're running multiple xpra users simultaneously (the actual multi-user proxy use case), you need to:

1. Create one virtual monitor per active user session
2. Assign processes to those monitors by launching them with `lpDesktop` pointing at the right window station, and ensuring their apps open on the right monitor (via `SetProcessDefaultLayout`, initial window placement, or by running each user in a separate window station entirely)

Window stations (`CreateWindowStation`) give you the cleanest isolation — each user gets their own `WinSta\Default` desktop. This is what Terminal Services does internally. Combined with virtual displays, you can get genuine multi-user headless isolation without RDS.

---

### Summary Recommendation

The cleanest practical path for xpra:

1. **Bundle parsec-vdd** (pre-signed IDD driver) in the xpra Windows installer — one-time install step
2. **Write a thin ctypes wrapper** around its control API in `xpra/platform/win32/virtual_display.py`
3. **Replace the paexec/DesktopLogon path** in `proxy_server.py` with: create virtual monitor → `CreateProcessAsUser` shadow server targeting that monitor → destroy monitor on disconnect
4. **Optionally pair with `CreateWindowStation`** for per-user isolation if you need multi-user support

The shadow server capture code, display enumeration, and named pipe IPC all already work and would need no changes.

**Comment by totaam** [comment]
I'm not completely stupid after all. This can never work well:

---

Everything in `WinSta0\Default` shares one set of global UI state:

| Resource | Scope | Consequence for simultaneous users |
|---|---|---|
| **Clipboard** | per **window station** | All sessions read/write one clipboard — user A copies, user B's paste gets it |
| **Foreground window / focus** | per **desktop** | One focused window globally. Two users typing → both keystrokes hit the same window |
| **System cursor** | per **desktop** | One cursor. Two users moving the mouse → it jerks between them |
| **`SendInput` injection** | per **desktop** | Each shadow injects into the same input stream — no per-user routing |
| **Z-order, Alt-Tab, taskbar** | per **desktop** | Shared; everyone's windows are enumerable and reachable by everyone (`EnumWindows` sees all) |

The per-monitor capture only partitions **what each client sees** (the pixel region). It does nothing for **input, clipboard, or window ownership**. So two *simultaneous* users would fight over a single cursor and keyboard focus. Model B is really **one interactive Windows session presented as multiple monitors** — fine for:

- **One headless user** (the common case: connect to your own machine remotely), or
- **One user with several virtual monitors**, or
- **Sequential users** (one at a time).

It is *not* isolated multi-user.

---

Geometry shifts when monitors are added/removed. This is a real and nasty failure mode:

1. **Coordinates shift.** All VDD monitors share one virtual-desktop bounding box. Remove the monitor at x=1920 and Windows re-lays-out the rest — the monitor that was at x=3840 moves to x=1920. Every other session's capture origin is now wrong.
2. **`\\.\DISPLAYn` renumbers.** We already mitigated this with `find_monitor_by_slot` + the `WM_DISPLAYCHANGE` handler, but…
3. **There's an in-flight window.** Between the display-change event and the handler re-resolving geometry, frames can be captured from the stale rectangle — exactly the "pixels that no longer correspond to the intended monitor" you're worried about.

Mitigations exist (pin each monitor's position with `ChangeDisplaySettingsEx` + `DM_POSITION` so they never reflow; re-validate geometry on every `WM_DISPLAYCHANGE`, which we built), but with *multiple simultaneous* sessions the coupling is inherent: **one user's session lifecycle perturbs every other user's coordinate space.** That's fragile by design.

## The underlying truth

The window-station experiment you just ran (Outcome 1) confirmed the wall:

> **Windows allows exactly one interactive session with a display. Everything else is Session 0 / non-interactive window stations with no display surface.**

- True simultaneous isolated desktops require **separate sessions**.
- Separate interactive sessions on Windows = **RDS (Remote Desktop Services)** — the multi-session licensing path we were trying to avoid at the very start.
- VDD is a **display** trick, not a **session** trick. It cannot manufacture a second interactive session, which is why the isolated window station captured black.

So the honest landscape:

| Goal | Viable approach |
|---|---|
| **One headless remote user** (no monitor, no RDP) | ✅ **VDD + shadow-device** — what you've built. Ship it. |
| One user, multiple virtual monitors | ✅ VDD + shadow-device (multiple slots) |
| **Multiple simultaneous isolated users** | ❌ Needs RDS multi-session. VDD doesn't change this. |
