### ISSUE TITLE
Bug in pyxdg throws error when a client connects

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#2863]
*Issue migrated from trac ticket # 2863*

**component:** server | **priority:** major | **resolution:** fixed | **keywords:** shadow,attach,pyxdg

#### 2020-08-15 22:29:06: seijikun created the issue

___
> ```
> xpra shadow :0 --bind-tcp=0.0.0.0:10000 -d server
> ```
> throws an error as soon as a client tries to connect when the pyxdg library is installed.
> 
> This because of: [https://gitlab.freedesktop.org/xdg/pyxdg/-/issues/20 ]
> 
> It does not seem that this will be fixed anytime soon, so you may want to catch this (if possible), or temporarily work around this by not attempting to use the library if python is too new.
> Verified by uninstalling the python3-pyxdg package. This solved the problem for us.
> 
> Stacktrace:
> 
> ```
> Error during threaded setup of <class 'xpra.server.mixins.child_command_server.ChildCommandServer'>
> Traceback (most recent call last):
> File "/usr/lib64/python3.8/site-packages/xpra/server/server_base.py", line 172, in threaded_init
> c.threaded_setup(self)
> File "/usr/lib64/python3.8/site-packages/xpra/server/mixins/child_command_server.py", line 107, in threaded_setup
> load_xdg_menu_data()
> File "/usr/lib64/python3.8/site-packages/xpra/platform/xposix/xdg_helper.py", line 233, in load_xdg_menu_data
> xdg_menu_data = do_load_xdg_menu_data()
> File "/usr/lib64/python3.8/site-packages/xpra/platform/xposix/xdg_helper.py", line 264, in do_load_xdg_menu_data
> menu = parse()
> File "/usr/lib/python3.8/site-packages/xdg/Menu.py", line 1128, in parse
> return XMLMenuBuilder(debug).parse(filename)
> File "/usr/lib/python3.8/site-packages/xdg/Menu.py", line 632, in parse
> menu = self.parse_menu(tree.getroot(), filename)
> File "/usr/lib/python3.8/site-packages/xdg/Menu.py", line 650, in parse_menu
> self.parse_node(node, filename, menu)
> File "/usr/lib/python3.8/site-packages/xdg/Menu.py", line 659, in parse_node
> menu = self.parse_menu(child, filename)
> File "/usr/lib/python3.8/site-packages/xdg/Menu.py", line 650, in parse_menu
> self.parse_node(node, filename, menu)
> File "/usr/lib/python3.8/site-packages/xdg/Menu.py", line 682, in parse_node
> parent.Rules.append(self.parse_rule(child))
> File "/usr/lib/python3.8/site-packages/xdg/Menu.py", line 759, in parse_rule
> return Rule(type, tree)
> File "/usr/lib/python3.8/site-packages/xdg/Menu.py", line 421, in __init__
> self.code = compile(self.expression, '<compiled-menu-rule>', 'eval')
> ValueError: Name node can't be used with 'True' constant
> ```
>

**Comment by totaam** [comment]
This was already fixed in [r27118](../commit/070651b36aa3751136ec353bba59edd55e5cd3f6), but seeing how often pyxdg throws new types of errors, I've changed the exception handler to catch all exceptions: [r27168](../commit/25a0a2570256722af6c0b63f55de5c4b5b90b6ad).
This is normally frowned upon, but better than suffering yet another pyxdg bug in the future.

**Comment by totaam** [comment]
For those unable to upgrade xpra or pyxdg, you can also apply this workaround: [Bugfix AttributeError: type is not stored in attribute but calculated by method](https://gitlab.freedesktop.org/xdg/pyxdg/-/commit/b3a4518267c93720ce384a165eb4142b9680268c)
