### ISSUE TITLE
cx_Freeze 6.5 is broken: No module named 'xpra__main__'

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#2994]
*Issue migrated from trac ticket # 2994*

**component:** packaging | **priority:** minor | **resolution:** upstream

#### 2021-01-06 17:24:49: antoine created the issue

___
> ```
> C:/msys64/mingw64/lib/python3.8/site-packages/cx_Freeze/common.py:124: UserWarning: camelCase values is obsolete and will be removed in the next major version -> use the new name 'target_name'
>   warnings.warn(
> Traceback (most recent call last):
>   File "./setup.py", line 2346, in <module>
>     main()
>   File "./setup.py", line 2342, in main
>     setup(**setup_options)
>   File "C:/msys64/mingw64/lib/python3.8/site-packages/cx_Freeze/dist.py", line 392, in setup
>     distutils.core.setup(**attrs)
>   File "C:/msys64/mingw64/lib/python3.8/distutils/core.py", line 148, in setup
>     dist.run_commands()
>   File "C:/msys64/mingw64/lib/python3.8/distutils/dist.py", line 966, in run_commands
>     self.run_command(cmd)
>   File "C:/msys64/mingw64/lib/python3.8/distutils/dist.py", line 985, in run_command
>     cmd_obj.run()
>   File "C:/msys64/mingw64/lib/python3.8/site-packages/cx_Freeze/dist.py", line 347, in run
>     self.run_command("build_exe")
>   File "C:/msys64/mingw64/lib/python3.8/distutils/cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "C:/msys64/mingw64/lib/python3.8/distutils/dist.py", line 985, in run_command
>     cmd_obj.run()
>   File "C:/msys64/mingw64/lib/python3.8/site-packages/cx_Freeze/dist.py", line 260, in run
>     freezer.Freeze()
>   File "C:/msys64/mingw64/lib/python3.8/site-packages/cx_Freeze/freezer.py", line 754, in Freeze
>     self._FreezeExecutable(executable)
>   File "C:/msys64/mingw64/lib/python3.8/site-packages/cx_Freeze/freezer.py", line 227, in _FreezeExecutable
>     finder.IncludeFile(exe.main_script, exe.main_module_name)
>   File "C:/msys64/mingw64/lib/python3.8/site-packages/cx_Freeze/finder.py", line 618, in IncludeFile
>     module = self._load_module(name, path, deferred_imports)
>   File "C:/msys64/mingw64/lib/python3.8/site-packages/cx_Freeze/finder.py", line 371, in _load_module
>     raise ImportError(f"No module named {name!r}", name=name)
> ImportError: No module named 'xpra__main__'
> ```

**Comment by totaam** [comment]
Seems to be this bug:
https://github.com/marcelotduarte/cx_Freeze/issues/891
