### ISSUE TITLE
Client disconnect due to UI thread block when using jpeg compression

### ISSUE THREAD

**Issue by thomase00** [Xpra-org/xpra#3025]
I'm experiencing a client disconnect with a particular application when using JPEG compression.

If tail the log file on the server from a separate ssh session, I can see that in response to a particular GUI operation while using the application, the following messages get written to the log file just before and during the disconnect:
```
2021-02-18 23:36:07,938 error on window 8
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/xpra/server/source/encodings_mixin.py", line 160, in recalculate_delays
    ws.reconfigure()
  File "/usr/lib64/python2.7/site-packages/xpra/server/window/window_source.py", line 1263, in reconfigure
    self.update_encoding_options(force_reload)
  File "/usr/lib64/python2.7/site-packages/xpra/server/window/window_video_source.py", line 1071, in update_encoding_options
    self.children)
  File "/usr/lib64/python2.7/site-packages/xpra/server/window/video_subregion.py", line 528, in identify_video_subregion
    scores[region] = score_region("child-window", region, 48*48)
  File "/usr/lib64/python2.7/site-packages/xpra/server/window/video_subregion.py", line 429, in score_region
    score = scoreinout(ww, wh, region, incount, outcount)
  File "/usr/lib64/python2.7/site-packages/xpra/server/window/video_subregion.py", line 31, in scoreinout
    assert total>0
AssertionError
```
After the above, I can still interact with the application for a short period of time, but it starts to get sluggish. Within a few seconds, it stops responding altogether and then the client disconnects. The following is written to the log file:
```
2021-02-18 23:37:25,677 client   4 @27.993 UI thread is now blocked
2021-02-18 23:37:37,150 client   4 @39.460 Warning: long timer waiting time,
2021-02-18 23:37:37,150 client   4 @39.464  UI thread polling waited 10.2 seconds longer than intended (10.7 vs 0.5)
2021-02-18 23:37:37,944 xpra client 4 disconnected.
```
I've run into similar stability issues when using H.264.

**Comment by totaam** [comment]
0f02130e3641f96945d8f95150df05b8884ef3c3 should avoid the `AssertionError` you reported. Thanks for that!

I'm not entirely sure why it would get sluggish after that though. Hopefully it will go away.

**Comment by totaam** [comment]
Related improvement in e7808f32963bd644ab427fc2495f6ee05c4611ec1a9394db3d27e9e9eacf8dec.
