### ISSUE TITLE
TypeError: make_revision_str() missing 1 required positional argument: 'commit'

### ISSUE THREAD

**Issue by stdedos** [Xpra-org/xpra#3030]
```py
Traceback (most recent call last):
  File "E:\Xpra/xpra/client/gtk_base/menu_helper.py", line 344, in show_session_info_cb
  File "E:\Xpra/xpra/client/gtk_base/menu_helper.py", line 237, in show_session_info
  File "E:\Xpra/xpra/client/gtk_base/gtk_client_base.py", line 581, in show_session_info
  File "E:\Xpra/xpra/client/gtk_base/session_info.py", line 186, in __init__
TypeError: make_revision_str() missing 1 required positional argument: 'commit'
```

**Comment by stdedos** [comment]
Verified as fixed in `r28507`

I think you really should start printing "Xpra GTK3 client version v4.0-xx-g123456 64-bit" as initial strings, in addition to r12345 (if you insist on keep counting)
