### ISSUE TITLE
vaapi crash on Fedora

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#3039]
Reproducible with just `xpra/codecs/loader.py`.

```
2385	        vaDestroyContext(ctx->hwctx->display, ctx->va_context);
```

```
Traceback (most recent call first):
  <built-in method init_encoder of xpra.codecs.enc_ffmpeg.encoder.Encoder object at remote 0x7fffe8f74f20>
  File "/usr/lib64/python3.9/site-packages/xpra/codecs/codec_checks.py", line 218, in do_testencoding
    e.init_context(W, H, cs_in, [cs_out], encoding, 0, 100, (1, 1), options)
  File "/usr/lib64/python3.9/site-packages/xpra/codecs/codec_checks.py", line 147, in testencoding
    do_testencoding(encoder_module, encoding, W, H, full)
  File "/usr/lib64/python3.9/site-packages/xpra/codecs/codec_checks.py", line 132, in testencoder
    testencoding(encoder_module, encoding, full)
  <built-in function selftest>
  File "/home/antoine/projects/xpra-git/./xpra/codecs/loader.py", line 71, in codec_import_check
    selftest(FULL_SELFTEST)
  File "/home/antoine/projects/xpra-git/./xpra/codecs/loader.py", line 141, in xpra_codec_import
    if codec_import_check(name, description, xpra_top_module, xpra_class_module, classname):
  File "/home/antoine/projects/xpra-git/./xpra/codecs/loader.py", line 183, in load_codec
    xpra_codec_import(name, description, top_module, class_module, classnames)
  File "/home/antoine/projects/xpra-git/./xpra/codecs/loader.py", line 192, in load
    load_codec(name)
  File "/home/antoine/projects/xpra-git/./xpra/codecs/loader.py", line 199, in load_codecs
    load(*ENCODER_VIDEO_CODECS)
  File "/home/antoine/projects/xpra-git/./xpra/codecs/loader.py", line 317, in main
    load_codecs()
  File "/home/antoine/projects/xpra-git/./xpra/codecs/loader.py", line 871, in <module>
```

```
Thread 1 "python3" received signal SIGSEGV, Segmentation fault.
0x00007fff9456965d in ff_vaapi_encode_close (avctx=0x5555564c1dc0) at libavcodec/vaapi_encode.c:2385
2385	        vaDestroyContext(ctx->hwctx->display, ctx->va_context);
(gdb) bt
#0  0x00007fff9456965d in ff_vaapi_encode_close (avctx=0x5555564c1dc0) at libavcodec/vaapi_encode.c:2385
#1  0x00007fff947c0aad in avcodec_open2 (avctx=0x5555564c1dc0, codec=0x7fff94aa2de0 <ff_vp8_vaapi_encoder>, options=options@entry=0x7fffffffbbf0) at libavcodec/utils.c:1022
#2  0x00007fffe42426e9 in __pyx_pf_4xpra_6codecs_10enc_ffmpeg_7encoder_7Encoder_8init_encoder
    (__pyx_v_self=<optimized out>, __pyx_v_quality=<optimized out>, __pyx_v_options=<optimized out>, __pyx_v_speed=<optimized out>) at xpra/codecs/enc_ffmpeg/encoder.c:15867
#3  0x00007ffff7d66d49 in cfunction_call
    (func=<built-in method init_encoder of xpra.codecs.enc_ffmpeg.encoder.Encoder object at remote 0x7fffe8f74f20>, args=<optimized out>, kwargs=<optimized out>)
    at /usr/src/debug/python3.9-3.9.2-1.fc33.x86_64/Objects/methodobject.c:539
#4  0x00007fffe421119e in __Pyx_PyObject_Call
    (func=<built-in method init_encoder of xpra.codecs.enc_ffmpeg.encoder.Encoder object at remote 0x7fffe8f74f20>, arg=(0, 100, <typedict at remote 0x7fffe8f9f180>), kw=0x0)
    at xpra/codecs/enc_ffmpeg/encoder.c:28952
#5  0x00007fffe4234d3d in __pyx_pf_4xpra_6codecs_10enc_ffmpeg_7encoder_7Encoder_init_context
    (__pyx_v_dst_formats=<optimized out>, __pyx_v_scaling=<optimized out>, __pyx_v_options=<typedict at remote 0x7fffe8f9f180>, __pyx_v_speed=100, __pyx_v_quality=0, __pyx_v_encoding=<optimized out>, __pyx_v_src_format=<optimized out>, __pyx_v_height=<optimized out>, __pyx_v_width=<optimized out>, __pyx_v_self=0x7fffe8f74f20) at xpra/codecs/enc_ffmpeg/encoder.c:11468
#6  __pyx_pw_4xpra_6codecs_10enc_ffmpeg_7encoder_7Encoder_1init_context
    (__pyx_v_self=<xpra.codecs.enc_ffmpeg.encoder.Encoder at remote 0x7fffe8f74f20>, __pyx_args=<optimized out>, __pyx_kwds=<optimized out>) at xpra/codecs/enc_ffmpeg/encoder.c:10325
```

This was working fine previously... so some update must have broken it.

**Comment by totaam** [comment]
Fixed in 9308043f8c32fbc08fc92a6d3349af29dd7b6d04
