### ISSUE TITLE
unsupported operand type(s) for +: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by stdedos** [Xpra-org/xpra#3078]
```py
unsupported operand type(s) for +: 'NoneType' and 'str'                          Xpra top 4.1.2
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xpra/client/top_client.py", line 485, in do_update_screen
    vstr = caps_to_version(build)
  File "/usr/lib/python3/dist-packages/xpra/version_util.py", line 41, in caps_to_version
    return caps.strget("version")+"-"+caps_to_revision(caps)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

`xpra top` was just running

**Comment by totaam** [comment]
Damn, forgot to backport ad8baf9c8e370e5b4cbb92d1199d13bb28e3a609.

Done now.
