### ISSUE TITLE
Excessive "New unix-domain connection received"

### ISSUE THREAD

**Issue by stdedos** [Xpra-org/xpra#3080]
On a relatively new server, I get:

```console
$ cat /run/user/1000/xpra/display-\:4-20210409-105907.log | perl -pe 's/\d\d\d\d-\d\d-\d\d \d\d:\d\d:\d\d,\d\d\d //g' | awk '!a[$0]++ {}; END { for (x in a) { printf "%s%%%s\n", a[x], x } }' | sort -nrk1 -t'%' | column -ts% | less
5392  New unix-domain connection received
2695   on '/home/u/.xpra/h-4'
1349   on '/run/user/1000/xpra/h-4'
1348   on '/run/xpra/h-4'
27        ve.init_context(enc_width, enc_height, enc_in_format,
27    Traceback (most recent call last):
27        if self.setup_pipeline_option(width, height, src_format, *option):
27      File "xpra/codecs/enc_ffmpeg/encoder.pyx", line 1406, in xpra.codecs.enc_ffmpeg.encoder.Encoder.init_encoder
27      File "xpra/codecs/enc_ffmpeg/encoder.pyx", line 1232, in xpra.codecs.enc_ffmpeg.encoder.Encoder.init_context
27      File "xpra/codecs/enc_ffmpeg/encoder.pyx", line 1216, in xpra.codecs.enc_ffmpeg.encoder.Encoder.init_context
27      File "/usr/lib/python3/dist-packages/xpra/server/window/window_video_source.py", line 1749, in setup_pipeline_option
27      File "/usr/lib/python3/dist-packages/xpra/server/window/window_video_source.py", line 1674, in setup_pipeline
27    Exception: could not open h264 encoder context: Not yet implemented in FFmpeg, patches welcome
4     Warning: remote clipboard request timed out
2     send_delayed_regions: using full window update 1600x837 as   png: merged region covers almost the whole window, from <bound method WindowSource.get_refresh_encoding of WindowVideoSource(5 : (1600, 837))>
2     send_delayed_regions: sent 1 regions using ['png']
2     Warning: failed to setup video pipeline (70, (1, 1), (1, 1), 2312, 1284, swscale(BGRX to NV12), 'NV12', (1, 1), 2312, 1284, ffmpeg(NV12 to h264))
2     Warning: failed to setup video pipeline (66, (1, 1), (1, 1), 2560, 1376, swscale(BGRX to NV12), 'NV12', (1, 1), 2560, 1376, ffmpeg(NV12 to h264))
2     Warning: failed to setup video pipeline (64, (1, 1), (1, 1), 2512, 1306, swscale(BGRX to NV12), 'NV12', (1, 1), 2512, 1306, ffmpeg(NV12 to h264))
2     Warning: failed to setup video pipeline (62, (1, 1), (1, 1), 2162, 1284, swscale(BGRX to NV12), 'NV12', (1, 1), 2162, 1284, ffmpeg(NV12 to h264))
2     Warning: failed to setup video pipeline (56, (1, 1), (1, 1), 2560, 1376, swscale(BGRX to NV12), 'NV12', (1, 1), 2560, 1376, ffmpeg(NV12 to h264))
2
1     xvfb pid=272754
1     xpra is ready.
1     xpra GTK3 X11 version 4.2 64-bit
1     xpra GTK3 X11 server is exiting
1     xpra client 1 disconnected.
1     (xpra:400485): Gtk-WARNING **: 10:59:07.229: Theme parsing error: gtk.css:14:1: '/*' in comment block
1     (Xpra:400485): Gtk-CRITICAL **: 10:59:13.904: gtk_widget_realize: assertion 'widget->priv->anchored || GTK_IS_INVISIBLE (widget)' failed
1      waiting up to 20 seconds
1     waiting for 1 items in work queue to complete
1     /usr/lib/python3/dist-packages/gi/overrides/Gtk.py:1632: Warning: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
1      using 'llvmpipe (LLVM 11.0.0, 256 bits)' renderer
... (more shown in less)
```

This sounds like a little bit excessive 😕

**Comment by stdedos** [comment]
Note: I do have `xpra top` running

**Comment by totaam** [comment]
`xpra top` will poll all the active servers, which results in those `New unix-domain connection received`.

The first one has twice the number of hits because it is also used for collecting `xpra info` which is then shown in the top window.

**Comment by stdedos** [comment]
I guess changing that to a plug-to-pipe architecture would be wasteful, right? 😕

**Comment by totaam** [comment]
> I guess changing that to a plug-to-pipe architecture would be time wasted, right?

The changeset above will avoid a lot of unnecessary work, including the `New unix-domain connection received` messages: when the connection is a simple probe (ie `xpra list`), we take a shortcut out.

**Comment by stdedos** [comment]
SO MANY CHANGES 😀

**Comment by totaam** [comment]
2274c883b4b9c1154d0402db00823f84a5acabf4 had caused #3346.
