### ISSUE TITLE
invalid None value in force-ungrab packet at index 1

### ISSUE THREAD

**Issue by stdedos** [Xpra-org/xpra#3081]
```
"Xpra-Python3-x86_64_4.2-r28802\xpra_cmd" attach ssh://user@ip/4 --ssh="plink -ssh -agent" --modal-windows=no --title="@title@ on @@/@server-display@" --headerbar=off --opengl=no --bandwidth-limit=6Mbps

XPRA_CUSTOM_TITLE_BAR=0
XPRA_EXECUTABLE=Xpra-Python3-x86_64_4.2-r28802
XPRA_REPAINT_ALL=1
XPRA_SCROLL_ENCODING=0

2021-04-09 14:00:59,885 Xpra GTK3 client version 4.2 64-bit
2021-04-09 14:00:59,887  running on Microsoft Windows 10
2021-04-09 14:01:01,193 GStreamer version 1.18.4 for Python 3.8.8 64-bit
2021-04-09 14:01:01,456 created named pipe 'Xpra\10768'
2021-04-09 14:01:01,703 keyboard layout code 0x409
2021-04-09 14:01:01,704 identified as 'United States - English' : us
2021-04-09 14:01:02,864  keyboard settings: layout=us
2021-04-09 14:01:02,873  desktop size is 4160x1440 with 1 screen:
2021-04-09 14:01:02,874   Default (1100x381 mm - DPI: 96x96) workarea: 4160x1400
2021-04-09 14:01:02,874     Generic PnP Monitor 1600x900 at 0x534 (309x174 mm - DPI: 132x131) workarea: 1600x860 at 0x534
2021-04-09 14:01:02,877     C32JG5x 2560x1440 at 1600x0 (697x392 mm - DPI: 93x93) workarea: 2560x1400 at 1600x0
2021-04-09 14:01:27,342 enabled remote logging
2021-04-09 14:01:27,344 Xpra GTK3 X11 server version 4.2-r28836 64-bit
2021-04-09 14:01:27,345  running on Linux Ubuntu 20.04 focal

....

2021-04-09 14:36:20,664 server is OK again
2021-04-09 14:36:42,127 Error: error in network packet write/format
2021-04-09 14:36:42,138  invalid None value in force-ungrab packet at index 1
Traceback (most recent call last):
  File "E:\Xpra/xpra/net/protocol.py", line 377, in write_format_thread_loop
  File "E:\Xpra/xpra/net/protocol.py", line 392, in _add_packet_to_queue
  File "E:\Xpra/xpra/net/protocol.py", line 545, in encode
TypeError: invalid None value in force-ungrab packet at index 1
2021-04-09 14:36:42,414 Connection lost
```

**Comment by totaam** [comment]
Interesting one.
The bug was easy enough to fix, we should never send `None` values as those are not handled by the bencoder.

What's puzzling is why you're using the bencoder at all: all the builds (even the html5 client nowadays, though not with all browsers) should be using `rencode` by default. (and `rencode` does handle `None` values..)

Connecting from MS Windows to Ubuntu Focal:
```shell
$ xpra info :2 | grep client.connection.encoder
client.connection.encoder=rencode
```

**Comment by stdedos** [comment]
> What's puzzling is why you're using the bencoder at all: all the builds (even the html5 client nowadays, though not with all browsers) should be using `rencode` by default. (and `rencode` does handle `None` values..)

Maybe related? https://github.com/Xpra-org/xpra/issues/3082

I don't think I explicitly have changed encoding codecs.
Maybe xenial>focal update did not work so well for xpra?

I did get a notice of conflicting versions for the 55_**.conf file, but nothing else (and even then, I applied your version)

**Comment by totaam** [comment]
> Maybe related? #3082

No. This is a packet encoder. Unrelated to picture encodings.

On my Ubuntu Focal test system, I see that rencode is there when I do this:
```shell
python3 xpra/net/net_util.py | grep rencode
```
And also:
```shell
dpkg --list python3-rencode
```

**Comment by stdedos** [comment]
I see it too:
```console
$ python3 /usr/lib/python3/dist-packages/xpra/net/net_util.py | grep rencode
* encoders                        : rencode, bencode, yaml, none
* rencode                         : True
$ dpkg --list python3-rencode | cat
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name            Version       Architecture Description
+++-===============-=============-============-==================================================================
ii  python3-rencode 1.0.6-1build1 amd64        Python encoding library similar to bittorrent's bencode (Python 3)
```

and, just for the sake of completeness:

```console
$ xpra showconfig | grep -P "used|default"
add-printer-options   (used)   = '-u allow:$USER', '-E', '-o printer-is-shared=false'  <class 'list'>
add-printer-options  (default) = '-E', '-o printer-is-shared=false', '-u allow:$USER'  <class 'list'>
compressors           (used)   = 'lz4', 'lzo', 'zlib', 'brotli'    <class 'list'>
compressors          (default) = 'none', 'lz4', 'lzo', 'zlib', 'brotli'  <class 'list'>
encodings             (used)   = 'all'                             <class 'list'>
encodings            (default) = 'h264', 'vp9', 'vp8', 'mpeg4', 'mpeg4+mp4', 'h264+mp4', 'vp8+webm', 'vp9+webm', 'png', 'png/P', 'png/L', 'webp', 'rgb', 'rgb24', 'rgb32', 'jpeg', 'h265', 'mpeg1', 'mpeg2', 'scroll', 'grayscale'  <class 'list'>
headerbar             (used)   = 'yes'                             <class 'str'>
headerbar            (default) = 'auto'                            <class 'str'>
log-file              (used)   = 'display-$DISPLAY-$TIMESTAMP.log'  <class 'str'>
log-file             (default) = '$DISPLAY.log'                    <class 'str'>
microphone            (used)   = 'disabled'                        <class 'str'>
microphone           (default) = 'off'                             <class 'str'>
min-quality           (used)   = 0                                 <class 'int'>
min-quality          (default) = 30                                <class 'int'>
min-speed             (used)   = 0                                 <class 'int'>
min-speed            (default) = 30                                <class 'int'>
packet-encoders       (used)   = 'rencode', 'bencode', 'yaml'      <class 'list'>
packet-encoders      (default) = 'rencode', 'bencode', 'yaml'      <class 'tuple'>
pdf-printer           (used)   = ''                                <class 'str'>
pdf-printer          (default) = '/usr/share/ppd/cupsfilters/Generic-PDF_Printer-PDF.ppd'  <class 'str'>
pings                 (used)   = 3                                 <class 'int'>
pings                (default) = 5                                 <class 'int'>
postscript-printer    (used)   = ''                                <class 'str'>
postscript-printer   (default) = 'drv:///sample.drv/generic.ppd'   <class 'str'>
pulseaudio-configure-commands           = 'pactl set-default-sink Xpra-Speaker', 'pactl set-default-source Xpra-Microphone.monitor'
speaker               (used)   = 'disabled'                        <class 'str'>
speaker              (default) = 'on'                              <class 'str'>
ssl-ca-certs                   = 'default'
start-on-last-client-exit  (used)   = 'bash -c 'xpra id "${DISPLAY}" | grep session-type= | cut -d = -f 2 | grep -qP "shadow" || exit 0 ; env DBUS_SESSION_BUS_ADDRESS="$(cut -f 2- -d= "${XDG_RUNTIME_DIR}/dbus-session")" gnome-screensaver-command -l''  <class 'list'>
start-on-last-client-exit (default) =                                   <class 'list'>
webcam                (used)   = 'no'                              <class 'str'>
webcam               (default) = 'auto'                            <class 'str'>
xvfb                  (used)   = 'Xvfb +extension GLX +extension Composite -screen 0  8192x4096x24+32 -nolisten tcp -noreset -auth $XAUTHORITY  -dpi 96'  <class 'str'>
xvfb                 (default) = 'Xvfb +extension GLX +extension Composite -screen 0 \\n    8192x4096x24+32 -nolisten tcp -noreset -auth $XAUTHORITY \\n    -dpi 96'  <class 'str'>
```

(although, some of those will "soon" change/be reverted)

**Comment by totaam** [comment]
My bad!
We check for `None` values explicitly. So `rencode` is fine and it is enabled on both your systems!

(and the fix will land in the next update - closing!)

**Comment by stdedos** [comment]
I am lost as to what happened :/

* If `rencode` is enabled, why is it not used? You seem to favor it (and I assume you wrote the code accordingly too)
* The `None` fix you did already, or something else?

**Comment by totaam** [comment]
> If `rencode` is enabled, why is it not used?

It was used. I guessed wrong.

> The `None` fix you did already, or something else?

I did add an explicit check so that it also blows up with `rencode`, as it should. (and then forgot about it..)

**Comment by stdedos** [comment]
This is also interesting:
```
packet-encoders       (used)   = 'rencode', 'bencode', 'yaml'      <class 'list'>
packet-encoders      (default) = 'rencode', 'bencode', 'yaml'      <class 'tuple'>
```

How do I make that one disappear? 😕

**Comment by stdedos** [comment]
What about these ones?

```console
$ grep -E '^encodings' 30_picture.conf
encodings = h264, vp9, vp8, mpeg4, mpeg4+mp4, h264+mp4, vp8+webm, vp9+webm, png, png/P, png/L, webp, rgb, rgb24, rgb32, jpeg, h265, mpeg1, mpeg2, scroll, grayscale
$ xpra showconfig | grep -P '\((used|default)'
encodings             (used)   = 'h264, vp9, vp8, mpeg4, mpeg4+mp4, h264+mp4, vp8+webm, vp9+webm, png, png/P, png/L, webp, rgb, rgb24, rgb32, jpeg, h265, mpeg1, mpeg2, scroll, grayscale'  <class 'list'>
encodings            (default) = 'h264', 'vp9', 'vp8', 'mpeg4', 'mpeg4+mp4', 'h264+mp4', 'vp8+webm', 'vp9+webm', 'png', 'png/P', 'png/L', 'webp', 'rgb', 'rgb24', 'rgb32', 'jpeg', 'h265', 'mpeg1', 'mpeg2', 'scroll', 'grayscale'  <class 'list'>

$ grep -E '^encodings' 30_picture.conf
encodings = 'h264', 'vp9', 'vp8', 'mpeg4', 'mpeg4+mp4', 'h264+mp4', 'vp8+webm', 'vp9+webm', 'png', 'png/P', 'png/L', 'webp', 'rgb', 'rgb24', 'rgb32', 'jpeg', 'h265', 'mpeg1', 'mpeg2', 'scroll', 'grayscale'
$ xpra showconfig | grep -P '\((used|default)' | grep encodings
encodings             (used)   = ''h264', 'vp9', 'vp8', 'mpeg4', 'mpeg4+mp4', 'h264+mp4', 'vp8+webm', 'vp9+webm', 'png', 'png/P', 'png/L', 'webp', 'rgb', 'rgb24', 'rgb32', 'jpeg', 'h265', 'mpeg1', 'mpeg2', 'scroll', 'grayscale''  <class 'list'>
encodings            (default) = 'h264', 'vp9', 'vp8', 'mpeg4', 'mpeg4+mp4', 'h264+mp4', 'vp8+webm', 'vp9+webm', 'png', 'png/P', 'png/L', 'webp', 'rgb', 'rgb24', 'rgb32', 'jpeg', 'h265', 'mpeg1', 'mpeg2', 'scroll', 'grayscale'  <class 'list'>
```

**Comment by totaam** [comment]
> What about these ones?

Fixed by the commits above, and also 152b8d2c1c5b33f55c8509c2c34679892ab125dc, 97b0b0582b0b68818e145721430f8e4f1d980a46, e21a170a1e57480f115c677d2eda94ba47a7a581

**Comment by stdedos** [comment]
Awesome! Looking forward to the next beta (whenever it comes 😀)

**Comment by stdedos** [comment]
Verified `showconfig` changes as fixed too
