### ISSUE TITLE
AttributeError: 'ClientConnectionMuxer' object has no attribute 'update_mouse'

### ISSUE THREAD

**Issue by stdedos** [Xpra-org/xpra#3084]
The log file looks like:

```console
$ ls -lah display-\:4-20210409-085700.log
-rw-r--r-- 1 u u 1,2G Απρ   9 17:39 display-:4-20210409-085700.log
$ cat display-\:4-20210409-085700.log | perl -pe 's/^\d\d\d\d-\d\d-\d\d \d\d:\d\d:\d\d,\d\d\d //g' | awk '!a[$0]++ {}; END { for (x in a) { printf "%s%%%s\n", a[x], x } }' | sort -nrk1 -t'%' | column -ts% | less
10418342   [Errno 24] Too many open files
10418338  Error: cannot accept new connection:
2133      Traceback (most recent call last):
1442        File "/usr/lib/python3/dist-packages/xpra/x11/x11_server_core.py", line 804, in _motion_signaled
1442      AttributeError: 'ClientConnectionMuxer' object has no attribute 'update_mouse'
998           ss.update_mouse(wid, event.x_root, event.y_root, event.x, event.y)
461       OSError: Load averages are unobtainable
414         File "/usr/lib/python3/dist-packages/xpra/server/server_base.py", line 918, in call_handler
412        using <bound method NetworkStateServer._process_ping of <server.XpraServer object at 0x7f6a8ec31680 (xpra+x11+server+XpraServer at 0x2066960)>>
412        received from Protocol(unix-domain socket:/run/user/1000/xpra/h-4):
412           handler(proto, packet)
412         File "/usr/lib/python3/dist-packages/xpra/server/source/networkstate_mixin.py", line 83, in process_ping
412         File "/usr/lib/python3/dist-packages/xpra/server/server_base.py", line 928, in process_packet
412         File "/usr/lib/python3/dist-packages/xpra/server/mixins/networkstate_server.py", line 193, in _process_ping
412       Error processing a 'ping' packet
412           call_handler()
330       New unix-domain connection received
226
224       Original exception was:
224       Error in sys.excepthook:
223         File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 118, in apport_excepthook
222       OSError: [Errno 24] Too many open files: '/proc/272753'
222         File "/usr/lib/python3/dist-packages/apport/report.py", line 593, in add_proc_info
156        received 0 bytes
156        after 21 seconds
133        on '/home/u/.xpra/h-4'
101        on '/run/user/1000/xpra/h-4'
96         on '/run/xpra/h-4'
55        Warning: failed to load '/var/lib/dbus/machine-id':
55        Warning: failed to load '/etc/machine-id':
55        Error: connection timed out: unix-domain socket:/run/xpra/h-4
55         [Errno 24] Too many open files: '/var/lib/dbus/machine-id'
55         [Errno 24] Too many open files: '/etc/machine-id'
54        Error: connection timed out: unix-domain socket:/home/u/.xpra/h-4
49            si = self.get_server_info()
49            si["load"] = tuple(int(x*1000) for x in os.getloadavg())
49            info = super().get_info(proto=proto, client_uuids=client_uuids)
49            info = ServerCore.get_info(self, proto)
49            info = self.get_info(proto, *args)
49          File "/usr/lib/python3/dist-packages/xpra/x11/x11_server_base.py", line 203, in get_info
49          File "/usr/lib/python3/dist-packages/xpra/server/server_core.py", line 2012, in get_info
49          File "/usr/lib/python3/dist-packages/xpra/server/server_core.py", line 2000, in get_server_info
49          File "/usr/lib/python3/dist-packages/xpra/server/server_core.py", line 1949, in _get_info_in_thread
49          File "/usr/lib/python3/dist-packages/xpra/server/server_base.py", line 604, in get_info
49        Error during info collection using <bound method X11ServerBase.get_info of <server.XpraServer object at 0x7f6a8ec31680 (xpra+x11+server+XpraServer at 0x2066960)>>
47        Error: connection timed out: unix-domain socket:/run/user/1000/xpra/h-4
38        send_delayed_regions: sent 1 regions using ['png']
29        Warning: more than 30 clipboard requests per second!
15        Warning: delayed region timeout
15         region is 15 seconds old, will retry - bad connection?
7         Handshake complete; enabling connection
6         Warning: PRIMARY selection request for 'TARGETS' timed out
6         send_delayed_regions: sent 1 regions using ['rgb24']
6         lpadmin: Printer drivers are deprecated and will stop working in a future version of CUPS.
5         /usr/lib/python3/dist-packages/gi/overrides/Gtk.py:1632: Warning: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
5         top client version 4.1.2-r2 64-bit
5           return _Gtk_main(*args, **kwargs)
5          connected from 'h' as 'u' - 'n'
4          server upgrade
4         send_delayed_regions: using full window update 2560x1377 as   png: merged region covers almost the whole window, from <bound method WindowSource.get_refresh_encoding of WindowVideoSource(52 : (2560, 1377))>
4         send_delayed_regions: using full window update 1600x837 as   png: merged region covers almost the whole window, from <bound method WindowSource.get_refresh_encoding of WindowVideoSource(20 : (1600, 837))>
4         send_delayed_regions: sent 3 regions using ['png', 'png', 'png']
3         send_delayed_regions: using full window update 320x208 as   png: merged region covers almost the whole window, from <bound method WindowSource.get_refresh_encoding of WindowVideoSource(39 : (320, 208))>
3         send_delayed_regions: using full window update 2560x1377 as   png: bytes cost (3093136) too high (max 2115072), from <bound method WindowSource.get_refresh_encoding of WindowVideoSource(52 : (2560, 1377))>
3         send_delayed_regions: using full window update 2560x1377 as   png: bytes cost (2913360) too high (max 2115072), from <bound method WindowSource.get_refresh_encoding of WindowVideoSource(52 : (2560, 1377))>
3         send_delayed_regions: sent 2 regions using ['png', 'png']
3         send_delayed_regions: packet_cost=3093136, merge_threshold=2115072, pixel_count=3091088
3         send_delayed_regions: packet_cost=2913360, merge_threshold=2115072, pixel_count=2911312
3           self.window = None
2         > Warning:          Symbol map for key <KPDL> redefined
... (more shown in less)
```

Hence, you'll have to make do with my diagnostics right now 😕 

```log
     21 2021-04-09 08:57:03,193 Python/GTK3 Microsoft Windows 10 aero client version 4.1-r28507 64-bit
     22 2021-04-09 08:57:03,193  OpenGL is enabled with Intel(R) HD Graphics 4000
     24 2021-04-09 08:57:03,195 setting key repeat rate from client: 500ms delay / 33ms interval
     25 2021-04-09 08:57:03,196 setting keyboard layout to 'us'
     26 2021-04-09 08:57:03,232  client root window size is 4160x1440 with 1 display:
     27 2021-04-09 08:57:03,232   Default (1100x381 mm - DPI: 96x96) workarea: 4160x1400
     28 2021-04-09 08:57:03,232     Generic PnP Monitor 1600x900 at 0x534 (309x174 mm - DPI: 132x131) workarea: 1600x860 at 0x534
     29 2021-04-09 08:57:03,232     C32JG5x 2560x1440 at 1600x0 (697x392 mm - DPI: 93x93) workarea: 2560x1400 at 1600x0
     30 2021-04-09 08:57:03,258 GStreamer version 1.16.2 for Python 3.8.5 64-bit
     31 2021-04-09 08:57:03,735 server virtual display now set to 4160x1440
     32 2021-04-09 08:57:03,857 DPI set to 96 x 96
     33 2021-04-09 08:57:03,890 New unix-domain connection received
```
```log
    563 2021-04-09 10:33:13,907 New unix-domain connection received
    564 2021-04-09 10:33:13,908  on '/home/u/.xpra/h-4'
    565 Traceback (most recent call last):
    566   File "/usr/lib/python3/dist-packages/xpra/x11/x11_server_core.py", line 804, in _motion_signaled
    567     ss.update_mouse(wid, event.x_root, event.y_root, event.x, event.y)
    568 AttributeError: 'ClientConnectionMuxer' object has no attribute 'update_mouse'
    569 Traceback (most recent call last):
    570   File "/usr/lib/python3/dist-packages/xpra/x11/x11_server_core.py", line 804, in _motion_signaled
    571     ss.update_mouse(wid, event.x_root, event.y_root, event.x, event.y)
    572 AttributeError: 'ClientConnectionMuxer' object has no attribute 'update_mouse'
    573 Traceback (most recent call last):
    574   File "/usr/lib/python3/dist-packages/xpra/x11/x11_server_core.py", line 804, in _motion_signaled
    575     ss.update_mouse(wid, event.x_root, event.y_root, event.x, event.y)
    576 AttributeError: 'ClientConnectionMuxer' object has no attribute 'update_mouse'
    577 Traceback (most recent call last):
    578   File "/usr/lib/python3/dist-packages/xpra/x11/x11_server_core.py", line 804, in _motion_signaled
    579     ss.update_mouse(wid, event.x_root, event.y_root, event.x, event.y)
    580 AttributeError: 'ClientConnectionMuxer' object has no attribute 'update_mouse'
    581 Traceback (most recent call last):
    582   File "/usr/lib/python3/dist-packages/xpra/x11/x11_server_core.py", line 804, in _motion_signaled
    583     ss.update_mouse(wid, event.x_root, event.y_root, event.x, event.y)
    584 AttributeError: 'ClientConnectionMuxer' object has no attribute 'update_mouse'
    585 Traceback (most recent call last):
    586   File "/usr/lib/python3/dist-packages/xpra/x11/x11_server_core.py", line 804, in _motion_signaled
    587     ss.update_mouse(wid, event.x_root, event.y_root, event.x, event.y)
    588 AttributeError: 'ClientConnectionMuxer' object has no attribute 'update_mouse'
    589 Traceback (most recent call last):
    590   File "/usr/lib/python3/dist-packages/xpra/x11/x11_server_core.py", line 804, in _motion_signaled
    591     ss.update_mouse(wid, event.x_root, event.y_root, event.x, event.y)
    592 AttributeError: 'ClientConnectionMuxer' object has no attribute 'update_mouse'
    593 2021-04-09 10:33:37,639 xpra client 6 disconnected.
```
```log
   4657 Traceback (most recent call last):
   4658   File "/usr/lib/python3/dist-packages/xpra/x11/x11_server_core.py", line 804, in _motion_signaled
   4659 AttributeError: 'ClientConnectionMuxer' object has no attribute 'update_mouse'
   4660 Error in sys.excepthook:
   4661 Traceback (most recent call last):
   4662   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 118, in apport_excepthook
   4663   File "/usr/lib/python3/dist-packages/apport/report.py", line 647, in add_proc_info
   4664   File "/usr/lib/python3/dist-packages/apport/report.py", line 1777, in get_logind_session
   4665 OSError: [Errno 24] Too many open files: 'cgroup'
   4666 
   4667 Original exception was:
   4668 Traceback (most recent call last):
   4669   File "/usr/lib/python3/dist-packages/xpra/x11/x11_server_core.py", line 804, in _motion_signaled
   4670 AttributeError: 'ClientConnectionMuxer' object has no attribute 'update_mouse'
   4671 Traceback (most recent call last):
   4672   File "/usr/lib/python3/dist-packages/xpra/x11/x11_server_core.py", line 804, in _motion_signaled
   4673 AttributeError: 'ClientConnectionMuxer' object has no attribute 'update_mouse'
   4674 Error in sys.excepthook:
   4675 Traceback (most recent call last):
   4676   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 118, in apport_excepthook
   4677   File "/usr/lib/python3/dist-packages/apport/report.py", line 593, in add_proc_info
   4678 OSError: [Errno 24] Too many open files: '/proc/272753'
   4679 
```
```log
   5016 Original exception was:
   5017 Traceback (most recent call last):
   5018   File "/usr/lib/python3/dist-packages/xpra/x11/x11_server_core.py", line 804, in _motion_signaled
   5019 AttributeError: 'ClientConnectionMuxer' object has no attribute 'update_mouse'
   5020 2021-04-09 10:36:05,849 Warning: failed to load '/etc/machine-id':
   5021 2021-04-09 10:36:05,849  [Errno 24] Too many open files: '/etc/machine-id'
   5022 2021-04-09 10:36:05,849 Warning: failed to load '/var/lib/dbus/machine-id':
   5023 2021-04-09 10:36:05,849  [Errno 24] Too many open files: '/var/lib/dbus/machine-id'
   5024 2021-04-09 10:36:05,849 Error during info collection using <bound method X11ServerBase.get_info of <server.XpraServer object at 0x7f6a8ec31680 (xpra+x11+server+XpraServer at 0x2066960)>>
   5025 Traceback (most recent call last):
   5026   File "/usr/lib/python3/dist-packages/xpra/server/server_core.py", line 1949, in _get_info_in_thread
   5027     info = self.get_info(proto, *args)
   5028   File "/usr/lib/python3/dist-packages/xpra/x11/x11_server_base.py", line 203, in get_info
   5029     info = super().get_info(proto=proto, client_uuids=client_uuids)
   5030   File "/usr/lib/python3/dist-packages/xpra/server/server_base.py", line 604, in get_info
   5031     info = ServerCore.get_info(self, proto)
   5032   File "/usr/lib/python3/dist-packages/xpra/server/server_core.py", line 2012, in get_info
   5033     si = self.get_server_info()
   5034   File "/usr/lib/python3/dist-packages/xpra/server/server_core.py", line 2000, in get_server_info
   5035     si["load"] = tuple(int(x*1000) for x in os.getloadavg())
   5036 OSError: Load averages are unobtainable
   5037 2021-04-09 10:36:06,794 client   5 @18.445 server is not responding, drawing spinners over the windows
   5038 2021-04-09 10:36:06,856 Warning: failed to load '/etc/machine-id':
   5039 2021-04-09 10:36:06,856  [Errno 24] Too many open files: '/etc/machine-id'
   5040 2021-04-09 10:36:06,856 Warning: failed to load '/var/lib/dbus/machine-id':
   5041 2021-04-09 10:36:06,856  [Errno 24] Too many open files: '/var/lib/dbus/machine-id'
   5042 2021-04-09 10:36:06,857 Error during info collection using <bound method X11ServerBase.get_info of <server.XpraServer object at 0x7f6a8ec31680 (xpra+x11+server+XpraServer at 0x2066960)>>
   5043 Traceback (most recent call last):
   5044   File "/usr/lib/python3/dist-packages/xpra/server/server_core.py", line 1949, in _get_info_in_thread
   5045     info = self.get_info(proto, *args)
   5046   File "/usr/lib/python3/dist-packages/xpra/x11/x11_server_base.py", line 203, in get_info
   5047     info = super().get_info(proto=proto, client_uuids=client_uuids)
   5048   File "/usr/lib/python3/dist-packages/xpra/server/server_base.py", line 604, in get_info
   5049     info = ServerCore.get_info(self, proto)
   5050   File "/usr/lib/python3/dist-packages/xpra/server/server_core.py", line 2012, in get_info
   5051     si = self.get_server_info()
   5052   File "/usr/lib/python3/dist-packages/xpra/server/server_core.py", line 2000, in get_server_info
   5053     si["load"] = tuple(int(x*1000) for x in os.getloadavg())
   5054 OSError: Load averages are unobtainable
   5055 2021-04-09 10:36:07,152 client   5 @18.700 server is OK again
```
```log
   7791 2021-04-09 10:36:35,471 Error processing a 'ping' packet
   7792 2021-04-09 10:36:35,471  received from Protocol(unix-domain socket:/run/user/1000/xpra/h-4):
   7793 2021-04-09 10:36:35,471  using <bound method NetworkStateServer._process_ping of <server.XpraServer object at 0x7f6a8ec31680 (xpra+x11+server+XpraServer at 0x2066960)>>
   7794 Traceback (most recent call last):
   7795   File "/usr/lib/python3/dist-packages/xpra/server/server_base.py", line 928, in process_packet
   7796     call_handler()
   7797   File "/usr/lib/python3/dist-packages/xpra/server/server_base.py", line 918, in call_handler
   7798     handler(proto, packet)
   7799   File "/usr/lib/python3/dist-packages/xpra/server/mixins/networkstate_server.py", line 193, in _process_ping
   7800   File "/usr/lib/python3/dist-packages/xpra/server/source/networkstate_mixin.py", line 83, in process_ping
   7801 OSError: Load averages are unobtainable
```
```log
   8513 2021-04-09 10:36:53,916 Warning: failed to load '/etc/machine-id':
   8514 2021-04-09 10:36:53,917  [Errno 24] Too many open files: '/etc/machine-id'
   8515 2021-04-09 10:36:53,917 Warning: failed to load '/var/lib/dbus/machine-id':
   8516 2021-04-09 10:36:53,917  [Errno 24] Too many open files: '/var/lib/dbus/machine-id'
   8517 2021-04-09 10:36:53,918 Error during info collection using <bound method X11ServerBase.get_info of <server.XpraServer object at 0x7f6a8ec31680 (xpra+x11+server+XpraServer at 0x2066960)>>
   8518 Traceback (most recent call last):
   8519   File "/usr/lib/python3/dist-packages/xpra/server/server_core.py", line 1949, in _get_info_in_thread
   8520     info = self.get_info(proto, *args)
   8521   File "/usr/lib/python3/dist-packages/xpra/x11/x11_server_base.py", line 203, in get_info
   8522     info = super().get_info(proto=proto, client_uuids=client_uuids)
   8523   File "/usr/lib/python3/dist-packages/xpra/server/server_base.py", line 604, in get_info
   8524     info = ServerCore.get_info(self, proto)
   8525   File "/usr/lib/python3/dist-packages/xpra/server/server_core.py", line 2012, in get_info
   8526     si = self.get_server_info()
   8527   File "/usr/lib/python3/dist-packages/xpra/server/server_core.py", line 2000, in get_server_info
   8528     si["load"] = tuple(int(x*1000) for x in os.getloadavg())
   8529 OSError: Load averages are unobtainable
   8530 2021-04-09 10:36:54,477 xpra client 7 disconnected.
   8531 2021-04-09 10:36:54,480 Error: cannot accept new connection:
   8532 2021-04-09 10:36:54,480  [Errno 24] Too many open files
   8533 2021-04-09 10:36:54,480 Error: cannot accept new connection:
   8534 2021-04-09 10:36:54,480  [Errno 24] Too many open files
```

Also, that specific server does not exist anymore - I did `xpra upgrade` to replace its "supervisor"
[_usr_bin_xpra.1000.crash.zip](https://github.com/Xpra-org/xpra/files/6286778/_usr_bin_xpra.1000.crash.zip)

**Comment by totaam** [comment]
I believe that the first backtrace (`AttributeError: 'ClientConnectionMuxer' object has no attribute 'update_mouse'`) ended up triggering the `apport_python_hook` which in turn failed when it ran out of file descriptors.
This caused the second backtrace (`OSError: Load averages are unobtainable`).

Both should be fixed now. Thanks!
