### ISSUE TITLE
Xpra_Browser v4.2.x-g11293f0e3 crashes on Mac OS X 10.16

### ISSUE THREAD

**Issue by d4nl** [Xpra-org/xpra#3161]
Info:
```
$ Xpra_Version_info
Build:
* branch                          : v4.2.x
* commit                          : g11293f0e3
* local_modifications             : 0
* revision                        : 0
* version                         : 4.2

Platform:
* architecture                    : 64bit,
* machine                         : x86_64
* name                            : Mac OS X 10.16
* platform                        : macOS-10.16-x86_64-i386-64bit
* processor                       : Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
* release                         : 20.5.0
* sys                             : darwin
* sysrelease                      : 10.16

Host:
* byteorder                       : little
* gid                             : 20
* hostname                        : user-MBP.local
* pid                             : 50320
* pyobjc.version                  : 7.1
* python
  - bits                          : 64
  - full_version                  : 3.9.5 (default, May  8 2021, 07:32:46) \n[Clang 11.0.0 (clang-1100.0.33.12)]
  - version                       : 3.9.5
* uid                             : 501

$ Xpra_Path_info
* app
  - default
    - dir                         : /Applications/Xpra.app/Contents/Resources/share/xpra
* client-socket
  - dirs                          : ~/.xpra/clients
* default_conf
  - dirs                          : /Applications/Xpra.app/Contents/Resources/etc/xpra
* desktop-background              : /System/Library/CoreServices/DefaultDesktop.jpg, /Library/Desktop Pictures/*jpg
* download
  - dir                           : ~/Downloads
* home                            : /Users/user
* icons                           : /Applications/Xpra.app/Contents/Resources/share/xpra/icons
* install
  - prefix                        : /Applications/Xpra.app/Contents/Resources
* libexec
  - dir                           : /Applications/Xpra.app/Contents/Helpers
* log
  - dirs                          : ~/Library/Logs/Xpra, /tmp
* mmap
  - dir                           : /var/folders/p4/5vq_trp90yv7fwn2gtwdqhh80000gn/T
* nodock_command                  : /Applications/Xpra.app/Contents/Xpra_NoDock.app/Contents/Helpers/Xpra
* python-execfile                 : /Applications/Xpra.app/Contents/Helpers/Python
* resources                       : /Applications/Xpra.app/Contents/Resources/
* socket
  - dirs                          : /var/tmp/501-Xpra, ~/.xpra
* sound_command                   : /Applications/Xpra.app/Contents/Xpra_NoDock.app/Contents/Helpers/Xpra
* ssh-known-hosts                 : ~/.ssh/known_hosts, ~/ssh/known_hosts
* ssh_conf
  - dirs                          : /private/etc, /etc/ssh, /usr/local/etc/ssh, ~/.ssh, ~/ssh
* sshpass_command                 : /Applications/Xpra.app/Contents/Resources/bin/sshpass
* system_conf
  - dirs                          : /Library/Application Support/Xpra, /etc/xpra
* user_conf
  - dirs                          : ~/Library/Application Support/Xpra, ~/.xpra
* xpra-module                     : /Applications/Xpra.app/Contents/Resources/lib/python/xpra/
* xpra-tmp
  - dir                           : /var/folders/p4/5vq_trp90yv7fwn2gtwdqhh80000gn/T
* xpra_command                    : /Applications/Xpra.app/Contents/MacOS/Xpra
```

Crash:
```
$ Xpra_Browser

(xpra-session-browser:51708): Gtk-CRITICAL **: 22:01:45.376: gtk_window_add_accel_group: assertion 'GTK_IS_WINDOW (window)' failed
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Applications/Xpra.app/Contents/Resources/lib/python/xpra/client/gtk_base/mdns_gui.py", line 101, in main
    return do_main(opts)
  File "/Applications/Xpra.app/Contents/Resources/lib/python/xpra/client/gtk_base/mdns_gui.py", line 87, in do_main
    if not get_listener_class():
  File "/Applications/Xpra.app/Contents/Resources/lib/python/xpra/net/mdns/__init__.py", line 30, in get_listener_class
    from xpra.net.mdns.zeroconf_listener import ZeroconfListener
  File "/Applications/Xpra.app/Contents/Resources/lib/python/xpra/net/mdns/zeroconf_listener.py", line 8, in <module>
    from zeroconf import ServiceBrowser, Zeroconf        #@UnresolvedImport
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "zeroconf/__init__.pyc", line 40, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "ifaddr/__init__.pyc", line 29, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "ifaddr/_posix.pyc", line 40, in <module>
  File "ctypes/__init__.pyc", line 374, in __init__
OSError: dlopen(/System/Library/Frameworks/c.framework/c, 6): image not found
```

Previous version (`v4.1.x-g3b149d83b`) does not present this problem

**Comment by totaam** [comment]
Is this an M1?
Could well be the same problem as #3150 and #3063.
Apple broke dlopen, which impacts anything that uses ctypes.

**Comment by d4nl** [comment]
> Is this an M1 or are you running Big Sur?
> Could well be the same problem as #3150 and #3063.
> Apple broke dlopen, which impacts anything that uses ctypes.

Yes, this on an intel platform, macbook pro 2017 running bigsur:
```
...
Platform:
* architecture                    : 64bit,
* machine                         : x86_64
* name                            : Mac OS X 10.16
* platform                        : macOS-10.16-x86_64-i386-64bit
* processor                       : Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
* release                         : 20.5.0
* sys                             : darwin
* sysrelease                      : 10.16
...
```

**Comment by totaam** [comment]
Can you try the latest 4.3 macos beta build from here: https://xpra.org/beta/MacOS/
It should work.

**Comment by totaam** [comment]
Please try the latest 4.3 beta packages from https://xpra.org/beta/MacOS (r29282 or later)
These should work.

**Comment by d4nl** [comment]
Seeing the same crash as before:

```
$ Xpra_Version_info
Build:
* branch                          : master
* commit                          : gedfe3234e
* local_modifications             : 0
* revision                        : 29282
* version                         : 4.3

Platform:
* architecture                    : 64bit,
* machine                         : x86_64
* name                            : Mac OS X 10.16
* platform                        : macOS-10.16-x86_64-i386-64bit
* processor                       : Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
* release                         : 20.5.0
* sys                             : darwin
* sysrelease                      : 10.16

Host:
* byteorder                       : little
* gid                             : 20
* hostname                        : user-MBP.local
* pid                             : 53871
* pyobjc.version                  : 7.1
* python
  - bits                          : 64
  - full_version                  : 3.9.5 (default, May  8 2021, 07:32:46) \n[Clang 11.0.0 (clang-1100.0.33.12)]
  - version                       : 3.9.5
* uid                             : 501
```

```
$ Xpra_Path_info
* app
  - default
    - dir                         : /Applications/Xpra.app/Contents/Resources/share/xpra
* client-socket
  - dirs                          : ~/.xpra/clients
* default_conf
  - dirs                          : /Applications/Xpra.app/Contents/Resources/etc/xpra
* desktop-background              : /System/Library/CoreServices/DefaultDesktop.jpg, /Library/Desktop Pictures/*jpg
* download
  - dir                           : ~/Downloads
* home                            : /Users/user
* icons                           : /Applications/Xpra.app/Contents/Resources/share/xpra/icons
* install
  - prefix                        : /Applications/Xpra.app/Contents/Resources
* libexec
  - dir                           : /Applications/Xpra.app/Contents/Helpers
* log
  - dirs                          : ~/Library/Logs/Xpra, /tmp
* mmap
  - dir                           : /var/folders/p4/5vq_trp90yv7fwn2gtwdqhh80000gn/T
* nodock_command                  : /Applications/Xpra.app/Contents/Xpra_NoDock.app/Contents/Helpers/Xpra
* python-execfile                 : /Applications/Xpra.app/Contents/Helpers/Python
* resources                       : /Applications/Xpra.app/Contents/Resources/
* socket
  - dirs                          : /var/tmp/501-Xpra, ~/.xpra
* sound_command                   : /Applications/Xpra.app/Contents/Xpra_NoDock.app/Contents/Helpers/Xpra
* ssh-known-hosts                 : ~/.ssh/known_hosts, ~/ssh/known_hosts
* ssh_conf
  - dirs                          : /private/etc, /etc/ssh, /usr/local/etc/ssh, ~/.ssh, ~/ssh
* sshpass_command                 : /Applications/Xpra.app/Contents/Resources/bin/sshpass
* system_conf
  - dirs                          : /Library/Application Support/Xpra, /etc/xpra
* user_conf
  - dirs                          : ~/Library/Application Support/Xpra, ~/.xpra
* xpra-module                     : /Applications/Xpra.app/Contents/Resources/lib/python/xpra/
* xpra-tmp
  - dir                           : /var/folders/p4/5vq_trp90yv7fwn2gtwdqhh80000gn/T
* xpra_command                    : /Applications/Xpra.app/Contents/MacOS/Xpra
```

Crash info:
```
$ Xpra_Browser

(xpra-session-browser:53939): Gtk-CRITICAL **: 18:05:47.925: gtk_window_add_accel_group: assertion 'GTK_IS_WINDOW (window)' failed
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Applications/Xpra.app/Contents/Resources/lib/python/xpra/client/gtk_base/mdns_gui.py", line 101, in main
    return do_main(opts)
  File "/Applications/Xpra.app/Contents/Resources/lib/python/xpra/client/gtk_base/mdns_gui.py", line 87, in do_main
    if not get_listener_class():
  File "/Applications/Xpra.app/Contents/Resources/lib/python/xpra/net/mdns/__init__.py", line 30, in get_listener_class
    from xpra.net.mdns.zeroconf_listener import ZeroconfListener
  File "/Applications/Xpra.app/Contents/Resources/lib/python/xpra/net/mdns/zeroconf_listener.py", line 8, in <module>
    from zeroconf import ServiceBrowser, Zeroconf        #@UnresolvedImport
  File "zeroconf/__init__.pyc", line 40, in <module>
  File "ifaddr/__init__.pyc", line 29, in <module>
  File "ifaddr/_posix.pyc", line 40, in <module>
  File "ctypes/__init__.pyc", line 374, in __init__
OSError: dlopen(/System/Library/Frameworks/c.framework/c, 6): image not found
```

**Comment by totaam** [comment]
Oh. I get it, I think.
You're running the wrapper script `Xpra_Browser` and this doesn't go through the usual main function which hooks the workaround for Big Sur.
Try: `Xpra mdns-gui` instead.

**Comment by totaam** [comment]
The commit above should fix the `Xpra_Browser` helper script.
Though there may be other scripts that end up calling ctypes and failing, those would also need patching up.

You can find a beta build with this fix here: https://xpra.org/beta/MacOS (use 4.3-r29294 or later)

**Comment by d4nl** [comment]
I can confirm that the latest beta solves this issue.

Thank you for the quick response!
