### ISSUE TITLE
xpra keyboard-test stacktrace: NameError: global name 'Gdk' is not defined, centos-7 server 3.1-10.10xpra1.el7

### ISSUE THREAD

**Issue by sto6** [Xpra-org/xpra#3213]
I believe keyboard-test did work some weeks back with recent but older xpra packages.
(Client is macos: Xpra-Python3-x86_64-4.1.3-r1.pkg.)
Thank you.

server started like:
```
xpra start-desktop :4 --exit-with-children=yes --start-child=startxfce4 \
    --keyboard-layout=us --resize-display=yes --xsettings=no --desktop-scaling=no --dpi=96
```

```
$ uname -a
Linux host-c7 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
```
$ xpra keyboard-test
xpra main error:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/xpra/scripts/main.py", line 118, in main
    return run_mode(script_file, err, options, args, mode, defaults)
  File "/usr/lib64/python2.7/site-packages/xpra/scripts/main.py", line 542, in run_mode
    return gtk_view_keyboard.main()
  File "/usr/lib64/python2.7/site-packages/xpra/gtk_common/gtk_view_keyboard.py", line 172, in main
    KeyboardStateInfoWindow()
  File "/usr/lib64/python2.7/site-packages/xpra/gtk_common/gtk_view_keyboard.py", line 52, in __init__
    display = Gdk.Display.get_default()
NameError: global name 'Gdk' is not defined
```

```
Installed Packages
ffmpeg-xpra.x86_64              4.3.1-4.el7_9                     @xpra
libvpx-xpra.x86_64              1.9.0-1.el7_9                     @xpra
libwebp-xpra.x86_64             1.1.0-1.el7_9                     @xpra
pygtkglext.x86_64               1.1.0-31.xpra1.el7_9              @xpra
python2-pyopengl.x86_64         3.1.5-1xpra1.el7_9                @xpra
python2-rencode.x86_64          1.0.6-1.xpra1.el7_9               @xpra
python2-xpra.x86_64             3.1-10.10xpra1.el7                @xpra
python2-xpra-client.x86_64      3.1-10.10xpra1.el7                @xpra
python2-xpra-server.x86_64      3.1-10.10xpra1.el7                @xpra
x264-xpra.x86_64                20210110-1.el7_9                  @xpra
xorg-x11-drv-dummy.x86_64       0.3.8-1.xpra2.el7_9               @xpra
xpra.x86_64                     3.1-10.10xpra1.el7                @xpra
xpra-common.noarch              3.1-10.10xpra1.el7                @xpra
xpra-common-client.noarch       3.1-10.10xpra1.el7                @xpra
xpra-common-server.noarch       3.1-10.10xpra1.el7                @xpra
xpra-html5.noarch               3.0.13-10.r28351xpra1.el7_9       @xpra
```

**Comment by totaam** [comment]
Ooops, sorry about that.
The backport brought in some python3-isms. The commit above fixes that.
