### ISSUE TITLE
connection lost, and lost, and lost, and...

### ISSUE THREAD

**Issue by karlkleinpaste** [Xpra-org/xpra#3219]
very bad update to latest, in all of f33, f34, and c8:
```
python3-xpra-4.3-10.r29494.fc33.x86_64.rpm
python3-xpra-audio-4.3-10.r29494.fc33.x86_64.rpm
python3-xpra-client-4.3-10.r29494.fc33.x86_64.rpm
python3-xpra-server-4.3-10.r29494.fc33.x86_64.rpm
xpra-4.3-10.r29494.fc33.x86_64.rpm
xpra-common-4.3-10.r29494.fc33.noarch.rpm
xpra-common-client-4.3-10.r29494.fc33.noarch.rpm
xpra-common-server-4.3-10.r29494.fc33.noarch.rpm
```
attempting to open new xpra session fails with repeating lost connection and re-connection. goes on without limit. attaching example logs from both local and remote ssh. note especially in ssh log, "running, N windows" and then connection repeatedly lost, where N rises on each re-connect: on slow remote connections, you can see the windows being ever so briefly created, then immediately destroyed before any content can be rendered into them as connection is lost.

it takes whacking ^C twice to get the cycle to break.

[xpra-local.txt](https://github.com/Xpra-org/xpra/files/6869704/xpra-local.txt)
[xpra-ssh.txt](https://github.com/Xpra-org/xpra/files/6869706/xpra-ssh.txt)

**Comment by totaam** [comment]
The reconnect feature #3010 probably needs a limit on retries.
And it definitely needs to strip `--start=` arguments when retrying (not so easy).

But I'm not sure why your connections drop in the first place. Will try this in a VM.

**Comment by totaam** [comment]
Reproduced - only a VM and I don't understand why - should have happened locally too!

The server log shows the problem quite clearly:
```
Traceback (most recent call last):
  File "/usr/lib64/python3.9/site-packages/xpra/net/protocol.py", line 602, in encode
    main_packet, proto_flags = self._encoder(packet)
  File "/usr/lib64/python3.9/site-packages/xpra/net/packet_encoding.py", line 27, in do_rencode
    return dumps(v), FLAGS_RENCODE
  File "rencode/rencode.pyx", line 336, in rencode._rencode.dumps
  File "rencode/rencode.pyx", line 316, in rencode._rencode.encode
  File "rencode/rencode.pyx", line 249, in rencode._rencode.encode_list
  File "rencode/rencode.pyx", line 319, in rencode._rencode.encode
  File "rencode/rencode.pyx", line 266, in rencode._rencode.encode_dict
  File "rencode/rencode.pyx", line 319, in rencode._rencode.encode
  File "rencode/rencode.pyx", line 261, in rencode._rencode.encode_dict
  File "rencode/rencode.pyx", line 319, in rencode._rencode.encode
  File "rencode/rencode.pyx", line 261, in rencode._rencode.encode_dict
  File "rencode/rencode.pyx", line 322, in rencode._rencode.encode
Exception: type <class 'function'> not handled
2021-07-23 23:26:35,177 None value in 'info-response' packet->[1]->value for key='windows'->value for key='1'->value for key='set-initial-position'
2021-07-23 23:26:35,188 unsupported type: <class 'function'> in 'info-response' packet->[1]->value for key='child'->value for key='6'->value for key='forget'
```
And then there's also `'forget': <function do_run_server.<locals>.xvfb_terminated at 0x7fc0ab8d2670>` in the process data.
This was caused by a3b153f5fca23ec5cb5949c0372d94170a680075 - the commit above fixes that.

(The window metadata also contains: `'set-initial-position': None` but that's only a problem for clients using `bencode` - like the html5 client with Safari, or older versions of the html5 client)
