### ISSUE TITLE
2 problems: centos 8 does not have /usr/bin/python; terminal resize error

### ISSUE THREAD

**Issue by karlkleinpaste** [Xpra-org/xpra#3232]
today's RPMs. centos 8 whines because there does not exist /usr/bin/python, only the version-specific /usr/bin/python3.
```
xpra start :37 --start-child=mate-terminal
using systemd-run to wrap 'start' server command
Running scope as unit: run-r8d1c89ebf03242fd946975d325e80c71.scope
/bin/bash: line 1: /usr/bin/python: No such file or directory
2021-08-05 14:07:40,525 Error 127 running source script '/etc/profile'
Entering daemon mode; any further errors will be reported to:
  /run/user/45512/xpra/37/server.log
```
of course i can make a symlink manually /usr/bin/python -> /usr/bin/python3, but it's unofficial.

once making that symlink and starting with a terminal, a simple function to induce terminal resize induces a traceback, and the resize does not occur.
```
function xresize ()
{
        echo -en '\033[8;'"$2"';'"$1"';t'
}
```
called as `xresize 200 50` for 200 columns, 50 rows. this does not succeed and induces this error:
```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/xpra/client/client_base.py", line 1058, in call_handler
    handler(packet)
  File "/usr/lib64/python3.6/site-packages/xpra/client/mixins/window_manager.py", line 1067, in _process_window_move_resize
    window.move_resize(ax, ay, aw, ah, resize_counter)
  File "/usr/lib64/python3.6/site-packages/xpra/client/gtk_base/gtk_client_window_base.py", line 2009, in move_resize
    x, y = self.adjusted_position(x, y)
  File "/usr/lib64/python3.6/site-packages/xpra/client/gtk_base/gtk_client_window_base.py", line 660, in adjusted_position
    if AWT_RECENTER and self.is_awt(self._metadata):
  File "/usr/lib64/python3.6/site-packages/xpra/client/gtk_base/gtk_client_window_base.py", line 543, in is_awt
    return wm_class and len(wm_class)==2 and wm_class[0].startswith("sun-awt-X11")
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```
i can still grab borders to resize manually.

**Comment by totaam** [comment]
Sorry about that!

The two commits above fix both issues.
