### ISSUE TITLE
parallel builds

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#3255]
Let's try to speed things up a bit.
Building all the packages for all the distributions takes many hours.

Already done for the CUDA kernels: f4c7a26ada124e353a7caba7d83108f2edc48143

**Comment by totaam** [comment]
Parallel cythonization is now disabled on MacOS because of this weird error:
```
Compiling xpra/net/websockets/mask.pyx because it changed.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/macos/gtk/inst/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/macos/gtk/inst/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/macos/gtk/inst/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/macos/gtk/inst/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/macos/gtk/inst/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/macos/gtk/inst/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/macos/gtk/inst/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/macos/xpra/setup.py", line 2408, in <module>
    setup_options["ext_modules"] = cythonize(ext_modules,
  File "/Users/macos/gtk/inst/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1078, in cythonize
    pool = multiprocessing.Pool(
  File "/Users/macos/gtk/inst/lib/python3.9/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/Users/macos/gtk/inst/lib/python3.9/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/Users/macos/gtk/inst/lib/python3.9/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/Users/macos/gtk/inst/lib/python3.9/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/Users/macos/gtk/inst/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/macos/gtk/inst/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/macos/gtk/inst/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/macos/gtk/inst/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/macos/gtk/inst/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/macos/gtk/inst/lib/python3.9/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Users/macos/gtk/inst/lib/python3.9/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```
