### ISSUE TITLE
Tray > Server > Run Command does not open

### ISSUE THREAD

**Issue by stdedos** [Xpra-org/xpra#3259]
```
"Xpra-Python3-x86_64_4.3-r29944\xpra_cmd" attach ssh://user@ip/2 --ssh="plink -ssh -agent" --title="@title@ on @@/@server-display@" --modal-windows=no --headerbar=off --use-display=yes --input-method=xim --csc-modules=libyuv --opengl=no

XPRA_CLIPBOARD_REMOTE_TIMEOUT=5000
XPRA_EXECUTABLE=Xpra-Python3-x86_64_4.3-r29944

2021-09-08 11:45:54,715 Xpra GTK3 client version 4.3-r29944 (g5fc11e6eb) 64-bit
2021-09-08 11:45:54,895  running on Microsoft Windows 10
2021-09-08 11:45:58,449 GStreamer version 1.18.4 for Python 3.9.6 64-bit
2021-09-08 11:45:59,056 created named pipe 'Xpra\27828'
2021-09-08 11:45:59,712 keyboard layout code 0x409
2021-09-08 11:45:59,945 identified as 'United States - English' : us
2021-09-08 11:46:01,478  keyboard settings: layout=us
2021-09-08 11:46:01,892  desktop size is 4160x1440:
2021-09-08 11:46:02,205   Default (1100x381 mm - DPI: 96x96) workarea: 4160x1400
2021-09-08 11:46:02,622     C32JG5x 2560x1440 at 1600x0    (697x392 mm - DPI: 93x93) workarea: 2560x1400 at 1600x0
2021-09-08 11:46:02,670     Generic PnP Monitor 1600x900 at    0x534  (309x174 mm - DPI: 132x131) workarea: 1600x860  at    0x534
2021-09-08 11:46:05,920 enabled remote logging
2021-09-08 11:46:05,923 Xpra X11 seamless server version 4.3-r29499 64-bit
2021-09-08 11:46:05,924  running on Linux Ubuntu 20.04 focal
2021-09-08 11:46:05,964 Attached to :22
2021-09-08 11:46:05,967  (press Control-C to detach)


(xpra_cmd:27828): Pango-WARNING **: 11:46:07.012: couldn't load font "Bitstream Vera Sans Not-Rotated 14.662109375", falling back to "Sans Not-Rotated 14.662109375", expect ugly output.

(xpra_cmd:27828): Pango-WARNING **: 11:46:07.139: couldn't load font "DejaVu Serif Not-Rotated 59.796875", falling back to "Sans Not-Rotated 59.796875", expect ugly output.

(xpra_cmd:27828): Pango-WARNING **: 11:46:07.169: couldn't load font "URW Bookman L Not-Rotated 52.76171875", falling back to "Sans Not-Rotated 52.76171875", expect ugly output.
2021-09-08 11:46:08,358 UI thread is now blocked
2021-09-08 11:46:09,146 running, 16 windows, 4 trays
2021-09-08 11:46:09,498 UI thread is running again, resuming
Traceback (most recent call last):
  File "E:/xpra/xpra/client/gtk_base/gtk_client_base.py", line 455, in show_start_new_command
  File "E:/xpra/xpra/client/gtk_base/start_new_command.py", line 28, in getStartNewCommand
  File "E:/xpra/xpra/client/gtk_base/start_new_command.py", line 60, in __init__
TypeError: Must be string, not bytes
```

**Comment by totaam** [comment]
This particular bug is fixed above.

The interesting question is why the windows installer doesn't update the default config in `%PROGRAMDATA%\Xpra`.
This is what is making your client use `rencode` instead of `rencodeplus`.
I've got the same problem here on my test machine, I will figure it out.

**Comment by stdedos** [comment]
> The interesting question is why the windows installer doesn't update the default config in `%PROGRAMDATA%\Xpra`.

**NOT** installed?? I use the zip packages 😀

Hence the otherwise-pretty pre-ample
```
"Xpra-Python3-x86_64_4.3-r29944\xpra_cmd" attach ssh://user@ip/2 --ssh="plink -ssh -agent" --title="@title@ on @@/@server-display@" --modal-windows=no --headerbar=off --use-display=yes --input-method=xim --csc-modules=libyuv --opengl=no

XPRA_CLIPBOARD_REMOTE_TIMEOUT=5000
XPRA_EXECUTABLE=Xpra-Python3-x86_64_4.3-r29944

2021-09-08 11:45:54,715 Xpra GTK3 client version 4.3-r29944 (g5fc11e6eb) 64-bit
```
that prints the almost-full arglist to the executable, and all of the environment variables starting with `XPRA_` (`XPRA_EXECUTABLE` being a env of my own)

Also `%PROGRAMDATA%\Xpra` is purged every time I happen to see it (in favor of defaults + arglist configuration only)

**Comment by totaam** [comment]
> NOT installed?? I use the zip packages grinning

No worries, I could reproduce the problem on my test system, with the EXE installer:
```
xpra showsetting packet-encoders
```
I had `rencode` first instead of `rencodeplus` because of the default config files found in `%PROGRAMDATA%\Xpra`.
The latest beta build now correctly includes the generated conf files (with `rencodeplus` first) and they overwrite the old ones on installation.
Yours probably came from the same place. If not then we have a different problem.

> running, 16 windows, 4 trays

:open_mouth:

**Comment by stdedos** [comment]
> > running, 16 windows, 4 trays
> 
> :open_mouth:

Oh yes - xpra grew up! 😍 

It's not my child, but I feel so proud 😄 

(even though 2 trays are defunct vmware-tray's stuck, and one of them is pure black - but IIRC it's working)

**Comment by stdedos** [comment]
> xpra showsetting packet-encoders

`xpra showsetting packet-encoders` shows correct values (global default `all`, portable one `rencodeplus, ...`)
However, every time I run it, there's one `%APPDATA%/Xpra/xpra.conf` created (which is empty, however)

Seems fixed in r29975 (cc90f5e47)

**Comment by totaam** [comment]
> However, every time I run it, there's one `%APPDATA%/Xpra/xpra.conf` created (which is empty, however)

Yes, it's a sample user config, but it shouldn't be empty:
https://github.com/Xpra-org/xpra/blob/8a0d2b663f9b47cce33ac4e843f9c0c7f9a5d468/xpra/scripts/config.py#L463-L482

**Comment by stdedos** [comment]
Empty-ish, you are right.

"Inconsequential" I should've said
