### ISSUE TITLE
ssh authentication timeout with Windows client

### ISSUE THREAD

**Issue by fooburger** [Xpra-org/xpra#3264]
Hello,

with the latest beta (also previous stable version) for Windows I'm unable to establish an SSH connection since the password prompt is shown **after** the timeout (30 seconds). The session is initiated like this:

`.\Xpra_cmd.exe start-desktop --start-child=startxfce4 --exit-with-children --opengl=no --splash=no ssh://foo@bar.lan -d ssh,auth`

The log shows the following messages:
```
2021-09-09 10:24:28,246 auth=password
2021-09-09 10:24:28,246 trying interactive authentication
2021-09-09 10:24:28,338 userauth is OK
2021-09-09 10:24:58,298 auth_interactive(..)
Traceback (most recent call last):
  File "E:/xpra/xpra/net/ssh.py", line 691, in auth_interactive
  File "C:/msys64/mingw64/lib/python3.9/site-packages/paramiko/transport.py", line 1633, in auth_interactive
  File "C:/msys64/mingw64/lib/python3.9/site-packages/paramiko/auth_handler.py", line 240, in wait_for_response
paramiko.ssh_exception.AuthenticationException: Authentication timeout.
2021-09-09 10:24:58,299 SSH password authentication failed:
2021-09-09 10:24:58,300  Authentication timeout.
```
Public-key authentication works without any issues though. The Linux server is running version 4.2.2.

Please let me know if I can provide any other information?

Regards,
Martin

**Comment by totaam** [comment]
Perhaps the password prompt dialog is getting stuck somewhere near here:
https://github.com/Xpra-org/xpra/blob/a239697a1ee0d983501f8b17c8391aa655ba9624/xpra/net/ssh.py#L89-L106
I have added debug logging, please try the latest beta build and post the full debug output.

We've had this problem before and it ended up being a problem with the installation: there was another mingw / python (can't remember which) on the `%PATH%` and that ended up interfering.

FWIW: I've tested the exact command you're using and I'm not seeing any problems:
```
2021-09-14 19:53:30,291 input_pass(please enter the SSH password for USER@IP:) using dialog
2021-09-14 19:53:30,291 dialog_pass('Password Input', 'please enter the SSH password for antoine@192.168.0.10:', 'E:/xpra/dist/share/xpra/icons/authentication.png') PINENTRY=False
2021-09-14 19:53:30,312 dialog_run(<pass_dialog.PasswordInputDialogWindow object at 0x00000209b5f26380 (xpra+client+gtk_base+pass_dialog+PasswordInputDialogWindow at 0x00000209b481f7c0)>) is_main_thread=True
2021-09-14 19:53:34,709 trying password authentication
2021-09-14 19:53:34,709 userauth is OK
2021-09-14 19:53:34,907 Authentication (password) successful!
```
(4 seconds to show the dialog and input the password)

**Comment by fooburger** [comment]
the same call with `-d all`
```
2021-09-15 07:33:08,176 auth=password
2021-09-15 07:33:08,177 trying interactive authentication
2021-09-15 07:33:08,198 userauth is OK
2021-09-15 07:33:08,225 get_pixbuf(C:\Users\foobar\apps\Xpra-Python3-x86_64_4.3-r30012\share\xpra\icons\authentication.png) icon_filename=C:\Users\foobar\apps\Xpra-Python3-x86_64_4.3-r30012\share\xpra\icons\authentication.png
2021-09-15 07:33:38,187 auth_interactive(..)
Traceback (most recent call last):
  File "E:/xpra/xpra/net/ssh.py", line 691, in auth_interactive
  File "C:/msys64/mingw64/lib/python3.9/site-packages/paramiko/transport.py", line 1633, in auth_interactive
  File "C:/msys64/mingw64/lib/python3.9/site-packages/paramiko/auth_handler.py", line 240, in wait_for_response
paramiko.ssh_exception.AuthenticationException: Authentication timeout.
2021-09-15 07:33:38,190 SSH password authentication failed:
2021-09-15 07:33:38,190  Authentication timeout.
2021-09-15 07:33:38,194 get_pixbuf(C:\Users\foobar\apps\Xpra-Python3-x86_64_4.3-r30012\share\xpra\icons\authentication.png) icon_filename=C:\Users\foobar\apps\Xpra-Python3-x86_64_4.3-r30012\share\xpra\icons\authentication.png
2021-09-15 07:33:38,196 PasswordInputDialogWindow.show()
2021-09-15 07:33:38,212 NotifyIconWndProc(199480, 28, 1, 244) instance=win32NotifyIcon(0x0), message(28)=None
2021-09-15 07:33:38,213 callbacks for event WM_ACTIVATEAPP: [<bound method ClientExtras.activateapp of <xpra.platform.win32.gui.ClientExtras object at 0x0000020a846a8550>>]
2021-09-15 07:33:38,213 WM_ACTIVATEAPP: 1/244 client=gtk3.client
2021-09-15 07:33:38,213 DefWindowProc(461524, 28, 1, 244)=0
2021-09-15 07:33:38,224 poll() procinfo list: [ProcInfo(612 : ['C:\\Users\\foobar\\apps\\Xpra-Python3-x86_64_4.3-r30012\\Xpra.exe', 'splash'])]
2021-09-15 07:33:38,229 SPI_GETSCREENSAVERRUNNING=False
2021-09-15 07:33:38,233 PasswordInputDialogWindow.show()
2021-09-15 07:33:39,718 dialog_run(<pass_dialog.PasswordInputDialogWindow object at 0x0000020a84764b00 (xpra+client+gtk_base+pass_dialog+PasswordInputDialogWindow at 0x0000020a822b5810)>) code=[1]
```

**Comment by totaam** [comment]
> the same call with `-d all`

@fooburger  Please try the latest beta build for MS Windows (r30024 or later) and post the full debug output.

**Comment by fooburger** [comment]
The result when using r30024:
```
2021-09-15 12:57:21,563 auth=password
2021-09-15 12:57:21,563 trying interactive authentication
2021-09-15 12:57:21,590 userauth is OK
2021-09-15 12:57:21,610 handle_request('', '', [('Password:', False)]) counter=0
2021-09-15 12:57:21,611 input_pass(Password:) using dialog
2021-09-15 12:57:21,612 dialog_pass('Password Input', 'Password:', 'C:\\Users\\foobar\\apps\\Xpra-Python3-x86_64_4.3-r30024\\share\\xpra\\icons\\authentication.png') PINENTRY=False
2021-09-15 12:57:21,612 dialog_run(<function dialog_pass.<locals>.password_input_run at 0x00000204b53a0ee0>) is_main_thread=False
--- Logging error ---
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python3.9/logging/__init__.py", line 1083, in emit
  File "C:/msys64/mingw64/lib/python3.9/logging/__init__.py", line 927, in format
  File "C:/msys64/mingw64/lib/python3.9/logging/__init__.py", line 663, in format
  File "C:/msys64/mingw64/lib/python3.9/logging/__init__.py", line 367, in getMessage
TypeError: not enough arguments for format string
Call stack:
  File "C:/msys64/mingw64/lib/python3.9/threading.py", line 930, in _bootstrap
  File "C:/msys64/mingw64/lib/python3.9/threading.py", line 973, in _bootstrap_inner
  File "C:/msys64/mingw64/lib/python3.9/site-packages/paramiko/transport.py", line 2109, in run
  File "C:/msys64/mingw64/lib/python3.9/site-packages/paramiko/auth_handler.py", line 669, in _parse_userauth_info_request
  File "E:/xpra/xpra/net/ssh.py", line 696, in handle_request
  File "E:/xpra/xpra/net/ssh.py", line 164, in input_pass
  File "E:/xpra/xpra/net/ssh.py", line 120, in dialog_pass
  File "E:/xpra/xpra/net/ssh.py", line 84, in dialog_run
  File "E:/xpra/xpra/log.py", line 432, in __call__
  File "E:/xpra/xpra/log.py", line 428, in log
  File "E:/xpra/xpra/log.py", line 145, in standard_logging
  File "C:/msys64/mingw64/lib/python3.9/logging/__init__.py", line 1512, in log
  File "C:/msys64/mingw64/lib/python3.9/logging/__init__.py", line 1589, in _log
  File "C:/msys64/mingw64/lib/python3.9/logging/__init__.py", line 1599, in handle
  File "C:/msys64/mingw64/lib/python3.9/logging/__init__.py", line 1661, in callHandlers
  File "C:/msys64/mingw64/lib/python3.9/logging/__init__.py", line 952, in handle
  File "E:/xpra/xpra/colorstreamhandler.py", line 123, in emit
  File "C:/msys64/mingw64/lib/python3.9/logging/__init__.py", line 1091, in emit
Message: 'dialog_run(%s) main_depth=%s'
Arguments: (0,)
2021-09-15 12:57:21,616 dialog_run(<function dialog_pass.<locals>.password_input_run at 0x00000204b53a0ee0>) waiting for main thread to run
2021-09-15 12:57:51,652 auth_interactive(..)
Traceback (most recent call last):
  File "E:/xpra/xpra/net/ssh.py", line 702, in auth_interactive
  File "C:/msys64/mingw64/lib/python3.9/site-packages/paramiko/transport.py", line 1633, in auth_interactive
  File "C:/msys64/mingw64/lib/python3.9/site-packages/paramiko/auth_handler.py", line 240, in wait_for_response
paramiko.ssh_exception.AuthenticationException: Authentication timeout.
2021-09-15 12:57:51,655 SSH password authentication failed:
2021-09-15 12:57:51,655  Authentication timeout.
2021-09-15 12:57:51,657 input_pass(please enter the SSH password for foobar@host.lan:) using dialog
2021-09-15 12:57:51,657 dialog_pass('Password Input', 'please enter the SSH password for foobar@host.lan:', 'C:\\Users\\foobar\\apps\\Xpra-Python3-x86_64_4.3-r30024\\share\\xpra\\icons\\authentication.png') PINENTRY=False
2021-09-15 12:57:51,658 dialog_run(<function dialog_pass.<locals>.password_input_run at 0x00000204b49afdc0>) is_main_thread=True
2021-09-15 12:57:51,661 get_pixbuf(C:\Users\foobar\apps\Xpra-Python3-x86_64_4.3-r30024\share\xpra\icons\authentication.png) icon_filename=C:\Users\foobar\apps\Xpra-Python3-x86_64_4.3-r30024\share\xpra\icons\authentication.png
2021-09-15 12:57:51,664 PasswordInputDialogWindow.show()
2021-09-15 12:57:51,681 NotifyIconWndProc(264314, 28, 1, 9808) instance=win32NotifyIcon(0x0), message(28)=None
2021-09-15 12:57:51,685 callbacks for event WM_ACTIVATEAPP: [<bound method ClientExtras.activateapp of <xpra.platform.win32.gui.ClientExtras object at 0x00000204b52d45b0>>]
2021-09-15 12:57:51,685 WM_ACTIVATEAPP: 1/9808 client=gtk3.client
2021-09-15 12:57:51,686 DefWindowProc(1773112, 28, 1, 9808)=0
2021-09-15 12:57:51,697 poll() procinfo list: [ProcInfo(14292 : ['C:\\Users\\foobar\\apps\\Xpra-Python3-x86_64_4.3-r30024\\Xpra.exe', 'splash'])]
2021-09-15 12:57:51,701 SPI_GETSCREENSAVERRUNNING=False
2021-09-15 12:57:51,708 main_thread_run()
2021-09-15 12:57:51,711 get_pixbuf(C:\Users\foobar\apps\Xpra-Python3-x86_64_4.3-r30024\share\xpra\icons\authentication.png) icon_filename=C:\Users\foobar\apps\Xpra-Python3-x86_64_4.3-r30024\share\xpra\icons\authentication.png
2021-09-15 12:57:51,715 PasswordInputDialogWindow.show()
2021-09-15 12:57:52,645 dialog_run(<function dialog_pass.<locals>.password_input_run at 0x00000204b53a0ee0>) code=[1]
2021-09-15 12:57:52,647 handle_request(..) returning 1 values
```

**Comment by totaam** [comment]
I don't understand why I am not seeing the same behaviour here during testing.
The updated beta builds now also check `Gtk.main_level` and run the dialog in the current thread if it looks like there is no active main loop.
If that still doesn't work then I will have to add some tricky code to detect when the gtk main loop is unavailable and we should not be using `GLib.idle_add` to schedule work.

**Comment by fooburger** [comment]
Now it's working:
```
2021-09-16 07:53:25,055 auth=password
2021-09-16 07:53:25,055 trying interactive authentication
2021-09-16 07:53:25,095 userauth is OK
2021-09-16 07:53:25,139 handle_request('', '', [('Password:', False)]) counter=0
2021-09-16 07:53:25,141 input_pass(Password:) using dialog
2021-09-16 07:53:25,141 dialog_pass('Password Input', 'Password:', 'C:\\Users\\foobar\\apps\\Xpra-Python3-x86_64_4.3-r30028\\share\\xpra\\icons\\authentication.png') PINENTRY=False
2021-09-16 07:53:25,142 dialog_run(<function dialog_pass.<locals>.password_input_run at 0x0000025018179f70>) is_main_thread=False, main_level=0
2021-09-16 07:53:25,172 debug enabled for xpra.os_util / ('util',)
2021-09-16 07:53:25,193 get_pixbuf(C:\Users\foobar\apps\Xpra-Python3-x86_64_4.3-r30028\share\xpra\icons\authentication.png) icon_filename=C:\Users\foobar\apps\Xpra-Python3-x86_64_4.3-r30028\share\xpra\icons\authentication.png
2021-09-16 07:53:25,253 PasswordInputDialogWindow.show()
2021-09-16 07:53:25,820 poll() procinfo list: [ProcInfo(16828 : ['C:\\Users\\foobar\\apps\\Xpra-Python3-x86_64_4.3-r30028\\Xpra.exe', 'splash'])]
2021-09-16 07:53:25,824 setup_xpra_tray()
2021-09-16 07:53:25,824 setup_menu(True)
2021-09-16 07:53:25,829 after_handshake(<function GTKTrayMenuBase.do_setup_menu.<locals>.set_menu_title at 0x0000025018169e50>, ()) on_handshake=[(<function run_remote_server.<locals>.handshake_complete at 0x000002501805b940>, ())]
```
