### ISSUE TITLE
xpra initialization error:  no such option: -s

### ISSUE THREAD

**Issue by stdedos** [Xpra-org/xpra#3267]
```
2021-09-14 10:53:34,937 Connection lost
CONNECTION_LOST, reconnecting

was: "Xpra-Python3-x86_64_4.3-r29975\xpra_cmd" start ssh://user@ip/2 --ssh="plink -ssh -agent" --title="@title@ on @@/@server-display@" --modal-windows=no --headerbar=off --use-display=yes --input-method=xim --csc-modules=libyuv --opengl=no

Press any key to continue . . . xpra initialization error:
 no such option: -s
```

I assume it's coming from `--ssh="plink -ssh -agent"`?

**Comment by totaam** [comment]
This looks like a command line parsing error? (is it almost instantaneous?)

Can you try again with a newer build?
Preferably with `-d ssh` and post the output.
I'm not seeing any problems here with a bare minimum setup and:
```
xpra_cmd.exe attach ssh://user@host/DISPLAY --ssh="plink -ssh -agent"
```

**Comment by stdedos** [comment]
> This looks like a command line parsing error? (is it almost instantaneous?)

Yeah (incomplete network setup)

> Can you try again with a newer build?

Happy r30012! 😀 I'll give it a go tomorrow

**Comment by stdedos** [comment]
```
"Xpra-Python3-x86_64_4.3-r30012\xpra_cmd" attach ssh://usr-linux@1.1.1.1/2 --ssh="plink -ssh -agent" -d ssh --title="@title@ on @@/@server-display@" --modal-windows=no --headerbar=off --use-display=yes --input-method=xim --csc-modules=libyuv --opengl=no

XPRA_CLIPBOARD_REMOTE_TIMEOUT=5000
XPRA_EXECUTABLE=Xpra-Python3-x86_64_4.3-r30012

2021-09-15 11:33:24,204 Xpra GTK3 client version 4.3-r30012 (g2493b5c73) 64-bit
2021-09-15 11:33:24,431  running on Microsoft Windows 10
2021-09-15 11:33:29,941 GStreamer version 1.18.5 for Python 3.9.6 64-bit
2021-09-15 11:33:30,193 debug enabled for xpra.net.ssh / ('network', 'ssh')
2021-09-15 11:33:30,821 created named pipe 'Xpra\8996'
2021-09-15 11:33:31,149 keyboard layout code 0x409
2021-09-15 11:33:31,311 identified as 'United States - English' : us
2021-09-15 11:33:32,175 executing ssh command: "plink" "-ssh" "-agent" "-l" "usr-linux" "-T" "1.1.1.1" "sh -c 'if command -v "xpra" > /dev/null 2>&1; then xpra _proxy ":2";elif [ -x $XDG_RUNTIME_DIR/xpra/run-xpra ]; then $XDG_RUNTIME_DIR/xpra/run-xpra _proxy ":2";elif [ -x /usr/local/bin/xpra ]; then /usr/local/bin/xpra _proxy ":2";elif [ -x ~/.xpra/run-xpra ]; then ~/.xpra/run-xpra _proxy ":2";elif [ -x Xpra_cmd.exe ]; then Xpra_cmd.exe _proxy ":2";else echo "no run-xpra command found"; exit 1; fi'"
2021-09-15 11:33:32,549  keyboard settings: layout=us
2021-09-15 11:33:32,721  desktop size is 4160x1440:
2021-09-15 11:33:32,730   Default (1100x381 mm - DPI: 96x96) workarea: 4160x1400
2021-09-15 11:33:32,731     C32JG5x 2560x1440 at 1600x0    (697x392 mm - DPI: 93x93) workarea: 2560x1400 at 1600x0
2021-09-15 11:33:32,732     Generic PnP Monitor 1600x900 at    0x534  (309x174 mm - DPI: 132x131) workarea: 1600x860  at    0x534
2021-09-15 11:33:39,716 enabled remote logging
2021-09-15 11:33:39,720 Xpra X11 seamless server version 4.3-r29499 64-bit
2021-09-15 11:33:39,721  running on Linux Ubuntu 20.04 focal
2021-09-15 11:33:39,760 Attached to xpra server at 1.1.1.1:22
2021-09-15 11:33:39,765  (press Control-C to detach)

...

2021-09-15 13:16:18,909 server is not responding, drawing spinners over the windows
2021-09-15 13:16:38,809 SSH EOF on stderr of ['plink', '-ssh', '-agent', '-l', 'usr-linux', '-T', '1.1.1.1', 'sh -c \'if command -v "xpra" > /dev/null 2>&1; then xpra _proxy ":2";elif [ -x $XDG_RUNTIME_DIR/xpra/run-xpra ]; then $XDG_RUNTIME_DIR/xpra/run-xpra _proxy ":2";elif [ -x /usr/local/bin/xpra ]; then /usr/local/bin/xpra _proxy ":2";elif [ -x ~/.xpra/run-xpra ]; then ~/.xpra/run-xpra _proxy ":2";elif [ -x Xpra_cmd.exe ]; then Xpra_cmd.exe _proxy ":2";else echo "no run-xpra command found"; exit 1; fi\'']
2021-09-15 13:16:39,426 Connection lost
CONNECTION_LOST, reconnecting

was: "Xpra-Python3-x86_64_4.3-r30012\xpra_cmd" start ssh://usr-linux@1.1.1.1/2 --ssh="plink -ssh -agent" -d ssh --title="@title@ on @@/@server-display@" --modal-windows=no --headerbar=off --use-display=yes --input-method=xim --csc-modules=libyuv --opengl=no

Press any key to continue . . . xpra initialization error:
 no such option: -s
```

**Comment by totaam** [comment]
Wait. I've only just noticed that this is only happening during re-connection! (#3010)
Now I can reproduce it.

**Comment by totaam** [comment]
Oh great: [os.execv fails with spaced names on Windows](https://bugs.python.org/issue19066#msg198580)
_This is a problem with Window's implementation of spawn*() and exec*()._
_Note that on Windows exec*() is useless: it just starts a subprocess and exits the current process_
[Windows exec*/spawn* problem with spaces in args](https://bugs.python.org/issue436259)

Updated beta builds now work OK and re-connect even when the command line contains spaces.
The downside is that the exit code of the initial `Xpra_cmd.exe` will always be zero when we re-connect on MS Windows as there's no way to make it work with this shambolic implementation of `exec`.

**Comment by stdedos** [comment]
> Note that on Windows exec*() is useless: it just starts a subprocess and exits the current process

That's bs too. But I guess it is what it is 😕

**Comment by stdedos** [comment]
```
2021-09-20 12:41:09,413 server requested disconnect:
2021-09-20 12:41:09,419  server upgrade
UPGRADE, reconnecting
xpra main error:
Traceback (most recent call last):
  File "E:/xpra/xpra/scripts/main.py", line 139, in main
  File "E:/xpra/xpra/scripts/main.py", line 412, in run_mode
  File "E:/xpra/xpra/scripts/main.py", line 451, in do_run_mode
  File "E:/xpra/xpra/scripts/main.py", line 1266, in run_client
  File "C:/msys64/mingw64/lib/python3.9/subprocess.py", line 951, in __init__
  File "C:/msys64/mingw64/lib/python3.9/subprocess.py", line 1420, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified


was: "Xpra-Python3-x86_64_4.3-r30040\xpra_cmd" start ssh://user@ip/2 --ssh="plink -ssh -agent" --title="@title@ on @@/@server-display@" --modal-windows=no --headerbar=off --use-display=yes --input-method=xim --csc-modules=libyuv --opengl=no
```

**Comment by totaam** [comment]
> `FileNotFoundError: ...`

My guess is that this has something to do with the path that you use: `Xpra-Python3-x86_64_4.3-r30040\xpra_cmd`.
So not only can we not use `exec` but also we cannot trust the path given to us by the OS either. Oh joy.
Hopefully 1baf2dd727b6ca6e17e8b80dd6211f9421b6cc93 fixes that.

**Comment by stdedos** [comment]
`$0` is an absolute path to the `xpra_cmd` (it doesn't show it, I know)

**Comment by totaam** [comment]
I've tested the commit above with various relative paths and it always seems to be able to run the same command again. Yay!

**Comment by stdedos** [comment]
🎉🎉🎉🎉🎉🎉

**Comment by stdedos** [comment]
I still get the same error 😕
I don't see any logging around the code - any suggestions?

**Comment by totaam** [comment]
> I don't see any logging around the code - any suggestions?

With 289a093712e0d046d762c6862ae7677c593f0623, add `-d exec`.
(there's lots of output with this debug flag, so watch it when re-connection occurs)

**Comment by stdedos** [comment]
Okay, it _miiiight_ be a little right:

```
CONNECTION_LOST, reconnecting
2021-09-29 11:01:25,750 debug enabled for xpra.scripts.main / ('exec',)
2021-09-29 11:01:25,751 Popen(args=['C:\\Users\\usr.win\\Documents\\xpra-clients\\Xpra-Python3-x86_64_4.3-r30066\\xpra_cmd', 'attach', 'ssh://user@ip/2', '--ssh=plink -ssh -agent', '-d', 'exec', '--title=@title@ on @@/@server-display@', '--modal-windows=no', '--headerbar=off', '--input-method=xim', '--csc-modules=libyuv', '--opengl=no'], executable=C:\Users\usr.win\Documents\xpra-clients\Xpra-Python3-x86_64_4.3-r30066\xpra_cmd)
xpra main error:
Traceback (most recent call last):
  File "E:/xpra/xpra/scripts/main.py", line 139, in main
  File "E:/xpra/xpra/scripts/main.py", line 412, in run_mode
  File "E:/xpra/xpra/scripts/main.py", line 451, in do_run_mode
  File "E:/xpra/xpra/scripts/main.py", line 1282, in run_client
  File "C:/msys64/mingw64/lib/python3.9/subprocess.py", line 951, in __init__
  File "C:/msys64/mingw64/lib/python3.9/subprocess.py", line 1420, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified


was: "C:\Users\usr.win\Documents\xpra-clients\Xpra-Python3-x86_64_4.3-r30066\xpra_cmd" start ssh://user@ip/2 --ssh="plink -ssh -agent" -d exec --title="@title@ on @@/@server-display@" --modal-windows=no --headerbar=off --use-display=yes --input-method=xim --csc-modules=libyuv --opengl=no

C:\Users\usr.win>dir C:\Users\usr.win\Documents\xpra-clients\Xpra-Python3-x86_64_4.3-r30066\xpra_cmd
 Volume in drive C has no label.
 Volume Serial Number is AAAA-3333

 Directory of C:\Users\usr.win\Documents\xpra-clients\Xpra-Python3-x86_64_4.3-r30066

File Not Found

C:\Users\usr.win>dir C:\Users\usr.win\Documents\xpra-clients\Xpra-Python3-x86_64_4.3-r30066\xpra_cmd*
 Volume in drive C has no label.
 Volume Serial Number is AAAA-3333

 Directory of C:\Users\usr.win\Documents\xpra-clients\Xpra-Python3-x86_64_4.3-r30066

24/09/2021  03:59 μμ            58.880 Xpra_cmd.exe
               1 File(s)         58.880 bytes
               0 Dir(s)  143.108.657.152 bytes free

C:\Users\usr.win>
```

However, Windows has this neat little feature (https://superuser.com/a/228693/533196) that it can execute executables without necessarily specifying their extension (`PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.PSC1` among others)

**Comment by stdedos** [comment]
By adding the missing `.exe` extension, it works.

So, this is up to you know

**Comment by totaam** [comment]
The latest beta builds try harder using `%PATHEXT%` and should finally fix this issue for you. Fingers crossed.

**Comment by totaam** [comment]
Can we close this one?

**Comment by stdedos** [comment]
I think I have tested it since your previous comment, and it worked like a charm.

Apologies for the stale issue
