### ISSUE TITLE
Errors popping out in journald when HTML5 client is accessed on proxy server with "http-scripts = all"

### ISSUE THREAD

**Issue by basilgello** [Xpra-org/xpra#3268]
```python
2021-09-15 13:37:44,581 Error: wss request failure for client ::ffff:127.0.0.1, 55390, 0, 0:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xpra/server/server_core.py", line 1482, in start_http
    WebSocketRequestHandler(sock, frominfo, new_websocket_client,
  File "/usr/lib/python3/dist-packages/xpra/net/websockets/handler.py", line 33, in __init__
    super().__init__(sock, addr, web_root, http_headers_dir, script_paths)
  File "/usr/lib/python3/dist-packages/xpra/net/http_handler.py", line 74, in __init__
    super().__init__(sock, addr, server)
  File "/usr/lib/python3.9/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/lib/python3.9/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.9/http/server.py", line 415, in handle_one_request
    method()
  File "/usr/lib/python3/dist-packages/xpra/net/websockets/handler.py", line 84, in do_GET
    super().do_GET()
  File "/usr/lib/python3/dist-packages/xpra/net/http_handler.py", line 205, in do_GET
    self.handle_request()
  File "/usr/lib/python3/dist-packages/xpra/net/websockets/handler.py", line 113, in handle_request
    super().handle_request()
  File "/usr/lib/python3/dist-packages/xpra/net/http_handler.py", line 208, in handle_request
    content = self.send_head()
  File "/usr/lib/python3/dist-packages/xpra/net/http_handler.py", line 236, in send_head
    content = script(self)
  File "/usr/lib/python3/dist-packages/xpra/server/server_core.py", line 1577, in http_menu_icon_request
    return self.send_icon(handler, icon_type, icon_data)
  File "/usr/lib/python3/dist-packages/xpra/server/server_core.py", line 1549, in send_icon
    return self.send_http_response(handler, icon_data, mime_type)
  File "/usr/lib/python3/dist-packages/xpra/server/server_core.py", line 1635, in send_http_response
    "Content-Length"    : len(content),
TypeError: object of type 'NoneType' has no len()
```

**Comment by basilgello** [comment]
@totaam

**Comment by totaam** [comment]
My guess is that you don't have `from gi.repository import Rsvg` installed and an svg icon is used by one of the menu entries.
Running with `-d menu` may give us a clue.

The server should now correctly reply with 404 when it fails to convert the svg icon to png.

**Comment by basilgello** [comment]
Yes, previous warning about absent `Rsvg`. I think the fix is appropriate because Debian lacks `python3-rsvg` package at all.
