### ISSUE TITLE
pulseaudio cookie missing

### ISSUE THREAD

**Issue by iDmple** [Xpra-org/xpra#3270]
Hi,

I get this error with xpra-html5 on Ubuntu 20.04 (within docker):
```
2021-09-17 14:33:42,315 pulseaudio server started with pid 116
2021-09-17 14:33:42,316  private server socket path:
2021-09-17 14:33:42,316  '/run/user/1000/xpra/pulse-80/pulse/native'
W: [pulseaudio] authkey.c: Failed to open cookie file '/home/xpra/.config/pulse/cookie': No such file or directory
W: [pulseaudio] authkey.c: Failed to load authentication key '/home/xpra/.config/pulse/cookie': No such file or directory
W: [pulseaudio] authkey.c: Failed to open cookie file '/home/xpra/.pulse-cookie': No such file or directory
W: [pulseaudio] authkey.c: Failed to load authentication key '/home/xpra/.pulse-cookie': No such file or directory
```
However the cookie exists and is readable for the xpra user!
```
root@xpra-server-s1:/home/xpra# ls -la .config/pulse/cookie   
-rw------- 1 xpra xpra 256 Sep 17 14:33 .config/pulse/cookie
```
```
root@xpra-server-s1:/home/xpra# xpra --version
xpra v4.2.2-r0
```

xpra-html5 is version 4.5

Am I doing anything wrong?

Thanks for your help.

**Comment by totaam** [comment]
Since you're running in a container, `$XDG_RUNTIME_DIR` probably does not exist when you run xpra.
Try creating it and setting the correct permissions.

(I've moved the issue from the xpra-html5 repo since there is no indication that this issue is in any way related to the html5 client)

**Comment by iDmple** [comment]
Indeed it does not exist! I will try creating it and report back.

**Comment by iDmple** [comment]
Actually, I was wrong it exists and is set to `/run/user/1000`, which is the uid of the user used to run xpra below.
The command used to run xpra is
```
runuser -l $XPRA_USER -c 'xpra start :80 --bind-tcp=0.0.0.0:8080 --html=on --no-daemon --start="xhost +"'
```

**Comment by totaam** [comment]
> .. `xhost +` ..

Yuk. What is that?
> I was wrong it exists and is set to `/run/user/1000`

Are you sure that the xpra process sees this environment variable?
Why does something end up trying to open `/home/xpra/.config/pulse/cookie`?
My guess is that you are running your X11 client applications by hand (hence the misguided `xhost +`) instead of using `--start=` which means that the environment they inherit is incorrect / incomplete.

**Comment by iDmple** [comment]
`xhost +` is needed so other containers can connect to the display. The applications are run from other containers using VGL. 
In any case this error has nothing to do with applications, since it appears at the start of xpra itself, without any app running.

If the variable is set before the xpra process is ran, xpra should see it?

**Comment by iDmple** [comment]
Some more logs:

```
2021-09-23 08:36:00,310 init_dbus(0, {})
2021-09-23 08:36:00,331 init_dbus_server() dbus_control=False
2021-09-23 08:36:00,331 init_dbus_server() env: {}
2021-09-23 08:36:00,358 pulseaudio server started with pid 116
2021-09-23 08:36:00,359  private server socket path:
2021-09-23 08:36:00,359  '/run/user/1000/xpra/pulse-80/pulse/native'
(Xpra:34): Gtk-CRITICAL **: 08:36:00.444: gtk_widget_realize: assertion 'widget->priv->anchored || GTK_IS_INVISIBLE (widget)' failed
W: [pulseaudio] authkey.c: Failed to open cookie file '/home/xpra/.config/pulse/cookie': No such file or directory
W: [pulseaudio] authkey.c: Failed to load authentication key '/home/xpra/.config/pulse/cookie': No such file or directory
W: [pulseaudio] authkey.c: Failed to open cookie file '/home/xpra/.pulse-cookie': No such file or directory
W: [pulseaudio] authkey.c: Failed to load authentication key '/home/xpra/.pulse-cookie': No such file or directory
Warning: failed to import GStreamer 1.x:
 Namespace Gst not available
2021-09-23 08:36:00,742 Error: failed to query sound subsystem:
2021-09-23 08:36:00,742  query did not return any data
...
2021-09-23 08:36:01,015  cannot load nvenc (nvenc encoder)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xpra/codecs/loader.py", line 52, in codec_import_check
    ic =  __import__(class_module, {}, {}, classnames)
  File "xpra/codecs/nvenc/encoder.pyx", line 10, in init xpra.codecs.nvenc.encoder
  File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 50, in <module>
    del os.environ[envkey]
  File "/usr/lib/python3.8/os.py", line 691, in __delitem__
    raise KeyError(key) from None
KeyError: 'OPENBLAS_MAIN_FREE'
```

**Comment by totaam** [comment]
> The applications are run from other containers using VGL.

And here we go... How on earth are the other containers supposed to find the pulseaudio directory?

> `Warning: failed to import GStreamer 1.x:`

And even if pulseaudio was working, you won't get any audio without gstreamer.

> `KeyError: 'OPENBLAS_MAIN_FREE'`

And your `numpy` installation is also borked..

**Comment by iDmple** [comment]
Thanks for pointing it out, these two errors were solved by installing `python3-gst-1.0`. I'm still trying to figure out the cookie error.

**Comment by iDmple** [comment]
The file is created, but probably too late, so the process can't find it:
```
root@xpra-server-s1:/home/xpra# ls -lah --full-time /home/xpra/.config/pulse/cookie 
-rw------- 1 xpra xpra 256 2021-09-23 11:24:57.986566473 +0000 /home/xpra/.config/pulse/cookie
```

```
2021-09-23 11:24:57,909  '/run/user/1000/xpra/pulse-80/pulse/native'
W: [pulseaudio] authkey.c: Failed to open cookie file '/home/xpra/.config/pulse/cookie': No such file or directory
W: [pulseaudio] authkey.c: Failed to load authentication key '/home/xpra/.config/pulse/cookie': No such file or directory
W: [pulseaudio] authkey.c: Failed to open cookie file '/home/xpra/.pulse-cookie': No such file or directory
W: [pulseaudio] authkey.c: Failed to load authentication key '/home/xpra/.pulse-cookie': No such file or directory

(Xpra:56): Gtk-CRITICAL **: 11:24:57.993: gtk_widget_realize: assertion 'widget->priv->anchored || GTK_IS_INVISIBLE (widget)' failed
2021-09-23 11:24:58,081 watching for applications menu changes in:
```

After restarting the container, the error disappears:
```
2021-09-23 11:33:16,114 created unix domain socket '/run/user/1000/xpra/xpra-server-s1-hipuser-80'                                         
2021-09-23 11:33:16,114 init_dbus(0, {})                                                                                                   
2021-09-23 11:33:16,141 init_dbus_server() dbus_control=False                                                                              
2021-09-23 11:33:16,141 init_dbus_server() env: {}
2021-09-23 11:33:16,177 pulseaudio server started with pid 113
2021-09-23 11:33:16,177  private server socket path:
2021-09-23 11:33:16,177  '/run/user/1000/xpra/pulse-80/pulse/native'
W: [pulseaudio] pid.c: Stale PID file, overwriting.
(Xpra:30): Gtk-CRITICAL **: 11:33:16.303: gtk_widget_realize: assertion 'widget->priv->anchored || GTK_IS_INVISIBLE (widget)' failed
2021-09-23 11:33:16,369 watching for applications menu changes in:
```

The error being only there the first time that pulseaudio is started, the ugly fix that works, if that helps someone:
```
pulseaudio --start; pulseaudio --kill; xpra start :80 --bind-tcp=0.0.0.0:8080 --html=on --no-daemon --start="xhost +"
```

**Comment by totaam** [comment]
Important note: this only works if you're running in a container and may mess up your local account's audio if you don't.
(and you should probably tell xpra not to start pulseaudio itself in this case using `--no-pulseaudio`)
