### ISSUE TITLE
`r30040`: Error loading OpenGL support: 'JPEG'

### ISSUE THREAD

**Issue by stdedos** [Xpra-org/xpra#3275]
```
"Xpra-Python3-x86_64_4.3-r30040\xpra_cmd" start ssh://user@ip/9 --ssh="plink -ssh -agent" --modal-windows=no --desktop-scaling=no --headerbar=off --title="@title@ on @@/@server-display@" --microphone=off --speaker=off --webcam=no --pulseaudio=no --start=gnome-terminal
```

However, "yeah, you are right", Intel is graylisted:
![xpra_2021-09-20_13-50-33](https://user-images.githubusercontent.com/133706/133991967-7cbb8f5f-544b-469b-9caa-50b3050bc503.png)

**Comment by totaam** [comment]
Haha, that's not a very useful message!

Can you please run it in debug mode? Either adding `-d opengl` or just running `Xpra_cmd opengl`.
(I don't have an opengl enabled system at hand to reproduce this)

**Comment by stdedos** [comment]
`-d opengl` is required

```
Xpra-Python3-x86_64_4.3-r30040\xpra_cmd" opengl -d opengl
debug enabled for xpra.scripts.main / ('opengl',)
do_run_glcheck(.., False)
debug enabled for xpra.client.gl.window_backend / ('opengl', 'paint')
get_gl_client_window_module()
debug enabled for xpra.client.gl.gtk3.gl_client_window / ('opengl', 'window')
OpenGL_accelerate module loaded
Using accelerated ArrayDatatype
debug enabled for xpra.client.gl.gl_check / ('opengl',)
debug enabled for xpra.client.gl.gl_window_backing_base / ('opengl', 'paint')
debug enabled for xpra.client.gl.gl_window_backing_base / ('opengl', 'fps')
debug enabled for xpra.platform.win32.gl_context / ('opengl',)
debug enabled for xpra.client.gl.gtk3.gl_drawing_area / ('opengl', 'paint')
check_support() GetModuleHandleW()=0x7ff79dc20000
check_support() RegisterClassExW()=0xc2ab
check_support() CreateWindowExW()=0x391272
create_wgl_context(0x391272) hdc=0x6a012607
ChoosePixelFormat for window 0x391272 and 8 bpc: 0x5
DescribePixelFormat: {'rgba': True, 'depth': 32, 'red-size': 8, 'green-size': 8, 'blue-size': 8, 'alpha-size': 8, 'red-shift': 16, 'green-shift': 8, 'blue-shift': 0, 'alpha-shift': 24, 'accum-red-size': 16, 'accum-green-size': 16, 'accum-blue-size': 16, 'accum-size': 64, 'depth-size': 24, 'stencil-size': 8, 'aux-buffers': 0, 'visible-mask': 0, 'double-buffered': True}
wglCreateContext(0x6a012607)=0x10000
wglMakeCurrent(0x6a012607, 0x10000)
BeginPaint hdc=0x6a012607
GL_VERSION=4.0.0 - Build 10.18.10.4276
found valid OpenGL version: 4.0
OpenGL_accelerate version 3.1.5
OpenGL extensions found: GL_EXT_blend_minmax, GL_EXT_blend_subtract, GL_EXT_blend_color, GL_EXT_abgr, GL_EXT_texture3D, GL_EXT_clip_volume_hint, GL_EXT_compiled_vertex_array, GL_SGIS_texture_edge_clamp, GL_SGIS_generate_mipmap, GL_EXT_draw_range_elements, GL_SGIS_texture_lod, GL_EXT_rescale_normal, GL_EXT_packed_pixels, GL_EXT_texture_edge_clamp, GL_EXT_separate_specular_color, GL_ARB_multitexture, GL_ARB_map_buffer_alignment, GL_ARB_conservative_depth, GL_EXT_texture_env_combine, GL_EXT_bgra, GL_EXT_blend_func_separate, GL_EXT_secondary_color, GL_EXT_fog_coord, GL_EXT_texture_env_add, GL_ARB_texture_cube_map, GL_ARB_transpose_matrix, GL_ARB_internalformat_query, GL_ARB_internalformat_query2, GL_ARB_texture_env_add, GL_IBM_texture_mirrored_repeat, GL_EXT_multi_draw_arrays, GL_SUN_multi_draw_arrays, GL_NV_blend_square, GL_ARB_texture_compression, GL_3DFX_texture_compression_FXT1, GL_EXT_texture_filter_anisotropic, GL_ARB_texture_border_clamp, GL_ARB_point_parameters, GL_ARB_texture_env_combine, GL_ARB_texture_env_dot3, GL_ARB_texture_env_crossbar, GL_EXT_texture_compression_s3tc, GL_ARB_shadow, GL_ARB_window_pos, GL_EXT_shadow_funcs, GL_EXT_stencil_wrap, GL_ARB_vertex_program, GL_EXT_texture_rectangle, GL_ARB_fragment_program, GL_EXT_stencil_two_side, GL_ATI_separate_stencil, GL_ARB_vertex_buffer_object, GL_EXT_texture_lod_bias, GL_ARB_occlusion_query, GL_ARB_fragment_shader, GL_ARB_shader_objects, GL_ARB_shading_language_100, GL_ARB_texture_non_power_of_two, GL_ARB_vertex_shader, GL_NV_texgen_reflection, GL_ARB_point_sprite, GL_ARB_fragment_program_shadow, GL_EXT_blend_equation_separate, GL_ARB_depth_texture, GL_ARB_texture_rectangle, GL_ARB_draw_buffers, GL_ARB_color_buffer_float, GL_ARB_half_float_pixel, GL_ARB_texture_float, GL_ARB_pixel_buffer_object, GL_EXT_framebuffer_object, GL_ARB_draw_instanced, GL_ARB_half_float_vertex, GL_ARB_occlusion_query2, GL_EXT_draw_buffers2, GL_WIN_swap_hint, GL_EXT_texture_sRGB, GL_ARB_multisample, GL_EXT_packed_float, GL_EXT_texture_shared_exponent, GL_ARB_texture_rg, GL_ARB_texture_compression_rgtc, GL_NV_conditional_render, GL_ARB_texture_swizzle, GL_EXT_texture_swizzle, GL_ARB_texture_gather, GL_ARB_sync, GL_ARB_framebuffer_sRGB, GL_EXT_packed_depth_stencil, GL_ARB_depth_buffer_float, GL_EXT_transform_feedback, GL_ARB_transform_feedback2, GL_ARB_draw_indirect, GL_EXT_framebuffer_blit, GL_EXT_framebuffer_multisample, GL_ARB_framebuffer_object, GL_ARB_framebuffer_no_attachments, GL_EXT_texture_array, GL_EXT_texture_integer, GL_ARB_map_buffer_range, GL_ARB_texture_buffer_range, GL_EXT_texture_buffer, GL_EXT_texture_snorm, GL_ARB_blend_func_extended, GL_INTEL_performance_queries, GL_INTEL_performance_query, GL_ARB_copy_buffer, GL_ARB_sampler_objects, GL_NV_primitive_restart, GL_ARB_seamless_cube_map, GL_ARB_uniform_buffer_object, GL_ARB_depth_clamp, GL_ARB_vertex_array_bgra, GL_ARB_shader_bit_encoding, GL_ARB_draw_buffers_blend, GL_ARB_geometry_shader4, GL_EXT_geometry_shader4, GL_ARB_texture_query_lod, GL_ARB_explicit_attrib_location, GL_ARB_draw_elements_base_vertex, GL_ARB_instanced_arrays, GL_ARB_base_instance, GL_ARB_fragment_coord_conventions, GL_EXT_gpu_program_parameters, GL_ARB_texture_buffer_object_rgb32, GL_ARB_compatibility, GL_ARB_texture_rgb10_a2ui, GL_ARB_texture_multisample, GL_ARB_vertex_type_2_10_10_10_rev, GL_ARB_timer_query, GL_ARB_tessellation_shader, GL_ARB_vertex_array_object, GL_ARB_provoking_vertex, GL_ARB_sample_shading, GL_ARB_texture_cube_map_array, GL_EXT_gpu_shader4, GL_ARB_gpu_shader5, GL_ARB_gpu_shader_fp64, GL_ARB_shader_subroutine, GL_ARB_transform_feedback3, GL_ARB_get_program_binary, GL_ARB_separate_shader_objects, GL_ARB_shader_precision, GL_ARB_vertex_attrib_64bit, GL_ARB_viewport_array, GL_ARB_transform_feedback_instanced, GL_ARB_compressed_texture_pixel_storage, GL_ARB_shader_atomic_counters, GL_ARB_shading_language_packing, GL_ARB_shading_language_420pack, GL_ARB_texture_storage, GL_EXT_texture_storage, GL_ARB_vertex_attrib_binding, GL_ARB_multi_draw_indirect, GL_ARB_program_interface_query, GL_ARB_texture_storage_multisample, GL_ARB_buffer_storage, GL_ARB_debug_output, GL_KHR_debug, GL_ARB_arrays_of_arrays, GL_INTEL_map_texture, GL_ARB_texture_compression_bptc, GL_ARB_ES2_compatibility, GL_ARB_ES3_compatibility, GL_ARB_robustness, GL_EXT_texture_sRGB_decode, GL_KHR_blend_equation_advanced, GL_EXT_shader_integer_mix, GL_ARB_stencil_texturing,
vendor: Intel
renderer: Intel(R) HD Graphics 4000
shading-language-version: 4.00 - Build 10.18.10.4276
GLU.version: 1.2.2.0 Microsoft Corporation
GLU.extensions: GL_EXT_bgra
renderer 'Intel(R) HD Graphics 4000' not found in blacklist: ['SVGA3D', 'Software Rasterizer', 'Mesa DRI Intel(R) Ivybridge Desktop', 'Mesa DRI Intel(R) Haswell Mobile', 'Intel(R) UHD Graphics 620']
vendor 'Intel' not found in blacklist: []
vendor 'Intel' found in greylist: ['Intel']
renderer 'Intel(R) HD Graphics 4000' not found in whitelist: ['Haswell', 'Skylake', 'Kabylake', 'Cannonlake', 'Whiskeylake', 'Amberlake', 'Cascadelake', 'Cometlake', 'Icelake', 'Cooperlake']
Warning: vendor 'Intel' is greylisted,
 you may want to turn off OpenGL if you encounter bugs
All the required OpenGL functions are available: glActiveTexture, glTexSubImage2D, glTexCoord2i, glViewport, glMatrixMode, glLoadIdentity, glOrtho, glEnableClientState, glGenTextures, glDisable, glBindTexture, glPixelStorei, glEnable, glBegin, glFlush, glTexParameteri, glTexEnvi, glHint, glBlendFunc, glLineStipple, glTexImage2D, glMultiTexCoord2i, glVertex2i, glEnd
All the required OpenGL functions are available: GL_FRAMEBUFFER (GL_FRAMEBUFFER), GL_COLOR_ATTACHMENT0 (GL_COLOR_ATTACHMENT0), glGenFramebuffers, glBindFramebuffer, glFramebufferTexture2D
All required extensions are present: ['GL_ARB_texture_rectangle', 'GL_ARB_vertex_program']
glInitFragmentProgramARB found
glInitTextureRectangleARB found
All the required OpenGL functions are available: glGenProgramsARB, glDeleteProgramsARB, glBindProgramARB, glProgramStringARB
GL_MAX_TEXTURE_SIZE=16384
Texture size GL_MAX_RECTANGLE_TEXTURE_SIZE=16384
GL_MAX_VIEWPORT_DIMS=(16384, 16384)
OpenGL accelerate missing: numpy_formathandler
EndPaint
check_support(False)={'pyopengl': '3.1.5', 'opengl': (4, 0), 'accelerate': '3.1.5', 'zerocopy': True, 'extensions': ['GL_EXT_blend_minmax', 'GL_EXT_blend_subtract', 'GL_EXT_blend_color', 'GL_EXT_abgr', 'GL_EXT_texture3D', 'GL_EXT_clip_volume_hint', 'GL_EXT_compiled_vertex_array', 'GL_SGIS_texture_edge_clamp', 'GL_SGIS_generate_mipmap', 'GL_EXT_draw_range_elements', 'GL_SGIS_texture_lod', 'GL_EXT_rescale_normal', 'GL_EXT_packed_pixels', 'GL_EXT_texture_edge_clamp', 'GL_EXT_separate_specular_color', 'GL_ARB_multitexture', 'GL_ARB_map_buffer_alignment', 'GL_ARB_conservative_depth', 'GL_EXT_texture_env_combine', 'GL_EXT_bgra', 'GL_EXT_blend_func_separate', 'GL_EXT_secondary_color', 'GL_EXT_fog_coord', 'GL_EXT_texture_env_add', 'GL_ARB_texture_cube_map', 'GL_ARB_transpose_matrix', 'GL_ARB_internalformat_query', 'GL_ARB_internalformat_query2', 'GL_ARB_texture_env_add', 'GL_IBM_texture_mirrored_repeat', 'GL_EXT_multi_draw_arrays', 'GL_SUN_multi_draw_arrays', 'GL_NV_blend_square', 'GL_ARB_texture_compression', 'GL_3DFX_texture_compression_FXT1', 'GL_EXT_texture_filter_anisotropic', 'GL_ARB_texture_border_clamp', 'GL_ARB_point_parameters', 'GL_ARB_texture_env_combine', 'GL_ARB_texture_env_dot3', 'GL_ARB_texture_env_crossbar', 'GL_EXT_texture_compression_s3tc', 'GL_ARB_shadow', 'GL_ARB_window_pos', 'GL_EXT_shadow_funcs', 'GL_EXT_stencil_wrap', 'GL_ARB_vertex_program', 'GL_EXT_texture_rectangle', 'GL_ARB_fragment_program', 'GL_EXT_stencil_two_side', 'GL_ATI_separate_stencil', 'GL_ARB_vertex_buffer_object', 'GL_EXT_texture_lod_bias', 'GL_ARB_occlusion_query', 'GL_ARB_fragment_shader', 'GL_ARB_shader_objects', 'GL_ARB_shading_language_100', 'GL_ARB_texture_non_power_of_two', 'GL_ARB_vertex_shader', 'GL_NV_texgen_reflection', 'GL_ARB_point_sprite', 'GL_ARB_fragment_program_shadow', 'GL_EXT_blend_equation_separate', 'GL_ARB_depth_texture', 'GL_ARB_texture_rectangle', 'GL_ARB_draw_buffers', 'GL_ARB_color_buffer_float', 'GL_ARB_half_float_pixel', 'GL_ARB_texture_float', 'GL_ARB_pixel_buffer_object', 'GL_EXT_framebuffer_object', 'GL_ARB_draw_instanced', 'GL_ARB_half_float_vertex', 'GL_ARB_occlusion_query2', 'GL_EXT_draw_buffers2', 'GL_WIN_swap_hint', 'GL_EXT_texture_sRGB', 'GL_ARB_multisample', 'GL_EXT_packed_float', 'GL_EXT_texture_shared_exponent', 'GL_ARB_texture_rg', 'GL_ARB_texture_compression_rgtc', 'GL_NV_conditional_render', 'GL_ARB_texture_swizzle', 'GL_EXT_texture_swizzle', 'GL_ARB_texture_gather', 'GL_ARB_sync', 'GL_ARB_framebuffer_sRGB', 'GL_EXT_packed_depth_stencil', 'GL_ARB_depth_buffer_float', 'GL_EXT_transform_feedback', 'GL_ARB_transform_feedback2', 'GL_ARB_draw_indirect', 'GL_EXT_framebuffer_blit', 'GL_EXT_framebuffer_multisample', 'GL_ARB_framebuffer_object', 'GL_ARB_framebuffer_no_attachments', 'GL_EXT_texture_array', 'GL_EXT_texture_integer', 'GL_ARB_map_buffer_range', 'GL_ARB_texture_buffer_range', 'GL_EXT_texture_buffer', 'GL_EXT_texture_snorm', 'GL_ARB_blend_func_extended', 'GL_INTEL_performance_queries', 'GL_INTEL_performance_query', 'GL_ARB_copy_buffer', 'GL_ARB_sampler_objects', 'GL_NV_primitive_restart', 'GL_ARB_seamless_cube_map', 'GL_ARB_uniform_buffer_object', 'GL_ARB_depth_clamp', 'GL_ARB_vertex_array_bgra', 'GL_ARB_shader_bit_encoding', 'GL_ARB_draw_buffers_blend', 'GL_ARB_geometry_shader4', 'GL_EXT_geometry_shader4', 'GL_ARB_texture_query_lod', 'GL_ARB_explicit_attrib_location', 'GL_ARB_draw_elements_base_vertex', 'GL_ARB_instanced_arrays', 'GL_ARB_base_instance', 'GL_ARB_fragment_coord_conventions', 'GL_EXT_gpu_program_parameters', 'GL_ARB_texture_buffer_object_rgb32', 'GL_ARB_compatibility', 'GL_ARB_texture_rgb10_a2ui', 'GL_ARB_texture_multisample', 'GL_ARB_vertex_type_2_10_10_10_rev', 'GL_ARB_timer_query', 'GL_ARB_tessellation_shader', 'GL_ARB_vertex_array_object', 'GL_ARB_provoking_vertex', 'GL_ARB_sample_shading', 'GL_ARB_texture_cube_map_array', 'GL_EXT_gpu_shader4', 'GL_ARB_gpu_shader5', 'GL_ARB_gpu_shader_fp64', 'GL_ARB_shader_subroutine', 'GL_ARB_transform_feedback3', 'GL_ARB_get_program_binary', 'GL_ARB_separate_shader_objects', 'GL_ARB_shader_precision', 'GL_ARB_vertex_attrib_64bit', 'GL_ARB_viewport_array', 'GL_ARB_transform_feedback_instanced', 'GL_ARB_compressed_texture_pixel_storage', 'GL_ARB_shader_atomic_counters', 'GL_ARB_shading_language_packing', 'GL_ARB_shading_language_420pack', 'GL_ARB_texture_storage', 'GL_EXT_texture_storage', 'GL_ARB_vertex_attrib_binding', 'GL_ARB_multi_draw_indirect', 'GL_ARB_program_interface_query', 'GL_ARB_texture_storage_multisample', 'GL_ARB_buffer_storage', 'GL_ARB_debug_output', 'GL_KHR_debug', 'GL_ARB_arrays_of_arrays', 'GL_INTEL_map_texture', 'GL_ARB_texture_compression_bptc', 'GL_ARB_ES2_compatibility', 'GL_ARB_ES3_compatibility', 'GL_ARB_robustness', 'GL_EXT_texture_sRGB_decode', 'GL_KHR_blend_equation_advanced', 'GL_EXT_shader_integer_mix', 'GL_ARB_stencil_texturing', ''], 'vendor': 'Intel', 'renderer': 'Intel(R) HD Graphics 4000', 'shading-language-version': '4.00 - Build 10.18.10.4276', 'GLU.version': '1.2.2.0 Microsoft Corporation', 'GLU.extensions': 'GL_EXT_bgra', 'safe': True, 'transparency': True, 'texture-size-limit': 16384, 'max-viewport-dims': (16384, 16384), 'display_mode': ['DOUBLE']}
do_run_glcheck() opengl_props={'pyopengl': '3.1.5', 'opengl': (4, 0), 'accelerate': '3.1.5', 'zerocopy': True, 'extensions': ['GL_EXT_blend_minmax', 'GL_EXT_blend_subtract', 'GL_EXT_blend_color', 'GL_EXT_abgr', 'GL_EXT_texture3D', 'GL_EXT_clip_volume_hint', 'GL_EXT_compiled_vertex_array', 'GL_SGIS_texture_edge_clamp', 'GL_SGIS_generate_mipmap', 'GL_EXT_draw_range_elements', 'GL_SGIS_texture_lod', 'GL_EXT_rescale_normal', 'GL_EXT_packed_pixels', 'GL_EXT_texture_edge_clamp', 'GL_EXT_separate_specular_color', 'GL_ARB_multitexture', 'GL_ARB_map_buffer_alignment', 'GL_ARB_conservative_depth', 'GL_EXT_texture_env_combine', 'GL_EXT_bgra', 'GL_EXT_blend_func_separate', 'GL_EXT_secondary_color', 'GL_EXT_fog_coord', 'GL_EXT_texture_env_add', 'GL_ARB_texture_cube_map', 'GL_ARB_transpose_matrix', 'GL_ARB_internalformat_query', 'GL_ARB_internalformat_query2', 'GL_ARB_texture_env_add', 'GL_IBM_texture_mirrored_repeat', 'GL_EXT_multi_draw_arrays', 'GL_SUN_multi_draw_arrays', 'GL_NV_blend_square', 'GL_ARB_texture_compression', 'GL_3DFX_texture_compression_FXT1', 'GL_EXT_texture_filter_anisotropic', 'GL_ARB_texture_border_clamp', 'GL_ARB_point_parameters', 'GL_ARB_texture_env_combine', 'GL_ARB_texture_env_dot3', 'GL_ARB_texture_env_crossbar', 'GL_EXT_texture_compression_s3tc', 'GL_ARB_shadow', 'GL_ARB_window_pos', 'GL_EXT_shadow_funcs', 'GL_EXT_stencil_wrap', 'GL_ARB_vertex_program', 'GL_EXT_texture_rectangle', 'GL_ARB_fragment_program', 'GL_EXT_stencil_two_side', 'GL_ATI_separate_stencil', 'GL_ARB_vertex_buffer_object', 'GL_EXT_texture_lod_bias', 'GL_ARB_occlusion_query', 'GL_ARB_fragment_shader', 'GL_ARB_shader_objects', 'GL_ARB_shading_language_100', 'GL_ARB_texture_non_power_of_two', 'GL_ARB_vertex_shader', 'GL_NV_texgen_reflection', 'GL_ARB_point_sprite', 'GL_ARB_fragment_program_shadow', 'GL_EXT_blend_equation_separate', 'GL_ARB_depth_texture', 'GL_ARB_texture_rectangle', 'GL_ARB_draw_buffers', 'GL_ARB_color_buffer_float', 'GL_ARB_half_float_pixel', 'GL_ARB_texture_float', 'GL_ARB_pixel_buffer_object', 'GL_EXT_framebuffer_object', 'GL_ARB_draw_instanced', 'GL_ARB_half_float_vertex', 'GL_ARB_occlusion_query2', 'GL_EXT_draw_buffers2', 'GL_WIN_swap_hint', 'GL_EXT_texture_sRGB', 'GL_ARB_multisample', 'GL_EXT_packed_float', 'GL_EXT_texture_shared_exponent', 'GL_ARB_texture_rg', 'GL_ARB_texture_compression_rgtc', 'GL_NV_conditional_render', 'GL_ARB_texture_swizzle', 'GL_EXT_texture_swizzle', 'GL_ARB_texture_gather', 'GL_ARB_sync', 'GL_ARB_framebuffer_sRGB', 'GL_EXT_packed_depth_stencil', 'GL_ARB_depth_buffer_float', 'GL_EXT_transform_feedback', 'GL_ARB_transform_feedback2', 'GL_ARB_draw_indirect', 'GL_EXT_framebuffer_blit', 'GL_EXT_framebuffer_multisample', 'GL_ARB_framebuffer_object', 'GL_ARB_framebuffer_no_attachments', 'GL_EXT_texture_array', 'GL_EXT_texture_integer', 'GL_ARB_map_buffer_range', 'GL_ARB_texture_buffer_range', 'GL_EXT_texture_buffer', 'GL_EXT_texture_snorm', 'GL_ARB_blend_func_extended', 'GL_INTEL_performance_queries', 'GL_INTEL_performance_query', 'GL_ARB_copy_buffer', 'GL_ARB_sampler_objects', 'GL_NV_primitive_restart', 'GL_ARB_seamless_cube_map', 'GL_ARB_uniform_buffer_object', 'GL_ARB_depth_clamp', 'GL_ARB_vertex_array_bgra', 'GL_ARB_shader_bit_encoding', 'GL_ARB_draw_buffers_blend', 'GL_ARB_geometry_shader4', 'GL_EXT_geometry_shader4', 'GL_ARB_texture_query_lod', 'GL_ARB_explicit_attrib_location', 'GL_ARB_draw_elements_base_vertex', 'GL_ARB_instanced_arrays', 'GL_ARB_base_instance', 'GL_ARB_fragment_coord_conventions', 'GL_EXT_gpu_program_parameters', 'GL_ARB_texture_buffer_object_rgb32', 'GL_ARB_compatibility', 'GL_ARB_texture_rgb10_a2ui', 'GL_ARB_texture_multisample', 'GL_ARB_vertex_type_2_10_10_10_rev', 'GL_ARB_timer_query', 'GL_ARB_tessellation_shader', 'GL_ARB_vertex_array_object', 'GL_ARB_provoking_vertex', 'GL_ARB_sample_shading', 'GL_ARB_texture_cube_map_array', 'GL_EXT_gpu_shader4', 'GL_ARB_gpu_shader5', 'GL_ARB_gpu_shader_fp64', 'GL_ARB_shader_subroutine', 'GL_ARB_transform_feedback3', 'GL_ARB_get_program_binary', 'GL_ARB_separate_shader_objects', 'GL_ARB_shader_precision', 'GL_ARB_vertex_attrib_64bit', 'GL_ARB_viewport_array', 'GL_ARB_transform_feedback_instanced', 'GL_ARB_compressed_texture_pixel_storage', 'GL_ARB_shader_atomic_counters', 'GL_ARB_shading_language_packing', 'GL_ARB_shading_language_420pack', 'GL_ARB_texture_storage', 'GL_EXT_texture_storage', 'GL_ARB_vertex_attrib_binding', 'GL_ARB_multi_draw_indirect', 'GL_ARB_program_interface_query', 'GL_ARB_texture_storage_multisample', 'GL_ARB_buffer_storage', 'GL_ARB_debug_output', 'GL_KHR_debug', 'GL_ARB_arrays_of_arrays', 'GL_INTEL_map_texture', 'GL_ARB_texture_compression_bptc', 'GL_ARB_ES2_compatibility', 'GL_ARB_ES3_compatibility', 'GL_ARB_robustness', 'GL_EXT_texture_sRGB_decode', 'GL_KHR_blend_equation_advanced', 'GL_EXT_shader_integer_mix', 'GL_ARB_stencil_texturing', ''], 'vendor': 'Intel', 'renderer': 'Intel(R) HD Graphics 4000', 'shading-language-version': '4.00 - Build 10.18.10.4276', 'GLU.version': '1.2.2.0 Microsoft Corporation', 'GLU.extensions': 'GL_EXT_bgra', 'safe': True, 'transparency': True, 'texture-size-limit': 16384, 'max-viewport-dims': (16384, 16384), 'display_mode': ['DOUBLE']}, gl_client_window_module=<module 'xpra.client.gl.gtk3.nativegl_client_window' from 'C:\\Users\\stavros.ntentos\\Documents\\xpra-clients\\Xpra-Python3-x86_64_4.3-r30040\\lib\\xpra\\client\\gl\\gtk3\\nativegl_client_window.pyc'>
do_run_glcheck() gl_client_window_class=<class 'xpra.client.gl.gtk3.nativegl_client_window.GLClientWindow'>, pixel_depth=0
init_formats() texture pixel format=RGB, internal format=RGB8, rgb modes=['YUV420P', 'YUV422P', 'YUV444P', 'GBRP', 'BGRA', 'BGRX', 'RGBA', 'RGBX', 'RGB', 'BGR']
resize_fbo(0, 0, 250, 250) context=None, offscreen_fbo=None
OpenGL: testing draw on GLClientWindow(4294967295 : GLDrawingArea(4294967295, (250, 250), None)) widget <Gtk.DrawingArea object at 0x000002b0861caec0 (GtkDrawingArea at 0x000002b0851d4210)> with rgb32 : BGRX
remove_backing() backing=GLDrawingArea(4294967295, (250, 250), None)
remove_backing() glarea=None
do_run_glcheck(..)
Traceback (most recent call last):
  File "E:/xpra/xpra/scripts/main.py", line 2167, in do_run_glcheck
  File "E:/xpra/xpra/client/gl/window_backend.py", line 143, in test_gl_client_window
  File "C:/msys64/mingw64/lib/python3.9/site-packages/PIL/Image.py", line 2224, in save
KeyError: 'JPEG'
error='JPEG'
debug enabled for xpra.scripts.main / ('opengl',)
run_glcheck(..) props={'success': False, 'message': "'JPEG'"}
message='JPEG'
success=False
```

**Comment by totaam** [comment]
`KeyError: 'JPEG'` is because of #3133, somewhat similar to #3139.
The packaged version of xpra doesn't have the ability to save (and load?) jpeg...
Either because the trimming done in #3133 was too aggressive or because python-pillow changed the dependencies.

Will fix ASAP.

**Comment by totaam** [comment]
The commit above should avoid failing opengl just because pillow is not packaged properly.
Sure enough, I can see that `jpeg` is missing - which will help me fix things - running `Encoding_info.exe -v`:
```
* enc_pillow           : lib\xpra\codecs\pillow\encoder.pyc
                         encodings: png, png/L, png/P, webp
                         encodings = ['png', 'png/L', 'png/P', 'webp']
```

**Comment by stdedos** [comment]
Verified as fixed here too 🙂 

_Side question:_ Awesome move to move the logs to their respective display folders! When did you do that? 😀

**Comment by totaam** [comment]
> Awesome move to move the logs to their respective display folders! When did you do that?

#3217 (July!)
