### ISSUE TITLE
server unable to start

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#3328]
Somehow the windows were left in a broken state:
```
2021-10-27 20:30:21,761 Error: cannot start the seamless server
Traceback (most recent call last):
  File "/usr/lib64/python3.9/site-packages/xpra/scripts/server.py", line 1342, in _do_run_server
    app.server_init()
  File "/usr/lib64/python3.9/site-packages/xpra/x11/server.py", line 217, in server_init
    X11ServerBase.server_init(self)
  File "/usr/lib64/python3.9/site-packages/xpra/x11/x11_server_core.py", line 101, in server_init
    self.x11_init()
  File "/usr/lib64/python3.9/site-packages/xpra/x11/server.py", line 270, in x11_init
    self._wm = Wm(self.clobber, self.wm_name)
  File "/usr/lib64/python3.9/site-packages/xpra/x11/gtk_x11/wm.py", line 239, in __init__
    for w in get_children(self._root):
  File "xpra/x11/gtk3/gdk_bindings.pyx", line 568, in xpra.x11.gtk3.gdk_bindings.get_children
    return _query_tree(pywindow)[1]
  File "xpra/x11/gtk3/gdk_bindings.pyx", line 556, in xpra.x11.gtk3.gdk_bindings._query_tree
    pychildren.append(_get_pywindow(pywindow, children[i]))
  File "xpra/x11/gtk3/gdk_bindings.pyx", line 481, in xpra.x11.gtk3.gdk_bindings._get_pywindow
    raise XError(BadWindow)
xpra.gtk_common.error.XError: XError: BadWindow (invalid Window parameter)
2021-10-27 20:30:21,763 XError: BadWindow (invalid Window parameter)
```

```
$ DISPLAY=:4 xwininfo -tree -root

xwininfo: Window id: 0x50f (the root window) "Xpra"

  Root window id: 0x50f (the root window) "Xpra"
  Parent window id: 0x0 (none)
     14 children:
     0xc00008 "Home": ("org.gnome.Nautilus" "Org.gnome.Nautilus")  1576x797+0+0  +0+0
        1 child:
        0xc00009 (has no name): ()  1x1+-1+-1  +-1+-1
     0x20001e "antoine@fedora:~": ("xterm" "XTerm")  499x316+0+0  +0+0
        1 child:
        0x20002d (has no name): ()  499x316+0+0  +0+0
           1 child:
           0x200032 (has no name): ()  14x316+-1+-1  +-1+-1
     0xc14423 "org.gnome.Nautilus": ("org.gnome.Nautilus" "Org.gnome.Nautilus")  1x1+-99+-99  +-99+-99
        1 child:
        0xc14424 (has no name): ()  1x1+-1+-1  +-100+-100
     0xc143a6 "org.gnome.Nautilus": ("org.gnome.Nautilus" "Org.gnome.Nautilus")  1x1+-99+-99  +-99+-99
        1 child:
        0xc143a7 (has no name): ()  1x1+-1+-1  +-100+-100
     0xc0bb78 "org.gnome.Nautilus": ("org.gnome.Nautilus" "Org.gnome.Nautilus")  280x427+1489+937  +1489+937
        1 child:
        0xc0bb79 (has no name): ()  1x1+-1+-1  +1488+936
     0xc00329 "org.gnome.Nautilus": ()  10x10+-100+-100  +-100+-100
     0xc00003 (has no name): ()  1x1+-1+-1  +-1+-1
     0xc00001 "org.gnome.Nautilus": ("org.gnome.Nautilus" "Org.gnome.Nautilus")  10x10+10+10  +10+10
     0x800008 (has no name): ()  1x1+0+0  +0+0
     0x800003 "ibus-xim": ()  1x1+0+0  +0+0
        1 child:
        0x800004 (has no name): ()  1x1+-1+-1  +-1+-1
     0x600001 "ibus-extension-gtk3": ("ibus-extension-gtk3" "Ibus-extension-gtk3")  10x10+10+10  +10+10
     0x800001 "ibus-x11": ("ibus-x11" "Ibus-x11")  10x10+10+10  +10+10
     0x200054 (has no name): ()  218x428+249+231  +249+231
     0xa00001 "xdg-desktop-portal-gtk": ("xdg-desktop-portal-gtk" "Xdg-desktop-portal-gtk")  10x10+10+10  +10+10
```

And just as I added more debug to my server command line... it fixed itself.

**Comment by totaam** [comment]
Happened again. With the tool added in the commit above I found that `gnome-shell` had created thousands of 1x1 windows on a display it wasn't even meant to access! WTH!
```shell
$ DISPLAY=:10 xwininfo -tree -root | grep 1x1 | awk '{print $1}' | xargs ./tests/xpra/x11/xres_get_pid.py  | grep -a gnome-shell  | wc -l
2602
```
Also found 106 `/usr/libexec/ibus-extension-gtk3` and 2 `/usr/libexec/gsd-color`!!!

Another process I found there which had *no* business being there was https://github.com/flatpak/xdg-desktop-portal

**Comment by luke-jr** [comment]
Very reliably reproduced with TDE's KMail in my experience.

IIRC, Xpra's startup is triggering it to create and destroy a window, and the error results from the window being destroyed when Xpra tries to access it.

**Comment by totaam** [comment]
@luke-jr please try the commit above, it should fix things.

**Comment by luke-jr** [comment]
I don't see how. Xpra fails to start 100% of the time with KMail running, so simply retrying isn't going to get anywhere...

**Comment by totaam** [comment]
Retrying is the only thing you can do when dealing with race conditions through a synchronous API.
Please try the patch.

**Comment by luke-jr** [comment]
Confirmed f0db45b372e52288497976533215b8a5f673b3d5 seems to have fixed it
