### ISSUE TITLE
Unhandled error in audio processing

### ISSUE THREAD

**Issue by jdstroy** [Xpra-org/xpra#3347]
Hello, and thank you for xpra! 

I received the following error messages on the client while using audio in Xpra:

```
2021-11-07 02:09:18,755 Unhandled error while processing a 'sound-data' packet from peer using <bound method AudioClient._process_sound_data of gtk3.client>
Traceback (most recent call last):
  File "E:/xpra/xpra/client/client_base.py", line 1047, in process_packet
  File "E:/xpra/xpra/client/client_base.py", line 1044, in call_handler
  File "E:/xpra/xpra/client/mixins/audio.py", line 608, in _process_sound_data
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
2021-11-07 02:09:19,790 Unhandled error while processing a 'sound-data' packet from peer using <bound method AudioClient._process_sound_data of gtk3.client>
Traceback (most recent call last):
  File "E:/xpra/xpra/client/client_base.py", line 1047, in process_packet
  File "E:/xpra/xpra/client/client_base.py", line 1044, in call_handler
  File "E:/xpra/xpra/client/mixins/audio.py", line 608, in _process_sound_data
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
2021-11-07 02:09:20,330 Unhandled error while processing a 'sound-data' packet from peer using <bound method AudioClient._process_sound_data of gtk3.client>
Traceback (most recent call last):
  File "E:/xpra/xpra/client/client_base.py", line 1047, in process_packet
  File "E:/xpra/xpra/client/client_base.py", line 1044, in call_handler
  File "E:/xpra/xpra/client/mixins/audio.py", line 608, in _process_sound_data
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
2021-11-07 02:09:20,979 Unhandled error while processing a 'sound-data' packet from peer using <bound method AudioClient._process_sound_data of gtk3.client>
Traceback (most recent call last):
  File "E:/xpra/xpra/client/client_base.py", line 1047, in process_packet
  File "E:/xpra/xpra/client/client_base.py", line 1044, in call_handler
  File "E:/xpra/xpra/client/mixins/audio.py", line 608, in _process_sound_data
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
2021-11-07 02:09:21,435 Unhandled error while processing a 'sound-data' packet from peer using <bound method AudioClient._process_sound_data of gtk3.client>
Traceback (most recent call last):
  File "E:/xpra/xpra/client/client_base.py", line 1047, in process_packet
  File "E:/xpra/xpra/client/client_base.py", line 1044, in call_handler
  File "E:/xpra/xpra/client/mixins/audio.py", line 608, in _process_sound_data
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
2021-11-07 02:09:21,750 Unhandled error while processing a 'sound-data' packet from peer using <bound method AudioClient._process_sound_data of gtk3.client>
Traceback (most recent call last):
  File "E:/xpra/xpra/client/client_base.py", line 1047, in process_packet
  File "E:/xpra/xpra/client/client_base.py", line 1044, in call_handler
  File "E:/xpra/xpra/client/mixins/audio.py", line 608, in _process_sound_data
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
2021-11-07 02:09:23,995 Unhandled error while processing a 'sound-data' packet from peer using <bound method AudioClient._process_sound_data of gtk3.client>
Traceback (most recent call last):
  File "E:/xpra/xpra/client/client_base.py", line 1047, in process_packet
  File "E:/xpra/xpra/client/client_base.py", line 1044, in call_handler
  File "E:/xpra/xpra/client/mixins/audio.py", line 608, in _process_sound_data
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
```

(This was repeated many times.)

Client: Windows 10, Xpra 4.2.3r3, gstreamer 1.18.5.0, pygst 3.40.1
Server: Ubuntu 20.04, Xpra 4.3r30117, gstreamer 1.16.2.0, pygst 3.36.0

**Comment by totaam** [comment]
Thanks for the report, this should be fixed by the commit above.
You must have selected "Off" for av-sync, which triggers this bug.

There's a beta 4.3-r30353 build with this fix here: https://xpra.org/beta/windows/

**Comment by jdstroy** [comment]
Yup, I was experiencing audio syncing issues (huge ~10+ second delay), so I was trying to twiddle with audio sync settings to try to reset it.  Thanks!
