### ISSUE TITLE
SSH authentication failure on Windows

### ISSUE THREAD

**Issue by molasses11** [Xpra-org/xpra#3372]
Using the xpra client on Windows I'm attempting to connect to a remote machine. I can connect to the remote machine via normal ssh without problem. When I try to use xpra, however, it prompts for the ssh key password (which I enter), then prompts for the remote user password (which I also enter), and then displays an SSH authentication error as shown in the image. The same error happens when I tried to start both a seamless and shadow session. I haven't tried any other sessions.

![image](https://user-images.githubusercontent.com/28744886/144144169-13818a36-8627-4cb3-8bee-9a47e3db93ec.png)

Note that I have been successful in using xpra to connect to this same remote machine from a different client machine that was not running Windows (specifically Ubuntu 20.04).

Sorry about the relatively little amount of information, I'm unsure of where to get any other information on the error as I can't find a setting in the GUI to show more verbose output, or to enable a log file or anything similar.

Any help or direction is appreciated!

Edit:
I ran `Xpra_cmd attach ssh://username@host/ -d ssh` and got the following output:
```
2021-12-01 12:51:22,218 Xpra GTK3 client version 4.2.3-r3 64-bit
2021-12-01 12:51:22,227  running on Microsoft Windows 10
2021-12-01 12:51:24,790 GStreamer version 1.18.5 for Python 3.9.7 64-bit
2021-12-01 12:51:24,909 created named pipe 'Xpra\3152'
2021-12-01 12:51:25,059 keyboard layout code 0x409
2021-12-01 12:51:25,059 identified as 'United States - English' : us
2021-12-01 12:51:25,120 OpenGL_accelerate module loaded
2021-12-01 12:51:25,142 Using accelerated ArrayDatatype
2021-12-01 12:51:25,635 OpenGL accelerate missing: numpy_formathandler
2021-12-01 12:51:25,638 OpenGL enabled with NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
2021-12-01 12:51:25,642 using paramiko ssh backend
2021-12-01 12:51:25,745 parsed user config 'C:\Users\Justin/.ssh/config'
2021-12-01 12:51:25,745 3 hosts found
2021-12-01 12:51:26,768 got host config for 'whidowmaker3.bluezone.usu.edu': {'hostname': 'whidowmaker3.bluezone.usu.edu', 'user': 'justin', 'identityfile': ['D:\\Users\\Justin\\.ssh\\nautilus_ed25519'], 'forwardx11': 'yes', 'forwardx11trusted': 'yes', 'compression': 'yes', 'compressionlevel': '6'}
2021-12-01 12:51:29,005 paramiko socket_connect: sockname=('129.123.36.12', 57894), peername=('144.39.227.129', 22)
2021-12-01 12:51:29,019 Connected (version 2.0, client OpenSSH_7.6p1)
2021-12-01 12:51:29,098 do_ssh_paramiko_connect_to(<paramiko.Transport at 0x3befdf0 (cipher aes128-ctr, 128 bits) (connected; awaiting auth)>, 'whidowmaker3.bluezone.usu.edu', 'justin', None, {'hostname': 'whidowmaker3.bluezone.usu.edu', 'user': 'justin', 'identityfile': ['D:\\Users\\Justin\\.ssh\\nautilus_ed25519'], 'forwardx11': 'yes', 'forwardx11trusted': 'yes', 'compression': 'yes', 'compressionlevel': '6'}, ['D:\\Users\\Justin\\.ssh\\nautilus_ed25519'], {'display_name': 'ssh://justin@whidowmaker3.bluezone.usu.edu/', 'type': 'ssh', 'proxy_command': ['_proxy'], 'exit_ssh': True, 'display': None, 'display_as_args': [], 'is_paramiko': True, 'username': 'justin', 'port': 22, 'host': 'whidowmaker3.bluezone.usu.edu', 'local': False, 'full_ssh': ['paramiko'], 'remote_xpra': ['xpra', '$XDG_RUNTIME_DIR/xpra/run-xpra', '/usr/local/bin/xpra', '~/.xpra/run-xpra', 'Xpra_cmd.exe']})
2021-12-01 12:51:29,099 SSH transport <paramiko.Transport at 0x3befdf0 (cipher aes128-ctr, 128 bits) (connected; awaiting auth)>
2021-12-01 12:51:29,099 remote_server_key=MD5:83:7a:0b:10:f8:1d:9c:7a:ff:5c:8f:b3:af:0e:82:14
2021-12-01 12:51:29,100 HostKeys.load(C:\Users\Justin/.ssh/known_hosts) successful
2021-12-01 12:51:29,100 host keys=<paramiko.hostkeys.HostKeys object at 0x000001f903c149a0>
2021-12-01 12:51:29,101 ed25519 host key 'MD5:83:7a:0b:10:f8:1d:9c:7a:ff:5c:8f:b3:af:0e:82:14' OK for host 'whidowmaker3.bluezone.usu.edu'
2021-12-01 12:51:29,101 starting authentication, authentication methods: ['none', 'agent', 'key', 'password']
2021-12-01 12:51:29,101 auth=none
2021-12-01 12:51:29,101 trying none authentication
2021-12-01 12:51:29,207 auth_none()
Traceback (most recent call last):
  File "E:/xpra/xpra/net/ssh.py", line 660, in auth_none
  File "C:/msys64/mingw64/lib/python3.9/site-packages/paramiko/transport.py", line 1446, in auth_none
  File "C:/msys64/mingw64/lib/python3.9/site-packages/paramiko/auth_handler.py", line 250, in wait_for_response
paramiko.ssh_exception.BadAuthenticationType: Bad authentication type; allowed types: ['publickey', 'password']
2021-12-01 12:51:29,208 auth=agent
2021-12-01 12:51:29,210 agent keys: ()
2021-12-01 12:51:29,210 auth=key
2021-12-01 12:51:29,210 trying public key authentication using ['D:\\Users\\Justin\\.ssh\\nautilus_ed25519']
2021-12-01 12:51:29,210 trying 'D:\Users\Justin\.ssh\nautilus_ed25519'
2021-12-01 12:51:29,211 trying to load as Ed25519
2021-12-01 12:51:29,211 D:\Users\Justin\.ssh\nautilus_ed25519 keyfile requires a passphrase; Private key file is encrypted
2021-12-01 12:51:29,212 dialog_pass('Password Input', 'please enter the passphrase for D:\\Users\\Justin\\.ssh\\nautilus_ed25519:', 'D:\\Programs\\Xpra\\share\\xpra\\icons\\authentication.png') PINENTRY=False
2021-12-01 12:51:29,212 dialog_run(<function dialog_pass.<locals>.password_input_run at 0x000001f903c604c0>) is_main_thread=False, main_level=1
2021-12-01 12:51:29,212 dialog_run(<function dialog_pass.<locals>.password_input_run at 0x000001f903c604c0>) main_depth=0
2021-12-01 12:51:29,213 dialog_run(<function dialog_pass.<locals>.password_input_run at 0x000001f903c604c0>) waiting for main thread to run
2021-12-01 12:51:29,213 main_thread_run() calling <function dialog_pass.<locals>.password_input_run at 0x000001f903c604c0>
2021-12-01 12:51:36,912 dialog_run(<function dialog_pass.<locals>.password_input_run at 0x000001f903c604c0>) code=[0]
2021-12-01 12:51:36,912 Error: cannot load private key 'D:\Users\Justin\.ssh\nautilus_ed25519'
2021-12-01 12:51:36,912 auth=password
2021-12-01 12:51:36,912 trying interactive authentication
2021-12-01 12:51:36,961 auth_interactive(..)
Traceback (most recent call last):
  File "E:/xpra/xpra/net/ssh.py", line 689, in auth_interactive
  File "C:/msys64/mingw64/lib/python3.9/site-packages/paramiko/transport.py", line 1633, in auth_interactive
  File "C:/msys64/mingw64/lib/python3.9/site-packages/paramiko/auth_handler.py", line 250, in wait_for_response
paramiko.ssh_exception.BadAuthenticationType: Bad authentication type; allowed types: ['publickey', 'password']
2021-12-01 12:51:36,962 SSH password authentication failed:
2021-12-01 12:51:36,962  Bad authentication type; allowed types: ['publickey', 'password']
2021-12-01 12:51:36,962 dialog_pass('Password Input', 'please enter the SSH password for justin@whidowmaker3.bluezone.usu.edu:', 'D:\\Programs\\Xpra\\share\\xpra\\icons\\authentication.png') PINENTRY=False
2021-12-01 12:51:36,963 dialog_run(<function dialog_pass.<locals>.password_input_run at 0x000001f903c604c0>) is_main_thread=False, main_level=1
2021-12-01 12:51:36,964 dialog_run(<function dialog_pass.<locals>.password_input_run at 0x000001f903c604c0>) main_depth=0
2021-12-01 12:51:36,964 dialog_run(<function dialog_pass.<locals>.password_input_run at 0x000001f903c604c0>) waiting for main thread to run
2021-12-01 12:51:36,964 main_thread_run() calling <function dialog_pass.<locals>.password_input_run at 0x000001f903c604c0>
2021-12-01 12:51:59,996 dialog_run(<function dialog_pass.<locals>.password_input_run at 0x000001f903c604c0>) code=[0]
Warning: failed to connect:
 SSH Authentication on whidowmaker3.bluezone.usu.edu failed
```

**Comment by totaam** [comment]
To get more diagnostics, please run from the command line:
```shell
Xpra_cmd attach ssh://username@host/ -d ssh
```
If that doesn't shed any light, you can look in your server's ssh authentication log.

**Comment by molasses11** [comment]
I edited my post with more information from the command. I'm not familiar enough with what the output from that command is saying to get any further on figuring out what the problem is though, so any help with that is appreciated!

**Comment by totaam** [comment]
Sorry, I'm not sure what is wrong here.
Perhaps switching back to plink will work:
```shell
Xpra_cmd.exe attach --ssh="plink.exe -ssh -agent" ...
```

**Comment by molasses11** [comment]
>FYI: ssh compression may well slow down xpra network traffic...
And enabling X11 forwarding may interfere.

I tried running `Xpra_cmd.exe attach ...` with all of the config fields disabled/commented out except for `hostname`, `user`, and `identityfile` and go the same behavior and error as before.

>Perhaps switching back to plink will work:
```Xpra_cmd.exe attach --ssh="plink.exe -ssh -agent" ...```
Though plink will ignore your host config.

I tried this and got the following log
```
2021-12-02 19:47:25,053 Xpra GTK3 client version 4.2.3-r3 64-bit
2021-12-02 19:47:25,062  running on Microsoft Windows 10
2021-12-02 19:47:27,578 GStreamer version 1.18.5 for Python 3.9.7 64-bit
2021-12-02 19:47:27,698 created named pipe 'Xpra\10208'
2021-12-02 19:47:27,846 identified as 'United States - English' : us
2021-12-02 19:47:27,907 OpenGL_accelerate module loaded
2021-12-02 19:47:27,929 Using accelerated ArrayDatatype
2021-12-02 19:47:28,413 OpenGL accelerate missing: numpy_formathandler
2021-12-02 19:47:28,415 OpenGL enabled with NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
2021-12-02 19:47:28,511 executing ssh command: "plink.exe" "-ssh" "-agent" "-l" "justin" "-T" "whidowmaker3.bluezone.usu.edu" "sh -c 'if which "xpra" > /dev/null 2>&1; then xpra _proxy;elif [ -x $XDG_RUNTIME_DIR/xpra/run-xpra ]; then $XDG_RUNTIME_DIR/xpra/run-xpra _proxy;elif [ -x /usr/local/bin/xpra ]; then /usr/local/bin/xpra _proxy;elif [ -x ~/.xpra/run-xpra ]; then ~/.xpra/run-xpra _proxy;elif [ -x Xpra_cmd.exe ]; then Xpra_cmd.exe _proxy;else echo "no run-xpra command found"; exit 1; fi'"
2021-12-02 19:47:28,530  keyboard settings: layout=us
2021-12-02 19:47:28,531  desktop size is 3520x1080 with 1 screen:
2021-12-02 19:47:28,531   Default (931x285 mm - DPI: 96x96) workarea: 3520x1050
2021-12-02 19:47:28,531     MZ215ED 1920x1080 (477x268 mm - DPI: 102x102) workarea: 1920x1050
2021-12-02 19:47:28,531     Generic PnP Monitor 1600x900 at 1920x66 (443x249 mm - DPI: 92x92) workarea: 1600x870 at 1920x66
2021-12-02 19:47:41,757 Error: failed to receive anything, not an xpra server?
2021-12-02 19:47:41,757   could also be the wrong protocol, username, password or port
2021-12-02 19:47:41,758   or the session was not found
2021-12-02 19:47:41,758 Connection lost
2021-12-02 19:47:41,762 SSH EOF on stderr of ['plink.exe', '-ssh', '-agent', '-l', 'justin', '-T', 'whidowmaker3.bluezone.usu.edu', 'sh -c \'if which "xpra" > /dev/null 2>&1; then xpra _proxy;elif [ -x $XDG_RUNTIME_DIR/xpra/run-xpra ]; then $XDG_RUNTIME_DIR/xpra/run-xpra _proxy;elif [ -x /usr/local/bin/xpra ]; then /usr/local/bin/xpra _proxy;elif [ -x ~/.xpra/run-xpra ]; then ~/.xpra/run-xpra _proxy;elif [ -x Xpra_cmd.exe ]; then Xpra_cmd.exe _proxy;else echo "no run-xpra command found"; exit 1; fi\'']
2021-12-02 19:47:41,762 remote SSH stderr:
2021-12-02 19:47:41,763  xpra initialization error:
2021-12-02 19:47:41,763   cannot find any live servers to connect to
```

**Comment by totaam** [comment]
The answer is right there:
```
xpra initialization error:
  cannot find any live servers to connect to
```
It doesn't find the session you are trying to connect to.

**Comment by molasses11** [comment]
Ok. After ensuring that the session existed (it had stopped without me realizing), I was able to attach using plink (`Xpra_cmd.exe attach --ssh="plink.exe -ssh -agent" ...`). The normal Xpra method still would fail to authenticate (both with and without the extra ssh config options)

**Comment by totaam** [comment]
> The normal Xpra method still would fail to authenticate just like before

Then the answer may be in the server's ssh log.
You may also want to try the latest MS Windows beta build as there was an ssh related fix in there.

**Comment by molasses11** [comment]
Looking at the server's ssh log it seems that it is the same problem as #3330. I'm not able to verify this for sure at the moment, but when I can I will use a beta build that addresses #3330 and verify that my issue is solved or not.

**Comment by totaam** [comment]
Closing as duplicate.
