### ISSUE TITLE
`run_remote_server`: `FileNotFoundError: [Errno 2] No such file or directory`

### ISSUE THREAD

**Issue by stdedos** [Xpra-org/xpra#3381]
I welcome myself back!

```
"Xpra-Python3-x86_64_4.3-r30644\xpra_cmd" shadow ssh://user@ip/0 --ssh="plink -ssh -agent" --modal-windows=no --desktop-scaling=no --headerbar=off --title="@title@ on @@/@server-display@" --microphone=off --speaker=off --webcam=no --pulseaudio=no

XPRA_EXECUTABLE=Xpra-Python3-x86_64_4.3-r30644

2021-12-08 20:22:32,171 Xpra GTK3 client version 4.3-r30644 (g0fc7073b8) 64-bit
2021-12-08 20:22:32,179  running on Microsoft Windows 10
2021-12-08 20:22:35,086 GStreamer version 1.18.5 for Python 3.9.7 64-bit
2021-12-08 20:22:35,487 created named pipe 'Xpra\8288'
2021-12-08 20:22:35,677 keyboard layout code 0x409
2021-12-08 20:22:35,678 identified as 'United States - English' : us
2021-12-08 20:22:35,736 OpenGL_accelerate module loaded
2021-12-08 20:22:35,753 Using accelerated ArrayDatatype
2021-12-08 20:22:36,172 OpenGL accelerate missing: numpy_formathandler
2021-12-08 20:22:36,175 OpenGL enabled with NVIDIA GeForce RTX 2080 SUPER/PCIe/SSE2
2021-12-08 20:22:36,376  keyboard settings: layout=us
2021-12-08 20:22:36,377  desktop size is 4480x1536:
2021-12-08 20:22:36,378   Default (1185x406 mm - DPI: 96x96) workarea: 4480x1496
2021-12-08 20:22:36,378     Samsung C32JG5x 2560x1440 at    0x0    (697x392 mm - DPI: 93x93) workarea: 2560x1400
2021-12-08 20:22:36,378     LG IPS234 1920x1080 at 2560x456  (510x290 mm - DPI: 96x95) workarea: 1920x1040 at 2560x456
2021-12-08 20:22:40,529 enabled remote logging
2021-12-08 20:22:40,529 Xpra shadow server version 4.3-r30607 64-bit
2021-12-08 20:22:40,530  running on Linux Ubuntu 20.04 focal
2021-12-08 20:22:40,530  remote desktop size is 1920x1080 with 1 screen:
2021-12-08 20:22:40,530   :0.0 (508x286 mm - DPI: 96x96) workarea: 1920x986  at    0x27
2021-12-08 20:22:40,531     LGD eDP-1 (309x174 mm - DPI: 158x158)
Traceback (most recent call last):
  File "E:/xpra/xpra/client/client_base.py", line 1111, in call_handler
  File "E:/xpra/xpra/client/mixins/window_manager.py", line 1014, in _process_new_window
  File "E:/xpra/xpra/client/mixins/window_manager.py", line 748, in _process_new_common
  File "E:/xpra/xpra/client/mixins/window_manager.py", line 751, in make_new_window
  File "E:/xpra/xpra/client/gtk_base/gtk_client_base.py", line 1271, in get_client_window_classes
  File "E:/xpra/xpra/client/gtk_base/gtk_client_base.py", line 1295, in can_use_opengl
AttributeError: 'NoneType' object has no attribute 'find'
2021-12-08 20:22:40,715 remote SSH stderr:
2021-12-08 20:22:40,715  Entering daemon mode; any further errors will be reported to:
2021-12-08 20:22:40,716    /run/user/1000/xpra/0/server.log.new
2021-12-08 20:22:40,716  Actual log file name is now: /run/user/1000/xpra/0/server.log
CONNECTION_LOST, reconnecting
xpra main error:
Traceback (most recent call last):
  File "E:/xpra/xpra/scripts/main.py", line 142, in main
  File "E:/xpra/xpra/scripts/main.py", line 415, in run_mode
  File "E:/xpra/xpra/scripts/main.py", line 425, in do_run_mode
  File "E:/xpra/xpra/scripts/main.py", line 1921, in run_remote_server
FileNotFoundError: [Errno 2] No such file or directory
```

Both Xpra-Python3-x86_64_4.3-r30644 (0fc7073b8) and Xpra-Python3-x86_64_4.3-r30322 versions exhibit this `FileNotFoundError: [Errno 2] No such file or directory` issue.

Server says:
```
 45 2021-12-08 20:22:40,554 Warning: failed to load '/usr/share/pixmaps/sqlitebrowser.svg':
 46 2021-12-08 20:22:40,554  [Errno 21] Is a directory: '/usr/share/pixmaps/sqlitebrowser.svg'
 47 2021-12-08 20:22:40,657 Error: processing new connection from Protocol(unix-domain socket:/home/usr/.xpra/usr-h-0):
 48 2021-12-08 20:22:40,657  rgb encoder is missing
```

Server Settings:
```
@u-h ➜ 0  xpra showconfig | grep -P '\((used|default)\)'
csc-modules           (used)   =                                   <class 'list'>
csc-modules          (default) = 'all'                             <class 'list'>
pdf-printer           (used)   = ''                                <class 'str'>
pdf-printer          (default) = '/usr/share/ppd/cupsfilters/Generic-PDF_Printer-PDF.ppd'  <class 'str'>
postscript-printer    (used)   = ''                                <class 'str'>
postscript-printer   (default) = 'drv:///sample.drv/generic.ppd'   <class 'str'>
proxy-video-encoders  (used)   =                                   <class 'list'>
proxy-video-encoders (default) = 'none'                            <class 'list'>
socket-dirs           (used)   = '/run/user/$UID/xpra', '/run/xpra', '~/.xpra'  <class 'list'>
socket-dirs          (default) = '/run/user/1000/xpra', '/run/xpra', '~/.xpra'  <class 'list'>
video-decoders        (used)   =                                   <class 'list'>
video-decoders       (default) = 'all'                             <class 'list'>
video-encoders        (used)   =                                   <class 'list'>
video-encoders       (default) = 'all'                             <class 'list'>
xvfb                  (used)   = 'Xvfb +extension GLX +extension Composite -screen 0  8192x4096x24+32 -nolisten tcp -noreset -auth $XAUTHORITY  -dpi 96'  <class 'str'>
xvfb                 (default) = 'Xvfb +extension GLX +extension Composite -screen 0 8192x4096x24+32 -nolisten tcp -noreset -auth $XAUTHORITY -dpi 96'  <class 'str'>
```
but that cannot be, since e.g.:
```
/etc/xpra/conf.d/ $ grep -vP '^(#.*|\s+)*$' 30_picture.conf 
encodings = all
encoding = auto
video-encoders = all
csc-modules = all
video-decoders = all
video-scaling = auto
quality = auto
min-quality = 1
speed = auto
min-speed = 1
auto-refresh-delay = 0.15
pixel-depth = 0
$ ls -lah ~/.xpra
total 32K
drwx------  2 stdedos stdedos 4,0K Δεκ   8 20:22 .
drwx------ 63 stdedos stdedos  24K Δεκ   8 20:39 ..
```

---------

PS: 

1. Page https://xpra.org/trac/wiki/Configuration is missing from the wiki (https://github.com/Xpra-org/xpra/wiki)
2. `I tried to find xpra/platform/path.py tool to check if there is more information, but there seems to be nothing:` seems to still be valid, after all this time? 😕 https://github.com/Xpra-org/xpra/issues/2582#issue-792145000
3. ```
 	 Traceback (most recent call last):
	    File "E:/xpra/xpra/client/client_base.py", line 1111, in call_handler
	    File "E:/xpra/xpra/client/mixins/window_manager.py", line 1014, in _process_new_window
	    File "E:/xpra/xpra/client/mixins/window_manager.py", line 748, in _process_new_common
	    File "E:/xpra/xpra/client/mixins/window_manager.py", line 751, in make_new_window
	    File "E:/xpra/xpra/client/gtk_base/gtk_client_base.py", line 1271, in get_client_window_classes
	    File "E:/xpra/xpra/client/gtk_base/gtk_client_base.py", line 1295, in can_use_opengl
	  AttributeError: 'NoneType' object has no attribute 'find'
	  ```
	  is new to Xpra-Python3-x86_64_4.3-r30644 (0fc7073b8)
4.   ```
	   80 2021-12-08 20:22:49,575 Warning: clipboard request id 0 not found
	   81 Traceback (most recent call last):
	   82   File "/usr/lib/python3/dist-packages/xpra/clipboard/clipboard_timeout_helper.py", line 94, in timeout_request
	   83     selection, target = self._clipboard_outstanding_requests.pop(request_id)[1:]
	   84 KeyError: 0
	   85 
	   86 During handling of the above exception, another exception occurred:
	   87 
	   88 Traceback (most recent call last):
	   89   File "/usr/lib/python3/dist-packages/xpra/clipboard/clipboard_timeout_helper.py", line 97, in timeout_request
	   90     log.warn(" selection=%s, target=%s", selection, target)
	   91 UnboundLocalError: local variable 'selection' referenced before assignment
	   92 2021-12-08 20:22:49,676 Warning: clipboard request id 1 not found
	   93 Traceback (most recent call last):
	   94   File "/usr/lib/python3/dist-packages/xpra/clipboard/clipboard_timeout_helper.py", line 94, in timeout_request
	   95     selection, target = self._clipboard_outstanding_requests.pop(request_id)[1:]
	   96 KeyError: 1
	   97 
	   98 During handling of the above exception, another exception occurred:
	   99 
	  100 Traceback (most recent call last):
	  101   File "/usr/lib/python3/dist-packages/xpra/clipboard/clipboard_timeout_helper.py", line 97, in timeout_request
	  102     log.warn(" selection=%s, target=%s", selection, target)
	  103 UnboundLocalError: local variable 'selection' referenced before assignment
	  ```

**Comment by totaam** [comment]
> `AttributeError: 'NoneType' object has no attribute 'find'`

Fixed: 7716c0bf9d00e5d12978fee0f5aa37d2970f3662

> `UnboundLocalError: local variable 'selection' referenced before assignment`

Fixed: b6e78d262d1615df5c920ab26ddfc13adf910a84

> Page `https://xpra.org/trac/wiki/Configuration` is missing from the wiki

This page is now part of the documentation:
https://github.com/Xpra-org/xpra/blob/master/docs/Usage/Configuration.md
and the documentation pages are now included in the xpra packages, including on win32 under `C:\Program Files\Xpra\doc\`.

> I tried to find `xpra/platform/path.py` tool to check if there is more information, but there seems to be nothing

On MS Windows, you can run `Path_info.exe`.
On Linux, it is definitely there or the server would not run!

> paramiko backend does not honour "User" attribute from ~/.ssh/config #2582 (comment)

Not sure what you mean. #3330?

---

> `Error: processing new connection from Protocol(unix-domain socket:/home/usr/.xpra/usr-h-0):`
> ` rgb encoder is missing`

That's a big problem!
I'm not sure why it's not found, it's definitely included in the packages:
```shell
$ dpkg -c  repo/focal/main/binary-amd64/xpra_4.3-r30644-1_amd64.deb | grep argb/encoder.py
-rw-r--r-- root/root      4656 2021-12-03 21:38 ./usr/lib/python3/dist-packages/xpra/codecs/argb/encoder.py
```

**Comment by stdedos** [comment]
> > I tried to find `xpra/platform/path.py` tool to check if there is more information, but there seems to be nothing
> 
> On MS Windows, you can run `Path_info.exe`. On Linux, it is definitely there or the server would not run! In both cases, you can also just run: `xpra path-info`. (using `Xpra_cmd.exe` on MS Windows)

It's `path*s*.py`, and I am blind, apparently 😛 

"I was looking" for that one `xpra path-info`, but apparently not enough at all (but I did try to open the main UI first, for a change 😄)

> Not sure what you mean.

I meant that the file was "missing" since that other report of mine, back in the day. (But apparently, I am blind)

-----------

> > `Error: processing new connection from Protocol(unix-domain socket:/home/usr/.xpra/usr-h-0):`
> > ` rgb encoder is missing`
> 
> That's a big problem! I'm not sure why it's not found, it's definitely included in the packages:
> 
> ```shell
> $ dpkg -c  repo/focal/main/binary-amd64/xpra_4.3-r30644-1_amd64.deb | grep argb/encoder.py
> -rw-r--r-- root/root      4656 2021-12-03 21:38 ./usr/lib/python3/dist-packages/xpra/codecs/argb/encoder.py
> ```

It is there (I have verified it myself too) - but I don't understand why the settings say that `video-encodecs (used) = <empty>`.

I don't have user-overrides (I have deleted them directories anyway). `xpra encodecs` "seem good to me":
```console
$ xpra encoding
found 2 vaapi codecs: h264, mpeg2
codecs and csc modules found:
* csc_cython           : codecs/csc_cython/colorspace_converter.cpython-38-x86_64-linux-gnu.so
* csc_libyuv           : 
* csc_swscale          : codecs/csc_swscale/colorspace_converter.cpython-38-x86_64-linux-gnu.so
* dec_avcodec2         : codecs/dec_avcodec2/decoder.cpython-38-x86_64-linux-gnu.so
* dec_jpeg             : codecs/jpeg/decoder.cpython-38-x86_64-linux-gnu.so
* dec_pillow           : codecs/pillow/decoder.py
* dec_spng             : 
* dec_vpx              : codecs/vpx/decoder.cpython-38-x86_64-linux-gnu.so
* dec_webp             : codecs/webp/decoder.cpython-38-x86_64-linux-gnu.so
* enc_ffmpeg           : codecs/enc_ffmpeg/encoder.cpython-38-x86_64-linux-gnu.so
* enc_jpeg             : codecs/jpeg/encoder.cpython-38-x86_64-linux-gnu.so
* enc_nvjpeg           : 
* enc_pillow           : codecs/pillow/encoder.py
* enc_rgb              : codecs/argb/encoder.py
* enc_spng             : 
* enc_vpx              : codecs/vpx/encoder.cpython-38-x86_64-linux-gnu.so
* enc_webp             : codecs/webp/encoder.cpython-38-x86_64-linux-gnu.so
* enc_x264             : codecs/enc_x264/encoder.cpython-38-x86_64-linux-gnu.so
* enc_x265             : 
* nvenc                : 

codecs versions:
* avcodec2                        : 58.54.100
* cython                          : 4.2
* ffmpeg                          : 58.54.100
* jpeg                            : 1.0
* numpy                           : 1.17.4
* pillow                          : 7.0.0
* rgb                             : 4.3
* swscale                         : 5.5.100
* vpx                             : 1.9.0
* webp                            : 0.6.1
* x264                            : 155
```

Correct me if I am wrong:
```console
$ xpra path-info
* app
  - default
    - dir                         : /usr/share/xpra
* client-socket
  - dirs                          : /run/user/1000/xpra/clients
* default_conf
  - dirs                          : []
* desktop-background              : /usr/share/backgrounds/images/default.png, /usr/share/backgrounds/images/*default*.png, /usr/share/backgrounds/*default*png, /usr/share/backgrounds/gnome/adwaita*.jpg, /usr/share/backgrounds/images/*jpg
* download
  - dir                           : ~/Downloads
* home                            : /home/stdedos
* icons                           : /usr/share/xpra/icons
* install
  - prefix                        : /usr
* libexec
  - dir                           : /usr/lib
* log
  - dirs                          : /run/user/1000/xpra, /tmp
* mmap
  - dir                           : /run/user/1000/xpra
* nodock_command                  : python3.8, /usr/bin/xpra
* python-execfile                 : python3
* resources                       : /usr/share/xpra
* script
  - dir                           : /run/user/1000/xpra
* sessions
  - dir                           : $XDG_RUNTIME_DIR/xpra
* socket
  - dirs                          : /run/user/1000/xpra, /run/xpra, ~/.xpra
* sound_command                   : python3.8, /usr/bin/xpra
* ssh-known-hosts                 : ~/.ssh/known_hosts, ~/ssh/known_hosts
* ssh_conf
  - dirs                          : /etc/ssh, /usr/local/etc/ssh, ~/.ssh, ~/ssh
* sshpass_command                 : /usr/bin/sshpass
* ssl-cert
  - dirs                          : ~/.config/xpra/ssl, ~/.xpra/ssl, /etc/xpra/, /etc/xpra/ssl, /usr/local/etc/xpra, /usr/local/etc/xpra/ssl, ./
* ssl-hosts-config
  - dirs                          : ~/.config/xpra/ssl/hosts, ~/.xpra/ssl/hosts, /etc/xpra/ssl/hosts, /usr/local/etc/xpra/ssl/hosts
* system_conf
  - dirs                          : /etc/xpra, /usr/local/etc/xpra, /etc/xdg/xdg-ubuntu/xpra, /etc/xdg/xpra
* user_conf
  - dirs                          : ~/.config/xpra, ~/.xpra
* xpra-module                     : /usr/lib/python3/dist-packages/xpra/
* xpra-tmp
  - dir                           : /run/user/1000/xpra/tmp
* xpra_command                    : python3.8, /usr/bin/xpra
```

I have emptied `~/.config/xpra`, `~/.xpra`, and, apart from `/etc/xpra`, there is no other directory found (`/usr/local/etc/xpra`, `/etc/xdg/xdg-ubuntu/xpra`, `/etc/xdg/xpra`).

```console
/etc/xpra $ grep -Trin video-decoders
ugrep: warning: cannot read key.pem: Permission denied
ugrep: warning: cannot read ssl-cert.pem: Permission denied
conf.d/30_picture.conf:    35:	# video-decoders = avcodec2, vpx
conf.d/30_picture.conf:    36:	# video-decoders = none
conf.d/30_picture.conf:    37:	# video-decoders = all
conf.d/30_picture.conf:    38:	video-decoders = all
```

I am grep-ing my system for any `video-encoders` set anywhere, but I cannot find any other reference to it (hasn't finished yet, however).

I also see the file:
```console
$ bat  /run/user/1000/xpra/0/cmdline 
/usr/bin/xpra
shadow
:0
--title=@title@ on @@/@server-display@
--ssh=plink -ssh -agent
--desktop-scaling=no
--speaker=off
--exit-with-client=yes
--splash=no
--video-encoders=
--csc-modules=
--video-decoders=
--env=XPRA_PROXY_START_UUID=5edde83c670e411c9cd1e15b79147a17
--daemon=yes
--systemd-run=no
```

but I don't know what to make out of it - I don't set it client-side 😕 

However ... there is also a core from yesterday:
[_usr_bin_xpra.1000.crash.gz](https://github.com/Xpra-org/xpra/files/7683927/_usr_bin_xpra.1000.crash.gz)

-----------------

PS: that might have flown under the radar:
> ```
> 45 2021-12-08 20:22:40,554 Warning: failed to load '/usr/share/pixmaps/sqlitebrowser.svg':
> 46 2021-12-08 20:22:40,554  [Errno 21] Is a directory: '/usr/share/pixmaps/sqlitebrowser.svg'
> ```

It's weird, but it's "acceptable practice", I guess.

**Comment by totaam** [comment]
> I don't understand why the settings say that

I'll have to look into that. The default install should have zero differences but there were some recent changes in this area... (including one that you had requested!)

> I don't have user-overrides

You may be interested in `xpra showsetting encoding` to see where a particular setting comes from.

> PS: that might have flown under the radar:
> `Warning: failed to load '/usr/share/pixmaps/sqlitebrowser.svg':`
> ` [Errno 21] Is a directory: '/usr/share/pixmaps/sqlitebrowser.svg'`

I don't know who thought it would be a good idea to have directory named like this. :-1: 
e10ce75dea6f7cac3724d0e8ac33b272e0730fdf will silently ignore it - and you may not get an icon for this app in the start menu.

**Comment by totaam** [comment]
> > `rgb encoder is missing`
> >
> That's a big problem!
>
I think that 1e8a46dce741c8aa1b47e196d25ea062d56b6b12 works around this bug for now, the proper fix will be in #3382.
Did you connect as soon as the server started? (remote start perhaps?)

PS: I am unable to make new MS Windows builds for now, an MSYS2 update broke gcc...

**Comment by stdedos** [comment]
> > I don't understand why the settings say that
> 
> I'll have to look into that. The default install should have zero differences but there were some recent changes in this area... (including one that you had requested!)
> 
> > I don't have user-overrides
> 
> You may be interested in `xpra showsetting encoding` to see where a particular setting comes from.

It does not help that much 😕 
```console
➜ ~  xpra showconfig video-encoders                
video-encoders        (used)   =                                   <class 'list'>
video-encoders       (default) = 'all'                             <class 'list'>
➜ ~  xpra showconfig encodings     
encodings                      = 'all'
➜ ~  xpra showconfig encoding 
encoding                       = 'auto'
➜ ~                           
```

I am not sure what am I doing wrong :/

I expected output like:
```
code-default: x
/etc/xpra/conf.d: y
~/.xpra: z
```

**Comment by stdedos** [comment]
> > > `rgb encoder is missing`
> > 
> > 
> > That's a big problem!
> 
> I think that [1e8a46d](https://github.com/Xpra-org/xpra/commit/1e8a46dce741c8aa1b47e196d25ea062d56b6b12) works around this bug for now, the proper fix will be in #3382. Did you connect as soon as the server started? (remote start perhaps?)

Yes, it was remote start. I should have tried without it, I guess? 😕 

> PS: I am unable to make new MS Windows builds for now, an MSYS2 update broke gcc...

I am sorry to hear that :-(
Luckily this does not appear to be a client issue

**Comment by totaam** [comment]
The latest beta builds have these fixes included.

The MS Windows builds are updated too, the problem turned out to be a false positive from windows defender that ended up removing `cc1plus.exe`.

**Comment by stdedos** [comment]
If you (would like to) split the "weird settings" debugging somewhere else, pls @mention me at the issue

Or, I can just open a new one for that.
Or you already know what I am doing wrong, pls put me out of my misery 🙂

**Comment by stdedos** [comment]
Verified as fixed:

```
"Xpra-Python3-x86_64_4.3-r30655\xpra_cmd" shadow ssh://user@ip/0 --ssh="plink -ssh -agent" --modal-windows=no --desktop-scaling=no --headerbar=off --title="@title@ on @@/@server-display@" --microphone=off --speaker=off --webcam=no --pulseaudio=no

XPRA_EXECUTABLE=Xpra-Python3-x86_64_4.3-r30655

2021-12-10 20:36:01,606 Xpra GTK3 client version 4.3-r30655 (g1e8a46dce) 64-bit
2021-12-10 20:36:01,614  running on Microsoft Windows 10
2021-12-10 20:36:03,233 GStreamer version 1.18.5 for Python 3.9.7 64-bit
2021-12-10 20:36:03,318 created named pipe 'Xpra\2808'
2021-12-10 20:36:03,351 keyboard layout code 0x409
2021-12-10 20:36:03,351 identified as 'United States - English' : us
2021-12-10 20:36:03,408 OpenGL_accelerate module loaded
2021-12-10 20:36:03,425 Using accelerated ArrayDatatype
2021-12-10 20:36:03,830 OpenGL accelerate missing: numpy_formathandler
2021-12-10 20:36:03,832 OpenGL enabled with NVIDIA GeForce RTX 2080 SUPER/PCIe/SSE2
2021-12-10 20:36:03,879  keyboard settings: layout=us
2021-12-10 20:36:03,881  desktop size is 4480x1536:
2021-12-10 20:36:03,881   Default (1185x406 mm - DPI: 96x96) workarea: 4480x1496
2021-12-10 20:36:03,881     Samsung C32JG5x 2560x1440 at    0x0    (697x392 mm - DPI: 93x93) workarea: 2560x1400
2021-12-10 20:36:03,881     LG IPS234 1920x1080 at 2560x456  (510x290 mm - DPI: 96x95) workarea: 1920x1040 at 2560x456
2021-12-10 20:36:08,796 enabled remote logging
2021-12-10 20:36:08,797 Xpra shadow server version 4.3-r30655 64-bit
2021-12-10 20:36:08,797  running on Linux Ubuntu 20.04 focal
2021-12-10 20:36:08,797  remote desktop size is 1920x1080 with 1 screen:
2021-12-10 20:36:08,798   :0.0 (508x286 mm - DPI: 96x96) workarea: 1920x986  at    0x27
2021-12-10 20:36:08,798     LGD eDP-1 (309x174 mm - DPI: 158x158)
2021-12-10 20:36:09,240 running, 1 window
```

**Comment by totaam** [comment]
The `xpra showconfig` differences should be gone as of 3a040b357cce05649628e979d8265c88c1fec925.

**Comment by stdedos** [comment]
I'm seeing again the same

```
"Xpra-x86_64_6.0-r34211\xpra_cmd" shadow ssh://user@ip/1 --ssh="plink -ssh -agent" --modal-windows=no --headerbar=off --source-start=gnome-keyring-daemon --title="@title@ on @@/@server-display@" --encodings=-webp --start="nohup systemd-inhibit --what=handle-lid-switch sleep 1d >/dev/null 2>&1 & inhibit_pid=\$! ; xpra xwait ; kill -9 \$inhibit_pid ; nohup systemd-inhibit --what=handle-lid-switch sleep 5m >/dev/null 2>&1 &" --microphone=off --speaker=off --webcam=no --pulseaudio=no --key-shortcut=Shift+F2:toggle_pointer_grab

...

2023-09-17 11:11:32,732  Actual log file name is now: '/run/user/1000/xpra/2/server.log'
CONNECTION_LOST, reconnecting
2023-09-17 11:11:33,252 xpra main error:
Traceback (most recent call last):
  File "E:/xpra/xpra/scripts/main.py", line 123, in main
  File "E:/xpra/xpra/scripts/main.py", line 457, in run_mode
  File "E:/xpra/xpra/scripts/main.py", line 497, in do_run_mode
  File "E:/xpra/xpra/scripts/main.py", line 2145, in run_remote_server
FileNotFoundError: [Errno 2] No such file or directory
```

Same cause or different issue?

**Comment by totaam** [comment]
>  ` File "E:/xpra/xpra/scripts/main.py", line 2145, in run_remote_server`

@stdedos That's a different one caused by auto-reconnect on MS Windows when the original command you use doesn't have `.exe` at the end...
Ugly platform specific (untested) workaround in 2cddeaa2ed1a90ddde5b5de6aeea3028e25734e8.

**Comment by stdedos** [comment]
I'll test tonight 🙃
