### ISSUE TITLE
No Start menu entries in XPRA HTML5 client

### ISSUE THREAD

**Issue by vaclcer** [Xpra-org/xpra#3424]
Hello, the XPRA HTML5 client Start menu does not show any entries. There is this error when server startup:

```
2022-01-12 11:24:22,020  no python-xdg module
Exception in thread load-menu-data:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.6/site-packages/xpra/server/menu_provider.py", line 142, in load
    self.get_desktop_sessions()
  File "/usr/lib64/python3.6/site-packages/xpra/server/menu_provider.py", line 221, in get_desktop_sessions
    self.desktop_sessions = load_desktop_sessions()
  File "/usr/lib64/python3.6/site-packages/xpra/platform/xposix/menu_helper.py", line 451, in load_desktop_sessions
    from xdg.DesktopEntry import DesktopEntry
ModuleNotFoundError: No module named 'xdg.DesktopEntry'
```

Obviously, I have installed everything I could related to XDG:

```
pip list | grep xdg
pyxdg               0.27      /tmp/xdg/pyxdg-rel-0.27
xdg                 5.1.1`
```

Running xpra v4.3.1-r0 at RHEL 8.5 (Rocky linux in fact), default Python 3.6.8. Is there something I can do about it? Many thanks!

![image](https://user-images.githubusercontent.com/39984150/149124126-212a2f4b-8fa2-44c3-8888-f52896acebc2.png)

**Comment by totaam** [comment]
I have transferred this issue because this has nothing to do with the html5 client.

You should have installed `python3-pyxdg` using your package manager, not using `pip`.
Once installed correctly, you should be able to run this command without any errors:
```shell
python3 -c "from xdg.DesktopEntry import DesktopEntry"
```
