### ISSUE TITLE
XPRA and PYENV?

### ISSUE THREAD

**Issue by jradxl** [Xpra-org/xpra#3464]
Please can you advise on the following...

I have pyenv loaded in my bash shell. (`https://github.com/pyenv/pyenv`)
I have edited `/usr/bin/xpra` to add a `print(sys.path)`

I use this command-line
`xpra start-desktop --start-child=mate-session --exit-with-children=yes --opengl=no --mdns=no ssh://zubuntu1/103`

RESULTS:
You can see that XPRA calls itself twice
And on the second time sys.path has been changed resulting in the Traceback messages
However, XPRA works fine
I could just ignore this...
But on the otherhand, can you suggest a mitigation?
(Of course, without PYENV all is fine!)
Thanks
John

```
$ xpra start-desktop --start-child=mate-session --exit-with-children=yes --opengl=no --mdns=no ssh://zubuntu1/103
['/usr/bin', '/usr/lib/python39.zip', '/usr/lib/python3.9', '/usr/lib/python3.9/lib-dynload', '/home/jradley/.local/lib/python3.9/site-packages', '/usr/local/lib/python3.9/dist-packages', '/usr/lib/python3/dist-packages', '/usr/lib/python3.9/dist-packages']
['/usr/bin', '/home/jradley/.pyenv/versions/3.9.9/lib/python39.zip', '/home/jradley/.pyenv/versions/3.9.9/lib/python3.9', '/home/jradley/.pyenv/versions/3.9.9/lib/python3.9/lib-dynload', '/home/jradley/.local/lib/python3.9/site-packages', '/home/jradley/.pyenv/versions/3.9.9/lib/python3.9/site-packages']
Traceback (most recent call last):
  File "/usr/bin/xpra", line 9, in <module>
    from xpra.platform import init, set_default_name
ModuleNotFoundError: No module named 'xpra'
2022-02-17 10:36:41,879 Xpra GTK3 X11 client version 4.3.2-r0 64-bit
2022-02-17 10:36:41,960  running on Linux Ubuntu 21.10 impish
2022-02-17 10:36:41,961  window manager is 'Metacity (Marco)'
Traceback (most recent call last):
  File "/usr/bin/xpra", line 9, in <module>
    from xpra.platform import init, set_default_name
ModuleNotFoundError: No module named 'xpra'
2022-02-17 10:36:42,032 Error: failed to query sound subsystem:
2022-02-17 10:36:42,032  query did not return any data
2022-02-17 10:36:42,098 created unix domain socket '/run/user/1000/xpra/clients/z390ma-14273'
2022-02-17 10:36:42,187 Connected (version 2.0, client OpenSSH_8.4p1)
2022-02-17 10:36:42,226 loaded RSA private key from '/home/jradley/.ssh/my-keys/xcase-z390ma-rsa-4096'
2022-02-17 10:36:42,241 Authentication (publickey) successful!
2022-02-17 10:36:42,641  keyboard settings: rules=evdev, model=pc105, layout=gb
2022-02-17 10:36:42,645  desktop size is 1920x1080:
2022-02-17 10:36:42,646   :0.0 (508x285 mm - DPI: 96x96) workarea: 1920x1024 at    0x28  
2022-02-17 10:36:42,646     SAM HDMI-1       (531x299 mm - DPI: 92x92)
2022-02-17 10:36:42,823  SSH: 'Entering daemon mode; any further errors will be reported to:'
2022-02-17 10:36:42,823  SSH: '  /run/user/1000/xpra/:103.log'
2022-02-17 10:36:48,122 enabled remote logging
2022-02-17 10:36:48,123 Xpra GTK3 X11 desktop server version 3.0.13-r28292 64-bit
2022-02-17 10:36:48,123  running on Linux Ubuntu 21.10 impish
2022-02-17 10:36:48,123  remote desktop size is 5760x2560
2022-02-17 10:36:48,277 running, 1 window
```

**Comment by totaam** [comment]
> `ModuleNotFoundError: No module named 'xpra'`

This should be fatal, but somehow it is not.

The second occurrence of `ModuleNotFoundError` is probably because xpra executes itself to probe `opengl` and `audio` properties.
With a default setup, it runs `xpra opengl` and `xpra _sound_query`.
You have `opengl=no` so I'm not sure where the first one comes from.

I'm not entirely sure why or how the environment would be correct for the outer `xpra` command and not the subprocesses that it launches - they should inherit the same environment.
Perhaps you need to specify `XPRA_COMMAND=/path/to/xpra` so that it can find itself.

**Comment by jradxl** [comment]
Fantastic, that fixed it!
```
# grep XPRA /etc/environment
export XPRA_COMMAND="/usr/bin/xpra"
```
Would never have thought of that.

opengl
Was off because because the Probe was failing.
I've now disable CUDA and ensured necessary Apt/Pip packages were loaded and it's working now.

My first time use of your project. 
It's quite amazing... Now to try to a remote VM!
Thanks
John

```
$ xpra start-desktop --start-child=mate-session --exit-with-children=yes --mdns=no ssh://zubuntu1/103 | more
2022-02-17 15:12:11,321 Xpra GTK3 X11 client version 4.3.2-r0 64-bit
2022-02-17 15:12:11,409  running on Linux Ubuntu 21.10 impish
2022-02-17 15:12:11,410  window manager is 'Metacity (Marco)'
2022-02-17 15:12:11,591 GStreamer version 1.18.5 for Python 3.9.7 64-bit
2022-02-17 15:12:11,652 created unix domain socket '/run/user/1000/xpra/clients/z390ma-7581'
2022-02-17 15:12:11,701 No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
2022-02-17 15:12:11,819 Warning: vendor 'Intel' is greylisted,
2022-02-17 15:12:11,819  you may want to turn off OpenGL if you encounter bugs
2022-02-17 15:12:11,890 OpenGL enabled with Mesa Intel(R) UHD Graphics 630 (CFL GT2)
2022-02-17 15:12:11,905 Connected (version 2.0, client OpenSSH_8.4p1)
2022-02-17 15:12:11,941 loaded RSA private key from '/home/jradley/.ssh/my-keys/xcase-z390ma-rsa-4096'
2022-02-17 15:12:11,956 Authentication (publickey) successful!
2022-02-17 15:12:12,480  SSH: 'found existing display :103 : UNKNOWN'
2022-02-17 15:12:12,485  keyboard settings: rules=evdev, model=pc105, layout=gb
2022-02-17 15:12:12,487  desktop size is 1920x1080:
2022-02-17 15:12:12,487   :0.0 (508x285 mm - DPI: 96x96) workarea: 1920x1024 at    0x28  
2022-02-17 15:12:12,487     SAM HDMI-1       (531x299 mm - DPI: 92x92)
2022-02-17 15:12:12,621  SSH: 'Entering daemon mode; any further errors will be reported to:'
2022-02-17 15:12:12,621  SSH: '  /run/user/1000/xpra/103/server.log'
2022-02-17 15:12:23,049 enabled remote logging
2022-02-17 15:12:23,050 Xpra X11 desktop server version 4.3.2-r0 64-bit
2022-02-17 15:12:23,050  running on Linux Ubuntu 21.10 impish
2022-02-17 15:12:23,050  remote desktop size is 8192x4096 with 1 screen:
2022-02-17 15:12:23,050   :103.0 (2167x1084 mm - DPI: 96x96)
2022-02-17 15:12:23,183 running, 1 window
```
