### ISSUE TITLE
No audio after client updated to 4.3.2r0, same with update to server 4.3.2r0

### ISSUE THREAD

**Issue by ScanCaster** [Xpra-org/xpra#3467]
**Describe the bug**
No audio from XPRA server AFTER upgrade to 4.3.2r0

**To Reproduce**
1. server command - `xpra start --env=XPRA_VAAPI=0 :100 --start=/home/server/dir/dir2/bin/program`
2. client command -  `xpra -d sound,gstreamer --auth=ssh:password:value=XXX --debug=ssh attach ssh/me@192.168.0.18/100`
3. specific action to trigger the bug - Just connecting will have no audio, no beep of audio start/connected.. Speaker shows: READY in Session info. Toggle on/off/on no joy.

**System Information (please complete the following information):**
 - Server OS:  Kubuntu 20.04 - FULL Updated
 - Client OS: Kubuntu 20.04 FULL Updated
 - Xpra Server Version 4.3.2.r0
 - Xpra Client Version 4.3.2.r0

WILL add the server `-d audio,gstreamer` output later, can't shut it down at this point in time.

**Additional context**
`-d audio,gstreamer` output CLIENT SIDE
```
xpra -d sound,gstreamer --auth=ssh:password:value=pass --debug=ssh attach ssh/me@192.168.0.18/100 
2022-02-17 18:24:46,463 Xpra GTK3 X11 client version 4.3.2-r0 64-bit
2022-02-17 18:24:46,619  running on Linux Ubuntu 20.04 focal
2022-02-17 18:24:46,620  window manager is 'KWin'
2022-02-17 18:24:48,200 GStreamer version 1.16.2 for Python 3.8.10 64-bit
2022-02-17 18:24:48,271 debug enabled for xpra.net.ssh / ('network', 'ssh')
2022-02-17 18:24:48,345 created unix domain socket '/run/user/1000/xpra/clients/me-angelinz-153305'
2022-02-17 18:24:48,567 No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
2022-02-17 18:24:48,995 OpenGL enabled with GeForce GT 730/PCIe/SSE2
2022-02-17 18:24:49,004 debug enabled for xpra.scripts.parsing / ('ssh',)
2022-02-17 18:24:49,004 using paramiko ssh backend
2022-02-17 18:24:49,207 paramiko socket_connect: sockname=('192.168.0.43', 59824), peername=('192.168.0.18', 22)
2022-02-17 18:24:49,208 starting thread (client mode): 0x835dd7c0
2022-02-17 18:24:49,208 Local version/idstring: SSH-2.0-paramiko_2.6.0
2022-02-17 18:24:49,227 Remote version/idstring: SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.4
2022-02-17 18:24:49,228 Connected (version 2.0, client OpenSSH_8.2p1)
2022-02-17 18:24:49,230 kex algos:['curve25519-sha256', 'curve25519-sha256@libssh.org', 'ecdh-sha2-nistp256', 'ecdh-sha2-nistp384', 'ecdh-sha2-nistp521', 'diffie-hellman-group-exchange-sha256', 'diffie-hellman-group16-sha512', 'diffie-hellman-group18-sha512', 'diffie-hellman-group14-sha256'] server key:['rsa-sha2-512', 'rsa-sha2-256', 'ssh-rsa', 'ecdsa-sha2-nistp256', 'ssh-ed25519'] client encrypt:['chacha20-poly1305@openssh.com', 'aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com'] server encrypt:['chacha20-poly1305@openssh.com', 'aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com'] client mac:['umac-64-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'umac-64@openssh.com', 'umac-128@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1'] server mac:['umac-64-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'umac-64@openssh.com', 'umac-128@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1'] client compress:['none', 'zlib@openssh.com'] server compress:['none', 'zlib@openssh.com'] client lang:[''] server lang:[''] kex follows?False
2022-02-17 18:24:49,230 Kex agreed: curve25519-sha256@libssh.org
2022-02-17 18:24:49,230 HostKey agreed: ssh-ed25519
2022-02-17 18:24:49,230 Cipher agreed: aes128-ctr
2022-02-17 18:24:49,231 MAC agreed: hmac-sha2-256
2022-02-17 18:24:49,231 Compression agreed: none
2022-02-17 18:24:49,253 kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
2022-02-17 18:24:49,253 Switch to new keys ...
2022-02-17 18:24:49,253 do_ssh_paramiko_connect_to(<paramiko.Transport at 0x835dd7c0 (cipher aes128-ctr, 128 bits) (connected; awaiting auth)>, '192.168.0.18', 'me', None, {'hostname': '*'}, ['/home/me/.ssh/id_ed25519', '/home/me/.ssh/id_ecdsa', '/home/me/.ssh/id_rsa', '/home/me/.ssh/id_dsa'], {'display_name': 'ssh/me@192.168.0.18/100', 'type': 'ssh', 'proxy_command': ['_proxy'], 'exit_ssh': True, 'display': ':100', 'display_as_args': [':100'], 'is_paramiko': True, 'username': 'me', 'host': '192.168.0.18', 'local': False, 'full_ssh': ['paramiko'], 'remote_xpra': ['xpra', '$XDG_RUNTIME_DIR/xpra/run-xpra', '/usr/local/bin/xpra', '~/.xpra/run-xpra', 'Xpra_cmd.exe']})
2022-02-17 18:24:49,254 SSH transport <paramiko.Transport at 0x835dd7c0 (cipher aes128-ctr, 128 bits) (connected; awaiting auth)>
2022-02-17 18:24:49,254 remote_server_key=MD5:1f:11:36:7c:69:fc:d3:05:6c:74:c5:8b:84:31:21:b7
2022-02-17 18:24:49,263 HostKeys.load(/home/me/.ssh/known_hosts) successful
2022-02-17 18:24:49,263 host keys=<paramiko.hostkeys.HostKeys object at 0x7f8d81d2b640>
2022-02-17 18:24:49,266 ed25519 host key 'MD5:1f:11:36:7c:69:fc:d3:05:6c:74:c5:8b:84:31:21:b7' OK for host '192.168.0.18'
2022-02-17 18:24:49,266 starting authentication, authentication methods: ['none', 'agent', 'key', 'password']
2022-02-17 18:24:49,266 auth=none
2022-02-17 18:24:49,266 trying none authentication
2022-02-17 18:24:49,267 userauth is OK
2022-02-17 18:24:49,277 Authentication type (none) not permitted.
2022-02-17 18:24:49,277 Allowed methods: ['publickey', 'password']
2022-02-17 18:24:49,277 auth_none()
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xpra/net/ssh.py", line 578, in auth_none
    transport.auth_none(username)                                                                                                                                                            
  File "/usr/lib/python3/dist-packages/paramiko/transport.py", line 1446, in auth_none                                                                                                       
    return self.auth_handler.wait_for_response(my_event)                                                                                                                                     
  File "/usr/lib/python3/dist-packages/paramiko/auth_handler.py", line 250, in wait_for_response                                                                                             
    raise e                                                                                                                                                                                  
paramiko.ssh_exception.BadAuthenticationType: Bad authentication type; allowed types: ['publickey', 'password']                                                                              
2022-02-17 18:24:49,281 auth=agent
2022-02-17 18:24:49,282 agent keys: ()
2022-02-17 18:24:49,282 auth=key
2022-02-17 18:24:49,282 trying public key authentication using ['/home/me/.ssh/id_ed25519', '/home/me/.ssh/id_ecdsa', '/home/me/.ssh/id_rsa', '/home/me/.ssh/id_dsa']
2022-02-17 18:24:49,282 no keyfile at '/home/me/.ssh/id_ed25519'
2022-02-17 18:24:49,282 no keyfile at '/home/me/.ssh/id_ecdsa'
2022-02-17 18:24:49,282 no keyfile at '/home/me/.ssh/id_rsa'
2022-02-17 18:24:49,282 no keyfile at '/home/me/.ssh/id_dsa'
2022-02-17 18:24:49,283 auth=password
2022-02-17 18:24:49,283 trying interactive authentication
2022-02-17 18:24:49,284 userauth is OK
2022-02-17 18:24:49,293 Authentication type (keyboard-interactive) not permitted.
2022-02-17 18:24:49,294 Allowed methods: ['publickey', 'password']
2022-02-17 18:24:49,294 auth_interactive(..)
Traceback (most recent call last):                                                                                                                                                           
  File "/usr/lib/python3/dist-packages/xpra/net/ssh.py", line 610, in auth_interactive                                                                                                       
    transport.auth_interactive(username, myiauthhandler.handle_request, "")                                                                                                                  
  File "/usr/lib/python3/dist-packages/paramiko/transport.py", line 1633, in auth_interactive                                                                                                
    return self.auth_handler.wait_for_response(my_event)                                                                                                                                     
  File "/usr/lib/python3/dist-packages/paramiko/auth_handler.py", line 250, in wait_for_response                                                                                             
    raise e                                                                                                                                                                                  
paramiko.ssh_exception.BadAuthenticationType: Bad authentication type; allowed types: ['publickey', 'password']                                                                              
2022-02-17 18:24:49,295 SSH password authentication failed:
2022-02-17 18:24:49,295  Bad authentication type
2022-02-17 18:24:49,295   allowed types: ['publickey', 'password']
2022-02-17 18:24:56,457 trying password authentication
2022-02-17 18:24:56,459 userauth is OK
2022-02-17 18:24:56,481 Authentication (password) successful!
2022-02-17 18:24:56,481 will try to run xpra from: ['xpra', '$XDG_RUNTIME_DIR/xpra/run-xpra', '/usr/local/bin/xpra', '~/.xpra/run-xpra', 'Xpra_cmd.exe']
2022-02-17 18:24:56,482 paramiko_run_test_command(transport, 'command -v xpra')
2022-02-17 18:24:56,482 [chan 0] Max packet in: 4096 bytes
2022-02-17 18:24:56,704 Received global request "hostkeys-00@openssh.com"
2022-02-17 18:24:56,704 Rejecting "hostkeys-00@openssh.com" global request from server.
2022-02-17 18:24:56,704 [chan 0] Max packet out: 32768 bytes
2022-02-17 18:24:56,705 Secsh channel 0 opened.
2022-02-17 18:24:56,707 [chan find command -v xpra] Sesch channel 0 request ok
2022-02-17 18:24:56,708 exec_command returned
2022-02-17 18:24:56,708 exit status is not ready yet, sleeping
2022-02-17 18:24:56,718 [chan find command -v xpra] EOF received (find command -v xpra)
2022-02-17 18:24:56,718 [chan find command -v xpra] EOF sent (find command -v xpra)
2022-02-17 18:24:56,718 exec_command('command -v xpra')=0
2022-02-17 18:24:56,719 exec_command out='/usr/bin/xpra\n'
2022-02-17 18:24:56,719 exec_command err=''
2022-02-17 18:24:56,719 adding xpra_cmd='/usr/bin/xpra'
2022-02-17 18:24:56,719 cmd(['_proxy'], [':100'])="/usr/bin/xpra" "_proxy" ":100"
2022-02-17 18:24:56,720 trying to open SSH session, window-size=134217727, timeout=60
2022-02-17 18:24:56,720 [chan 1] Max packet in: 4096 bytes
2022-02-17 18:24:56,721 [chan 1] Max packet out: 32768 bytes
2022-02-17 18:24:56,721 Secsh channel 1 opened.
2022-02-17 18:24:56,721 channel exec_command("/usr/bin/xpra" "_proxy" ":100")
2022-02-17 18:24:56,723 [chan run-xpra] Sesch channel 1 request ok
2022-02-17 18:24:56,733  keyboard settings: rules=evdev, model=pc105, layout=us
2022-02-17 18:24:56,890  desktop size is 3840x1080:
2022-02-17 18:24:56,892   :0.0 (1060x301 mm - DPI: 92x91) workarea: 3840x1044
2022-02-17 18:24:56,892     ACR VGA-0        1920x1080 at    0x0    (527x296 mm - DPI: 93x93) workarea: 1920x1080
2022-02-17 18:24:56,892     ACR HDMI-0       1920x1080 at 1920x0    (527x296 mm - DPI: 93x93) workarea: 1920x1044 at 1920x0
2022-02-17 18:24:57,171 enabled remote logging
2022-02-17 18:24:57,172 Xpra X11 seamless server version 4.3.2-r0 64-bit
2022-02-17 18:24:57,172  running on Linux Ubuntu 20.04 focal
2022-02-17 18:24:57,200 Attached to xpra server at ssh://me@192.168.0.18/100
2022-02-17 18:24:57,201  (press Control-C to detach)

2022-02-17 18:24:57,464 audio playback found 2 audio output devices:
2022-02-17 18:24:57,465 audio playback  * Built-in Audio Analog Stereo
2022-02-17 18:24:57,465 audio playback    alsa_output.pci-0000_00_14.2.analog-stereo
2022-02-17 18:24:57,465 audio playback  * GF108 High Definition Audio Controller Digital Stereo (HDMI 4)
2022-02-17 18:24:57,465 audio playback    alsa_output.pci-0000_01_00.1.hdmi-stereo-extra3
2022-02-17 18:24:57,465 audio playback  to select a specific one,
2022-02-17 18:24:57,465 audio playback  use the environment variable 'XPRA_PULSE_SINK_DEVICE_NAME'
2022-02-17 18:24:57,466 audio playback using default pulseaudio device
2022-02-17 18:24:57,468 running, 1 window
2022-02-17 18:24:58,016 audio playback using 'opus' audio codec
```

**Comment by ScanCaster** [comment]
THANK YOU! I look forward to testing this out in 4.4 when it is available.....see if I give this a whirl... 
Again, **THANK YOU!**

**Comment by ScanCaster** [comment]
OK... I can **_CONFIRM, AUDIO WORKS on the 4.4 beta on *buntu 22.04._**... so when that hits the stable side, I can upgrade the clients on 20.04 and 22.04.. those ones are not in a cycle where I touch them...  Thanks!

But ttheres another issue, in re xpra_launcher... I will post it else where....

**Comment by felipemarinho97** [comment]
I was having this issue with the `xpra` package from Arch Linux repos, installing `xpra-git` (which will install 4.4 beta) from AUR solved the problem!
