### ISSUE TITLE
Server occasionally sends incorrectly-sized (16384x16384, 450x16384, 563x16384) windows to client (4.3-r30545)

### ISSUE THREAD

**Issue by jdstroy** [Xpra-org/xpra#3517]
**Describe the bug**
On xpra server 4.3-r30545, arm64, when I have many Firefox windows in a single session, occasionally the server will send 16384x16384 windows or 563x16384 windows to the client on connection, which causes the client to abort decoding.  This results in the server malfunctioning, with the thread servicing that connection to spin in an infinite loop, consuming as many CPU cycles as it is given by the kernel's scheduler.  Subsequent connections spawn new threads which are able to serve client requests, but the malfunctioning threads continue to consume CPU resources.

The resulting log looks like this (from the server):

```
Exception: BUG: failed to find a scaling value for window size 563x16384
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xpra/server/server_base.py", line 895, in call_handler
    handler(proto, packet)
  File "/usr/lib/python3/dist-packages/xpra/x11/server.py", line 1024, in _process_configure_window
    self._set_client_properties(proto, wid, window, cprops)
  File "/usr/lib/python3/dist-packages/xpra/x11/server.py", line 1125, in _set_client_properties
    super()._set_client_properties(proto, wid, window, new_client_properties)
  File "/usr/lib/python3/dist-packages/xpra/server/server_base.py", line 679, in _set_client_properties
    ss.set_client_properties(wid, window, typedict(new_client_properties))
  File "/usr/lib/python3/dist-packages/xpra/server/source/windows_mixin.py", line 532, in set_client_properties
    ws.set_client_properties(new_client_properties)
  File "/usr/lib/python3/dist-packages/xpra/server/window/window_source.py", line 715, in set_client_properties
    self.do_set_client_properties(properties)
  File "/usr/lib/python3/dist-packages/xpra/server/window/window_video_source.py", line 415, in do_set_client_properties
    super().do_set_client_properties(properties)
  File "/usr/lib/python3/dist-packages/xpra/server/window/window_source.py", line 738, in do_set_client_properties
    self.update_encoding_selection(self.encoding)
  File "/usr/lib/python3/dist-packages/xpra/server/window/window_video_source.py", line 404, in update_encoding_selection
    super().update_encoding_selection(encoding, exclude, init)
  File "/usr/lib/python3/dist-packages/xpra/server/window/window_source.py", line 847, in update_encoding_selection
    self.update_encoding_options()
  File "/usr/lib/python3/dist-packages/xpra/server/window/window_video_source.py", line 1078, in update_encoding_options
    self.check_pipeline_score(force_reload)
  File "/usr/lib/python3/dist-packages/xpra/server/window/window_video_source.py", line 1150, in check_pipeline_score
    scores = self.get_video_pipeline_options(eval_encodings, w, h, self.pixel_format, force_reload)
  File "/usr/lib/python3/dist-packages/xpra/server/window/window_video_source.py", line 1309, in get_video_pipeline_options
    add_scores("via %s" % out_csc, csc_spec, out_csc)
  File "/usr/lib/python3/dist-packages/xpra/server/window/window_video_source.py", line 1279, in add_scores
    scaling = self.calculate_scaling(width, height, max_w, max_h)
  File "/usr/lib/python3/dist-packages/xpra/server/window/window_video_source.py", line 1413, in calculate_scaling
    scaling = get_min_required_scaling()
  File "/usr/lib/python3/dist-packages/xpra/server/window/window_video_source.py", line 1377, in get_min_required_scaling
    raise Exception("BUG: failed to find a scaling value for window size %sx%s" % (width, height))
Exception: BUG: failed to find a scaling value for window size 563x16384
```

```
2022-01-06 16:33:58,806 client   5 @37.880 server is not responding, drawing spinners over the windows
2022-01-06 16:33:59,977 client   5 @38.592 UI thread is now blocked
2022-01-06 16:34:00,450 client   5 @39.568 UI thread is running again, resuming
2022-01-06 16:34:01,297 client   5 @40.491 server is OK again
2022-01-06 16:34:04,358 client   5 @43.347 server is not responding, drawing spinners over the windows
2022-01-06 16:34:05,110 client   5 @44.339 UI thread is now blocked
2022-01-06 16:34:05,207 client   5 @44.436 UI thread is running again, resuming
2022-01-06 16:34:07,630 client   5 @46.868 UI thread is now blocked
2022-01-06 16:34:07,855 client   5 @47.095 UI thread is running again, resuming
2022-01-06 16:34:09,272 client   5 @48.403 UI thread is now blocked
2022-01-06 16:34:09,408 client   5 @48.636 server is OK again
2022-01-06 16:34:09,408 client   5 @48.647 UI thread is running again, resuming
2022-01-06 16:34:10,494 client   5 @49.696 Error drawing on window 46
2022-01-06 16:34:10,592 client   5 @49.696   File "E:/xpra/xpra/client/mixins/window_manager.py", line 1470, in _do_draw
2022-01-06 16:34:10,592 client   5 @49.696   File "E:/xpra/xpra/client/client_window_base.py", line 742, in draw_region
2022-01-06 16:34:10,593 client   5 @49.696   File "E:/xpra/xpra/client/window_backing_base.py", line 718, in draw_region
2022-01-06 16:34:10,593 client   5 @49.696   File "E:/xpra/xpra/client/window_backing_base.py", line 366, in paint_image
2022-01-06 16:34:10,593 client   5 @49.696   File "E:/xpra/xpra/codecs/pillow/decoder.py", line 112, in decompress
2022-01-06 16:34:10,593 client   5 @49.696   File "C:/msys64/mingw64/lib/python3.9/site-packages/PIL/Image.py", line 3009, in open
2022-01-06 16:34:10,593 client   5 @49.696   File "C:/msys64/mingw64/lib/python3.9/site-packages/PIL/Image.py", line 2996, in _open_core
2022-01-06 16:34:10,593 client   5 @49.696   File "C:/msys64/mingw64/lib/python3.9/site-packages/PIL/Image.py", line 2905, in _decompression_bomb_check
2022-01-06 16:34:10,593 client   5 @49.696 DecompressionBombError: Image size (268435456 pixels) exceeds limit of 178956970 pixels, could be decompression bomb DOS attack.
2022-01-06 16:34:10,594 client   5 @49.742 Error 'Image size (268435456 pixels) exceeds limit of 178956970 pixels, could be decompression bomb DOS attack.' processing draw packet2022-01-06 16:34:10,594 client   5 @49.742   File "E:/xpra/xpra/client/mixins/window_manager.py", line 1401, in _draw_thread_loop
2022-01-06 16:34:10,594 client   5 @49.742   File "E:/xpra/xpra/client/mixins/window_manager.py", line 1470, in _do_draw
2022-01-06 16:34:10,594 client   5 @49.742   File "E:/xpra/xpra/client/client_window_base.py", line 742, in draw_region
2022-01-06 16:34:10,594 client   5 @49.742   File "E:/xpra/xpra/client/window_backing_base.py", line 718, in draw_region
2022-01-06 16:34:10,594 client   5 @49.742   File "E:/xpra/xpra/client/window_backing_base.py", line 366, in paint_image
2022-01-06 16:34:10,594 client   5 @49.742   File "E:/xpra/xpra/codecs/pillow/decoder.py", line 112, in decompress
2022-01-06 16:34:10,594 client   5 @49.742   File "C:/msys64/mingw64/lib/python3.9/site-packages/PIL/Image.py", line 3009, in open
2022-01-06 16:34:10,689 client   5 @49.742   File "C:/msys64/mingw64/lib/python3.9/site-packages/PIL/Image.py", line 2996, in _open_core
2022-01-06 16:34:10,689 client   5 @49.742   File "C:/msys64/mingw64/lib/python3.9/site-packages/PIL/Image.py", line 2905, in _decompression_bomb_check
2022-01-06 16:34:10,689 client   5 @49.742 DecompressionBombError: Image size (268435456 pixels) exceeds limit of 178956970 pixels, could be decompression bomb DOS attack.
2022-01-06 16:34:10,838 Warning: client decoding error:
2022-01-06 16:34:10,838  Image size (268435456 pixels) exceeds limit of 178956970 pixels, could be decompression bomb DOS attack.
2022-01-06 16:34:11,585 client   5 @50.786 server is not responding, drawing spinners over the windows
2022-01-06 16:34:12,211 client   5 @51.434 UI thread is now blocked
2022-01-06 16:34:12,359 client   5 @51.521 server is OK again
2022-01-06 16:34:12,367 client   5 @51.522 UI thread is running again, resuming
2022-01-06 16:34:16,595 client   5 @55.790 server is not responding, drawing spinners over the windows
2022-01-06 16:34:18,744 client   5 @56.772 server is OK again
2022-01-06 16:34:23,454 client   5 @00.798 server is not responding, drawing spinners over the windows
2022-01-06 16:34:25,245 client   5 @04.217 UI thread is now blocked
2022-01-06 16:34:33,001 client   5 @12.045 server is not responding, drawing spinners over the windows
2022-01-06 16:34:33,002 client   5 @12.084 UI thread is running again, resuming
/usr/lib/python3/dist-packages/gi/overrides/Gtk.py:1632: Warning: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
  return _Gtk_main(*args, **kwargs)
/usr/lib/python3/dist-packages/gi/overrides/Gtk.py:1632: Warning: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
  return _Gtk_main(*args, **kwargs)
/usr/lib/python3/dist-packages/gi/overrides/Gtk.py:1632: Warning: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
  return _Gtk_main(*args, **kwargs)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xpra/server/server_base.py", line 895, in call_handler
    handler(proto, packet)
  File "/usr/lib/python3/dist-packages/xpra/x11/server.py", line 1024, in _process_configure_window
    self._set_client_properties(proto, wid, window, cprops)
  File "/usr/lib/python3/dist-packages/xpra/x11/server.py", line 1125, in _set_client_properties
    super()._set_client_properties(proto, wid, window, new_client_properties)
  File "/usr/lib/python3/dist-packages/xpra/server/server_base.py", line 679, in _set_client_properties
    ss.set_client_properties(wid, window, typedict(new_client_properties))
  File "/usr/lib/python3/dist-packages/xpra/server/source/windows_mixin.py", line 532, in set_client_properties
    ws.set_client_properties(new_client_properties)
  File "/usr/lib/python3/dist-packages/xpra/server/window/window_source.py", line 715, in set_client_properties
    self.do_set_client_properties(properties)
  File "/usr/lib/python3/dist-packages/xpra/server/window/window_video_source.py", line 415, in do_set_client_properties
    super().do_set_client_properties(properties)
  File "/usr/lib/python3/dist-packages/xpra/server/window/window_source.py", line 738, in do_set_client_properties
    self.update_encoding_selection(self.encoding)
  File "/usr/lib/python3/dist-packages/xpra/server/window/window_video_source.py", line 404, in update_encoding_selection
    super().update_encoding_selection(encoding, exclude, init)
  File "/usr/lib/python3/dist-packages/xpra/server/window/window_source.py", line 847, in update_encoding_selection
    self.update_encoding_options()
  File "/usr/lib/python3/dist-packages/xpra/server/window/window_video_source.py", line 1078, in update_encoding_options
    self.check_pipeline_score(force_reload)
  File "/usr/lib/python3/dist-packages/xpra/server/window/window_video_source.py", line 1150, in check_pipeline_score
    scores = self.get_video_pipeline_options(eval_encodings, w, h, self.pixel_format, force_reload)
  File "/usr/lib/python3/dist-packages/xpra/server/window/window_video_source.py", line 1309, in get_video_pipeline_options
    add_scores("via %s" % out_csc, csc_spec, out_csc)
  File "/usr/lib/python3/dist-packages/xpra/server/window/window_video_source.py", line 1279, in add_scores
    scaling = self.calculate_scaling(width, height, max_w, max_h)
  File "/usr/lib/python3/dist-packages/xpra/server/window/window_video_source.py", line 1401, in calculate_scaling
    scaling = get_min_required_scaling()
  File "/usr/lib/python3/dist-packages/xpra/server/window/window_video_source.py", line 1377, in get_min_required_scaling
    raise Exception("BUG: failed to find a scaling value for window size %sx%s" % (width, height))
Exception: BUG: failed to find a scaling value for window size 16384x16384
```

**To Reproduce**
1. server command
```
systemd-run --user --unit=xpra-20 -- choom -n 800 -- xpra start --daemon=no --sharing=yes --sound=yes --bind-tcp=127.1.56.22:39393 :20
```
3. client command
```
# loop-back binding is manually created over SSH; 
# the problem also manifested over SSH when a pipe was created for display 10 pointing to the corresponding TCP socket
xpra attach tcp://127.1.56.22:39393
xpra attach ssh://user@host/10
```
5. specific action to trigger the bug

Run ~10 Firefox windows and ~3 Thunderbird windows in the same session.  Re-connect to the session.

**System Information (please complete the following information):**
 - Server OS: `Ubuntu 20.04` arm64
 - Client OS: `Windows 10`; `Windows 11`
 - Xpra Server Version `4.3-r30545`
 - Xpra Client Version `4.2.3-r3 64-bit`

**Additional context**
This isn't something that I can reproduce consistently, but it appears to be aggregated when there are more windows in a session.

Client is in a High-DPI environment with scaling set to "125%".

The windows that are incorrectly sized are "appropriately" sized on disconnect (i.e. set to something "reasonable" and usable on a 1920x1080 screen).

**Comment by jdstroy** [comment]
Update, I'm able to reproduce this on xpra server 4.4-r30923, Ubuntu 20.04/focal, arm64, with client 4.2.3-r3 64-bit, Windows 11.

Client command line:

```
"C:\Program Files\Xpra\Xpra_cmd.exe" attach ssh://user@host/22
```

Server command line:

```
/usr/bin/xpra start --systemd-run=yes --daemon=no --sharing=yes --sound=yes :22
```

Some of the Firefox windows were maximized; no Thunderbird instances were running this time, but lxterminal had a few windows and at least one gimp window was running.

**Comment by totaam** [comment]
I've seen this one before, Firefox creates a humongous window 16768 or larger, which creates all sorts of problems.
For one, GTK crashes on some platforms with such large windows.
Another is that we end up spending ridiculous amounts of CPU trying to compress those windows.
It's not clear what should be done with such windows: some applications may have valid use cases for extra large windows.
Steps to reproduce would be very welcome.

**Comment by jdstroy** [comment]
I did some more experimentation with this, but had to cut things a little short due to a pretty [big gaffe](https://community.oracle.com/customerconnect/discussion/627566/vnic-public-address-has-disappeared) at Oracle where someone accidentally harvested in-use IPv4 addresses for reuse.

I was able to reproduce this while running Thunderbird and lxterminal; it does not appear to be isolated to a problem in Firefox.  Similar conditions as in Firefox -- the window is initially something smaller than 1920 x 1080, but somewhere between disconnection and re-attachment, the window is resized to something absurd.  I am unsure if this is caused by maximized windows or not, as some of the windows were maximized in both test conditions (with Firefox and Thunderbird).

**Comment by tou2** [comment]
I temporarily solved the problem on my server by modifying the last lines in `etc/xpra/conf.d/55_server_x11.conf` form this:

```
 #Selecting virtual X server:
xvfb = Xvfb +extension GLX +extension Composite -screen 0 \
    8192x4096x24+32 -nolisten tcp -noreset -auth $XAUTHORITY \
    -dpi 96
```

To this:

```
 #Selecting virtual X server:
xvfb = Xvfb +extension GLX +extension Composite -screen 0 \
    1920x1080x24+32 -nolisten tcp -noreset -auth $XAUTHORITY \
    -dpi 96
```

And I am on version 4.3 installed and updated from `https://xpra.org focal InRelease`
