### ISSUE TITLE
Having problem with xpra session launch 

### ISSUE THREAD

**Issue by bishnoi29nitin** [Xpra-org/xpra#3526]
Hello, 

I am using xpra to connect server and client, in this I want to display my server side application on the client web browser. I am facing the issue as multiple session are being launched simultaneously and I required only one.

Using the below mentioned command to make proxy server.
```
sudo xpra proxy :100 --wss-auth=pam --bind-wss=0.0.0.0:5905 --ssl-cert=/path_to_cert --ssl=on
```

Then using the command 
```
xpra start --ssl-cert=/path_to_cert --ssl=on --start=xterm
```

But this command launch two session 
```shell
$ xpra list
Found the following xpra sessions:
/run/xpra:
	INACCESSIBLE session at :100
$ xpra list
Found the following xpra sessions:
/run/user/1020/xpra:
	LIVE session at :5
	LIVE session at :6
/run/xpra:
	INACCESSIBLE session at :100 
```
May you please help me with this.

**Comment by totaam** [comment]
@bishnoi29nitin please see https://github.com/Xpra-org/xpra/wiki/Reporting-Bugs and provide more details on the version, OS, etc..

**Comment by bishnoi29nitin** [comment]
On running the command > xpra bug-report, this is the output shown on the terminal
xpra main error:
Traceback (most recent call last):
File "/usr/lib64/python2.7/site-packages/xpra/scripts/main.py", line 121, in main
return run_mode(script_file, err, options, args, mode, defaults)
File "/usr/lib64/python2.7/site-packages/xpra/scripts/main.py", line 482, in run_mode
bug_main(["xpra"]+args)
File "/usr/lib64/python2.7/site-packages/xpra/scripts/bug_report.py", line 18, in main
from xpra.x11.gtk_x11.gdk_display_source import init_gdk_display_source
File "/usr/lib64/python2.7/site-packages/xpra/x11/gtk_x11/gdk_display_source.py", line 8, in
from xpra.x11.gtk2 import gdk_display_source #@UnresolvedImport, @UnusedImport
File "xpra/x11/gtk2/gdk_display_source.pyx", line 17, in init xpra.x11.gtk2.gdk_display_source
File "/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/init.py", line 64, in
_init()
File "/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/init.py", line 52, in _init
_gtk.init_check()
RuntimeError: could not open display

$ xpra list
Found the following xpra sessions:
/run/xpra:
INACCESSIBLE session at :100
$ xpra list
Found the following xpra sessions:
/run/user/1020/xpra:
LIVE session at :5
LIVE session at :6
/run/xpra:
INACCESSIBLE session at :100

**Comment by bishnoi29nitin** [comment]
The log file of session 5 is,

2022-04-20 12:05:53,901 cannot access python uinput module:
2022-04-20 12:05:53,902  No module named uinput
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: server already running
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: server already running
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: server already running
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: server already running
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: server already running
2022-04-20 12:05:54,055 created unix domain socket '/run/user/1020/xpra/ssl-hn-5'
2022-04-20 12:05:54,055 cannot create group socket '/run/xpra/ssl-hn-5'
2022-04-20 12:05:54,055  [Errno 13] Permission denied
2022-04-20 12:05:54,055 Warning: missing sound module
2022-04-20 12:05:54,095 Warning: zlib is the only compressor enabled
2022-04-20 12:05:54,095  install and enable lz4 support for better performance
2022-04-20 12:05:54,095 pointer device emulation using XTest
2022-04-20 12:05:54,105 serving html content from '/usr/share/xpra/www'
2022-04-20 12:05:54,589 OpenGL is supported on display ':5'
2022-04-20 12:05:54,590  using 'llvmpipe (LLVM 5.0, 256 bits)' renderer
2022-04-20 12:05:54,622 D-Bus notification forwarding is available
2022-04-20 12:05:54,650 Warning: webcam forwarding is disabled
2022-04-20 12:05:54,650  the virtual video directory '/sys/devices/virtual/video4linux' was not found
2022-04-20 12:05:54,650  make sure that the 'v4l2loopback' kernel module is installed and loaded
2022-04-20 12:05:54,650 found 0 virtual video devices for webcam forwarding
2022-04-20 12:05:54,652 printer forwarding enabled using postscript and pdf
2022-04-20 12:05:54,726 xpra is ready.
2022-04-20 12:05:54,727 xpra GTK2 X11 version 3.0.12-r27627 64-bit
2022-04-20 12:05:54,734 Warning: cannot use application menu data:
2022-04-20 12:05:54,734  no python-xdg module
2022-04-20 12:05:54,773  uid=1020 (parade), gid=1022 (parade)
2022-04-20 12:05:54,773  running with pid 25790 on Linux CentOS 7.5.1804 Core
2022-04-20 12:05:54,774  connected to X11 display :5 with 24 bit colors
2022-04-20 12:05:54,840 92.9GB of system memory 
2022-04-20 12:05:54,955 New unix-domain connection received
2022-04-20 12:05:54,955  on '/run/user/1020/xpra/ssl-hn-5'
2022-04-20 12:05:55,030 New unix-domain connection received
2022-04-20 12:05:55,030  on '/run/user/1020/xpra/ssl-hn-5'
2022-04-20 12:05:55,052 Handshake complete; enabling connection
2022-04-20 12:05:55,058  automatic picture encoding enabled, also available:
 43 2022-04-20 12:05:55,058   jpeg, png, rgb32, webp, h264, mpeg1
 44 2022-04-20 12:05:55,058 HTML5 Linux Chrome client version 3.0.12
 45 2022-04-20 12:05:55,058   as 'parade'
 46 2022-04-20 12:05:55,059  via Linux 3.10.0-862.14.4.el7.x86_64 proxy version 3.0.12 on 'ssl-hn'
 47 2022-04-20 12:05:55,107 setting keyboard layout to 'en'
 48 The XKEYBOARD keymap compiler (xkbcomp) reports:
 49 > Error:            Can't find file "en" for symbols include
 50 >                   Exiting
 51 >                   Abandoning symbols file "default"
 52 Errors from xkbcomp are not fatal to the X server
 53 2022-04-20 12:05:55,120 Error loading new keyboard description
 54 2022-04-20 12:05:55,125  client root window size is 1600x726 with 1 display:
 55 2022-04-20 12:05:55,126   HTML (423x192 mm - DPI: 96x96)
 56 2022-04-20 12:05:55,126     Canvas
 57 2022-04-20 12:05:55,627 Error writing fake xinerama file '/root/.None-fakexinerama':
 58 2022-04-20 12:05:55,627  [Errno 13] Permission denied: '/root/.None-fakexinerama'
 59 2022-04-20 12:05:55,627 Error writing fake xinerama file '/root/.fakexinerama':
 60 2022-04-20 12:05:55,627  [Errno 13] Permission denied: '/root/.fakexinerama'
 61 2022-04-20 12:05:55,630 server virtual display now set to 1600x726
 62 2022-04-20 12:05:55,639 DPI set to 96 x 96
 63 2022-04-20 12:05:55,663 client   1 received xdg start menu data
 64 2022-04-20 12:05:55,663 client   1 startup complete
 65 2022-04-20 12:05:55,663 client   1 connection-established
 66 lpadmin: Forbidden
 67 2022-04-20 12:05:55,668 lpadmin failed and returned error code: 1
 68 2022-04-20 12:05:55,668  verify that user 'parade' has all the required permissions
 69 2022-04-20 12:05:55,668  for running: '/usr/sbin/lpadmin'
 70 2022-04-20 12:05:55,668  full command: '/usr/sbin/lpadmin' '-p' 'HTML5-client' '-v' 'xpraforwarder:/tmp?mimetype=application%2Fpdf&socket-path=%2Frun%2Fuser%2F1020%2Fxpra%2    Fssl-hn-5&remote-printer=HTML5+client&remote-device-uri=None&source=ebf31d9d-6281-3421-2f93-4842d8a90cb6&display=%3A5' '-D' 'Print to PDF in client browser' '-L' 'via xpra'     '-E' '-o' 'printer-is-shared=false' '-u' 'allow:parade' '-P' '/usr/share/ppd/cupsfilters/Generic-PDF_Printer-PDF.ppd'
 71 2022-04-20 12:05:55,859 New unix-domain connection received
 72 2022-04-20 12:05:55,859  on '/run/user/1020/xpra/ssl-hn-5'
 73 2022-04-20 12:05:56,029 New unix-domain connection received
 74 2022-04-20 12:05:56,029  on '/run/user/1020/xpra/ssl-hn-5'
 75 2022-04-20 12:06:01,388 New unix-domain connection received
 76 2022-04-20 12:06:01,388  on '/run/user/1020/xpra/ssl-hn-5'


System Information (please complete the following information):

Server OS: Centos 7
Client OS: Centos 7
Xpra Server Version xpra v3.0.12-r27627
Xpra Client Version xpra v3.0.12-r27627

**Comment by totaam** [comment]
> On running the command > xpra bug-report, this is the output shown on the terminal
> (..)
> `RuntimeError: could not open display`

The bug report tool is a GUI and requires a display.

> `Version xpra v3.0.12-r27627`

The current version is 3.0.13.

Running the exact commands that you used does not create an extra session.
If that were the case, we would get hundreds of complaints.
So whatever you are doing, it's something different.

**Comment by totaam** [comment]
Not heard back.
