### ISSUE TITLE
Having problem with xpra session launch

### ISSUE THREAD

**Issue by bishnoi29nitin** [Xpra-org/xpra#3527]
**Describe the bug**
Hello,

I am using xpra to connect server and client, in this I want to display my server side application on the client web browser. I am facing the issue as multiple session are being launched simultaneously and I required only one.

**To Reproduce**
1. server command > sudo xpra proxy :100 --wss-auth=pam --bind-wss=0.0.0.0:5905 --ssl-cert=/path_to_cert --ssl=on
 > xpra start --ssl-cert=/path_to_cert --ssl=on --start=xterm
3. specific action to trigger the bug

**System Information (please complete the following information):**
 - Server OS: Centos 7
 - Client OS: Centos 7
 - Xpra Server Version xpra v3.0.12-r27627
 - Xpra Client Version xpra v3.0.12-r27627

**Additional context**
On running the command > xpra bug-report, this is the output shown on the terminal 
xpra main error:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/xpra/scripts/main.py", line 121, in main
    return run_mode(script_file, err, options, args, mode, defaults)
  File "/usr/lib64/python2.7/site-packages/xpra/scripts/main.py", line 482, in run_mode
    bug_main(["xpra"]+args)
  File "/usr/lib64/python2.7/site-packages/xpra/scripts/bug_report.py", line 18, in main
    from xpra.x11.gtk_x11.gdk_display_source import init_gdk_display_source
  File "/usr/lib64/python2.7/site-packages/xpra/x11/gtk_x11/gdk_display_source.py", line 8, in <module>
    from xpra.x11.gtk2 import gdk_display_source    #@UnresolvedImport, @UnusedImport
  File "xpra/x11/gtk2/gdk_display_source.pyx", line 17, in init xpra.x11.gtk2.gdk_display_source
  File "/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py", line 64, in <module>
    _init()
  File "/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py", line 52, in _init
    _gtk.init_check()
RuntimeError: could not open display

$ xpra list
Found the following xpra sessions:
/run/xpra:
	INACCESSIBLE session at :100
$ xpra list
Found the following xpra sessions:
/run/user/1020/xpra:
	LIVE session at :5
	LIVE session at :6
/run/xpra:
	INACCESSIBLE session at :100

**Comment by totaam** [comment]
Please don't spam the bug tracker and just reply to your original ticket: #3527
