### ISSUE TITLE
xpra_launcher fails to start via CLI (*buntu 22.04)

### ISSUE THREAD

**Issue by ScanCaster** [Xpra-org/xpra#3552]
**Describe the bug**
Usinjg xpra_launcher via CLI with a XPRA connection file OR just attempting to start the xpra_launcher GUI via CLI, results in an error.

Connecting to server via CLI with 
xpra --auth=ssh:password:value=XXXXX --debug=ssh attach ssh/XXXXX@192.168.0.XXX/100

Works fine.... xpra_launcher, no joy.

**To Reproduce**
1. server command : xpra start --env=XPRA_VAAPI=0 --env=CUTTER_THRESHOLD=0 :100 --start=/home/....
2. client command  xpra_launcher XprafileA.xpra
3. specific action to trigger the bug : use xpra_launcher via CLI to open GUI or XPRA Connection file, 

**System Information (please complete the following information):**
 - Server OS:  Kubuntu 20.04
 - Client OS: Kubuntu 22.04
 - Xpra Server Version 4.3.3
 - Xpra Client Version : BETA 4.4

**Additional context**

$ xpra_launcher XprafileA.xpra
Traceback (most recent call last):
  File "/usr/bin/xpra_launcher", line 10, in <module>
    sys.exit(do_main(sys.argv))
  File "/usr/lib/python3/dist-packages/xpra/client/gtk_base/client_launcher.py", line 1101, in do_main
    init_gdk_display_source()
  File "xpra/x11/gtk3/gdk_display_source.pyx", line 46, in xpra.x11.gtk3.gdk_display_source.init_gdk_display_source
xpra.scripts.config.InitException: cannot use X11 bindings with  and GTK3 (buggy)

UserMe@UserMe-Inspironxxx55:~$ xpra_launcher
Traceback (most recent call last):
  File "/usr/bin/xpra_launcher", line 10, in <module>
    sys.exit(do_main(sys.argv))
  File "/usr/lib/python3/dist-packages/xpra/client/gtk_base/client_launcher.py", line 1101, in do_main
    init_gdk_display_source()
  File "xpra/x11/gtk3/gdk_display_source.pyx", line 46, in xpra.x11.gtk3.gdk_display_source.init_gdk_display_source
xpra.scripts.config.InitException: cannot use X11 bindings with  and GTK3 (buggy)

**Comment by totaam** [comment]
Sorry about that, bug reproduced and fixed.

It will be in the next builds.

**Comment by ScanCaster** [comment]
Ok... great.. No big deal.. things happen...
