### ISSUE TITLE
Commit 19bea4c1 breaks VAAPI codec

### ISSUE THREAD

**Issue by interj** [Xpra-org/xpra#3559]
**Describe the bug**
Commit 19bea4c172d0157a6fa36db5f36586a8619a8a3d causes `h264_vaapi` encoder to fail.

**To Reproduce**
1. `XPRA_VAAPI=1 XPRA_VAAPI_ENCODINGS=h264,vp8,vp9  xpra start --bind-tcp=0.0.0.0:14500`

**System Information (please complete the following information):**
 - Server OS: Debian 11
 - Xpra Server Version: any after 19bea4c172d0157a6fa36db5f36586a8619a8a3d

**Additional context**

`enc_ffmpeg` fails with:
```
2022-06-20 20:42:21,056 init_vaapi_device()=0x7fd26c0a40c0
2022-06-20 20:42:21,056 h264_vaapi: "H.264/AVC (VAAPI)", codec flags: DR1, DELAY
2022-06-20 20:42:21,056 init_encoder(50, 50, typedict({'b-frames': True, 'dst-formats': ['YUV420P'], 'quality': 50, 'speed': 50}))
2022-06-20 20:42:21,056 h264_vaapi options: low_power, idr_interval, b_depth, rc_mode, auto, CQP, CBR, VBR, ICQ, QVBR, AVBR, qp, quality, coder, cavlc, cabac, vlc, ac, aud, sei, identifier, timing, recovery_point, profile, constrained_baseline, main, high, level, 1, 1.1, 1.2, 1.3, 2, 2.1, 2.2, 3, 3.1, 3.2, 4, 4.1, 4.2, 5, 5.1, 5.2, 6, 6.1, 6.2
2022-06-20 20:42:21,056 init_encoder() profile=main
2022-06-20 20:42:21,056 init_encoder() level=0
2022-06-20 20:42:21,056 init_encoder() compression_level=4
2022-06-20 20:42:21,056 init_encoder(50, 50, typedict({'b-frames': True, 'dst-formats': ['YUV420P'], 'quality': 50, 'speed': 50})) failed
Traceback (most recent call last):
  File "xpra/codecs/enc_ffmpeg/encoder.pyx", line 1297, in xpra.codecs.enc_ffmpeg.encoder.Encoder.init_context
  File "xpra/codecs/enc_ffmpeg/encoder.pyx", line 1495, in xpra.codecs.enc_ffmpeg.encoder.Encoder.init_encoder
Exception: could not open h264 encoder context: Invalid argument
2022-06-20 20:42:21,057 load_icon_from_file(/usr/share/icons/hicolor/48x48/apps/konqueror.png, 0)
2022-06-20 20:42:21,057 enc_ffmpeg.Encoder({'version': (58, 134, 100), 'encoding': 'h264', 'formats': ['NV12'], 'type': 'ffmpeg', 'frames': 0, 'width': 64, 'height': 32, 'video-codec': 'h264_vaapi', 'video-description': 'H.264/AVC (VAAPI)', 'src_format': 'NV12', 'encoder_width': 64, 'encoder_height': 32}).clean_encoder()
2022-06-20 20:42:21,057 clean_encoder() freeing AVCodecContext: 0x7fd26c09d600
2022-06-20 20:42:21,057 clean_encoder() done
2022-06-20 20:42:21,057 enc_ffmpeg.Encoder(*closed*).clean_encoder()
2022-06-20 20:42:21,057 clean_encoder() freeing AVCodecContext: 0x0
2022-06-20 20:42:21,057 clean_encoder() done
2022-06-20 20:42:21,057 ffmpeg: h264 encoding failed
Traceback (most recent call last):
  File "/home/interj/.local/lib/python3.9/site-packages/xpra/codecs/codec_checks.py", line 156, in testencoder
    testencoding(encoder_module, encoding, full)
  File "/home/interj/.local/lib/python3.9/site-packages/xpra/codecs/codec_checks.py", line 173, in testencoding
    do_testencoding(encoder_module, encoding, W, H, full)
  File "/home/interj/.local/lib/python3.9/site-packages/xpra/codecs/codec_checks.py", line 249, in do_testencoding
    e.init_context(encoding, W, H, cs_in, options)
  File "xpra/codecs/enc_ffmpeg/encoder.pyx", line 1313, in xpra.codecs.enc_ffmpeg.encoder.Encoder.init_context
  File "xpra/codecs/enc_ffmpeg/encoder.pyx", line 1297, in xpra.codecs.enc_ffmpeg.encoder.Encoder.init_context
  File "xpra/codecs/enc_ffmpeg/encoder.pyx", line 1495, in xpra.codecs.enc_ffmpeg.encoder.Encoder.init_encoder
Exception: could not open h264 encoder context: Invalid argument
2022-06-20 20:42:21,058 got icon data from '/usr/share/icons/hicolor/48x48/apps/konqueror.png': 4054 bytes
2022-06-20 20:42:21,058 Warning: ffmpeg encoder testing failed with h264:
2022-06-20 20:42:21,058  could not open h264 encoder context: Invalid argument
```
and `ffmpeg 4.4.2-1` doesn't like `-qp 0` for `h264_vaapi`, but doesn't fail:
```
ffmpeg -hwaccel vaapi -hwaccel_output_format vaapi -vaapi_device /dev/dri/renderD128 -v verbose -i ./bbb_sunflower_2160p_60fps_normal.mp4 -c:v h264_vaapi -compression_level 7 -qp 0 -f mp4 /dev/null
...
[h264_vaapi @ 0x55f2f09f8980] No quality level set; using default (20).  <-----it's a warning btw
[h264_vaapi @ 0x55f2f09f8980] RC mode: CQP.
[h264_vaapi @ 0x55f2f09f8980] RC quality: 20.
...
frame=  808 fps=114 q=-0.0 Lsize=   84525kB time=00:00:13.45 bitrate=51481.7kbits/s dup=2 drop=0 speed=1.89x
```

Setting `self.video_ctx.global_quality` to non-zero value for vaapi codecs or in general solves the problem.

**Comment by totaam** [comment]
Does the commit above fix things?

**Comment by interj** [comment]
It does, using this codec still causes xpra to leak memory, but that's another problem, closing the issue.
