### ISSUE TITLE
`OverflowError: can't convert negative value to unsigned int`

### ISSUE THREAD

**Issue by stdedos** [Xpra-org/xpra#3591]
**Describe the bug**
```
       │ File: /home/stdedos/Documents/_usr_bin_xpra.1000-short.crash
       │ Size: 3.4 KB
───────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ ProblemType: Crash
   2   │ CrashCounter: 1
   3   │ Date: Wed Jul 20 22:48:17 2022
   4   │ ExecutablePath: /usr/bin/xpra
   5   │ ExecutableTimestamp: 1640186809
   6   │ ProcCmdline: /usr/bin/xpra\ start\ :2\ --title=@title@\ on\ @@/@server-display@\ --ssh=plink\ -ssh\ -agent\ --border=#FF5733,5\ --desktop-scaling=no\ --speaker=off\ --webcam=no\ --splash=no\ --start=nohup\ systemd-inhibit\ --what=handle-lid-switch\ sleep\ 1d\ >/dev/
       │ null\ 2>&1\ &\ inhibit_pid=$\ ;\ xpra\ xwait\ ;\ kill\ -9\ \ ;\ nohup\ systemd-inhibit\ --what=handle-lid-switch\ sleep\ 5m\ >/dev/null\ 2>&1\ &\ --start=gnome-terminal\ --env=XPRA_PROXY_START_UUID=b8c89b6e2662467d9f716dba10409994\ --daemon=yes\ --systemd-run=no
   7   │ ProcCwd: /
   8   │ ProcEnviron: 
   9   │ PythonArgs: ['/usr/bin/xpra', 'start', ':2', '--title=@title@ on @@/@server-display@', '--ssh=plink -ssh -agent', '--border=#FF5733,5', '--desktop-scaling=no', '--speaker=off', '--webcam=no', '--splash=no', '--start=nohup systemd-inhibit --what=handle-lid-switch sle
       │ ep 1d >/dev/null 2>&1 & inhibit_pid=$ ; xpra xwait ; kill -9  ; nohup systemd-inhibit --what=handle-lid-switch sleep 5m >/dev/null 2>&1 &', '--start=gnome-terminal', '--env=XPRA_PROXY_START_UUID=b8c89b6e2662467d9f716dba10409994', '--daemon=yes', '--systemd-run=no']
  10   │ Traceback:
  11   │  Traceback (most recent call last):
  12   │    File "/usr/lib/python3/dist-packages/xpra/server/window/video_subregion.py", line 235, in nonvideo_refresh
  13   │      if self.refresh_cb(nonvideo):
  14   │    File "/usr/lib/python3/dist-packages/xpra/server/window/window_video_source.py", line 633, in refresh_subregion
  15   │      super().do_send_delayed_regions(now, regions, encoding, options,
  16   │    File "/usr/lib/python3/dist-packages/xpra/server/window/window_source.py", line 1987, in do_send_delayed_regions
  17   │      if not self.process_damage_region(damage_time, region.x, region.y, region.width, region.height,
  18   │    File "/usr/lib/python3/dist-packages/xpra/server/window/window_video_source.py", line 862, in process_damage_region
  19   │      image = self.get_damage_image(x, y, w, h)
  20   │    File "/usr/lib/python3/dist-packages/xpra/server/window/window_source.py", line 2033, in get_damage_image
  21   │      image = self.window.get_image(x, y, w, h)
  22   │    File "/usr/lib/python3/dist-packages/xpra/x11/models/core.py", line 366, in get_image
  23   │      return self._composite.get_image(x, y, width, height)
  24   │    File "/usr/lib/python3/dist-packages/xpra/x11/gtk_x11/window_damage.py", line 180, in get_image
  25   │      shm_image = shm.get_image(handle.get_pixmap(), x, y, width, height)
  26   │    File "xpra/x11/bindings/ximage.pyx", line 570, in xpra.x11.bindings.ximage.XShmWrapper.get_image
  27   │  OverflowError: can't convert negative value to unsigned int
  28   │ UserGroups: adm cdrom dip docker lpadmin lxd plugdev sambashare sudo
  29   │ _LogindSession: 27
  30   │ ApportVersion: 2.20.11-0ubuntu27.24
  31   │ Architecture: amd64
  32   │ CasperMD5CheckResult: skip
  33   │ DistroRelease: Ubuntu 20.04
  34   │ InstallationDate: Installed on 2022-04-06 (105 days ago)
  35   │ InstallationMedia: Ubuntu 20.04.4 LTS "Focal Fossa" - Release amd64 (20220223)
  36   │ ProcVersionSignature: Ubuntu 5.14.0-1045.51-oem 5.14.21
  37   │ SourcePackage: xpra
  38   │ Tags: third-party-packages focal
  39   │ Title: xpra crashed with OverflowError in xpra.x11.bindings.ximage.XShmWrapper.get_image(): can't convert negative value to unsigned int
  40   │ Uname: Linux 5.14.0-1045-oem x86_64
  41   │ UnreportableReason: This is not an official Ubuntu package. Please remove any third party package and try again.
  42   │ UpgradeStatus: No upgrade log present (probably fresh install)
  43   │ _MarkForUpload: True
```
Seemed to not be so serious, but then it became ... and "on some future time", it also "automagically" dropped the client, but the server was a-ok.

[client-2.zip](https://github.com/Xpra-org/xpra/files/9154530/client-2.zip)

**To Reproduce**
1. server command
2. client command
3. specific action to trigger the bug

**System Information (please complete the following information):**
- Server OS: Ubuntu 20.04.3 LTS
- Client OS: Microsoft Windows [Version 10.0.18363.836]
- Xpra Server Version (see above)
- Xpra Client Version (see above)

**Additional context**

_"Food for thought": Can xpra accept connections in a child thread? If non-critical server code blows up, that means we loose the client, not the server ..._

**Comment by totaam** [comment]
Odd. This code has not changed in years.
I don't see how you managed to get negative (`signed int`) values to land in that Cython function call.
The two commits above should now continue more gracefully and chop the image as needed.
(new builds will be posted later today)

---

Note to self: we don't validate the coordinates in the `WindowSource` because other backends do support negative coordinates, X11 does not so that's where the validation has to be done.

**Comment by stdedos** [comment]
_Haven't seen this any other time, assuming fixed_
