### ISSUE TITLE
`return ((bytestostr(k), v) for k, v in chain(mapping, getattr(kwargs, "items")())): 'NoneType' object is not iterable`

### ISSUE THREAD

**Issue by stdedos** [Xpra-org/xpra#3594]
**Describe the bug**

```
 111   │ 2022-07-24 22:31:15,167 Error: processing new connection from Protocol(unix-domain socket:/run/user/1000/xpra/2/socket):
 112   │ Traceback (most recent call last):
 113   │   File "/usr/lib/python3/dist-packages/xpra/server/server_base.py", line 434, in _process_hello_ui
 114   │     self.parse_hello(ss, c, send_ui)
 115   │   File "/usr/lib/python3/dist-packages/xpra/server/server_base.py", line 455, in parse_hello
 116   │     bc.parse_hello(self, ss, c, send_ui)
 117   │   File "/usr/lib/python3/dist-packages/xpra/server/mixins/input_server.py", line 79, in parse_hello
 118   │     self.parse_hello_ui_keyboard(ss, caps)
 119   │   File "/usr/lib/python3/dist-packages/xpra/server/mixins/input_server.py", line 87, in parse_hello_ui_keyboard
 120   │     ss.keyboard_config = self.get_keyboard_config(c)    #pylint: disable=assignment-from-none
 121   │   File "/usr/lib/python3/dist-packages/xpra/x11/x11_server_core.py", line 448, in get_keyboard_config
 122   │     keyboard_config.parse_options(props)
 123   │   File "/usr/lib/python3/dist-packages/xpra/x11/server_keyboard_config.py", line 142, in parse_options
 124   │     keymap_dict = typedict(props.dictget("keymap"))
 125   │   File "/usr/lib/python3/dist-packages/xpra/util.py", line 358, in __init__
 126   │     super().__init__(self._process_args(mapping, **kwargs))
 127   │   File "/usr/lib/python3/dist-packages/xpra/util.py", line 356, in <genexpr>
 128   │     return ((bytestostr(k), v) for k, v in chain(mapping, getattr(kwargs, "items")()))
 129   │ TypeError: 'NoneType' object is not iterable
```

**To Reproduce**
1. server command
2. client command
3. specific action to trigger the bug

**System Information (please complete the following information):**
- Server OS: Ubuntu 20.04.3 LTS
- Client OS: Microsoft Windows [Version 10.0.18363.836]
- Xpra Server Version 4.4-r31576-1
- Xpra Client Version (see above)

**Additional context**
Please see "reporting bugs" in the wiki section.

**Comment by totaam** [comment]
Was caused by 42b407a346318499619675d99974f84c06100b39, tiny trivial fix above.

**Comment by stdedos** [comment]
SyntaxError 😛

**Comment by totaam** [comment]
Dammit!
You're right. My `vim` lacks syntax highlighting.

**Comment by stdedos** [comment]
🤯 🤯 🤯 🤯 🤯 🤯 🤯 🤯
