### ISSUE TITLE
TypeError: object of type xpra+x11+models+or_window+OverrideRedirectWindowModel' does not have property client-geometry'

### ISSUE THREAD

**Issue by TijZwa** [Xpra-org/xpra#3611]
**Describe the bug**
If you connect a client with a different resolution then the server, while a window with the Override Redirect flag is still open, the connection fails.

**To Reproduce**
1. Connect Xpra
2. Open an OR windows; ie lxpanel menu or right-click context menu
3. Disconnect
4. Connect with another screen size

Server log:

```
2022-08-31 08:47:51,377 Error: processing new connection from WebSocket(ws socket: 10.0.0.3:9999 <- 10.0.0.2:43352):
Traceback (most recent call last):
  File "/usr/lib64/python3.10/site-packages/xpra/server/server_base.py", line 438, in _process_hello_ui
    self.parse_hello(ss, c, send_ui)
  File "/usr/lib64/python3.10/site-packages/xpra/server/server_base.py", line 459, in parse_hello
    bc.parse_hello(self, ss, c, send_ui)
  File "/usr/lib64/python3.10/site-packages/xpra/server/mixins/display_manager.py", line 57, in parse_hello
    self.parse_screen_info(ss)
  File "/usr/lib64/python3.10/site-packages/xpra/server/mixins/display_manager.py", line 189, in parse_screen_info
    return self.do_parse_screen_info(ss, ss.desktop_size)
  File "/usr/lib64/python3.10/site-packages/xpra/server/mixins/display_manager.py", line 202, in do_parse_screen_info
    sw, sh = self.configure_best_screen_size()
  File "/usr/lib64/python3.10/site-packages/xpra/x11/x11_server_base.py", line 125, in configure_best_screen_size
    root_w, root_h = super().configure_best_screen_size()
  File "/usr/lib64/python3.10/site-packages/xpra/x11/x11_server_core.py", line 585, in configure_best_screen_size
    return self.set_screen_size(w, h, bigger)
  File "/usr/lib64/python3.10/site-packages/xpra/x11/server.py", line 314, in set_screen_size
    cg = window.get_property("client-geometry")
TypeError: object of type xpra+x11+models+or_window+OverrideRedirectWindowModel' does not have property client-geometry'
```

**Comment by totaam** [comment]
I am very confident that this has already been fixed in 1e0a51cc970b73cb52f5d4da5cc79b37eceef9df, so I am closing this ticket.

Please make sure that you're running an up to date build.
