### ISSUE TITLE
Large clipboard selections cause target appliacation to hang

### ISSUE THREAD

**Issue by adamnew123456** [Xpra-org/xpra#3636]
**Describe the bug**
Once a clipboard selection gets big enough (500ish bytes in my testing) Xpra is no longer able to paste them into server applications. Whatever application I paste them into will hang or timeout when requesting the clipboard data.

**To Reproduce**

1. Logon to the server (sol) and run `xpra start --bind-tcp=0.0.0.0:1995 --daemon=no -d clipboard :1`
2. Connect from the client (jupiter) via `xpra attach tcp://sol.lan:1995 --start=xterm`
3. Open Firefox locally, visit https://wiki.c2.com/ and copy all the body text onto the clipboard.
4. Invoke `xclip -out -selection clipboard` on the xterm spawned by Xpra.

At this point `xclip` will hang and the console running the Xpra server will show these messages:

```
2022-10-04 14:00:39,584 got_contents('UTF8_STRING', 'UTF8_STRING', 8, b'See fedwiki\'s C2 for Me\n\nWelcome to the Wik .. ou are overwhelmed by the big list of options. ') pending=(<GdkX11.X11Window object at 0x7f739bfadb00 (GdkX11Window at 0x55f3d1fde360)>, 'UTF8_STRING', 'XCLIP_OUT', 0)
2022-10-04 14:00:39,584 setting response b'See fedwiki\'s C2 for Me\n\nWelcome to the Wik .. ou are overwhelmed by the big list of options. ' as 'UTF8_STRING' on property 'XCLIP_OUT' of window 0x50d as UTF8_STRING
2022-10-04 14:00:39,584 set_selection_response(<GdkX11.X11Window object at 0x7f739bfadb00 (GdkX11Window at 0x55f3d1fde360)>, UTF8_STRING, XCLIP_OUT, UTF8_STRING, 8, b'See fedwiki\'s C2 for Me\n\nWelcome to the Wik .. ou are overwhelmed by the big list of options. ', 0)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xpra/clipboard/clipboard_core.py", line 506, in process_clipboard_packet
    handler(packet)
  File "/usr/lib/python3/dist-packages/xpra/clipboard/clipboard_core.py", line 475, in _process_clipboard_contents
    self._clipboard_got_contents(request_id, dtype, dformat, raw_data)
  File "/usr/lib/python3/dist-packages/xpra/clipboard/clipboard_timeout_helper.py", line 120, in _clipboard_got_contents
    proxy.got_contents(target, dtype, dformat, data)
  File "/usr/lib/python3/dist-packages/xpra/x11/gtk_x11/clipboard.py", line 501, in got_contents
    self.set_selection_response(requestor, actual_target, prop, dtype, dformat, data, time)
  File "/usr/lib/python3/dist-packages/xpra/x11/gtk_x11/clipboard.py", line 472, in set_selection_response
    X11Window.XChangeProperty(xid, prop, dtype, dformat, data)
  File "xpra/x11/bindings/window_bindings.pyx", line 1050, in xpra.x11.bindings.window_bindings.X11WindowBindingsInstance.XChangeProperty
TypeError: expected bytes, memoryview found
```

**System Information:**
 - Server OS: Debian Unstable
 - Client OS: Multiple (reproduces on Debian Unstable, Windows 10)
 - Xpra Server Version: xpra v4.4-r31983 (g7766ff357) beta
 - Xpra Client Version: xpra v4.4-r31841 (gce6d7019b) beta

**Additional context**

I worked around this this locally with a small patch to the X11 clipboard handling code which converts the `memoryview` instance into `bytes`, in the same way that `str` instances are converted to `bytes`:

```diff
diff --git a/xpra/x11/gtk_x11/clipboard.py b/xpra/x11/gtk_x11/clipboard.py
index 4338f8a1c..cec422214 100644
--- a/xpra/x11/gtk_x11/clipboard.py
+++ b/xpra/x11/gtk_x11/clipboard.py
@@ -483,6 +483,8 @@ class ClipboardProxy(ClipboardProxyCore, GObject.GObject):
                             data = strtobytes(data)
                         except UnicodeEncodeError:
                             data = data.encode("utf8")
+                    if isinstance(data, memoryview):
+                        data = bytes(data)
                     X11Window.XChangeProperty(xid, prop, dtype, dformat, data)
                 else:
                     #maybe even delete the property?
```

**Comment by markmandel** [comment]
I'm not seeing that specific exception on `xpra v4.4-r0`, but definitely have noticed that with this new version, anything over ~5 lines of text , if I hit ctrl+v on my local machine, it just doesn't get pasted on the attached xpra application instances.

Wondering if it's related?

**Comment by totaam** [comment]
This is caused by #3601: the new cython bindings return a memoryview.

The fix suggested above is correct, it just needs to be moved to a more generic location as other platforms will need the same fix.
