### ISSUE TITLE
unit.server.mixins.child_command_test fails due to missing idle_add method

### ISSUE THREAD

**Issue by chewi** [Xpra-org/xpra#3642]
**Describe the bug**
The test suite under 4.4 or current master fails due to bc8bf26c44d1b151d709232460483f5432f79f5b. It's not clear how `idle_add` should be defined in this `ChildCommandServer`. There are also other instances of `self.idle_add` in this class.

```
running unit.server.mixins.child_command_test

E
======================================================================
ERROR: test_command_server (__main__.ChildCommandMixinTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/x11-wm/xpra-9999/work/xpra-9999/tests/unittests/unit/server/mixins/child_command_test.py", line 26, in test_command_server
    self.do_test_command_server()
  File "/var/tmp/portage/x11-wm/xpra-9999/work/xpra-9999/tests/unittests/unit/server/mixins/child_command_test.py", line 55, in do_test_command_server
    self._test_mixin_class(_ChildCommandServer, opts)
  File "/var/tmp/portage/x11-wm/xpra-9999/work/xpra-9999/tests/unittests/unit/server/mixins/servermixintest_util.py", line 78, in _test_mixin_class
    x = self.mixin = mclass()
  File "/var/tmp/portage/x11-wm/xpra-9999/work/xpra-9999/tests/unittests/unit/server/mixins/child_command_test.py", line 52, in _ChildCommandServer
    ccs = child_command_server.ChildCommandServer()
  File "/var/tmp/portage/x11-wm/xpra-9999/work/xpra-9999_python3.10/test/lib/xpra/server/mixins/child_command_server.py", line 75, in __init__
    self.idle_add(self.late_start)
AttributeError: 'ChildCommandServer' object has no attribute 'idle_add'
```

**To Reproduce**
Run the test suite.

**System Information (please complete the following information):**
Gentoo Linux with Xpra 4.4 or fa3e6ed7a02c4a5e8aef95102431c423df25c689.

**Comment by totaam** [comment]
I have reverted it in 4.4 for now.
For master, I would like the test code to emulate the server interface more fully.
