### ISSUE TITLE
xpra start --encoding=help throws NotImplementedError

### ISSUE THREAD

**Issue by firejox** [Xpra-org/xpra#3654]
**Describe the bug**
According to the man pages, we can use `--encoding=help` to see what encodings are supported. However it throws NotImplementedError.

**To Reproduce**
`xpra start --encoding=help`

**System Information (please complete the following information):**
 - Server OS: Windows 10 WSL2
 - Xpra Server Version v4.4-r0

**Additional context**
Error Output:
```
Warning: XDG_RUNTIME_DIR is not defined
 and '/run/user/1000' does not exist
 using '/tmp'
xpra server supports the following encodings:
(please wait, encoder initialization may take a few seconds)
xpra main error:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xpra/scripts/main.py", line 142, in main
    return run_mode(script_file, cmdline, err, options, args, mode, defaults)
  File "/usr/lib/python3/dist-packages/xpra/scripts/main.py", line 451, in run_mode
    return do_run_mode(script_file, cmdline, error_cb, options, args, mode, defaults)
  File "/usr/lib/python3/dist-packages/xpra/scripts/main.py", line 486, in do_run_mode
    return run_server(script_file, cmdline, error_cb, options, args, mode, defaults)
  File "/usr/lib/python3/dist-packages/xpra/scripts/main.py", line 1836, in run_server
    return do_run_server(script_file, cmdline, error_cb, options, args, mode, display, defaults)
  File "/usr/lib/python3/dist-packages/xpra/scripts/server.py", line 720, in do_run_server
    return show_encoding_help(opts)
  File "/usr/lib/python3/dist-packages/xpra/scripts/server.py", line 248, in show_encoding_help
    sb = ServerBase()
  File "/usr/lib/python3/dist-packages/xpra/server/server_base.py", line 103, in __init__
    c.__init__(self)
  File "/usr/lib/python3/dist-packages/xpra/server/mixins/child_command_server.py", line 75, in __init__
    self.idle_add(self.late_start)
  File "/usr/lib/python3/dist-packages/xpra/server/server_base.py", line 130, in idle_add
    raise NotImplementedError()
NotImplementedError
```

**Comment by totaam** [comment]
Fixed in the commit above.
