### ISSUE TITLE
ssh access, attach semi-failure on "file exists" errors

### ISSUE THREAD

**Issue by karlkleinpaste** [Xpra-org/xpra#3664]
F35, up to date with `v5.0-r32078 (g490565040) beta` at both ends. On `attach`:
```
2022-10-21 10:47:00,143 Connected (version 2.0, client OpenSSH_8.7)
2022-10-21 10:47:00,240 Authentication (publickey) successful!
2022-10-21 10:47:00,357 [major:19]	ssh server OS is 'linux-gnu'
2022-10-21 10:47:00,496 [major:19]	paramiko SSH agent forwarding enabled
2022-10-21 10:47:00,542 [major:19]	 keyboard settings: rules=evdev, model=pc105, layout=us
2022-10-21 10:47:00,544 [major:19]	 desktop size is 5760x1080:
2022-10-21 10:47:00,544 [major:19]	  :0.0 (1023x191 mm - DPI: 143x144) workarea: 5760x1029 at    0x26  
2022-10-21 10:47:00,544 [major:19]	    PRO DP-3         1920x1080 at    0x0    (344x193 mm - DPI: 142x142) workarea: 1920x1029 at    0x26
2022-10-21 10:47:00,544 [major:19]	    AUO DP-2         1920x1080 at 1920x0    (344x193 mm - DPI: 142x142) workarea: 1920x1080 at 1920x0
2022-10-21 10:47:00,544 [major:19]	    PRO DP-1         1920x1080 at 3840x0    (344x193 mm - DPI: 142x142) workarea: 1920x1080 at 3840x0
2022-10-21 10:47:00,728 [major:19]	 SSH: 'Error setting up client ssh agent forwarding socket'
2022-10-21 10:47:00,728 [major:19]	 SSH: 'Traceback (most recent call last):'
2022-10-21 10:47:00,728 [major:19]	 SSH: '  File "/usr/lib64/python3.10/site-packages/xpra/scripts/main.py", line 2681, in run_proxy'
2022-10-21 10:47:00,728 [major:19]	 SSH: '    setup_proxy_ssh_socket(cmdline)'
2022-10-21 10:47:00,728 [major:19]	 SSH: '  File "/usr/lib64/python3.10/site-packages/xpra/scripts/main.py", line 2611, in setup_proxy_ssh_socket'
2022-10-21 10:47:00,728 [major:19]	 SSH: '    os.symlink(auth_sock, agent_uuid_sockpath)'
2022-10-21 10:47:00,728 [major:19]	 SSH: "FileExistsError: [Errno 17] File exists: '/tmp/ssh-XXXX3ukZbV/agent.972302' -> '/run/user/5271/xpra/19/ssh/f8c056853a97afc83ef1b5df0b5f0b2ccf420426a84351d16c505d1abb205158'"
2022-10-21 10:47:02,714 [major:19]	enabled remote logging
```
But it manages to continue.
This manifests in all commands, including simple ones like `version`:
```
xpra version ssh://major/27
Connected (version 2.0, client OpenSSH_8.7)
Authentication (publickey) successful!
ssh server OS is 'linux-gnu'
paramiko SSH agent forwarding enabled
 SSH: 'Error setting up client ssh agent forwarding socket'
 SSH: 'Traceback (most recent call last):'
 SSH: '  File "/usr/lib64/python3.10/site-packages/xpra/scripts/main.py", line 2681, in run_proxy'
 SSH: '    setup_proxy_ssh_socket(cmdline)'
 SSH: '  File "/usr/lib64/python3.10/site-packages/xpra/scripts/main.py", line 2611, in setup_proxy_ssh_socket'
 SSH: '    os.symlink(auth_sock, agent_uuid_sockpath)'
 SSH: "FileExistsError: [Errno 17] File exists: '/tmp/ssh-XXXX9LQYQy/agent.973821' -> '/run/user/5271/xpra/27/ssh/f8c056853a97afc83ef1b5df0b5f0b2ccf420426a84351d16c505d1abb205158'"
5
SSH EOF on stderr of run-xpra
```
Server start:
`xpra start ssh://major/19 --attach=no --start-child=vterm`
Client start:
`xpra attach ssh://major/19 --border=blue,1`

Side issue: What's with the simplistic answer to `version`, just `5`, instead of a full version naming? Reports like this need to be very specific as to what's just lately installed.

**Comment by totaam** [comment]
> `FileExistsError`...

That's weird, it should have deleted the symlink if it already exists:
https://github.com/Xpra-org/xpra/blob/36fe7466dc8ffecd7e8a0b3939020986d6597285/xpra/scripts/main.py#L2638-L2647
(or just kept it if it was still valid)

> Side issue: What's with the simplistic answer to version, just 5, instead of a full version naming? Reports like this need to be very specific as to what's just lately installed.

As part of #3582, the client and server now limit the amount of information exposed.
This one should probably be reverted though.

**Comment by totaam** [comment]
@karlkleinpaste can you please check if those files really exist and are owned by your user?
`File exists: '/tmp/ssh-XXXX9LQYQy/agent.973821' -> '/run/user/5271/xpra/27/ssh/f8c056853a97afc83ef1b5df0b5f0b2ccf420426a84351d16c505d1abb205158'"`
Because I can't reproduce this and I can't trigger it when trying.

**Comment by karlkleinpaste** [comment]
That was from a previous run, so I started over, to be sure I had to-the-moment current filenames in action.
```
$ xp s major 19
2022-10-21 12:15:02,123 Connected (version 2.0, client OpenSSH_8.7)
2022-10-21 12:15:02,214 Authentication (publickey) successful!
2022-10-21 12:15:02,346 [major:19]	ssh server OS is 'linux-gnu'
2022-10-21 12:15:02,490 [major:19]	paramiko SSH agent forwarding enabled
2022-10-21 12:15:03,375 [major:19]	 SSH: 'Entering daemon mode; any further errors will be reported to:'
2022-10-21 12:15:03,375 [major:19]	 SSH: "  '/run/user/5271/xpra/19/server.log'"
2022-10-21 12:15:09,426 [major:19]	 SSH: 'Error setting up client ssh agent forwarding socket'
2022-10-21 12:15:09,426 [major:19]	 SSH: 'Traceback (most recent call last):'
2022-10-21 12:15:09,426 [major:19]	 SSH: '  File "/usr/lib64/python3.10/site-packages/xpra/scripts/main.py", line 2681, in run_proxy'
2022-10-21 12:15:09,426 [major:19]	 SSH: '    setup_proxy_ssh_socket(cmdline)'
2022-10-21 12:15:09,426 [major:19]	 SSH: '  File "/usr/lib64/python3.10/site-packages/xpra/scripts/main.py", line 2611, in setup_proxy_ssh_socket'
2022-10-21 12:15:09,426 [major:19]	 SSH: '    os.symlink(auth_sock, agent_uuid_sockpath)'
2022-10-21 12:15:09,426 [major:19]	 SSH: "FileExistsError: [Errno 17] File exists: '/tmp/ssh-XXXXzdbSzH/agent.1057755' -> '/run/user/5271/xpra/19/ssh/f8c056853a97afc83ef1b5df0b5f0b2ccf420426a84351d16c505d1abb205158'"
2022-10-21 12:15:09,434 [major:19]	SSH EOF on stderr of run-xpra
$ xp a major 19
2022-10-21 12:15:19,525 [major:19]	Xpra GTK3 X11 client version 5.0-r32078 (g490565040) beta 64-bit
2022-10-21 12:15:19,549 [major:19]	 running on Linux Fedora 35 ThirtyFive
2022-10-21 12:15:19,549 [major:19]	 window manager is 'compiz'
2022-10-21 12:15:20,371 [major:19]	GStreamer loaded
2022-10-21 12:15:20,503 [major:19]	created unix domain socket '/run/user/5271/xpra/clients/godiva.kleinpaste.org-555876'
2022-10-21 12:15:20,543 OpenGL_accelerate module loaded
2022-10-21 12:15:20,547 Using accelerated ArrayDatatype
2022-10-21 12:15:20,741 [major:19]	OpenGL enabled on 'NVIDIA GeForce RTX 2070 with Max-Q Design/PCIe/SSE2'
2022-10-21 12:15:20,763 Connected (version 2.0, client OpenSSH_8.7)
2022-10-21 12:15:20,849 Authentication (publickey) successful!
2022-10-21 12:15:20,959 [major:19]	ssh server OS is 'linux-gnu'
2022-10-21 12:15:21,086 [major:19]	paramiko SSH agent forwarding enabled
2022-10-21 12:15:21,132 [major:19]	 keyboard settings: rules=evdev, model=pc105, layout=us
2022-10-21 12:15:21,133 [major:19]	 desktop size is 5760x1080:
2022-10-21 12:15:21,134 [major:19]	  :0.0 (1023x191 mm - DPI: 143x144) workarea: 5760x1029 at    0x26  
2022-10-21 12:15:21,134 [major:19]	    PRO DP-3         1920x1080 at    0x0    (344x193 mm - DPI: 142x142) workarea: 1920x1029 at    0x26
2022-10-21 12:15:21,134 [major:19]	    AUO DP-2         1920x1080 at 1920x0    (344x193 mm - DPI: 142x142) workarea: 1920x1080 at 1920x0
2022-10-21 12:15:21,134 [major:19]	    PRO DP-1         1920x1080 at 3840x0    (344x193 mm - DPI: 142x142) workarea: 1920x1080 at 3840x0
2022-10-21 12:15:21,200 [major:19]	 SSH: 'Error setting up client ssh agent forwarding socket'
2022-10-21 12:15:21,200 [major:19]	 SSH: 'Traceback (most recent call last):'
2022-10-21 12:15:21,200 [major:19]	 SSH: '  File "/usr/lib64/python3.10/site-packages/xpra/scripts/main.py", line 2681, in run_proxy'
2022-10-21 12:15:21,200 [major:19]	 SSH: '    setup_proxy_ssh_socket(cmdline)'
2022-10-21 12:15:21,200 [major:19]	 SSH: '  File "/usr/lib64/python3.10/site-packages/xpra/scripts/main.py", line 2611, in setup_proxy_ssh_socket'
2022-10-21 12:15:21,200 [major:19]	 SSH: '    os.symlink(auth_sock, agent_uuid_sockpath)'
2022-10-21 12:15:21,200 [major:19]	 SSH: "FileExistsError: [Errno 17] File exists: '/tmp/ssh-XXXX9Ok1ht/agent.1058543' -> '/run/user/5271/xpra/19/ssh/f8c056853a97afc83ef1b5df0b5f0b2ccf420426a84351d16c505d1abb205158'"
2022-10-21 12:15:23,191 [major:19]	enabled remote logging
2022-10-21 12:15:23,191 [major:19]	Xpra X11 seamless server version 5.0
2022-10-21 12:15:23,191 [major:19]	 running on unknown
2022-10-21 12:15:23,195 [major:19]	Attached to xpra server at ssh://karl@major:7887/19
2022-10-21 12:15:23,195 [major:19]	 (press Control-C to detach)

2022-10-21 12:15:23,349 [major:19]	running, 1 window
2022-10-21 12:15:23,419 audio playback using pulseaudio device:
2022-10-21 12:15:23,419 audio playback  'Comet Lake PCH cAVS'
2022-10-21 12:15:23,938 audio playback using 'opus' audio codec
```
With this seen from the client, I go to the newly-opened terminal, where I find that the 1st `/tmp` symlink doesn't exist (transient during the `start` phase?), the 2nd does, and the `/run/user` socket does.
![screenshot1](https://user-images.githubusercontent.com/7548920/197242690-19bf8e9c-8657-407c-8139-5a275a31151f.png)

`xp` is a script that simplifies my invocations. It has a `-k` (kidding) option to show what it would do, without doing it.
```
$ xp -k s major 19
export XPRA_LOG_PREFIX=[major:19]	
exec xpra start ssh://major/19 --attach=no --start-child=vterm --border=blue,1
$ xp -k a major 19
export XPRA_LOG_PREFIX=[major:19]	
exec xpra attach ssh://major/19 --border=blue,1
```

**Comment by karlkleinpaste** [comment]
Obviously, in a hurry to write, I got somewhat confused about what's a symlink and what's a socket. But you can interpolate what I meant from the screenshot... :-|

**Comment by totaam** [comment]
Sorry it's taken so long to fix this.

The fix was obvious once you realize that a broken symlink does not exist but is a symlink:
```python
>>> import os.path
>>> os.symlink("/this-does-not-exist", "./link")
>>> os.path.exists("./link")
False
>>> os.path.islink("./link")
True
```
