### ISSUE TITLE
Windows build is broken

### ISSUE THREAD

**Issue by mschnelte** [Xpra-org/xpra#3673]
I downloaded the latest release 4.4.1 for windows and tried to start it but it does fail with "Initialization error".

1. download the 4.4.1 release for windows. 
2. Unzip it.
3.  run xpra.exe
 Result: A message box appears saying "Initialization error:".

If i run 
```
Xpra-Python3-x86_64_4.4.1-r0> .\Xpra-Launcher-Debug.exe

** (process:3284): WARNING **: 09:15:04.416: Failed to load shared library 'libpango-1.0-0.dll' referenced by the typelib: 'libpango-1.0-0.dll': The specified module could not be found.
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python3.10/site-packages/cx_Freeze/initscripts/__startup__.py", line 120, in run
  File "C:/msys64/mingw64/lib/python3.10/site-packages/cx_Freeze/initscripts/console.py", line 16, in run
  File "fs/bin/xpra_launcher", line 9, in <module>
  File "E:/xpra/xpra/client/gtk_base/client_launcher.py", line 25, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 672, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 632, in _load_backward_compatible
  File "C:/msys64/mingw64/lib/python3.10/site-packages/gi/importer.py", line 150, in load_module
  File "C:/msys64/mingw64/lib/python3.10/site-packages/gi/overrides/__init__.py", line 118, in load_overrides
  File "C:/msys64/mingw64/lib/python3.10/importlib/__init__.py", line 126, in import_module
  File "C:/msys64/mingw64/lib/python3.10/site-packages/gi/overrides/Pango.py", line 41, in <module>
  File "C:/msys64/mingw64/lib/python3.10/site-packages/gi/overrides/__init__.py", line 195, in override
AssertionError
```

I also downloaded \Xpra-Python3-x86_64_4.4-r0. Here the debug-launcher is starting up just fine.

System: Windows 10

**Comment by totaam** [comment]
Testing the latest builds - it seems that some MSYS2 package update has already fixed the problem, not sure which one, likely `cx_Freeze` or `python-gobject-introspection`.

So I am re-issuing the 4.4.1 builds, please re-download.
The filenames are identical - down the same git commit id, the contents are not due to the aforementioned library updates.
