### ISSUE TITLE
brotli test fails in github actions

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#3682]
As can be seen here:
https://github.com/Xpra-org/xpra/actions/runs/3394612172/jobs/5643392978#step:4:2328

```
======================================================================
ERROR: test_compress (__main__.TestBrotli)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/xpra/xpra/tests/unittests/unit/net/brotli_test.py", line 87, in test_compress
    self.tc(b"hello", b'\x0b\x02\x80hello\x03', l)
  File "/home/runner/work/xpra/xpra/tests/unittests/unit/net/brotli_test.py", line 54, in tc
    value = compress(v, level)
  File "xpra/net/brotli/compressor.pyx", line 106, in xpra.net.brotli.compressor.compress
ValueError: brotli compression failed: 0

======================================================================
ERROR: test_roundtrip (__main__.TestBrotli)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/xpra/xpra/tests/unittests/unit/net/brotli_test.py", line 113, in test_roundtrip
    c = self.tc(v, level=l)
  File "/home/runner/work/xpra/xpra/tests/unittests/unit/net/brotli_test.py", line 54, in tc
    value = compress(v, level)
  File "xpra/net/brotli/compressor.pyx", line 106, in xpra.net.brotli.compressor.compress
ValueError: brotli compression failed: 0
```

Running the same test in an Ubuntu 20.04 VM succeeds...
(and also on Fedora and every other platform I have tested on)

**Comment by totaam** [comment]
FWIW the same problem occurs with `unit/notifications/common_test.py`: it only fails as a github action..

So both will be disabled from now on and someone else can figure it out.

**Comment by totaam** [comment]
Could be related to #3829

**Comment by totaam** [comment]
This test is now running OK and has been re-enabled for a while: d1c8010626e2b98e17909aa5a5f05005bdaeaca8
