### ISSUE TITLE
xpra start --start=konsole

### ISSUE THREAD

**Issue by FoldingBike** [Xpra-org/xpra#3687]
**Describe the bug**
I created a Debian package according to https://github.com/Xpra-org/xpra/blob/master/docs/Build/Debian.md with version 4.4.2.
I installed also all prerequisites (except html5 interface).
Building and installing via dpkg was successful.
However, upon starting an xpra session with e.g.
`xpra start --start=konsole`

The session fails with:
```
2022-11-16 11:54:28,122 Warning: cannot enable SSH socket upgrades
2022-11-16 11:54:28,123  cannot import name 'nogssapi_context' from 'xpra.net.ssh' (/usr/lib/python3/dist-packages/x
pra/net/ssh/__init__.py)
2022-11-16 11:54:28,128 no uinput module (not usually needed)
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: server already running
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: server already running
xpra main error:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xpra/scripts/main.py", line 142, in main
    return run_mode(script_file, cmdline, err, options, args, mode, defaults)
  File "/usr/lib/python3/dist-packages/xpra/scripts/main.py", line 451, in run_mode
    return do_run_mode(script_file, cmdline, error_cb, options, args, mode, defaults)
  File "/usr/lib/python3/dist-packages/xpra/scripts/main.py", line 486, in do_run_mode
    return run_server(script_file, cmdline, error_cb, options, args, mode, defaults)
  File "/usr/lib/python3/dist-packages/xpra/scripts/main.py", line 1836, in run_server
    return do_run_server(script_file, cmdline, error_cb, options, args, mode, display, defaults)
  File "/usr/lib/python3/dist-packages/xpra/scripts/server.py", line 759, in do_run_server
    return _do_run_server(script_file, cmdline,
  File "/usr/lib/python3/dist-packages/xpra/scripts/server.py", line 1452, in _do_run_server
    app = make_server(clobber)
  File "/usr/lib/python3/dist-packages/xpra/scripts/server.py", line 311, in make_server
    from xpra.x11.server import XpraServer
  File "/usr/lib/python3/dist-packages/xpra/x11/server.py", line 34, in <module>
    from xpra.x11.x11_server_base import X11ServerBase
  File "/usr/lib/python3/dist-packages/xpra/x11/x11_server_base.py", line 16, in <module>
    from xpra.x11.x11_server_core import X11ServerCore, XTestPointerDevice
  File "/usr/lib/python3/dist-packages/xpra/x11/x11_server_core.py", line 30, in <module>
    from xpra.server.gtk_server_base import GTKServerBase
  File "/usr/lib/python3/dist-packages/xpra/server/gtk_server_base.py", line 25, in <module>
    from xpra.server.server_base import ServerBase
  File "/usr/lib/python3/dist-packages/xpra/server/server_base.py", line 12, in <module>
    from xpra.server.server_core import ServerCore
  File "/usr/lib/python3/dist-packages/xpra/server/server_core.py", line 43, in <module>
    from xpra.net.protocol import Protocol, CONNECTION_LOST, GIBBERISH, INVALID
ImportError: cannot import name 'Protocol' from 'xpra.net.protocol' (/usr/lib/python3/dist-packages/xpra/net/protocol/__
init__.py)
```

I also tried it with version 4.4 and the same happened. Importing the Protocol class with the python3 interpreter gives the same ImportError...
Currently I have no Idea what is the cause of this problem...

**To Reproduce**
1. `xpra start --start=konsole`

**System Information (please complete the following information):**
 -Debian Bullseye

**Comment by totaam** [comment]
This tells me that you are not building from the 4.4.x branch but from trunk:
```
ImportError: cannot import name 'Protocol' from 'xpra.net.protocol' (/usr/lib/python3/dist-packages/xpra/net/protocol/__init__.py)
```
`xpra.net.protocol.Protocol` used to live in `xpra/net/protocol.py` whereas now it lives below `xpra/net/protocol/`.
So my guess is that you have another version installed and it is causing conflicts.
Clean everything up and start again.
