### ISSUE TITLE
Add support for "attach" through the forward proxy (with authentication).

### ISSUE THREAD

**Issue by Laxhy** [Xpra-org/xpra#3704]
To connect from a secure site to an external xpra server, it is necessary to use a "forward proxy".

Add parameters for the possibility of proxy definition, similar to what is possible with java.

Thx

**Comment by totaam** [comment]
That's already possible and should even be auto-detected on platforms where `libproxy` is available: #2105

**Comment by Laxhy** [comment]
- problem with & soled, I'm ashamed :)
  - wss/ws - yes, intergration flow is "client (win, macos, lnux) -> forwarding proxy -> reverse proxy -> xpra server"
  - xpra_cmd (yes we use xpra_cmd for windows) copy-paste error, sorry

Thanks a lot

**Comment by Laxhy** [comment]
@rrthomas I have one more question. (It is possible that it is a problem on the side of the proxy server). But I will try to ask:

**Log from the client site:**

2022-12-08 09:28:33,488 Xpra GTK3 client version 4.4.3-r0 64-bit
2022-12-08 09:28:33,504  running on Microsoft Windows 2012ServerR2
2022-12-08 09:28:35,381 GStreamer version 1.20.4
2022-12-08 09:28:35,522 created named pipe 'Xpra\2184'
2022-12-08 09:28:35,662  cannot load dec_nvjpeg (nvjpeg decoder)
Traceback (most recent call last):
 File "E:/xpra/xpra/codecs/loader.py", line 81, in codec_import_check
 File "xpra/codecs/nvjpeg/decoder.pyx", line 28, in init xpra.codecs.nvjpeg.decoder
 File "E:/xpra/xpra/codecs/cuda_common/cuda_context.py", line 29, in <module>
 File "C:/msys64/mingw64/lib/python3.10/site-packages/pycuda-2022.2-py3.10-mingw_x86_64.egg/pycuda/driver.py", line 60, in <module>
 File "C:/msys64/mingw64/lib/python3.10/site-packages/pycuda-2022.2-py3.10-mingw_x86_64.egg/pycuda/driver.py", line 35, in _add_cuda_libdir_to_dll_path
 File "C:/msys64/mingw64/lib/python3.10/os.py", line 1118, in add_dll_directory
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Program Files\\Xpra\\bin\\bin'
2022-12-08 09:28:35,709 keyboard layout 'United States - English' : 'us' (0x409)
 Warning: failed to connect:
 **connection failed: Socket error: SOCKS5 proxy server sent invalid data**


**On the proxy server:**

2022/12/08 09:30:24 [info] 14805#14805: *1999 client sent invalid method while reading client request line, client: 10.79.1.1, server: , request: "^E^B^@^B"
2022/12/08 09:30:24 [info] 14805#14805: *1999 recv() failed (104: Connection reset by peer) while reading client request line, client: 10.79.1.1, server: , request: "^E^B^@^B"


It's probably an SSL problem, but I have no idea what to do with it :(

Thx

**Comment by rrthomas** [comment]
@Laxhy I think you tagged me by mistake here?

**Comment by Laxhy** [comment]
@rrthomas I'm so sorry, my mistake...

**Comment by totaam** [comment]
> `FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Program Files\\Xpra\\bin\\bin'`

This one is unrelated and this is news to me! Probably caused by 31f2d624a3a4bce4092c51c9878f925aaa0de4b7
