### ISSUE TITLE
`cannot load dec_nvjpeg (nvjpeg decoder)`, `\\bin\\bin` is not found

### ISSUE THREAD

**Issue by stdedos** [Xpra-org/xpra#3710]
**Describe the bug**

```
"Xpra-Python3-x86_64_5.0-r32364\xpra_cmd" shadow ssh://user@ip/1 --ssh="plink -ssh -agent" --modal-windows=no --desktop-scaling=1.25 --headerbar=off --title="@title@ on @@/@server-display@" --start="nohup systemd-inhibit --what=handle-lid-switch sleep 1d >/dev/null 2>&1 & inhibit_pid=$ ; xpra xwait ; kill -9 $inhibit_pid ; nohup systemd-inhibit --what=handle-lid-switch sleep 5m >/dev/null 2>&1 &" --key-shortcut=Shift+F2:toggle_pointer_grab --border=#FF5733,5 --microphone=off --speaker=off --webcam=no --pulseaudio=no

Note: GDK_WIN32_DISABLE_HIDPI is ignored due to preset
      DPI awareness settings in user settings or application
      manifest, DPI awareness is still enabled.2022-12-17 11:59:07,211 Xpra GTK3 client version 5.0-r32364 (g3e61ef1c8) beta 64-bit
2022-12-17 11:59:07,223  running on Microsoft Windows 10
2022-12-17 11:59:08,993 GStreamer version 1.20.4
2022-12-17 11:59:09,104 created named pipe 'Xpra\9924'
2022-12-17 11:59:09,211  cannot load dec_nvjpeg (nvjpeg decoder)
Traceback (most recent call last):
  File "E:/xpra/xpra/codecs/loader.py", line 81, in codec_import_check
  File "xpra/codecs/nvidia/nvjpeg/decoder.pyx", line 28, in init xpra.codecs.nvidia.nvjpeg.decoder
  File "E:/xpra/xpra/codecs/nvidia/cuda_context.py", line 31, in <module>
  File "C:/msys64/mingw64/lib/python3.10/site-packages/pycuda-2022.2-py3.10-mingw_x86_64.egg/pycuda/driver.py", line 60, in <module>
  File "C:/msys64/mingw64/lib/python3.10/site-packages/pycuda-2022.2-py3.10-mingw_x86_64.egg/pycuda/driver.py", line 35, in _add_cuda_libdir_to_dll_path
  File "C:/msys64/mingw64/lib/python3.10/os.py", line 1118, in add_dll_directory
FileNotFoundError: [WinError 2] Δεν είναι δυνατή η εύρεση του καθορισμένου αρχείου από το σύστημα: 'E:\\path\\xpra\\Xpra-Python3-x86_64_5.0-r32364\\bin\\bin'
```

**To Reproduce**
1. server command
2. client command
3. specific action to trigger the bug

**System Information (please complete the following information):**
- Server OS: Ubuntu 20.04.5 LTS
- Client OS: Microsoft Windows [Version 10.0.18363.836]
- Xpra Server Version (see above)
- Xpra Client Version (see above)

**Additional context**
Please see "reporting bugs" in the wiki section.

**Comment by totaam** [comment]
Already fixed in 919036d5929cf7de32775ccb199221008e212b44

**Comment by stdedos** [comment]
Good to know! It wasn't on the `Xpra-Python3-x86_64_5.0-r32364.zip` version, apparently 😃

**Comment by totaam** [comment]
> It wasn't on the `Xpra-Python3-x86_64_5.0-r32364.zip` version, apparently

No, and I am unable to make any new builds until the computer shop figures out what is wrong with my desktop PC - which is quite ill!
