### ISSUE TITLE
Could not start Xpra Launcher

### ISSUE THREAD

**Issue by MrLoyal** [Xpra-org/xpra#3715]
**Describe the bug**
When we run Xpra-Laucher-Debug.exe, it prints the following error log:

```
D:\Xpra-Client-PRD>.\Xpra-Launcher-Debug.exe
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = 'D:\Xpra-Client-PRD\Xpra-Launcher-Debug.exe'
  isolated = 0
  environment = 0
  user site = 1
  import site = 0
  sys._base_executable = 'D:\\Xpra-Client-PRD\\Xpra-Launcher-Debug.exe'
  sys.base_prefix = ''
  sys.base_exec_prefix = ''
  sys.platlibdir = 'lib'
  sys.executable = 'D:\\Xpra-Client-PRD\\Xpra-Launcher-Debug.exe'
  sys.prefix = ''
  sys.exec_prefix = ''
  sys.path = [
    'D:\\Xpra-Client-PRD\\lib\\library.zip',
    'D:\\Xpra-Client-PRD\\lib',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
Traceback (most recent call last):
  File "<frozen zipimport>", line 520, in _get_decompress_func
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1414, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1386, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1517, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1560, in _fill_cache
OSError: [WinError 87] The parameter is incorrect: 'D:\\Xpra-Client-PRD\\lib'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<frozen zipimport>", line 568, in _get_data
  File "<frozen zipimport>", line 523, in _get_decompress_func
zipimport.ZipImportError: can't decompress data; zlib not available
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<frozen zipimport>", line 241, in load_module
  File "<frozen zipimport>", line 709, in _get_module_code
  File "<frozen zipimport>", line 570, in _get_data
zipimport.ZipImportError: can't decompress data; zlib not available
```

**System Information (please complete the following information):**
 - Server OS: It is not important here because the connection is not made yet
 - Client OS: Windows 10
 - Xpra Server Version [e.g. 4.2.3]
 - Xpra Client Version 1.4.2.2

**Additional context**
We can successfully run the program on many laptops, and then we copy it to another one and error happened only on that one only.

What we have tried is set the environment variable PYTHONHOME to point to Python installation directory but the issue stays the same.

**Comment by totaam** [comment]
> `Xpra Client Version 1.4.2.2`

This is not a version we have ever shipped.
Please try the very latest version available instead.

My guess is that your system has another `zlib.dll` available on the `%PATH%` and this causes a conflict with the one shipped with xpra.
Do not modify `PYTHONHOME` as this will only cause problems.

**Comment by totaam** [comment]
> The actual version is 4.2.2

Current version is 4.4.3, try that instead.

> I will check the `zlib.dll` on the `%PATH%`

Could be any DLL, not just this one.
Try running with a clean `%PATH%` to confirm.

**Comment by MrLoyal** [comment]
Could not get it work with even with a clean Path but working well after a Windows re-installation.
Thank you @totaam for your support!
