### ISSUE TITLE
Paste from windows not working in 3.1.3 client (server 3.1.2): NameError: name 'ellipsizer' is not defined

### ISSUE THREAD

**Issue by puremourning** [Xpra-org/xpra#3727]
Hi there,

I recently updated my MS WIndows Xpra client from 2.* to 3.1.3 and have noticed that pasting from the windows clipboard is timing out, then failing (eventually pasting something from one of the X selections).

Steps to reproduce:

1. server `xpra start :1011 --start=xterm`
2. client `xpra_cmd attach ssh://user@hostname/:1011`
3. in windows open notepad and type 'test'. copy 'test' text to clipboard with "ctrl-c" 
5. in the xterm, press middle click

expect: paste "test" to the xterm
actual: xterm hangs for a few seconds, nothing is pasted.

# Configuration

[xpra_bug_client_data.zip](https://github.com/Xpra-org/xpra/files/10361753/xpra_bug_client_data.zip)

# Logs

Client:

```
C:\Program Files\Xpra>Xpra_cmd.exe attach ssh://benj@ukfd-ltp4l/:1011
2023-01-06 16:52:54,055 Xpra GTK3 client version 3.1.3-r0 64-bit
2023-01-06 16:52:54,105  running on Microsoft Windows 10
2023-01-06 16:52:54,762 GStreamer version 1.20.2 for Python 3.9.12 64-bit
2023-01-06 16:52:54,962 keyboard layout code 0x809
2023-01-06 16:52:54,964 identified as 'United States - English' : gb
2023-01-06 16:52:55,222 Connected (version 2.0, client OpenSSH_7.4)
2023-01-06 16:52:55,345 Authentication (publickey) successful!
2023-01-06 16:52:55,713  keyboard settings: layout=US
2023-01-06 16:52:55,718  desktop size is 4480x1440 with 1 screen:
2023-01-06 16:52:55,722   Default (1185x381 mm - DPI: 96x96) workarea: 4417x1440
2023-01-06 16:52:55,722     (Standard monitor types) Generic Non-PnP Monitor 2560x1440 at 1920x0 (590x330 mm - DPI: 110x110) workarea: 2497x1440
2023-01-06 16:52:55,723     (Standard monitor types) Generic Non-PnP Monitor 1920x1080 at 0x360 (470x260 mm - DPI: 103x105) workarea: 1858x1080
2023-01-06 16:52:55,836 cannot query network interface:
2023-01-06 16:52:55,840  module 'comtypes.gen.WbemScripting' has no attribute 'ISWbemLocator'
2023-01-06 16:52:56,483 enabled remote logging
2023-01-06 16:52:56,486 Xpra GTK2 X11 server version 3.1.2-r25 64-bit
2023-01-06 16:52:56,489  running on Linux RedHatEnterpriseServer 7.9 Maipo
2023-01-06 16:52:56,495 Attached to ssh://benj@ukfd-ltp4l/1011
2023-01-06 16:52:56,497  (press Control-C to detach)


(Xpra_cmd.exe:5216): GLib-GIO-WARNING **: 16:52:58.557: Unexpectedly, UWP app `microsoft.windowscommunicationsapps_16005.11629.20316.0_x64__8wekyb3d8bbwe' (AUMId `microsoft.windowscommunicationsapps_8wekyb3d8bbwe!microsoft.windowslive.mail') supports 1 extensions but has no verbs

(Xpra_cmd.exe:5216): GLib-GIO-WARNING **: 16:52:58.582: Unexpectedly, UWP app `microsoft.windowscommunicationsapps_16005.11629.20316.0_x64__8wekyb3d8bbwe' (AUMId `microsoft.windowscommunicationsapps_8wekyb3d8bbwe!microsoft.windowslive.calendar') supports 2 extensions but has no verbs
2023-01-06 16:53:08,135 unknown string message: 0xc0be / 0x52 / 0x1e7
2023-01-06 16:53:08,145 unknown string message: 0xc0be / 0x50 / 0x0
Traceback (most recent call last):
  File "E:/xpra/src/xpra/client/mixins/clipboard.py", line 218, in _process_clipboard_packet
  File "E:/xpra/src/xpra/clipboard/clipboard_core.py", line 526, in process_clipboard_packet
  File "E:/xpra/src/xpra/clipboard/clipboard_core.py", line 435, in _process_clipboard_request
  File "E:/xpra/src/xpra/platform/win32/clipboard.py", line 209, in get_contents
  File "E:/xpra/src/xpra/platform/win32/clipboard.py", line 284, in get_clipboard_text
  File "E:/xpra/src/xpra/platform/win32/clipboard.py", line 159, in with_clipboard_lock
  File "E:/xpra/src/xpra/platform/win32/clipboard.py", line 278, in get_text
NameError: name 'ellipsizer' is not defined
Traceback (most recent call last):
  File "E:/xpra/src/xpra/client/mixins/clipboard.py", line 218, in _process_clipboard_packet
  File "E:/xpra/src/xpra/clipboard/clipboard_core.py", line 526, in process_clipboard_packet
  File "E:/xpra/src/xpra/clipboard/clipboard_core.py", line 435, in _process_clipboard_request
  File "E:/xpra/src/xpra/platform/win32/clipboard.py", line 209, in get_contents
  File "E:/xpra/src/xpra/platform/win32/clipboard.py", line 284, in get_clipboard_text
  File "E:/xpra/src/xpra/platform/win32/clipboard.py", line 159, in with_clipboard_lock
  File "E:/xpra/src/xpra/platform/win32/clipboard.py", line 278, in get_text
NameError: name 'ellipsizer' is not defined
Traceback (most recent call last):
  File "E:/xpra/src/xpra/client/mixins/clipboard.py", line 218, in _process_clipboard_packet
  File "E:/xpra/src/xpra/clipboard/clipboard_core.py", line 526, in process_clipboard_packet
  File "E:/xpra/src/xpra/clipboard/clipboard_core.py", line 435, in _process_clipboard_request
  File "E:/xpra/src/xpra/platform/win32/clipboard.py", line 209, in get_contents
  File "E:/xpra/src/xpra/platform/win32/clipboard.py", line 284, in get_clipboard_text
  File "E:/xpra/src/xpra/platform/win32/clipboard.py", line 159, in with_clipboard_lock
  File "E:/xpra/src/xpra/platform/win32/clipboard.py", line 278, in get_text
NameError: name 'ellipsizer' is not defined
```

The NameErorr occurs when attempting to paste.  On the server side i see:

Server (full log https://gist.github.com/puremourning/e557bd89ede429ed642fb9e8735f8877)

```
ESC[33m2023-01-06 16:53:11,800 Warning: remote clipboard request timed outESC[0m
ESC[33m2023-01-06 16:53:11,800  request id 0, selection=PRIMARY, target=UTF8_STRINGESC[0m
ESC[33m2023-01-06 16:53:13,303 Warning: remote clipboard request timed outESC[0m
ESC[33m2023-01-06 16:53:13,303  request id 1, selection=PRIMARY, target=TEXTESC[0m
ESC[33m2023-01-06 16:53:14,812 Warning: remote clipboard request timed outESC[0m
ESC[33m2023-01-06 16:53:14,812  request id 3, selection=PRIMARY, target=STRINGESC[0m
2023-01-06 16:53:22,198 client   1 @28.028 unknown string message: 0xc0be / 0x52 / 0x1e8ESC[0m
2023-01-06 16:53:22,204 client   1 @28.035 unknown string message: 0xc0be / 0x50 / 0x0ESC[0m

```

# Versions

Server

```
$ xpra version
6.1.2-r25

$ lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: RedHatEnterpriseServer
Description:    Red Hat Enterprise Linux Server release 7.9 (Maipo)
Release:        7.9
Codename:       Maipo
```

And the following client version:

```
2023-01-06 16:47:22,966 Xpra GTK3 client version 3.1.3-r0 64-bit
2023-01-06 16:47:23,017  running on Microsoft Windows 10
2023-01-06 16:47:24,088 GStreamer version 1.20.2 for Python 3.9.12 64-bit
2023-01-06 16:47:25,802 keyboard layout code 0x809
2023-01-06 16:47:25,803 identified as 'United States - English' : gb
2023-01-06 16:47:26,734 Connected (version 2.0, client OpenSSH_7.4)
2023-01-06 16:47:26,961 Authentication (publickey) successful!
```

**Comment by totaam** [comment]
Please try the current version instead. 4.4.3 is the latest.

**Comment by puremourning** [comment]
Sorry i can't because Xpra 4 is not supported on RHEL 7

**Comment by totaam** [comment]
Then you can try to apply the commit above or wait for an eventual newer release.

**Comment by totaam** [comment]
@puremourning I have uploaded some 3.1.4 RC builds in the beta area which should fix many problems, including this one: https://xpra.org/beta/windows/
(please close this ticket if this works for you)

**Comment by totaam** [comment]
This should be fixed in the latest releases.
