### ISSUE TITLE
Error during startup

### ISSUE THREAD

**Issue by MarkoSchuetz** [Xpra-org/xpra#3774]
**Describe the bug**
I see the following in the log file:
```
2023-02-28 17:43:22,465 XError: <class 'TypeError'>, XTestPointerDevice.move_pointer() missing 1 required positional argument:
 'props'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/xpra/x11/x11_server_base.py", line 202, in verify_uinput_pointer_device
    xtest.move_pointer(0, ox, oy)
TypeError: XTestPointerDevice.move_pointer() missing 1 required positional argument: 'props'
xpra main error:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/xpra/scripts/main.py", line 139, in main
    return run_mode(script_file, cmdline, err, options, args, mode, defaults)
  File "/usr/lib/python3.10/site-packages/xpra/scripts/main.py", line 440, in run_mode
    return do_run_mode(script_file, cmdline, error_cb, options, args, mode, defaults)
  File "/usr/lib/python3.10/site-packages/xpra/scripts/main.py", line 475, in do_run_mode
    return run_server(script_file, cmdline, error_cb, options, args, mode, defaults)
  File "/usr/lib/python3.10/site-packages/xpra/scripts/main.py", line 1854, in run_server
    return do_run_server(script_file, cmdline, error_cb, options, args, mode, display, defaults)
  File "/usr/lib/python3.10/site-packages/xpra/scripts/server.py", line 713, in do_run_server
    return _do_run_server(script_file, cmdline,
  File "/usr/lib/python3.10/site-packages/xpra/scripts/server.py", line 1413, in _do_run_server
    app.init_virtual_devices(devices)
  File "/usr/lib/python3.10/site-packages/xpra/x11/x11_server_base.py", line 185, in init_virtual_devices
    self.verify_uinput_pointer_device()
  File "/usr/lib/python3.10/site-packages/xpra/x11/x11_server_base.py", line 204, in verify_uinput_pointer_device
    self.pointer_device.move_pointer(0, nx, ny)
TypeError: UInputPointerDevice.move_pointer() missing 1 required positional argument: 'props'

```

**To Reproduce**
1. `xpra start --sharing=yes  --html=on --bind-tcp=192.168.xxx.xxx:14501 --start-via-proxy=no --start='zathura Some.pdf'`
2. no client needed
3. mo further action needed

**System Information (please complete the following information):**
 - Linux 6.1.12-1-MANJARO
 - n/a
 - xpra v5.0-r32780 (g3f3a42c32) beta

**Comment by totaam** [comment]
Thanks, fixed in the commit above.
Why are you using `uinput` devices? This should never be the default input device backend.

**Comment by MarkoSchuetz** [comment]
I am getting this after the change:
```
2023-03-01 09:33:31,688 XError: <class 'TypeError'>, XTestPointerDevice.move_pointer() missing 2 required positional arguments: 'y' and 'props'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/xpra/x11/x11_server_base.py", line 202, in verify_uinput_pointer_device
    xtest.move_pointer(ox, oy)
TypeError: XTestPointerDevice.move_pointer() missing 2 required positional arguments: 'y' and 'props'
xpra main error:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/xpra/scripts/main.py", line 139, in main
    return run_mode(script_file, cmdline, err, options, args, mode, defaults)
  File "/usr/lib/python3.10/site-packages/xpra/scripts/main.py", line 440, in run_mode
    return do_run_mode(script_file, cmdline, error_cb, options, args, mode, defaults)
  File "/usr/lib/python3.10/site-packages/xpra/scripts/main.py", line 475, in do_run_mode
    return run_server(script_file, cmdline, error_cb, options, args, mode, defaults)
  File "/usr/lib/python3.10/site-packages/xpra/scripts/main.py", line 1854, in run_server
    return do_run_server(script_file, cmdline, error_cb, options, args, mode, display, defaults)
  File "/usr/lib/python3.10/site-packages/xpra/scripts/server.py", line 713, in do_run_server
    return _do_run_server(script_file, cmdline,
  File "/usr/lib/python3.10/site-packages/xpra/scripts/server.py", line 1413, in _do_run_server
    app.init_virtual_devices(devices)
  File "/usr/lib/python3.10/site-packages/xpra/x11/x11_server_base.py", line 185, in init_virtual_devices
    self.verify_uinput_pointer_device()
  File "/usr/lib/python3.10/site-packages/xpra/x11/x11_server_base.py", line 204, in verify_uinput_pointer_device
    self.pointer_device.move_pointer(nx, ny)
TypeError: UInputPointerDevice.move_pointer() missing 1 required positional argument: 'props'
```

**Comment by totaam** [comment]
@MarkoSchuetz my bad, the commit above should fix that.
But again, totally untested - why are you using `uinput` exactly?

**Comment by MarkoSchuetz** [comment]
> why are you using `uinput` exactly

I'm actually not quite sure why this is being used. For a while I experimented with using an Android tablet as input device. Maybe I have some leftovers still running...
