### ISSUE TITLE
LDAP authentication issue

### ISSUE THREAD

**Issue by walakee** [Xpra-org/xpra#3781]
**Describe the bug**
I can't seem to be able to get LDAP authentication working against the ForumSYS LDAP test server: https://www.forumsys.com/2022/05/10/online-ldap-test-server/

**To Reproduce**
1. server command

```
/usr/bin/xpra proxy :14500 --daemon=no "--tcp-auth=ldap,host=ldap.forumsys.com,port=389,username_format=uid=%username,dc=example,dc=com" --bind-tcp=0.0.0.0:14500 --bind=none --debug=auth
```

3. client command

I'm using the HTML5 client to connect via http://192.168.56.116:14500/connect.html

4. specific action to trigger the bug

I'm entering the test credentials Username: riemann / Password: password

**System Information (please complete the following information):**
 - Server OS: CentOS Linux release 7.9.2009 (Core)
 - Client OS: MacOS Catalina 10.15.7 / Brave [Version 1.48.171 Chromium: 110.0.5481.177 (Official Build) (x86_64)](https://brave.com/latest/)
 - Xpra Server Version: xpra v3.1.3-r0
 - Xpra Client Version: xpra-html5 v5.1-1.r12.el7

**Additional context**

Testing the access with ldapsearch works OK...

```
[root@iqlcen7vm ~]# ldapsearch -x -h ldap.forumsys.com -p 389 -D "cn=read-only-admin,dc=example,dc=com" -b "dc=example,dc=com" -s sub 'uid=riemann' -w "password"
# extended LDIF
#
# LDAPv3
# base <dc=example,dc=com> with scope subtree
# filter: uid=riemann
# requesting: ALL
#

# riemann, example.com
dn: uid=riemann,dc=example,dc=com
objectClass: inetOrgPerson
objectClass: organizationalPerson
objectClass: person
objectClass: top
cn: Bernhard Riemann
sn: Riemann
uid: riemann
mail: riemann@ldap.forumsys.com

# search result
search: 2
result: 0 Success

# numResponses: 2
# numEntries: 1
[root@iqlcen7vm ~]# 
```

Testing the access from python works OK...

```
[root@iqlcen7vm ~]# python
Python 2.7.5 (default, Jun 28 2022, 15:30:04) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ldap
>>> conn = ldap.initialize('ldap://ldap.forumsys.com')
>>> conn.simple_bind_s('uid=riemann,dc=example,dc=com', 'password')
(97, [], 1, [])
>>> conn.unbind_s()
>>> 
[root@iqlcen7vm ~]# 
```

The Xpra server logs are as follows...

```
[root@iqlcen7vm ~]# /usr/bin/xpra proxy :14500 --daemon=no "--tcp-auth=ldap,host=ldap.forumsys.com,port=389,username_format=uid=%username,dc=example,dc=com" --bind-tcp=0.0.0.0:14500 --bind=none --debug=auth
2023-03-02 21:49:24,825 created tcp socket '0.0.0.0:14500'
2023-03-02 21:49:24,849 Warning: missing sound module
2023-03-02 21:49:24,885 serving html content from '/usr/share/xpra/www'
2023-03-02 21:49:24,885 get_auth_modules(local-auth, [], {..})
2023-03-02 21:49:24,885 get_auth_modules(tcp, ['ldap,host=ldap.forumsys.com,port=389,username_format=uid=%username,dc=example,dc=com'], {..})
2023-03-02 21:49:24,885 get_auth_module(tcp, ldap,host=ldap.forumsys.com,port=389,username_format=uid=%username,dc=example,dc=com, {..})
2023-03-02 21:49:24,885 auth module name for 'ldap': 'xpra.server.auth.ldap_auth'
2023-03-02 21:49:24,886 auth module for 'ldap': <module 'xpra.server.auth.ldap_auth' from '/usr/lib64/python2.7/site-packages/xpra/server/auth/ldap_auth.pyc'>
2023-03-02 21:49:24,886 get_auth_modules(ws, [], {..})
2023-03-02 21:49:24,886 get_auth_modules(wss, [], {..})
2023-03-02 21:49:24,887 get_auth_modules(ssl, [], {..})
2023-03-02 21:49:24,887 get_auth_modules(ssh, [], {..})
2023-03-02 21:49:24,887 get_auth_modules(rfb, [], {..})
2023-03-02 21:49:24,887 get_auth_modules(vsock, [], {..})
2023-03-02 21:49:24,887 get_auth_modules(udp, [], {..})
2023-03-02 21:49:24,887 init_auth(..) auth={'udp': None, 'rfb': None, 'vsock': None, 'tcp': (('ldap', <class 'xpra.server.auth.ldap_auth.Authenticator'>, {'exec_cwd': '/root', 'username_format': 'uid=%username', 'host': 'ldap.forumsys.com', 'port': '389', 'dc': 'com'}),), 'ssl': None, 'wss': None, 'ws': None, 'ssh': None, 'unix-domain': None}
2023-03-02 21:49:24,911 xpra is ready.
2023-03-02 21:49:24,912 xpra proxy version 3.1.3-r0 64-bit
2023-03-02 21:49:24,912  uid=0 (root), gid=0 (root)
2023-03-02 21:49:24,912  running with pid 15850 on Linux CentOS Linux 7.9.2009 Core
2023-03-02 21:49:32,876 Error sending '/usr/share/xpra/www/Sessions':
2023-03-02 21:49:32,876  [Errno 2] No such file or directory
2023-03-02 21:49:32,880 Error sending '/usr/share/xpra/www/Menu':
2023-03-02 21:49:32,881  [Errno 2] No such file or directory
2023-03-02 21:49:32,885 Error sending '/usr/share/xpra/www/DesktopMenu':
2023-03-02 21:49:32,885  [Errno 2] No such file or directory
2023-03-02 21:49:32,900 Error sending '/usr/share/xpra/www/Displays':
2023-03-02 21:49:32,900  [Errno 2] No such file or directory
2023-03-02 21:49:43,248 socktype=ws, encryption=, keyfile=
2023-03-02 21:49:43,567 make_authenticators('tcp', 'riemann', ws socket: 192.168.56.116:14500 <- 192.168.56.1:63001)
2023-03-02 21:49:43,568 creating authenticators ('ldap', <class 'xpra.server.auth.ldap_auth.Authenticator'>, {'exec_cwd': '/root', 'username_format': 'uid=%username', 'host': 'ldap.forumsys.com', 'port': '389', 'dc': 'com'}) for tcp, with username=riemann, connection=ws socket: 192.168.56.116:14500 <- 192.168.56.1:63001
2023-03-02 21:49:43,568 Warning: unused keyword arguments for ldap authentication:
2023-03-02 21:49:43,568  {'dc': 'com'}
2023-03-02 21:49:43,568 ldap auth: host=ldap.forumsys.com, port=389, tls=False, username_format=uid=%username, cacert=None, encoding=utf-8
2023-03-02 21:49:43,568 authenticator 0: ldap(riemann, {'connection': ws socket: 192.168.56.116:14500 <- 192.168.56.1:63001, 'dc': 'com', 'exec_cwd': '/root', 'host': 'ldap.forumsys.com', 'username_format': 'uid=%username', 'socket-dirs': ['/run/user/$UID/xpra', '/run/xpra', '~/.xpra'], 'port': '389'})=ldap
2023-03-02 21:49:43,568 processing authentication with (ldap,), remaining=(ldap,), response=None, client_salt='', digest_modes=['hmac', 'hmac+md5', 'xor', 'keycloak', 'hmac+md5', 'hmac+sha256', 'hmac+sha1', 'hmac+sha512', 'hmac+sha384', 'hmac+sha512/256', 'hmac+sha512/224'], salt_digest_modes=['hmac', 'hmac+md5', 'xor', 'keycloak', 'hmac+md5', 'hmac+sha256', 'hmac+sha1', 'hmac+sha512', 'hmac+sha384', 'hmac+sha512/256', 'hmac+sha512/224']
2023-03-02 21:49:43,568 authenticator[0]=ldap, requires-challenge=True, challenge-sent=False
2023-03-02 21:49:43,568 get_challenge(['hmac', 'hmac+md5', 'xor', 'keycloak', 'hmac+md5', 'hmac+sha256', 'hmac+sha1', 'hmac+sha512', 'hmac+sha384', 'hmac+sha512/256', 'hmac+sha512/224'])= 6c571551bc82259e5ab82c15c3e3f8712da7c874ce725b145cb7f254216725e933ed1575fe7995d312ccefacf0c8d8b5601629aabc5de6b070315398e82be7b1, xor
2023-03-02 21:49:43,568 Authentication required by ldap authenticator module 1
2023-03-02 21:49:43,568  sending challenge for username 'riemann' using xor digest
2023-03-02 21:49:43,575 processing authentication with (ldap,), remaining=(ldap,), response='I\x04\x11\x11AZCU', client_salt='\xd7\xad\xaa)[\x1a\xaa\xc0\t\xcc\xde\xe7\x11\x05\xaf\x9e\x12\\\xf1e\x19b\xa5\xc0q\x15F\xb8\xa7\x06h\xb6', digest_modes=['hmac', 'hmac+md5', 'xor', 'keycloak', 'hmac+md5', 'hmac+sha256', 'hmac+sha1', 'hmac+sha512', 'hmac+sha384', 'hmac+sha512/256', 'hmac+sha512/224'], salt_digest_modes=['hmac', 'hmac+md5', 'xor', 'keycloak', 'hmac+md5', 'hmac+sha256', 'hmac+sha1', 'hmac+sha512', 'hmac+sha384', 'hmac+sha512/256', 'hmac+sha512/224']
2023-03-02 21:49:43,575 authenticator[0]=ldap, requires-challenge=True, challenge-sent=True
2023-03-02 21:49:43,575 combined salt(6c571551bc82259e5ab82c15c3e3f8712da7c874ce725b145cb7f254216725e933ed1575fe7995d312ccefacf0c8d8b5601629aabc5de6b070315398e82be7b1, d7adaa295b1aaac009ccdee71105af9e125cf1651962a5c0711546b8a70668b6)=3965626236353131653761666264316331303664643262393433353739353965643335326535316366363137356164363261376235623631373136386561373531643335386437396537373733323439333437663131663863343730383636303965363063356364343363613562623031636230326536356431356365346136
2023-03-02 21:49:43,575 authenticate_check(*******************, '\xd7\xad\xaa)[\x1a\xaa\xc0\t\xcc\xde\xe7\x11\x05\xaf\x9e\x12\\\xf1e\x19b\xa5\xc0q\x15F\xb8\xa7\x06h\xb6') response salt='9ebb6511e7afbd1c106dd2b94357959ed352e51cf6175ad62a7b5b617168ea751d358d79e7773249347f11f8c47086609e60c5cd43ca5bb01cb02e65d15ce4a6'
2023-03-02 21:49:43,575 check(********)
*** <ldap.ldapobject.SimpleLDAPObject instance at 0x7fc2184ce1b8> ldap://ldap.forumsys.com:389 - SimpleLDAPObject.set_option
((17, 3), {})
*** <ldap.ldapobject.SimpleLDAPObject instance at 0x7fc2184ce1b8> ldap://ldap.forumsys.com:389 - SimpleLDAPObject.set_option
((17, 3), {})
*** <ldap.ldapobject.SimpleLDAPObject instance at 0x7fc2184ce1b8> ldap://ldap.forumsys.com:389 - SimpleLDAPObject.set_option
((8, 0), {})
2023-03-02 21:49:43,587 ldap.open(ldap://ldap.forumsys.com:389)=<ldap.ldapobject.SimpleLDAPObject instance at 0x7fc2184ce1b8>
2023-03-02 21:49:43,587 user=uid=riemann
2023-03-02 21:49:43,587 ldap encoded password as utf-8
*** <ldap.ldapobject.SimpleLDAPObject instance at 0x7fc2184ce1b8> ldap://ldap.forumsys.com:389 - SimpleLDAPObject.simple_bind
(('uid=riemann', 'password', None, None), {})
*** <ldap.ldapobject.SimpleLDAPObject instance at 0x7fc2184ce1b8> ldap://ldap.forumsys.com:389 - SimpleLDAPObject.result4
((1, 1, -1, 0, 0, 0), {})
2023-03-02 21:49:43,825 check(..)
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/xpra/server/auth/ldap_auth.py", line 103, in check
    v = conn.simple_bind_s(user, password)
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 208, in simple_bind_s
    resp_type, resp_data, resp_msgid, resp_ctrls = self.result3(msgid,all=1,timeout=self.timeout)
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 469, in result3
    resp_ctrl_classes=resp_ctrl_classes
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 476, in result4
    ldap_result = self._ldap_call(self._l.result4,msgid,all,timeout,add_ctrls,add_intermediates,add_extop)
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 99, in _ldap_call
    result = func(*args,**kwargs)
INVALID_CREDENTIALS: {'desc': 'Invalid credentials'}
2023-03-02 21:49:43,826 authenticate_check(..)=False
2023-03-02 21:49:43,827 Warning: authentication failed
2023-03-02 21:49:43,827  authentication failed
2023-03-02 21:49:44,829 Disconnecting client ('192.168.56.1', 63001):
2023-03-02 21:49:44,830  authentication failed
2023-03-02 21:49:45,025 Error sending '/usr/share/xpra/www/Sessions':
2023-03-02 21:49:45,025  [Errno 2] No such file or directory
2023-03-02 21:49:45,029 Error sending '/usr/share/xpra/www/Menu':
2023-03-02 21:49:45,029  [Errno 2] No such file or directory
2023-03-02 21:49:45,034 Error sending '/usr/share/xpra/www/DesktopMenu':
2023-03-02 21:49:45,035  [Errno 2] No such file or directory
2023-03-02 21:49:45,040 Error sending '/usr/share/xpra/www/Displays':
2023-03-02 21:49:45,040  [Errno 2] No such file or directory
^C
2023-03-02 21:50:01,504 got signal SIGINT
2023-03-02 21:50:01,504 exiting
2023-03-02 21:50:01,605 closing tcp socket '0.0.0.0:14500'
[root@iqlcen7vm ~]#
```

I have tried to understand how to set up Xpra for LDAP authentication from https://xpra.org/trac/ticket/1791 , but I'm sure I am missing something.

Any help would be greatly appreciated.

Many thanks,
Walakee

**Comment by totaam** [comment]
FYI: This module has not been used much - at least by me, since #1791 was implemented.

> `user=uid=riemann`

The problem comes from your `username_format=uid=%username,dc=example,dc=com"` option getting split by the parser into separate options. We need a smarter option parser.

Until then, the commits above allow you to set the default `username` option using an env var:
```shell
xpra --env="XPRA_LDAP_USERNAME_FORMAT=id=%username,dc=example,dc=com" ...
```

**Comment by walakee** [comment]
Many thanks for the instant response / action. I will go ahead and try to test it.

Just one question: if the authentication is successful via LDAP, but I don't have a local user called _**riemann**_ _(used of the LDAP authentication)_, what user will the session be started with? Is there a config option for a default local user to use in such case?

Many thanks,
Walakee

**Comment by walakee** [comment]
I have applied the changes as follows...

```
[root@iqlcen7vm auth]# pwd
/usr/lib64/python2.7/site-packages/xpra/server/auth
[root@iqlcen7vm auth]# ls -la ldap_auth*
-rw-r--r--. 1 root root 6197 Jun 26  2022 ldap_auth_factory.py
-rw-r--r--. 1 root root 6650 Jun 26  2022 ldap_auth_factory.pyc
-rw-r--r--. 1 root root 6558 Jun 26  2022 ldap_auth_factory.pyo
-rw-r--r--. 1 root root 6375 Mar  6 21:11 ldap_auth.py
-rw-r--r--. 1 root root 6213 Mar  6 21:12 ldap_auth.pyc
[root@iqlcen7vm auth]# diff ldap_auth_factory.py ldap_auth.py
21a22
> LDAP_USERNAME_FORMAT = os.environ.get("XPRA_LDAP_USERNAME_FORMAT", "cn=%username, o=%domain")
38c39,40
<         self.username_format = kwargs.pop("username_format", "cn=%username, o=%domain")
---
>         self.username_format = kwargs.pop("username_format", LDAP_USERNAME_FORMAT)
>         #self.username_format = kwargs.pop("username_format", "cn=%username, o=%domain")
[root@iqlcen7vm auth]#
```

Then I have set the XPRA_LDAP_USERNAME_FORMAT environment variable...

```
[root@iqlcen7vm site-packages]# XPRA_LDAP_USERNAME_FORMAT="uid=%username,dc=example,dc=com"
[root@iqlcen7vm site-packages]# export XPRA_LDAP_USERNAME_FORMAT
[root@iqlcen7vm site-packages]# echo ${XPRA_LDAP_USERNAME_FORMAT}
uid=%username,dc=example,dc=com
[root@iqlcen7vm site-packages]#
```

Then I have tested the authentication

```
[root@iqlcen7vm site-packages]# pwd 
/usr/lib64/python2.7/site-packages
[root@iqlcen7vm site-packages]# python xpra/server/auth/ldap_auth.py riemann password ldap.forumsys.com 389
success: True
[root@iqlcen7vm site-packages]#
```

*SUCCESS!!!*

Then I have tested Xpra, with the username _*riemann*_

```
[root@iqlcen7vm site-packages]# /usr/bin/xpra proxy :14500 --daemon=no "--tcp-auth=ldap,host=ldap.forumsys.com,port=389" --bind-tcp=0.0.0.0:14500 --bind=none --debug=auth
2023-03-06 21:27:24,721 created tcp socket '0.0.0.0:14500'
2023-03-06 21:27:24,769 Warning: missing sound module
2023-03-06 21:27:24,817 serving html content from '/usr/share/xpra/www'
2023-03-06 21:27:24,817 get_auth_modules(local-auth, [], {..})
2023-03-06 21:27:24,817 get_auth_modules(tcp, ['ldap,host=ldap.forumsys.com,port=389'], {..})
2023-03-06 21:27:24,817 get_auth_module(tcp, ldap,host=ldap.forumsys.com,port=389, {..})
2023-03-06 21:27:24,817 auth module name for 'ldap': 'xpra.server.auth.ldap_auth'
2023-03-06 21:27:24,818 auth module for 'ldap': <module 'xpra.server.auth.ldap_auth' from '/usr/lib64/python2.7/site-packages/xpra/server/auth/ldap_auth.pyc'>
2023-03-06 21:27:24,818 get_auth_modules(ws, [], {..})
2023-03-06 21:27:24,818 get_auth_modules(wss, [], {..})
2023-03-06 21:27:24,818 get_auth_modules(ssl, [], {..})
2023-03-06 21:27:24,818 get_auth_modules(ssh, [], {..})
2023-03-06 21:27:24,818 get_auth_modules(rfb, [], {..})
2023-03-06 21:27:24,818 get_auth_modules(vsock, [], {..})
2023-03-06 21:27:24,818 get_auth_modules(udp, [], {..})
2023-03-06 21:27:24,818 init_auth(..) auth={'udp': None, 'rfb': None, 'vsock': None, 'tcp': (('ldap', <class 'xpra.server.auth.ldap_auth.Authenticator'>, {'exec_cwd': '/usr/lib64/python2.7/site-packages', 'host': 'ldap.forumsys.com', 'port': '389'}),), 'ssl': None, 'wss': None, 'ws': None, 'ssh': None, 'unix-domain': None}
2023-03-06 21:27:24,846 xpra is ready.
2023-03-06 21:27:24,847 xpra proxy version 3.1.3-r0 64-bit
2023-03-06 21:27:24,847  uid=0 (root), gid=0 (root)
2023-03-06 21:27:24,847  running with pid 6080 on Linux CentOS Linux 7.9.2009 Core
2023-03-06 21:27:34,353 Error sending '/usr/share/xpra/www/Sessions':
2023-03-06 21:27:34,353  [Errno 2] No such file or directory
2023-03-06 21:27:34,359 Error sending '/usr/share/xpra/www/Menu':
2023-03-06 21:27:34,359  [Errno 2] No such file or directory
2023-03-06 21:27:34,364 Error sending '/usr/share/xpra/www/DesktopMenu':
2023-03-06 21:27:34,364  [Errno 2] No such file or directory
2023-03-06 21:27:34,382 Error sending '/usr/share/xpra/www/Displays':
2023-03-06 21:27:34,382  [Errno 2] No such file or directory
2023-03-06 21:27:49,291 socktype=ws, encryption=, keyfile=
2023-03-06 21:27:49,735 make_authenticators('tcp', 'riemann', ws socket: 192.168.56.116:14500 <- 192.168.56.1:50619)
2023-03-06 21:27:49,735 creating authenticators ('ldap', <class 'xpra.server.auth.ldap_auth.Authenticator'>, {'exec_cwd': '/usr/lib64/python2.7/site-packages', 'host': 'ldap.forumsys.com', 'port': '389'}) for tcp, with username=riemann, connection=ws socket: 192.168.56.116:14500 <- 192.168.56.1:50619
2023-03-06 21:27:49,735 ldap auth: host=ldap.forumsys.com, port=389, tls=False, username_format=uid=%username,dc=example,dc=com, cacert=None, encoding=utf-8
2023-03-06 21:27:49,735 authenticator 0: ldap(riemann, {'exec_cwd': '/usr/lib64/python2.7/site-packages', 'connection': ws socket: 192.168.56.116:14500 <- 192.168.56.1:50619, 'host': 'ldap.forumsys.com', 'socket-dirs': ['/run/user/$UID/xpra', '/run/xpra', '~/.xpra'], 'port': '389'})=ldap
2023-03-06 21:27:49,736 processing authentication with (ldap,), remaining=(ldap,), response=None, client_salt='', digest_modes=['hmac', 'hmac+md5', 'xor', 'keycloak', 'hmac+md5', 'hmac+sha256', 'hmac+sha1', 'hmac+sha512', 'hmac+sha384', 'hmac+sha512/256', 'hmac+sha512/224'], salt_digest_modes=['hmac', 'hmac+md5', 'xor', 'keycloak', 'hmac+md5', 'hmac+sha256', 'hmac+sha1', 'hmac+sha512', 'hmac+sha384', 'hmac+sha512/256', 'hmac+sha512/224']
2023-03-06 21:27:49,736 authenticator[0]=ldap, requires-challenge=True, challenge-sent=False
2023-03-06 21:27:49,736 get_challenge(['hmac', 'hmac+md5', 'xor', 'keycloak', 'hmac+md5', 'hmac+sha256', 'hmac+sha1', 'hmac+sha512', 'hmac+sha384', 'hmac+sha512/256', 'hmac+sha512/224'])= 7860e6e195680a07785d2b304bcde2a7f3515c2814aae158fe404b8c69bf96f3f012a6a18cf8c92b3f7034b5ed35e28a9c01a88edd0dc0448ab2c8fe170d5643, xor
2023-03-06 21:27:49,736 Authentication required by ldap authenticator module 1
2023-03-06 21:27:49,736  sending challenge for username 'riemann' using xor digest
2023-03-06 21:27:49,744 processing authentication with (ldap,), remaining=(ldap,), response='@\x00ADFW\x17\x02', client_salt='\x17\xe29\x19\x81\xb4n:L\xfd0\x1dj\x8f\x8e\xf6\xd6-\xde\xdaQ=a\x9c\x99\xc9r\x85\xfe\xd9\xbf\r', digest_modes=['hmac', 'hmac+md5', 'xor', 'keycloak', 'hmac+md5', 'hmac+sha256', 'hmac+sha1', 'hmac+sha512', 'hmac+sha384', 'hmac+sha512/256', 'hmac+sha512/224'], salt_digest_modes=['hmac', 'hmac+md5', 'xor', 'keycloak', 'hmac+md5', 'hmac+sha256', 'hmac+sha1', 'hmac+sha512', 'hmac+sha384', 'hmac+sha512/256', 'hmac+sha512/224']
2023-03-06 21:27:49,744 authenticator[0]=ldap, requires-challenge=True, challenge-sent=True
2023-03-06 21:27:49,745 combined salt(7860e6e195680a07785d2b304bcde2a7f3515c2814aae158fe404b8c69bf96f3f012a6a18cf8c92b3f7034b5ed35e28a9c01a88edd0dc0448ab2c8fe170d5643, 17e2391981b46e3a4cfd301d6a8f8ef6d62ddeda513d619c99c97285fed9bf0d)=3061323731386566663130616234313439643632333761616231643866653531373535346531303632303466313433636635356535633536613936396232623139653362613865396638633436373433386634653630386161366536633564313638393166383638663266306433646338366166663561303966343163636331
2023-03-06 21:27:49,746 authenticate_check(*******************, '\x17\xe29\x19\x81\xb4n:L\xfd0\x1dj\x8f\x8e\xf6\xd6-\xde\xdaQ=a\x9c\x99\xc9r\x85\xfe\xd9\xbf\r') response salt='0a2718eff10ab4149d6237aab1d8fe517554e106204f143cf55e5c56a969b2b19e3ba8e9f8c467438f4e608aa6e6c5d16891f868f2f0d3dc86aff5a09f41ccc1'
2023-03-06 21:27:49,746 check(********)
*** <ldap.ldapobject.SimpleLDAPObject instance at 0x7f8bc89e3368> ldap://ldap.forumsys.com:389 - SimpleLDAPObject.set_option
((17, 3), {})
*** <ldap.ldapobject.SimpleLDAPObject instance at 0x7f8bc89e3368> ldap://ldap.forumsys.com:389 - SimpleLDAPObject.set_option
((17, 3), {})
*** <ldap.ldapobject.SimpleLDAPObject instance at 0x7f8bc89e3368> ldap://ldap.forumsys.com:389 - SimpleLDAPObject.set_option
((8, 0), {})
2023-03-06 21:27:49,762 ldap.open(ldap://ldap.forumsys.com:389)=<ldap.ldapobject.SimpleLDAPObject instance at 0x7f8bc89e3368>
2023-03-06 21:27:49,762 user=uid=riemann,dc=example,dc=com
2023-03-06 21:27:49,762 ldap encoded password as utf-8
*** <ldap.ldapobject.SimpleLDAPObject instance at 0x7f8bc89e3368> ldap://ldap.forumsys.com:389 - SimpleLDAPObject.simple_bind
(('uid=riemann,dc=example,dc=com', 'password', None, None), {})
*** <ldap.ldapobject.SimpleLDAPObject instance at 0x7f8bc89e3368> ldap://ldap.forumsys.com:389 - SimpleLDAPObject.result4
((1, 1, -1, 0, 0, 0), {})
2023-03-06 21:27:50,143 simple_bind_s(uid=riemann,dc=example,dc=com, ********)=(97, [], 1, [])
2023-03-06 21:27:50,143 authenticate_check(..)=True
2023-03-06 21:27:50,143 authentication challenge passed for ldap
2023-03-06 21:27:50,143 all authentication modules passed
2023-03-06 21:27:50,144 ldap.get_sessions() uid=99, gid=99
2023-03-06 21:27:50,149 sockdir=DotXpra(/run/user/99/xpra, ['/run/user/99/xpra', '/run/xpra', '~riemann/.xpra'] - 99:99 - riemann), results=[], displays=[]
2023-03-06 21:27:50,149 ldap.get_sessions()=(99, 99, [], {}, {})
2023-03-06 21:27:50,149 proxy_auth ldap.get_sessions()=(99, 99, [], {}, {})
2023-03-06 21:27:50,149 proxy_auth(WebSocket(ws socket: 192.168.56.116:14500 <- 192.168.56.1:50619), {..}, None) found sessions: (99, 99, [], {}, {})
2023-03-06 21:27:50,150 proxy_session: displays=[], start_sessions=True, start-new-session={'start': ['/usr/bin/xterm'], 'mode': 'start'}
Entering daemon mode; any further errors will be reported to:
  /run/user/99/xpra/S6143.log
2023-03-06 21:28:10,191 Error: displayfd failed
2023-03-06 21:28:10,191  did not provide a display number using displayfd
Actual display used: :0
Actual log file name is now: /run/user/99/xpra/:0.log
2023-03-06 21:29:40,226 Error: failed to start server subprocess:
2023-03-06 21:29:40,226  failed to identify the new server display!
2023-03-06 21:29:40,236 Error sending '/usr/share/xpra/www/Sessions':
2023-03-06 21:29:40,237  [Errno 2] No such file or directory
2023-03-06 21:29:40,241 Error sending '/usr/share/xpra/www/Menu':
2023-03-06 21:29:40,241  [Errno 2] No such file or directory
2023-03-06 21:29:40,244 Error sending '/usr/share/xpra/www/DesktopMenu':
2023-03-06 21:29:40,244  [Errno 2] No such file or directory
2023-03-06 21:29:40,252 Error sending '/usr/share/xpra/www/Displays':
2023-03-06 21:29:40,252  [Errno 2] No such file or directory
^C
2023-03-06 21:29:40,248 got signal SIGINT
2023-03-06 21:29:40,250 exiting
2023-03-06 21:29:40,351 closing tcp socket '0.0.0.0:14500'
[root@iqlcen7vm site-packages]# 
```

The authentication phase passed successfully. Appreciate the help with that.

Unfortunately however, since the LDAP user _*riemann*_ does not exist on my local system, the server process could not start. I know it is not tightly related to the original issue, but is there any way around that perhaps? I'm thinking along the lines of...

- either opening the server session with a predefined default user, or
- running a script, after successful login, which would get the username as the parameter, and could create a local useraccount with the same name, if not exist?

Many thanks,
Walakee

**Comment by totaam** [comment]
> `Entering daemon mode; any further errors will be reported to:`
> (..)
> `Actual log file name is now: /run/user/99/xpra/:0.log`
>
> Unfortunately however, since the LDAP user riemann does not exist on my local system, the server process could not start.

Do you have the exact error from the log file?

If you run the proxy as root, it should get the `username` from the uid - which is an option of the authentication module:
https://github.com/Xpra-org/xpra/blob/996f300b0e85ce73203f25f891e3269e09e3ac15/xpra/server/proxy/proxy_server.py#L379

It may be possible to configure the system's `pam` modules to create a user account when `root` switches to this uid for starting the new instance.

> opening the server session with a predefined default user

That should be possible but not very secure and definitely problematic with a lot of applications (ie: `Firefox` and many gnome applications) .

> running a script, after successful login, which would get the username as the parameter, and could create a local useraccount with the same name

That's almost already possible by adding a second authentication module of type `exec` and using a command to create the user account:
https://github.com/Xpra-org/xpra/blob/996f300b0e85ce73203f25f891e3269e09e3ac15/xpra/server/auth/exec_auth.py#L23
(the only thing missing is that the `username` is not given to this command, but we could very easily change that)
Feel free to create a new ticket for this.

**Comment by walakee** [comment]
Many thanks for the detailed reply. Please see my comments below...

> Do you have the exact error from the log file?

Sure, please find it below...

```
2023-03-09 10:58:52,601 cannot access python uinput module:^[[0m
2023-03-09 10:58:52,601  No module named uinput^[[0m

X.Org X Server 1.20.4
X Protocol Version 11, Revision 0
Build Operating System:  3.10.0-957.1.3.el7.x86_64
Current Operating System: Linux iqlcen7vm 3.10.0-1160.71.1.el7.x86_64 #1 SMP Tue Jun 28 15:37:28 UTC 2022 x86_64
Kernel command line: BOOT_IMAGE=/vmlinuz-3.10.0-1160.71.1.el7.x86_64 root=/dev/mapper/centos-root ro crashkernel=auto spectre_v2=retpoline rd.lvm.lv=centos/root rd.lvm.lv=centos/swap rhgb quiet numa=off transparent_hugepage=never LANG=en_US.UTF-8
Build Date: 04 January 2022  05:44:44PM
Build ID: xorg-x11-server 1.20.4-17.el7_9
Current version of pixman: 0.34.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/run/user/99/xpra/Xorg.S2732.log", Time: Thu Mar  9 10:58:52 2023
(++) Using config file: "/etc/xpra/xorg.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
xauth:  timeout in locking authority file /.Xauthority
^[[33m2023-03-09 10:59:13,658 Warning: xauth command took 20 seconds and failed^[[0m
^[[31m2023-03-09 10:59:13,658 Error adding xauth entry for :0^[[0m
^[[31m2023-03-09 10:59:13,658  using command "xauth -f /.Xauthority add :0 MIT-MAGIC-COOKIE-1 222ffd5bc1d14e0cb4e7c3076165bf4b":^[[0m
^[[31m2023-03-09 10:59:13,658  non-zero exit code: 1^[[0m
^[[31m2023-03-09 10:59:13,659 write_displayfd failed
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/xpra/scripts/server.py", line 690, in do_run_server
    assert write_displayfd(displayfd, display_no), "timeout"
  File "/usr/lib64/python2.7/site-packages/xpra/platform/displayfd.py", line 36, in write_displayfd
    count = os.write(w_pipe, buf)
OSError: [Errno 32] Broken pipe^[[0m
^[[31m2023-03-09 10:59:13,662 Error: failed to write ':0' to fd=11^[[0m
^[[31m2023-03-09 10:59:13,662  [Errno 32] Broken pipe^[[0m
Unable to create //.dbus
Unable to create //.dbus/session-bus
^[[33m2023-03-09 10:59:13,934 Warning: failed to create socket directory '/.xpra'^[[0m
^[[33m2023-03-09 10:59:13,934  [Errno 13] Permission denied: '/.xpra'^[[0m
2023-03-09 10:59:13,934 created unix domain socket '/run/user/99/xpra/iqlcen7vm-0'^[[0m
2023-03-09 10:59:13,934 cannot create group socket '/run/xpra/iqlcen7vm-0'^[[0m
2023-03-09 10:59:13,934  [Errno 13] Permission denied^[[0m
^[[31m2023-03-09 10:59:13,934 Error: failed to create socket '/.xpra/iqlcen7vm-0':^[[0m
^[[31m2023-03-09 10:59:13,935  [Errno 2] No such file or directory^[[0m
2023-03-09 10:59:13,935 removing socket '/run/user/99/xpra/iqlcen7vm-0'^[[0m
xpra initialization error:
 failed to create socket /.xpra/iqlcen7vm-0
```

> It may be possible to configure the system's pam modules to create a user account when root switches to this uid for starting the new instance.

Thanks for the idea. Unfortunately this is way above my level of Linux knowledge :)

> That should be possible but not very secure and definitely problematic with a lot of applications (ie: Firefox and many gnome applications).

I think you are right.

> (the only thing missing is that the username is not given to this command, but we could very easily change that)
> Feel free to create a new ticket for this.

Thanks, will do.

Appreciate all the quick and relevant help... :)
Walakee
