### ISSUE TITLE
Error parsing version of libx264 while building the debian package

### ISSUE THREAD

**Issue by iDmple** [Xpra-org/xpra#3793]
While building the .deb package of xpra on Ubuntu 20.04 I get this error (master branch):

```
python3 setup.py clean
setup.py clean
Xpra version 5.0
found pkg-config version: 0.29.1
ARCH=x86_64

using INCLUDE_DIRS=['/usr/include', '/usr/local/include']
CPP=cpp
Traceback (most recent call last):
  File "setup.py", line 226, in <module>
    enc_x264_ENABLED        = DEFAULT and pkg_config_version("0.155", "x264")
  File "setup.py", line 137, in pkg_config_version
    return parse(out)>=parse(req_version)
  File "/usr/local/lib/python3.8/dist-packages/packaging/version.py", line 52, in parse
    return Version(version)
  File "/usr/local/lib/python3.8/dist-packages/packaging/version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: '0.155.2917 0a84d98'
make[1]: *** [debian/rules:15: override_dh_auto_clean] Error 1
make[1]: Leaving directory '/xpra'
make: *** [debian/rules:12: clean] Error 2
dpkg-buildpackage: error: debian/rules clean subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui -b failed
````

There seems to already be a workaround in the code for libx264 but it looks like it doesn't work anymore?

**Comment by totaam** [comment]
What an epic disaster this version parsing is!
b7520675c4b479646341e96f7ac45808cc0c9471 was needed before, and then 7d29c44cd42a7e3747c82b640bbd8e065c7c45cc.
The commit above should fix this particular one.
I miss the old, but sadly deprecated, `LooseVersion`. That one just worked.

**Comment by iDmple** [comment]
Thanks for fixing it so fast, as always!
It works now :)
