### ISSUE TITLE
ModuleNotFoundError: No module named 'xpra.client.spinner'

### ISSUE THREAD

**Issue by allo-** [Xpra-org/xpra#3809]
**Describe the bug**
Exception

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xpra/client/gtk3/gtk3_client_window.py", line 219, in draw_widget
    self.paint_spinner(context)
  File "/usr/lib/python3/dist-packages/xpra/client/gtk_base/gtk_client_window_base.py", line 1947, in paint_spinner
    from xpra.client.spinner import cv
ModuleNotFoundError: No module named 'xpra.client.spinner'
```

**System Information (please complete the following information):**
 - Server OS: Debian stable
 - Client OS: Debian testing
 - Xpra Server Version: 4.4.4-r0-1
 - Xpra Client Version: xpra-client-gtk3=5.0-r32941-1

**Additional context**
Probably related to the split of xpra/xpra-client-gtk3

**Comment by totaam** [comment]
Thanks!
Fixed in the commit above.
