### ISSUE TITLE
Packet encoding error when xdg-menu contains None values

### ISSUE THREAD

**Issue by jacklovell** [Xpra-org/xpra#3832]
**Describe the bug**
Connecting from the HTML client to an Xpra server running on a system with `None` entires in `xdg-menu` results in `ValueError: found None value` in the log and and a blank screen in the client browser. The server log indicates the client disconnected, but the browser doesn't reflect this and I have to select the Disconnect item in the menu.

Connecting via the command line does not cause the same problem, via SSL or SSH.

**To Reproduce**
1. server command: `xpra start :10002 --bind-tcp=127.0.0.1:10002 --ssl=off --html=on --start=xterm`
2. client command: Connect to http://localhost:10002 from a web browser (Firefox in my case)
3. Attempt to connect to server.

**System Information (please complete the following information):**
 - Server OS: Scientific Linux 7 (CentOS 7)
 - Client OS: Firefox 112 on same system (also observed on Ubuntu client)
 - Xpra Server Version: xpra v3.1.4-r3M
 - Xpra Client Version: xpra-html5 3.0.13 (also observed with xpra-html5

**Additional context**
Please see "reporting bugs" in the wiki section.

Relevant log output:
```
2023-04-21 12:07:28,823  client root window size is 1920x921 with 1 display:
2023-04-21 12:07:28,824   HTML (508x244 mm - DPI: 96x95)
2023-04-21 12:07:28,824     Canvas
2023-04-21 12:07:29,337 server virtual display now set to 1920x921
Traceback (most recent call last):
  File "xpra/net/bencode/cython_bencode.pyx", line 194, in xpra.net.bencode.cython_bencode.bencode
  File "xpra/net/bencode/cython_bencode.pyx", line 179, in xpra.net.bencode.cython_bencode.encode
  File "xpra/net/bencode/cython_bencode.pyx", line 154, in xpra.net.bencode.cython_bencode.encode_list
  File "xpra/net/bencode/cython_bencode.pyx", line 183, in xpra.net.bencode.cython_bencode.encode
  File "xpra/net/bencode/cython_bencode.pyx", line 163, in xpra.net.bencode.cython_bencode.encode_dict
  File "xpra/net/bencode/cython_bencode.pyx", line 183, in xpra.net.bencode.cython_bencode.encode
  File "xpra/net/bencode/cython_bencode.pyx", line 163, in xpra.net.bencode.cython_bencode.encode_dict
  File "xpra/net/bencode/cython_bencode.pyx", line 183, in xpra.net.bencode.cython_bencode.encode
  File "xpra/net/bencode/cython_bencode.pyx", line 163, in xpra.net.bencode.cython_bencode.encode_dict
  File "xpra/net/bencode/cython_bencode.pyx", line 187, in xpra.net.bencode.cython_bencode.encode
ValueError: found None value!
2023-04-21 12:07:29,602 Error: failed to encode packet: ['setting-change', 'xdg-menu', {u'Development': {'Comment': '', 'Name': u'Development', 'GenericName': '', 'Entries': {u'OpenJDK Policy Tool x86_64-2.6.22.2.
Traceback (most recent call last):
  File "/home/jlovell/Software/xpra-install/usr/lib64/python2.7/site-packages/xpra/net/protocol.py", line 614, in encode
    main_packet, proto_flags = self._encoder(packet)
  File "/home/jlovell/Software/xpra-install/usr/lib64/python2.7/site-packages/xpra/net/packet_encoding.py", line 122, in do_bencode
    return bencode(data), FLAGS_BENCODE
  File "xpra/net/bencode/cython_bencode.pyx", line 199, in xpra.net.bencode.cython_bencode.bencode
ValueError: cannot encode '['setting-change', 'xdg-menu', {u'Development': {'Comment': '', 'Name': u'Development', 'GenericName': '', 'Entries': {u'OpenJDK Policy Tool x86_64-2.6.22.2.el7_8': {'MimeTypes': [], 'Ic
2023-04-21 12:07:29,799 DPI set to 96 x 96
2023-04-21 12:07:29,875 None value in 'setting-change' packet->[2]->value for key='Other'->value for key='Entries'->value for key=''
2023-04-21 12:07:29,927 Error: error in network packet write/format
2023-04-21 12:07:29,928  cannot encode '['setting-change', 'xdg-menu', {u'Development': {'Comment': '', 'Name': u'Development', 'GenericName': '', 'Entries': {u'OpenJDK Policy Tool x86_64-2.6.22.2.el7_8': {'MimeTy
Traceback (most recent call last):
  File "/home/jlovell/Software/xpra-install/usr/lib64/python2.7/site-packages/xpra/net/protocol.py", line 378, in _write_format_thread_loop
    self._add_packet_to_queue(*gpc())
  File "/home/jlovell/Software/xpra-install/usr/lib64/python2.7/site-packages/xpra/net/protocol.py", line 393, in _add_packet_to_queue
    chunks = self.encode(packet)
  File "/home/jlovell/Software/xpra-install/usr/lib64/python2.7/site-packages/xpra/net/protocol.py", line 614, in encode
    main_packet, proto_flags = self._encoder(packet)
  File "/home/jlovell/Software/xpra-install/usr/lib64/python2.7/site-packages/xpra/net/packet_encoding.py", line 122, in do_bencode
    return bencode(data), FLAGS_BENCODE
  File "xpra/net/bencode/cython_bencode.pyx", line 199, in xpra.net.bencode.cython_bencode.bencode
ValueError: cannot encode '['setting-change', 'xdg-menu', {u'Development': {'Comment': '', 'Name': u'Development', 'GenericName': '', 'Entries': {u'OpenJDK Policy Tool x86_64-2.6.22.2.el7_8': {'MimeTypes': [], 'Ic
2023-04-21 12:07:29,983 xpra client 1 disconnected.
```
The log has very long lines which I've truncated (it's 13 MB in full), but the key part appears to be that one of the entries in the `xdg-menu` dict is this:
```
u'Other':  {'Comment': '', 'Name': u'Other', 'GenericName': '', 'Entries': {'': None, ...
```

**Comment by totaam** [comment]
Oh, joy. So your system generates xdg data that includes `None` values...

I have tried to add defensive code to prevent this from propagating to the network layer, which does not allow it.

@jacklovell Can you try to drop the newer version of this file:
https://github.com/Xpra-org/xpra/blob/v3.1.x/xpra/platform/xposix/xdg_helper.py
Onto your installation - so somewhere in:
```
/home/jlovell/Software/xpra-install/usr/lib64/python2.7/site-packages/xpra/platform/xposix/
```
BTW, this is a non-standard installation and should have be explained better.

**Comment by jacklovell** [comment]
The modified file fixes the problem: thanks!

Xpra is running on a legacy system which I don't have full control over, hence the unconventional install. But I'm pretty confident nothing about the install itself is causing the problem here, and this would have shown up with  a vanilla yum install if that was possible. The dodgy XDG data seems to come from a weird applications menu entry somewhere, which I'm unable to a) find and b) fix. But having xpra be able to tolerate it is greatly appreciated.
