### ISSUE TITLE
Issues starting xpra on first try

### ISSUE THREAD

**Issue by iDmple** [Xpra-org/xpra#3838]
I'm on the latest commits of the master branch and built the .deb on Ubuntu-20.04.

When I start xpra for the first time, I get this error:
```
root@800720d85bbe:/home/xpra# su xpra                                                                                              
xpra@800720d85bbe:~$ xpra start :80 --bind-tcp=0.0.0.0:8080 --html=on --no-daemon                                                  
2023-04-28 11:03:42,754 Warning: cannot enable SSH socket upgrades                                                                 
2023-04-28 11:03:42,755  No module named 'paramiko'                                                                                
2023-04-28 11:03:42,755 created tcp socket '0.0.0.0:8080'                                                                          
Socket path '/tmp/.X11-unix/X80' not found                                                                                         
2023-04-28 11:03:42,758 no uinput module (not usually needed)                                                                      
xpra main error:                                                                                                                   
Traceback (most recent call last):                                                                                                 
  File "/usr/lib/python3/dist-packages/xpra/scripts/main.py", line 155, in main                                                    
    return run_mode(script_file, cmdline, err, options, args, mode, defaults)                                                      
  File "/usr/lib/python3/dist-packages/xpra/scripts/main.py", line 463, in run_mode                                                
    return do_run_mode(script_file, cmdline, error_cb, options, args, mode, defaults)                                              
  File "/usr/lib/python3/dist-packages/xpra/scripts/main.py", line 498, in do_run_mode                                             
    return run_server(script_file, cmdline, error_cb, options, args, mode, defaults)                                               
  File "/usr/lib/python3/dist-packages/xpra/scripts/main.py", line 1884, in run_server                                             
    return do_run_server(script_file, cmdline, error_cb, options, args, mode, display, defaults)                                   
  File "/usr/lib/python3/dist-packages/xpra/scripts/server.py", line 714, in do_run_server                                         
    return _do_run_server(script_file, cmdline,                                                                                    
  File "/usr/lib/python3/dist-packages/xpra/scripts/server.py", line 1195, in _do_run_server                                       
    xauth_add(xauthority, display_name, xauth_data, uid, gid)                                                                      
  File "/usr/lib/python3/dist-packages/xpra/x11/vfb_util.py", line 436, in xauth_add                                               
    code = call(xauth_cmd, preexec_fn=preexec)                                                                                     
  File "/usr/lib/python3.8/subprocess.py", line 340, in call                                                                       
    with Popen(*popenargs, **kwargs) as p:                                                                                         
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__                                                                   
    self._execute_child(args, executable, preexec_fn, close_fds,                                                                   
  File "/usr/lib/python3.8/subprocess.py", line 1639, in _execute_child                                                            
    self.pid = _posixsubprocess.fork_exec(                                                                                         
TypeError: expected str, bytes or os.PathLike object, not NoneType  
```

On the second try, it goes as normal, however I get an issue with Gstreamer. I would appreciate a hint on how to fix this:
```
xpra@800720d85bbe:~$ xpra start :80 --bind-tcp=0.0.0.0:8080 --html=on --no-daemon                                                  
2023-04-28 11:03:45,214 Warning: cannot enable SSH socket upgrades                                                                 
2023-04-28 11:03:45,214  No module named 'paramiko'                                                                                
2023-04-28 11:03:45,215 created tcp socket '0.0.0.0:8080'                                                                          
(EE) Failed to open authorization file "$XAUTHORITY": No such file or directory                                                    
2023-04-28 11:03:45,313 no uinput module (not usually needed)                                                                      
2023-04-28 11:03:45,626 pointer device emulation using XTest                                                                       
2023-04-28 11:03:45,697 serving html content from '/usr/share/xpra/www'                                                            
2023-04-28 11:03:45,698 wrote pid 55 to '/run/user/1000/xpra/80/server.pid'                                                        
2023-04-28 11:03:45,723 created unix domain socket '/run/user/1000/xpra/800720d85bbe-80'                                           
2023-04-28 11:03:45,724 created unix domain socket '/run/user/1000/xpra/80/socket'                                                 
2023-04-28 11:03:45,724 xvfb pid not found                                                                                         
2023-04-28 11:03:45,752 pulseaudio server started with pid 64                                                                      
2023-04-28 11:03:45,753  private server socket path:                                                                               
2023-04-28 11:03:45,753  '/run/user/1000/xpra/80/pulse/pulse/native'                                                               
W: [pulseaudio] authkey.c: Failed to open cookie file '/home/xpra/.config/pulse/cookie': No such file or directory                 
W: [pulseaudio] authkey.c: Failed to load authentication key '/home/xpra/.config/pulse/cookie': No such file or directory          
W: [pulseaudio] authkey.c: Failed to open cookie file '/home/xpra/.pulse-cookie': No such file or directory                        
W: [pulseaudio] authkey.c: Failed to load authentication key '/home/xpra/.pulse-cookie': No such file or directory                 
2023-04-28 11:03:45,864 watching for applications menu changes in:
2023-04-28 11:03:45,864  '/usr/share/applications'
2023-04-28 11:03:46,248 xpra is ready.
2023-04-28 11:03:46,250 xpra X11 seamless server version 5.0-r1238M
2023-04-28 11:03:46,252  uid=1000 (xpra), gid=121 (xpra)
2023-04-28 11:03:46,252  running with pid 55 on Linux Ubuntu 20.04 focal
2023-04-28 11:03:46,253  connected to X11 display :80 with 24 bit colors
2023-04-28 11:03:46,255 some GStreamer elements are missing or unavailable on this system:
2023-04-28 11:03:46,255  vaapih264enc, vaapih265enc, x264enc, av1enc
2023-04-28 11:03:46,328 GStreamer version 1.16.3
2023-04-28 11:03:46,391 Error setting up the pipeline:
2023-04-28 11:03:46,391  gst_parse_error: no property "leaky-type" in element "src" (2)
2023-04-28 11:03:46,391  GStreamer pipeline for:
2023-04-28 11:03:46,391   appsrc name=src emit-signals=0 leaky-type=0 do-timestamp=1 block=0 is-live=1 stream-type=0 format=4 caps=
video/x-raw,width=128,height=128,format=(string)I420,framerate=60/1,interlace=(string)progressive,colorimetry=(string)bt709 ! \
2023-04-28 11:03:46,392   vp8enc deadline=1 error-resilient=0 name=encoder ! \
2023-04-28 11:03:46,392   video/x-vp8,alignment=(string)au,stream-format=(string)byte-stream ! \
2023-04-28 11:03:46,392   appsink name=sink emit-signals=true max-buffers=10 drop=false sync=false async=false qos=true
2023-04-28 11:03:46,392 Warning: gstreamer 'vp8enc' encoder failed
2023-04-28 11:03:46,393  failed to setup gstreamer pipeline
2023-04-28 11:03:46,393 Error setting up the pipeline:
2023-04-28 11:03:46,394  gst_parse_error: no property "leaky-type" in element "src" (2)
2023-04-28 11:03:46,394  GStreamer pipeline for:
2023-04-28 11:03:46,394   appsrc name=src emit-signals=0 leaky-type=0 do-timestamp=1 block=0 is-live=1 stream-type=0 format=4 caps=
video/x-raw,width=128,height=128,format=(string)Y444,framerate=60/1,interlace=(string)progressive,colorimetry=(string)bt709 ! \
2023-04-28 11:03:46,395   vp9enc deadline=1 error-resilient=0 lag-in-frames=0 cpu-used=16 name=encoder ! \
2023-04-28 11:03:46,395   video/x-vp9,alignment=(string)au,stream-format=(string)byte-stream ! \
2023-04-28 11:03:46,395   appsink name=sink emit-signals=true max-buffers=10 drop=false sync=false async=false qos=true
2023-04-28 11:03:46,395 Warning: gstreamer 'vp9enc' encoder failed
2023-04-28 11:03:46,395  failed to setup gstreamer pipeline
2023-04-28 11:03:46,403 15.6GB of system memory
2023-04-28 11:03:47,224 OpenGL is supported on display ':80'
2023-04-28 11:03:47,224  using 'llvmpipe (LLVM 12.0.0, 256 bits)' renderer
2023-04-28 11:03:47,237 started command `ibus-daemon` with pid 131
2023-04-28 11:03:47,500 loaded 20 start menu entries from 4 sub-menus in 1.5 seconds
```

When I was previously building xpra from commit e8b97243e58ba0f6d03074e1d0bdc9c2d0fc9f9b I did not have these issues.

Thanks for your help on these two problems.

Edit: for comparison log of the previously working version (this one has auth, I deactivated that above for clarity but I have the same issues with it on, and a pulseaudio server is also running):
```
2023-04-27 12:19:24,676 Warning: cannot enable SSH socket upgrades
2023-04-27 12:19:24,676  No module named 'paramiko'
2023-04-27 12:19:24,677 created tcp socket '0.0.0.0:8080'
2023-04-27 12:19:24,682 no uinput module (not usually needed)
2023-04-27 12:19:26,294 debug enabled for xpra.server.auth.auth_helper / ('auth',)
2023-04-27 12:19:26,295 debug enabled for xpra.server.server_core / ('auth',)
2023-04-27 12:19:26,315 debug enabled for xpra.server.server_base / ('auth',)
2023-04-27 12:19:26,324 pointer device emulation using XTest
2023-04-27 12:19:26,409 serving html content from '/usr/share/xpra/www'
2023-04-27 12:19:26,409 get_auth_modules(tcp, [], ..)
2023-04-27 12:19:26,409 get_auth_modules(ws, [], ..)
2023-04-27 12:19:26,409 get_auth_modules(wss, [], ..)
2023-04-27 12:19:26,409 get_auth_modules(ssl, [], ..)
2023-04-27 12:19:26,409 get_auth_modules(ssh, [], ..)
2023-04-27 12:19:26,409 get_auth_modules(rfb, [], ..)
2023-04-27 12:19:26,409 get_auth_modules(vsock, [], ..)
2023-04-27 12:19:26,409 get_auth_modules(socket, [], ..)
2023-04-27 12:19:26,409 get_auth_modules(named-pipe, [], ..)
2023-04-27 12:19:26,409 get_auth_modules(quic, [], ..)
2023-04-27 12:19:26,410 init_auth(..) auth={'tcp': None, 'ws': None, 'wss': None, 'ssl': None, 'ssh': None, 'rfb': None, 'vsock': None, 'socket': None, 'named-pipe': None, 'quic': None}
2023-04-27 12:19:26,410 wrote pid 29 to '/run/user/1000/xpra/80/server.pid'
2023-04-27 12:19:26,437 created unix domain socket '/run/user/1000/xpra/1ac005b76a93-80'
2023-04-27 12:19:26,438 created unix domain socket '/run/user/1000/xpra/80/socket'
2023-04-27 12:19:26,438 xvfb pid=33
2023-04-27 12:19:26,473 pulseaudio server started with pid 54
2023-04-27 12:19:26,474  private server socket path:
2023-04-27 12:19:26,474  '/run/user/1000/xpra/80/pulse/pulse/native'
2023-04-27 12:19:26,932 waiting for initialization thread to complete
2023-04-27 12:19:26,934 xpra is ready.
2023-04-27 12:19:26,940 xpra X11 seamless server version 5.0-r2244
2023-04-27 12:19:26,984 watching for applications menu changes in:
2023-04-27 12:19:26,984  '/usr/share/applications'
2023-04-27 12:19:26,990 started command `xhost +` with pid 71
2023-04-27 12:19:26,991 62.8GB of system memory
access control disabled, clients can connect from any host
2023-04-27 12:19:27,107  uid=1000 (xpra), gid=121 (xpra)
2023-04-27 12:19:27,107  running with pid 29 on Linux Ubuntu 20.04 focal
2023-04-27 12:19:27,108  connected to X11 display :80 with 24 bit colors
2023-04-27 12:19:27,235 GStreamer version 1.16.3
2023-04-27 12:19:28,005 OpenGL is supported on display ':80'
2023-04-27 12:19:28,005  using 'llvmpipe (LLVM 12.0.0, 256 bits)' renderer
2023-04-27 12:19:28,029 started command `ibus-daemon` with pid 115
2023-04-27 12:19:28,374 loaded 20 start menu entries from 4 sub-menus in 1.4 seconds
```

**Comment by totaam** [comment]
> I'm on the latest commits of the master branch

Which is?
> `TypeError: expected str, bytes or os.PathLike object, not NoneType`

I'm pretty sure the fix for this was pushed yesterday.

**Comment by iDmple** [comment]
Perfect thank you so much!
