### ISSUE TITLE
Xpra on Windows can't open session files

### ISSUE THREAD

**Issue by shururuun** [Xpra-org/xpra#3875]
**Describe the bug**
Xpra 4.4.5 on Windows can't open session files directly anymore, at least with SSH connections.

**To Reproduce**
1. Start Xpra session launcher, fill in the following values:
Mode: SSH
Server: username @ host : 22 : 23
No server password
2. Save session file
3. Close Xpra session launcher
4. Open saved session file from Explorer

Opening the file in the session launcher manually works.

**System Information (please complete the following information):**
 - Server OS: Debian 11
 - Client OS: Windows 11
 - Xpra Server Version 4.4.5-r0-1
 - Xpra Client Version 4.4.5

Error message (from OCR, because the window doesn't allow copy&paste):
```
Error creating launcher form
Traceback (most recent call last):
File "E:/xpra/xpra/client/gtk_base/client_launcher.py", line 1151, in
do_main
File "E:/xpra/xpra/client/gtk_base/client_launcher.py", line 144, in
__init__
File "E:/xpra/xpra/client/gtk_base/client_launcher.py", line 156, in
parse_ssh
File "E:/xpra/xpra/scripts/parsing.py", line 674, in parse_ssh_option
File "C:/msys64/mingw64/Iib/python3.10/site-packages/paranmiko/
__init__.py", line 22, in <module>
File "C:/msys64/mingw64/Iib/python3.10/site-packages/paramiko/
transport.py", line 135, in <module»
File I O/site-packages/paramiko/
transport.py", line 209, in Transport
File "C:/msys64/mingw64/Iib/python3.10/site-packages/paramiko/
kex_curve25519.py", line 30, in is_available
File "C:/msys64/nfrrgw64/Iib/python3.10/site-packages/
cryptography/hazmat/primitives/asynnetric/x25519.py", line 52, in
generate
File "C:/msys64/mingw64/Iib/python3.10/site-packages/
cryptography/hazmat/backends/openssl/_init_.py", line 6, in
<module>
File "C:/msys64/mingw64/Iib/python3.10/site-packages/
cryptography/hazmat/backends/openssl/backend.py", line 57, in
< module>
File "C:/msys64/mingw64/lib/python3.10/site-packages/
cryptography/hazmat/bindings/openssl/binding.py", line 179, in
<module>
File "C:/msys64/mingw64/Iib/python3.10/site-packages/
cryptography/hazmat/bindings/openssl/binding.py", line 146, in
init_static_locks
File "C:/msys64/mingw64/Iib/python3.10/site-packages/
cryptography/hazmat/bindings/openssl/binding.py", line 135, in
_ensure_ffi_initialized
File "C:/msys64/mingw64/Iib/python3.10/site-packages/
cryptography/hazmat/bindings/openssl/binding.py", line 42, in
_legacy_provider_error
RuntimeError: OpenSSL 3.0's legacy provider failed to Ioad. This is a
fatal error by default, but cryptography supports running without
legacy algorithms by setting the environment variable
CRYPTOGRAPHY_OPENSSL_NO_LEGACY. If you did not expect this
error, you have likely made a mistake with your OpenSSL
configuration.
```

**Comment by totaam** [comment]
Ah, we already set `CRYPTOGRAPHY_OPENSSL_NO_LEGACY=1`:
https://github.com/Xpra-org/xpra/blob/c4a31c32e25e96fdf34ac09179a7be5bcaf73909/xpra/scripts/main.py#L111-L112
But the launcher uses a different entry point when called from the file explorer. Will fix.

**Comment by totaam** [comment]
The commits above fix this issue and a more elegant solution has been merged in git master.

You can find updated builds with these fixes in [the beta area](https://xpra.org/beta/)
