### ISSUE TITLE
Receiving "Error: cannot start the seamless server" and "RuntimeError: can't start new thread" starting xpra in Ubuntu container

### ISSUE THREAD

**Issue by josh-endries** [Xpra-org/xpra#3878]
I'm trying to run xpra 4.4.5-r0 in a container using Ubuntu 22.04.2. The container works on my dev box (which is 22.04.1), but on the VM host it won't start up. Here is the server log/output:

```
# xpra start :80 --sharing=yes --window-close=disconnect --printing=no --speaker=disabled --mdns=no --lock=no \
--webcam=no --system-tray=no --tray=no --file-transfer=off --open-files=off --exit-with-client=no \
--start-new-commands=no --no-daemon

Warning: running as root
2023-06-01 13:28:18,330 cannot use uinput for virtual devices,
2023-06-01 13:28:18,333  this is usually a permission issue:
2023-06-01 13:28:18,333  [Errno 2] Failed to open the uinput device: No such file or directory. Perhaps load the uinput kernel module first?
2023-06-01 13:28:18,472 pointer device emulation using XTest
2023-06-01 13:28:18,560 serving html content from '/usr/share/xpra/www'
2023-06-01 13:28:18,562 wrote pid 107 to '/run/xpra/80/server.pid'
2023-06-01 13:28:18,605 created unix domain socket '/run/user/0/xpra/75c725bd26d6-80'
2023-06-01 13:28:18,606 created unix domain socket '/run/xpra/75c725bd26d6-80'
2023-06-01 13:28:18,608 created unix domain socket '/root/.xpra/75c725bd26d6-80'
2023-06-01 13:28:18,609 created unix domain socket '/run/xpra/80/socket'
2023-06-01 13:28:18,610 xvfb pid=81
2023-06-01 13:28:18,656 Error: cannot start the seamless server
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xpra/scripts/server.py", line 1491, in _do_run_server
    app.setup()
  File "/usr/lib/python3/dist-packages/xpra/x11/server.py", line 122, in setup
    X11ServerBase.setup(self)
  File "/usr/lib/python3/dist-packages/xpra/server/server_base.py", line 167, in setup
    c.setup(self)
  File "/usr/lib/python3/dist-packages/xpra/server/server_core.py", line 301, in setup
    self.init_thread.start()
  File "/usr/lib/python3.10/threading.py", line 935, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
2023-06-01 13:28:18,665 can't start new thread
2023-06-01 13:28:18,667
2023-06-01 13:28:18,794 removing unix domain socket '/run/user/0/xpra/75c725bd26d6-80'
2023-06-01 13:28:18,795 removing unix domain socket '/run/xpra/75c725bd26d6-80'
2023-06-01 13:28:18,796 removing unix domain socket '/root/.xpra/75c725bd26d6-80'
2023-06-01 13:28:18,797 removing unix domain socket '/run/xpra/80/socket'
```
I had this working previously on Ubuntu 20.04 but I'm not sure what the issue is with the newer container, especially as the container works on my local box. It seems like some dependency or host/OS issue, if it can't start a thread, but I'm not sure what to try or look into next...

**Comment by totaam** [comment]
This is not an xpra issue, you should be able to reproduce this with just about any python script that uses the threading module.
Looks exactly like: [Python in docker – RuntimeError: can't start new thread](https://stackoverflow.com/questions/70087344/).
