### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'append'  

### ISSUE THREAD

**Issue by iDmple** [Xpra-org/xpra#3882]
Hi,

I'm getting this error on commit 322e0df8a7f0fd50e7cbe440f9ba939a4c34794b of Xpra running on Ubuntu 20.04 from the debian package:
```
2023-06-05 08:53:06,747 error on window 2                                                                                                  
Traceback (most recent call last):                                                                                                         
  File "/usr/lib/python3/dist-packages/xpra/server/source/encodings.py", line 159, in recalculate_delays                                   
    ws.calculate_batch_delay(wid==focus,                                                                                                   
  File "/usr/lib/python3/dist-packages/xpra/server/window/window_source.py", line 1272, in calculate_batch_delay                           
    calculate_batch_delay(self.wid, self.window_dimensions, has_focus,                                                                     
  File "/usr/lib/python3/dist-packages/xpra/server/window/batch_delay_calculator.py", line 56, in calculate_batch_delay                    
    mayaddfac("focus", {"has_focus" : has_focus}, int(not has_focus), int(has_focus))                                                      
  File "/usr/lib/python3/dist-packages/xpra/server/window/batch_delay_calculator.py", line 53, in mayaddfac                                
    factors.append((metric, info, factor, weight))                                                                                         
AttributeError: 'tuple' object has no attribute 'append'  
```
This happens when running this app:
https://github.com/rordenlab/MRIcroGL/releases/tag/v1.2.20220720

Maybe this is already fixed, if so I'm sorry.

**Comment by totaam** [comment]
Already fixed in 3ad7474352af5f17f84f05c5db4dc95e5d440e33

**Comment by iDmple** [comment]
Ty!! I will update

**Comment by iDmple** [comment]
I updated to commit fe63a6882daf7f5db40a2519bb5da91560e12407

and got this error:
```
2023-06-05 11:57:02,048 client   1 title= 0.196166Ã-0.143068Ã-0.228613mm (103Ã150Ã97) =  19.2367
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xpra/server/window/window_source.py", line 2334, in refresh_timer_function
    self.timer_full_refresh()
  File "/usr/lib/python3/dist-packages/xpra/server/window/window_video_source.py", line 642, in timer_full_refresh
    super().timer_full_refresh()
  File "/usr/lib/python3/dist-packages/xpra/server/window/window_source.py", line 2353, in timer_full_refresh
    self.send_delayed_regions_excluding(now, regions, self.auto_refresh_encodings[0], options,
AttributeError: 'WindowVideoSource' object has no attribute 'send_delayed_regions_excluding'
```

**Comment by totaam** [comment]
Ooops: that was causing the auto-refresh to fail, the commit above fixes that.
