### ISSUE TITLE
AES python-cryptography regression

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#3896]
Discovered on MS Windows.

Connecting with `AES` and the correct keyfile:
```
2023-06-12 22:44:27,448 Xpra GTK3 client version 5.0-r33668 (g0e11c6775) beta
2023-06-12 22:44:27,464  running on Microsoft Windows 10
2023-06-12 22:44:30,057 GStreamer version 1.22.3
2023-06-12 22:44:30,206 created named pipe 'Xpra\\4624'
2023-06-12 22:44:30,468 keyboard layout 'United Kingdom' : 'gb' (0x809)
2023-06-12 22:44:30,590 get_encryption() connection options encryption='AES'
2023-06-12 22:44:30,592 get_encryption() connection options encryption='AES'
2023-06-12 22:44:30,592 encryption=AES
2023-06-12 22:44:30,592 crypto_backend_init() pycryptography=None
2023-06-12 22:44:30,593 failed to import commoncrypto
Traceback (most recent call last):
  File "E:/xpra/xpra/net/crypto.py", line 105, in patch_crypto_be_discovery
    from cryptography.hazmat.backends.commoncrypto.backend import backend as be_cc
ModuleNotFoundError: No module named 'cryptography.hazmat.backends.commoncrypto'
2023-06-12 22:44:30,596 loaded _ssl=<module '_ssl' from 'E:/xpra/dist/lib/_ssl.cp310-mingw_x86_64.pyd'>
2023-06-12 22:44:30,596 default_backend()=<OpenSSLBackend(version: OpenSSL 3.1.1 30 May 2023, FIPS: False, Legacy: False)>
2023-06-12 22:44:30,596 backends=[]
2023-06-12 22:44:30,597 validate_backend() will validate AES modes: CBC, GCM, CFB, CTR
2023-06-12 22:44:30,597 testing AES-CBC
2023-06-12 22:44:30,598 Error: cannot initialize python-cryptography
Traceback (most recent call last):
  File "E:/xpra/xpra/net/crypto.py", line 87, in crypto_backend_init
    validate_backend()
  File "E:/xpra/xpra/net/crypto.py", line 143, in validate_backend
    key = get_key(password, key_salt, key_hash, DEFAULT_KEYSIZE, iterations)
  File "E:/xpra/xpra/net/crypto.py", line 314, in get_key
    key = kdf.derive(strtobytes(password))
  File "C:/msys64/mingw64/lib/python3.10/site-packages/cryptography/hazmat/primitives/kdf/pbkdf2.py", line 53, in derive
    return rust_openssl.kdf.derive_pbkdf2_hmac(
TypeError: Expected instance of hashes.HashAlgorithm.
2023-06-12 22:44:30,599 error preparing connection: invalid encryption 'AES', options: 
Traceback (most recent call last):
  File "E:/xpra/xpra/client/base/client_base.py", line 381, in send_hello
    hello = self.make_hello_base()
  File "E:/xpra/xpra/client/base/client_base.py", line 460, in make_hello_base
    cipher_caps = self.get_cipher_caps()
  File "E:/xpra/xpra/client/base/client_base.py", line 479, in get_cipher_caps
    raise ValueError(f"invalid encryption {enc!r}, options: {csv(ciphers)}")
```

**Comment by totaam** [comment]
Fixed in b34a198a30fb734afb51d8e0767cc2fe93f55b11
