### ISSUE TITLE
TypeError: %x format: an integer is required, not X11Window

### ISSUE THREAD

**Issue by s-kotte** [Xpra-org/xpra#3915]
**Describe the bug**
I get the following error message after some time (randomly) `TypeError: %x format: an integer is required, not X11Window`. After that it is no longer possible to interact with the program, it seems to be frozen. `xpra recover` did not fix the problem.

**To Reproduce**
Unfortunately, I have not found a way to reproduce this. It happens randomly, e.g. after a few hours. 
1. `xpra start --start-child-after-connect="wine ./program/LCS.exe" --bind-tcp=0.0.0.0:8085 --no-daemon -d x11`
2. I usually notice the error when I resize the window, I don't know if that's the reason.

**System Information:**
 - Server OS: Ubuntu 20.04
 - Client OS: Ubuntu 20.04
 - Xpra Server Version: 4.4.6 (with xvfb)
 - Xpra Client Version: 7.0 (html5)

**Additional context**
Server log:
```
2023-07-07T14:12:57+02:00	2023-07-07 14:12:57,451 parse_event(..)=<X11:XKBNotify {'send_event': '0', 'serial': '0x6a3c', 'subtype': 'bell', 'device': '3', 'percent': '50', 'pitch': '400', 'duration': '100', 'bell_class': '0', 'bell_id': '0', 'window': '0x50e', 'event_only': 'False', 'delivered_to': '0x50e', 'window_model': 'None', 'bell_name': ''}>
2023-07-07T14:12:57+02:00	2023-07-07 14:12:57,451 x_event_filter event=('xpra-xkb-event', None)/XKBNotify took 1.0ms
2023-07-07T14:12:57+02:00	2023-07-07 14:12:57,512 do_process_mouse_common(WebSocket(ws socket: 10.136.1.228:8085 <- 10.136.0.153:56216), 4, (584, 277), -1)
2023-07-07T14:12:57+02:00	2023-07-07 14:12:57,512 <bound method XTestPointerDevice.click of XTestPointerDevice>(1, False, ())
2023-07-07T14:12:57+02:00	2023-07-07 14:12:57,512 xtest_fake_button(1, False)
2023-07-07T14:12:57+02:00	2023-07-07 14:12:57,613 do_process_mouse_common(WebSocket(ws socket: 10.136.1.228:8085 <- 10.136.0.153:56216), 4, (584, 277), -1)
2023-07-07T14:12:57+02:00	2023-07-07 14:12:57,613 <bound method XTestPointerDevice.click of XTestPointerDevice>(1, True, ())
2023-07-07T14:12:57+02:00	2023-07-07 14:12:57,613 xtest_fake_button(1, True)
2023-07-07T14:12:57+02:00	2023-07-07 14:12:57,614 x_event_filter event=('xpra-xkb-event', None)/XKBNotify window=0x26e0dc22
2023-07-07T14:12:57+02:00	2023-07-07 14:12:57,614 XKBNotify event received xkb_type=8
2023-07-07T14:12:57+02:00	--- Logging error ---
2023-07-07T14:12:57+02:00	Traceback (most recent call last):
2023-07-07T14:12:57+02:00	  File "/usr/lib/python3/dist-packages/xpra/log.py", line 498, in emit
2023-07-07T14:12:57+02:00	    msg = self.format(record)
2023-07-07T14:12:57+02:00	  File "/usr/lib/python3.8/logging/__init__.py", line 929, in format
2023-07-07T14:12:57+02:00	    return fmt.format(record)
2023-07-07T14:12:57+02:00	  File "/usr/lib/python3.8/logging/__init__.py", line 668, in format
2023-07-07T14:12:57+02:00	    record.message = record.getMessage()
2023-07-07T14:12:57+02:00	  File "/usr/lib/python3.8/logging/__init__.py", line 373, in getMessage
2023-07-07T14:12:57+02:00	    msg = msg % self.args
2023-07-07T14:12:57+02:00	TypeError: %x format: an integer is required, not X11Window
2023-07-07T14:12:57+02:00	Call stack:
2023-07-07T14:12:57+02:00	  File "/usr/bin/xpra", line 10, in <module>
2023-07-07T14:12:57+02:00	    sys.exit(main(sys.argv[0], sys.argv))
2023-07-07T14:12:57+02:00	  File "/usr/lib/python3/dist-packages/xpra/scripts/main.py", line 156, in main
2023-07-07T14:12:57+02:00	    return run_mode(script_file, cmdline, err, options, args, mode, defaults)
2023-07-07T14:12:57+02:00	  File "/usr/lib/python3/dist-packages/xpra/scripts/main.py", line 465, in run_mode
2023-07-07T14:12:57+02:00	    return do_run_mode(script_file, cmdline, error_cb, options, args, mode, defaults)
2023-07-07T14:12:57+02:00	  File "/usr/lib/python3/dist-packages/xpra/scripts/main.py", line 500, in do_run_mode
2023-07-07T14:12:57+02:00	    return run_server(script_file, cmdline, error_cb, options, args, mode, defaults)
2023-07-07T14:12:57+02:00	  File "/usr/lib/python3/dist-packages/xpra/scripts/main.py", line 1853, in run_server
2023-07-07T14:12:57+02:00	    return do_run_server(script_file, cmdline, error_cb, options, args, mode, display, defaults)
2023-07-07T14:12:57+02:00	  File "/usr/lib/python3/dist-packages/xpra/scripts/server.py", line 760, in do_run_server
2023-07-07T14:12:57+02:00	    return _do_run_server(script_file, cmdline,
2023-07-07T14:12:57+02:00	  File "/usr/lib/python3/dist-packages/xpra/scripts/server.py", line 1524, in _do_run_server
2023-07-07T14:12:57+02:00	    r = app.run()
2023-07-07T14:12:57+02:00	  File "/usr/lib/python3/dist-packages/xpra/server/server_core.py", line 446, in run
2023-07-07T14:12:57+02:00	    self.do_run()
2023-07-07T14:12:57+02:00	  File "/usr/lib/python3/dist-packages/xpra/server/gtk_server_base.py", line 129, in do_run
2023-07-07T14:12:57+02:00	    Gtk.main()
2023-07-07T14:12:57+02:00	  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 1632, in main
2023-07-07T14:12:57+02:00	    return _Gtk_main(*args, **kwargs)
2023-07-07T14:12:57+02:00	  File "/usr/lib/python3/dist-packages/xpra/log.py", line 460, in __call__
2023-07-07T14:12:57+02:00	    self.log(logging.DEBUG, msg, *args, **kwargs)
2023-07-07T14:12:57+02:00	  File "/usr/lib/python3/dist-packages/xpra/log.py", line 456, in log
2023-07-07T14:12:57+02:00	    global_logging_handler(self.logger.log, self.level_override or level, msg, *args, **kwargs)
2023-07-07T14:12:57+02:00	  File "/usr/lib/python3/dist-packages/xpra/log.py", line 146, in standard_logging
2023-07-07T14:12:57+02:00	    log(level, msg, *args, **kwargs)
2023-07-07T14:12:57+02:00	  File "/usr/lib/python3.8/logging/__init__.py", line 1512, in log
2023-07-07T14:12:57+02:00	    self._log(level, msg, args, **kwargs)
2023-07-07T14:12:57+02:00	  File "/usr/lib/python3.8/logging/__init__.py", line 1589, in _log
2023-07-07T14:12:57+02:00	    self.handle(record)
2023-07-07T14:12:57+02:00	  File "/usr/lib/python3.8/logging/__init__.py", line 1599, in handle
2023-07-07T14:12:57+02:00	    self.callHandlers(record)
2023-07-07T14:12:57+02:00	  File "/usr/lib/python3.8/logging/__init__.py", line 1661, in callHandlers
2023-07-07T14:12:57+02:00	    hdlr.handle(record)
2023-07-07T14:12:57+02:00	  File "/usr/lib/python3.8/logging/__init__.py", line 954, in handle
2023-07-07T14:12:57+02:00	    self.emit(record)
2023-07-07T14:12:57+02:00	  File "/usr/lib/python3/dist-packages/xpra/log.py", line 508, in emit
2023-07-07T14:12:57+02:00	    self.handleError(record)
2023-07-07T14:12:57+02:00	Message: 'bell using root window=%#x'
2023-07-07T14:12:57+02:00	Arguments: (<GdkX11.X11Window object at 0x7f11c459ea00 (GdkX11Window at 0x199c750)>,)
2023-07-07T14:12:57+02:00	2023-07-07 14:12:57,615 parse_event(..)=<X11:XKBNotify {'send_event': '0', 'serial': '0x6a49', 'subtype': 'bell', 'device': '3', 'percent': '50', 'pitch': '400', 'duration': '100', 'bell_class': '0', 'bell_id': '0', 'window': '0x50e', 'event_only': 'False', 'delivered_to': '0x50e', 'window_model': 'None', 'bell_name': ''}>
2023-07-07T14:12:57+02:00	2023-07-07 14:12:57,615 x_event_filter event=('xpra-xkb-event', None)/XKBNotify took 0.6ms
2023-07-07T14:12:57+02:00	2023-07-07 14:12:57,678 do_process_mouse_common(WebSocket(ws socket: 10.136.1.228:8085 <- 10.136.0.153:56216), 4, (584, 277), -1)
2023-07-07T14:12:57+02:00	2023-07-07 14:12:57,678 <bound method XTestPointerDevice.click of XTestPointerDevice>(1, False, ())
2023-07-07T14:12:57+02:00	2023-07-07 14:12:57,678 xtest_fake_button(1, False)
2023-07-07T14:12:57+02:00	2023-07-07 14:12:57,780 do_process_mouse_common(WebSocket(ws socket: 10.136.1.228:8085 <- 10.136.0.153:56216), 4, (584, 277), -1)
2023-07-07T14:12:57+02:00	2023-07-07 14:12:57,780 <bound method XTestPointerDevice.click of XTestPointerDevice>(1, True, ())
2023-07-07T14:12:57+02:00	2023-07-07 14:12:57,780 xtest_fake_button(1, True)
2023-07-07T14:12:57+02:00	2023-07-07 14:12:57,781 x_event_filter event=('xpra-xkb-event', None)/XKBNotify window=0x26e0dcc8
2023-07-07T14:12:57+02:00	2023-07-07 14:12:57,781 XKBNotify event received xkb_type=8
2023-07-07T14:12:57+02:00	--- Logging error ---
2023-07-07T14:12:57+02:00	Traceback (most recent call last):
2023-07-07T14:12:57+02:00	  File "/usr/lib/python3/dist-packages/xpra/log.py", line 498, in emit
2023-07-07T14:12:57+02:00	    msg = self.format(record)
2023-07-07T14:12:57+02:00	  File "/usr/lib/python3.8/logging/__init__.py", line 929, in format
2023-07-07T14:12:57+02:00	    return fmt.format(record)
2023-07-07T14:12:57+02:00	  File "/usr/lib/python3.8/logging/__init__.py", line 668, in format
2023-07-07T14:12:57+02:00	    record.message = record.getMessage()
2023-07-07T14:12:57+02:00	  File "/usr/lib/python3.8/logging/__init__.py", line 373, in getMessage
2023-07-07T14:12:57+02:00	    msg = msg % self.args
2023-07-07T14:12:57+02:00	TypeError: %x format: an integer is required, not X11Window
2023-07-07T14:12:57+02:00	Call stack:
2023-07-07T14:12:57+02:00	  File "/usr/bin/xpra", line 10, in <module>
2023-07-07T14:12:57+02:00	    sys.exit(main(sys.argv[0], sys.argv))
2023-07-07T14:12:57+02:00	  File "/usr/lib/python3/dist-packages/xpra/scripts/main.py", line 156, in main
2023-07-07T14:12:57+02:00	    return run_mode(script_file, cmdline, err, options, args, mode, defaults)
2023-07-07T14:12:57+02:00	  File "/usr/lib/python3/dist-packages/xpra/scripts/main.py", line 465, in run_mode
2023-07-07T14:12:57+02:00	    return do_run_mode(script_file, cmdline, error_cb, options, args, mode, defaults)
2023-07-07T14:12:57+02:00	  File "/usr/lib/python3/dist-packages/xpra/scripts/main.py", line 500, in do_run_mode
2023-07-07T14:12:57+02:00	    return run_server(script_file, cmdline, error_cb, options, args, mode, defaults)
2023-07-07T14:12:57+02:00	  File "/usr/lib/python3/dist-packages/xpra/scripts/main.py", line 1853, in run_server
2023-07-07T14:12:57+02:00	    return do_run_server(script_file, cmdline, error_cb, options, args, mode, display, defaults)
2023-07-07T14:12:57+02:00	  File "/usr/lib/python3/dist-packages/xpra/scripts/server.py", line 760, in do_run_server
2023-07-07T14:12:57+02:00	    return _do_run_server(script_file, cmdline,
2023-07-07T14:12:57+02:00	  File "/usr/lib/python3/dist-packages/xpra/scripts/server.py", line 1524, in _do_run_server
2023-07-07T14:12:57+02:00	    r = app.run()
2023-07-07T14:12:57+02:00	  File "/usr/lib/python3/dist-packages/xpra/server/server_core.py", line 446, in run
2023-07-07T14:12:57+02:00	    self.do_run()
2023-07-07T14:12:57+02:00	  File "/usr/lib/python3/dist-packages/xpra/server/gtk_server_base.py", line 129, in do_run
2023-07-07T14:12:57+02:00	    Gtk.main()
2023-07-07T14:12:57+02:00	  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 1632, in main
2023-07-07T14:12:57+02:00	    return _Gtk_main(*args, **kwargs)
2023-07-07T14:12:57+02:00	  File "/usr/lib/python3/dist-packages/xpra/log.py", line 460, in __call__
2023-07-07T14:12:57+02:00	    self.log(logging.DEBUG, msg, *args, **kwargs)
2023-07-07T14:12:57+02:00	  File "/usr/lib/python3/dist-packages/xpra/log.py", line 456, in log
2023-07-07T14:12:57+02:00	    global_logging_handler(self.logger.log, self.level_override or level, msg, *args, **kwargs)
2023-07-07T14:12:57+02:00	  File "/usr/lib/python3/dist-packages/xpra/log.py", line 146, in standard_logging
2023-07-07T14:12:57+02:00	    log(level, msg, *args, **kwargs)
2023-07-07T14:12:57+02:00	  File "/usr/lib/python3.8/logging/__init__.py", line 1512, in log
2023-07-07T14:12:57+02:00	    self._log(level, msg, args, **kwargs)
2023-07-07T14:12:57+02:00	  File "/usr/lib/python3.8/logging/__init__.py", line 1589, in _log
2023-07-07T14:12:57+02:00	    self.handle(record)
2023-07-07T14:12:57+02:00	  File "/usr/lib/python3.8/logging/__init__.py", line 1599, in handle
2023-07-07T14:12:57+02:00	    self.callHandlers(record)
2023-07-07T14:12:57+02:00	  File "/usr/lib/python3.8/logging/__init__.py", line 1661, in callHandlers
2023-07-07T14:12:57+02:00	    hdlr.handle(record)
2023-07-07T14:12:57+02:00	  File "/usr/lib/python3.8/logging/__init__.py", line 954, in handle
2023-07-07T14:12:57+02:00	    self.emit(record)
2023-07-07T14:12:57+02:00	  File "/usr/lib/python3/dist-packages/xpra/log.py", line 508, in emit
2023-07-07T14:12:57+02:00	    self.handleError(record)
2023-07-07T14:12:57+02:00	Message: 'bell using root window=%#x'
2023-07-07T14:12:57+02:00	Arguments: (<GdkX11.X11Window object at 0x7f11c459ea00 (GdkX11Window at 0x199c750)>,)
```

**Comment by totaam** [comment]
The commit above should fix the error shown in your log, which is related to bell events.
This error only occurs when `x11` debugging is enabled, so this is not a big problem.

> After that it is no longer possible to interact with the program, it seems to be frozen

That's odd.
I would have expected this bell event to be missed by xpra but other events should continue as before.
Perhaps there is a separate issue.

**Comment by s-kotte** [comment]
Ok, thanks for the logging fix. If the error occurs again, I will create a new issue.
