### ISSUE TITLE
Mac: No keyboard support due to internal python error

### ISSUE THREAD

**Issue by gbmerrall** [Xpra-org/xpra#3934]
**Describe the bug**
When starting Xpra on my Mac, the following error appears in the startup log info. As a result all keyboard input is disabled in Xpra.

```
Warning: no keyboard support, dlopen(/Applications/Xpra.app/Contents/Resources/lib/python/lib-dynload/objc/_objc.so, 0x0002): symbol not found in flat namespace '_ffi_find_closure_for_code_np'
```

Full traceback
```
Traceback (most recent call last):
  File "/Applications/Xpra.app/Contents/Resources/lib/python/xpra/scripts/main.py", line 156, in main
    return run_mode(script_file, cmdline, err, options, args, mode, defaults)
  File "/Applications/Xpra.app/Contents/Resources/lib/python/xpra/scripts/main.py", line 465, in run_mode
    return do_run_mode(script_file, cmdline, error_cb, options, args, mode, defaults)
  File "/Applications/Xpra.app/Contents/Resources/lib/python/xpra/scripts/main.py", line 610, in do_run_mode
    return run_splash(args)
  File "/Applications/Xpra.app/Contents/Resources/lib/python/xpra/scripts/main.py", line 2195, in run_splash
    return splash_screen.main(args)
  File "/Applications/Xpra.app/Contents/Resources/lib/python/xpra/client/gtk3/splash_screen.py", line 288, in main
    with program_context("splash", "Splash"):
  File "/Applications/Xpra.app/Contents/Resources/lib/python/xpra/platform/__init__.py", line 38, in __enter__
    init(self.prgname, self.appname)
  File "/Applications/Xpra.app/Contents/Resources/lib/python/xpra/platform/__init__.py", line 23, in init
    do_init()
  File "/Applications/Xpra.app/Contents/Resources/lib/python/xpra/platform/darwin/__init__.py", line 16, in do_init
    from AppKit import NSApp    #@UnresolvedImport
  File "AppKit/__init__.pyc", line 10, in <module>
  File "Foundation/__init__.pyc", line 9, in <module>
  File "CoreFoundation/__init__.pyc", line 9, in <module>
  File "objc/__init__.pyc", line 6, in <module>
  File "objc/_objc.pyc", line 14, in <module>
  File "objc/_objc.pyc", line 10, in __load
  File "imp.pyc", line 343, in load_dynamic
ImportError: dlopen(/Applications/Xpra.app/Contents/Resources/lib/python/lib-dynload/objc/_objc.so, 0x0002): symbol not found in flat namespace '_ffi_find_closure_for_code_np'
```

**To Reproduce**
1. server command
```
/usr/bin/xpra start :100 --systemd-run=no
```

3. client command
```
xpra attach --video-scaling=off --desktop-scaling=off --dpi=96 --ssh=/usr/bin/ssh 'ssh://user@192.168.xx.xx/:100'
```

5. specific action to trigger the bug
Connecting.

**System Information (please complete the following information):**
 - Server OS: [e.g. RHEL 8.x] Ubuntu 20.04 Focal
 - Client OS: [e.g. Windows 10] Mac Ventura13.4.1 (c) 
 - Xpra Server Version [e.g. 4.2.3]

```
$ xpra --version
xpra v4.4.6-r29
```

 - Xpra Client Version [e.g. 4.3]

> `2023-07-24 11:54:20,479 Xpra GTK3 client version 4.4.6-r29 64-bit`
> `2023-07-24 11:54:20,500  running on Mac OS X 13.4.1`

**Additional context**
Please see "reporting bugs" in the wiki section.

Xpra installed via Mac app download - not homebrew
Python on Mac: Python 3.10.10 (via pyenv)

```
$ pyenv which python
/Users/xx/.pyenv/versions/3.10.10/bin/python
```

**Comment by totaam** [comment]
> `Warning: no keyboard support`

This  does not match the backtrace you provided, which happens in the splash screen.

> `xpra attach --video-scaling=off --desktop-scaling=off --dpi=96 --ssh=/usr/bin/ssh 'ssh://user@192.168.xx.xx/:100'`
> (..)
> specific action to trigger the bug
> Connecting.

Connecting? Is this really necessary?
If there is a problem when importing `xpra/platform/darwin/__init__.py`, running just `xpra` should also trigger it.
Does it?


> Xpra installed via Mac app download - not homebrew
> Python on Mac: Python 3.10.10 (via pyenv)

Red flag.
Xpra does not use the system python or any other python installed on your local system.
Perhaps this pyenv version is somehow interfering, or a leftover from another installation.
Please remove it / move it out of the way and ensure your environment is clean before running xpra directly from the DMG:
`/Volumes/Xpra/Xpra.app/Contents/MacOS/Xpra`

---

Otherwise, this could be related to the `ffi` problems in https://github.com/Xpra-org/gtk-osx-build/issues/22#issuecomment-1448276050

**Comment by gbmerrall** [comment]
Thanks for response. I assumed the errors were releated due to the warning about keyboard support and the dlopen failure being on the same line. 

> If there is a problem when importing xpra/platform/darwin/__init__.py, running just xpra should also trigger it.
> Does it?
Yes same error ocurs. 

> Red flag.
> Xpra does not use the system python or any other python installed on your local system.
> Perhaps this pyenv version is somehow interfering, or a leftover from another installation.
> Please remove it / move it out of the way and ensure your environment is clean before running xpra directly from the DMG:

Thanks. Didn't realise it used bundled Python so I included this for the sake of completeness. Regardless have moved it out of the way.
Downlaoded https://xpra.org/dists/MacOS/arm64/Xpra-Python3-arm64-4.4.6-r29.dmg

Issue still occurs
$ /Volumes/Xpra/Xpra.app/Contents/MacOS/Xpra
```
grep: /usr/share/locale/locale.alias: No such file or directory
xpra main error:
Traceback (most recent call last):
  File "/Volumes/Xpra/Xpra.app/Contents/Resources/lib/python/xpra/scripts/main.py", line 156, in main
    return run_mode(script_file, cmdline, err, options, args, mode, defaults)
  File "/Volumes/Xpra/Xpra.app/Contents/Resources/lib/python/xpra/scripts/main.py", line 465, in run_mode
    return do_run_mode(script_file, cmdline, error_cb, options, args, mode, defaults)
  File "/Volumes/Xpra/Xpra.app/Contents/Resources/lib/python/xpra/scripts/main.py", line 567, in do_run_mode
    return gui.main(cmdline)
  File "/Volumes/Xpra/Xpra.app/Contents/Resources/lib/python/xpra/gtk_common/gui.py", line 262, in main
    from xpra.platform.darwin.gui import wait_for_open_handlers
  File "/Volumes/Xpra/Xpra.app/Contents/Resources/lib/python/xpra/platform/darwin/gui.py", line 14, in <module>
    import objc                         #@UnresolvedImport
  File "objc/__init__.pyc", line 6, in <module>
  File "objc/_objc.pyc", line 14, in <module>
  File "objc/_objc.pyc", line 10, in __load
  File "imp.pyc", line 343, in load_dynamic
ImportError: dlopen(/Volumes/Xpra/Xpra.app/Contents/Resources/lib/python/lib-dynload/objc/_objc.so, 0x0002): symbol not found in flat namespace '_ffi_find_closure_for_code_np'
```

I ran from the DMG with '-d keyboard' . Output below.

> Edit: is this x86_64 or arm64?
arm64 

Log output
```
grep: /usr/share/locale/locale.alias: No such file or directory
2023-07-25 10:23:59,112 debug enabled for xpra.gtk_common.keymap / ('keyboard',)
2023-07-25 10:23:59,146 debug enabled for xpra.client.client_window_base / ('keyboard',)
2023-07-25 10:23:59,146 debug enabled for xpra.client.gtk_base.gtk_client_window_base / ('keyboard',)
2023-07-25 10:23:59,146 debug enabled for xpra.client.gtk_base.gtk_client_window_base / ('keyboard', 'events')
grep: /usr/share/locale/locale.alias: No such file or directory
2023-07-25 10:23:59,231 debug enabled for xpra.client.keyboard_shortcuts_parser / ('keyboard',)
2023-07-25 10:23:59,231 debug enabled for xpra.client.keyboard_helper / ('keyboard',)
2023-07-25 10:23:59,254 debug enabled for xpra.client.ui_client_base / ('client', 'keyboard')
2023-07-25 10:23:59,299 Xpra GTK3 client version 4.4.6-r29 64-bit
2023-07-25 10:23:59,369  running on Mac OS X 13.4.1
xpra main error:
Traceback (most recent call last):
  File "/Volumes/Xpra/Xpra.app/Contents/Resources/lib/python/xpra/scripts/main.py", line 156, in main
    return run_mode(script_file, cmdline, err, options, args, mode, defaults)
  File "/Volumes/Xpra/Xpra.app/Contents/Resources/lib/python/xpra/scripts/main.py", line 465, in run_mode
    return do_run_mode(script_file, cmdline, error_cb, options, args, mode, defaults)
  File "/Volumes/Xpra/Xpra.app/Contents/Resources/lib/python/xpra/scripts/main.py", line 610, in do_run_mode
    return run_splash(args)
  File "/Volumes/Xpra/Xpra.app/Contents/Resources/lib/python/xpra/scripts/main.py", line 2195, in run_splash
    return splash_screen.main(args)
  File "/Volumes/Xpra/Xpra.app/Contents/Resources/lib/python/xpra/client/gtk3/splash_screen.py", line 288, in main
    with program_context("splash", "Splash"):
  File "/Volumes/Xpra/Xpra.app/Contents/Resources/lib/python/xpra/platform/__init__.py", line 38, in __enter__
    init(self.prgname, self.appname)
  File "/Volumes/Xpra/Xpra.app/Contents/Resources/lib/python/xpra/platform/__init__.py", line 23, in init
    do_init()
  File "/Volumes/Xpra/Xpra.app/Contents/Resources/lib/python/xpra/platform/darwin/__init__.py", line 16, in do_init
    from AppKit import NSApp    #@UnresolvedImport
  File "AppKit/__init__.pyc", line 10, in <module>
  File "Foundation/__init__.pyc", line 9, in <module>
  File "CoreFoundation/__init__.pyc", line 9, in <module>
  File "objc/__init__.pyc", line 6, in <module>
  File "objc/_objc.pyc", line 14, in <module>
  File "objc/_objc.pyc", line 10, in __load
  File "imp.pyc", line 343, in load_dynamic
ImportError: dlopen(/Volumes/Xpra/Xpra.app/Contents/Resources/lib/python/lib-dynload/objc/_objc.so, 0x0002): symbol not found in flat namespace '_ffi_find_closure_for_code_np'

grep: /usr/share/locale/locale.alias: No such file or directory
2023-07-25 10:24:00,976 GStreamer version 1.22.3
2023-07-25 10:24:01,525 created unix domain socket '/Users/gmerrall/.xpra/clients/gmerrall-macbookpro3.roam.internal-19934'
2023-07-25 10:24:02,021 debug enabled for xpra.platform.keyboard_base / ('keyboard',)
2023-07-25 10:24:02,027 error instantiating <class 'xpra.client.gtk_base.gtk_keyboard_helper.GTKKeyboardHelper'>
Traceback (most recent call last):
  File "/Volumes/Xpra/Xpra.app/Contents/Resources/lib/python/xpra/client/ui_client_base.py", line 203, in init_ui
    self.keyboard_helper = self.keyboard_helper_class(send_keyboard, opts.keyboard_sync,
  File "/Volumes/Xpra/Xpra.app/Contents/Resources/lib/python/xpra/client/gtk_base/gtk_keyboard_helper.py", line 18, in __init__
    KeyboardHelper.__init__(self, *args)
  File "/Volumes/Xpra/Xpra.app/Contents/Resources/lib/python/xpra/client/keyboard_helper.py", line 44, in __init__
    from xpra.platform.keyboard import Keyboard
  File "/Volumes/Xpra/Xpra.app/Contents/Resources/lib/python/xpra/platform/keyboard.py", line 13, in <module>
    platform_import(globals(), "keyboard", True,
  File "/Volumes/Xpra/Xpra.app/Contents/Resources/lib/python/xpra/platform/__init__.py", line 129, in platform_import
    platform_module = __import__(module, {}, {}, imports)
  File "/Volumes/Xpra/Xpra.app/Contents/Resources/lib/python/xpra/platform/darwin/keyboard.py", line 13, in <module>
    from xpra.platform.darwin.osx_menu import getOSXMenuHelper
  File "/Volumes/Xpra/Xpra.app/Contents/Resources/lib/python/xpra/platform/darwin/osx_menu.py", line 19, in <module>
    from xpra.platform.darwin.gui import get_OSXApplication
  File "/Volumes/Xpra/Xpra.app/Contents/Resources/lib/python/xpra/platform/darwin/gui.py", line 14, in <module>
    import objc                         #@UnresolvedImport
  File "objc/__init__.pyc", line 6, in <module>
  File "objc/_objc.pyc", line 14, in <module>
  File "objc/_objc.pyc", line 10, in __load
  File "imp.pyc", line 343, in load_dynamic
ImportError: dlopen(/Volumes/Xpra/Xpra.app/Contents/Resources/lib/python/lib-dynload/objc/_objc.so, 0x0002): symbol not found in flat namespace '_ffi_find_closure_for_code_np'
2023-07-25 10:24:02,028 Warning: no keyboard support, dlopen(/Volumes/Xpra/Xpra.app/Contents/Resources/lib/python/lib-dynload/objc/_objc.so, 0x0002): symbol not found in flat namespace '_ffi_find_closure_for_code_np'
2023-07-25 10:24:02,281  desktop size is 3440x1440:
2023-07-25 10:24:02,281   gmerrall-macbookpro3.lan (910x381 mm - DPI: 96x96)
2023-07-25 10:24:02,281     monitor 1        (801x338 mm - DPI: 109x108) workarea: 3440x1360 at    0x25
2023-07-25 10:24:02,388 enabled remote logging
2023-07-25 10:24:02,388 Xpra X11 seamless server version 4.4
2023-07-25 10:24:02,389 Warning: no clipboard support
2023-07-25 10:24:02,389 Attached to xpra server at 192.168.86.234:22
2023-07-25 10:24:02,389  (press Control-C to detach)

2023-07-25 10:24:02,713 running
2023-07-25 10:24:04,033 Xpra OpenGL Acceleration Failure
2023-07-25 10:24:04,033 probe error

```

**Comment by totaam** [comment]
I can reproduce the problem on the build env.

Until this is fixed, you may be able to use the `x86_64` builds.

**Comment by totaam** [comment]
@gbmerrall The fix comes from upstream:
https://github.com/Xpra-org/gtk-osx-build/issues/28#issuecomment-1650153738

You can find new 4.4.7 RC build here with all these fixes:
https://xpra.org/beta/MacOS/arm64/
(there are no `x86_64` builds yet)

**Comment by gbmerrall** [comment]
Unfortunately I'm not getting an alternate error from the DMG downloaded from https://xpra.org/beta/MacOS/arm64/Xpra-Python3-arm64-4.4.7-r22.dmg

This relates to freetype which I was referenced in the PR from that issue so perhaps a regression has crept in?

$ /Volumes/Xpra/Xpra.app/Contents/MacOS/Xpra 
```
xpra main error:
Traceback (most recent call last):
  File "/Volumes/Xpra/Xpra.app/Contents/Resources/lib/python/gi/importer.py", line 142, in load_module
    introspection_module = get_introspection_module(namespace)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Xpra/Xpra.app/Contents/Resources/lib/python/gi/module.py", line 263, in get_introspection_module
    module = IntrospectionModule(namespace, version)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Xpra/Xpra.app/Contents/Resources/lib/python/gi/module.py", line 110, in __init__
    repository.require(namespace, version)
gi.RepositoryError: Typelib file for namespace 'freetype2', version '2.0' not found

During handling of the above exception, another exception occurred:


Traceback (most recent call last):
  File "/Volumes/Xpra/Xpra.app/Contents/Resources/lib/python/xpra/scripts/main.py", line 144, in main
    defaults = make_defaults_struct()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Xpra/Xpra.app/Contents/Resources/lib/python/xpra/scripts/config.py", line 1296, in make_defaults_struct
    return do_make_defaults_struct(extras_defaults or {}, extras_types or {}, extras_validation or {},
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Xpra/Xpra.app/Contents/Resources/lib/python/xpra/scripts/config.py", line 1304, in do_make_defaults_struct
    defaults = read_xpra_defaults(username, uid, gid)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Xpra/Xpra.app/Contents/Resources/lib/python/xpra/scripts/config.py", line 429, in read_xpra_defaults
    dirs = get_xpra_defaults_dirs(username, uid, gid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Xpra/Xpra.app/Contents/Resources/lib/python/xpra/scripts/config.py", line 450, in get_xpra_defaults_dirs
    dirs = get_default_conf_dirs() + get_system_conf_dirs() + get_user_conf_dirs(uid)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Xpra/Xpra.app/Contents/Resources/lib/python/xpra/platform/paths.py", line 81, in get_default_conf_dirs
    return envaslist_or_delegate("XPRA_DEFAULT_CONF_DIRS", do_get_default_conf_dirs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Xpra/Xpra.app/Contents/Resources/lib/python/xpra/platform/paths.py", line 27, in envaslist_or_delegate
    return impl(*args)
           ^^^^^^^^^^^
  File "/Volumes/Xpra/Xpra.app/Contents/Resources/lib/python/xpra/platform/darwin/paths.py", line 75, in do_get_default_conf_dirs
    return [os.path.join(get_resources_dir(), "etc", "xpra")]
                         ^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Xpra/Xpra.app/Contents/Resources/lib/python/xpra/platform/paths.py", line 199, in get_resources_dir
    return env_or_delegate("XPRA_RESOURCES_DIR", do_get_resources_dir)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Xpra/Xpra.app/Contents/Resources/lib/python/xpra/platform/paths.py", line 32, in env_or_delegate
    return impl(*args)
           ^^^^^^^^^^^
  File "/Volumes/Xpra/Xpra.app/Contents/Resources/lib/python/xpra/platform/darwin/paths.py", line 27, in do_get_resources_dir
    macapp = get_OSXApplication()
             ^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Xpra/Xpra.app/Contents/Resources/lib/python/xpra/platform/darwin/__init__.py", line 41, in get_OSXApplication
    from gi.repository import GtkosxApplication #@UnresolvedImport
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Xpra/Xpra.app/Contents/Resources/lib/python/gi/importer.py", line 144, in load_module
    raise ImportError(e)
ImportError: Typelib file for namespace 'freetype2', version '2.0' not found
```

**Comment by totaam** [comment]
Sorry about that, the GTK updates brought in a new dependency and somehow the binary image was still finding it on the system I was testing on by using a fallback path pointing to my build environment.
I have re-tested with the environment temporarily moved out of the way and reproduced the bug, then applied 0ca49bc38814a043ee578d04c1f52d5d615391d3 and re-tested again.
It should be OK now. (r33880 and later)

**Comment by totaam** [comment]
I assume that this is no longer a problem with v5.

**Comment by zhaofengli** [comment]
Sadly this still seems to be a problem with the ARM version of 5.0.4-r1 on macOS 14.4 beta:

```

❯ /Applications/Xpra.app/Contents/MacOS/Xpra attach --ssh=ssh ssh:host:10
grep: /usr/share/locale/locale.alias: No such file or directory
grep: /usr/share/locale/locale.alias: No such file or directory

2024-02-04 21:46:21,014 Xpra GTK3 client version 5.0.4-r1
2024-02-04 21:46:21,034  running on Mac OS X
xpra main error:
Traceback (most recent call last):
  File "/Applications/Xpra.app/Contents/Resources/lib/python/xpra/scripts/main.py", line 121, in main
    return run_mode(script_file, cmdline, err, options, args, mode, defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/Xpra.app/Contents/Resources/lib/python/xpra/scripts/main.py", line 455, in run_mode
    return do_run_mode(script_file, cmdline, error_cb, options, args, mode, defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/Xpra.app/Contents/Resources/lib/python/xpra/scripts/main.py", line 642, in do_run_mode
    return run_splash(args)
           ^^^^^^^^^^^^^^^^
  File "/Applications/Xpra.app/Contents/Resources/lib/python/xpra/scripts/main.py", line 2395, in run_splash
    return splash_screen.main(args)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/Xpra.app/Contents/Resources/lib/python/xpra/splash_screen.py", line 294, in main
    with program_context("splash", "Splash"):
  File "/Applications/Xpra.app/Contents/Resources/lib/python/xpra/platform/__init__.py", line 79, in __enter__
    init(self.prgname, self.appname)
  File "/Applications/Xpra.app/Contents/Resources/lib/python/xpra/platform/__init__.py", line 24, in init
    do_init()
  File "/Applications/Xpra.app/Contents/Resources/lib/python/xpra/platform/darwin/__init__.py", line 15, in do_init
    from AppKit import NSApp    #@UnresolvedImport
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "AppKit/__init__.pyc", line 148, in <module>
  File "AppKit/__init__.pyc", line 12, in _setup
  File "Foundation/__init__.pyc", line 188, in <module>
  File "Foundation/__init__.pyc", line 12, in _setup
  File "CoreFoundation/__init__.pyc", line 37, in <module>
  File "CoreFoundation/__init__.pyc", line 12, in _setup
  File "objc/__init__.pyc", line 6, in <module>
  File "objc/_objc.pyc", line 14, in <module>
  File "objc/_objc.pyc", line 10, in __load
  File "imp.pyc", line 343, in load_dynamic
ImportError: dlopen(/Applications/Xpra.app/Contents/Resources/lib/python/lib-dynload/objc/_objc.so, 0x0002): symbol not found in flat namespace '_ffi_find_closure_for_code_np'
```

(Installed from `Xpra-arm64-5.0.4-r1.dmg`)
