### ISSUE TITLE
Xpra Startup Error: Unable to import OpenGL.arrays.numpymodule.NumpyHandler

### ISSUE THREAD

**Issue by nanangarsyad** [Xpra-org/xpra#3947]
I am using the Xpra distribution downloaded from the Github release page (version 4.4.6-r29) on Windows 11. I try to start it with the command: 
```
❯ .\Xpra_cmd.exe start --start=alacritty --clipboard=yes --clipboard-direction=both --remote-clipboard=CLIPBOARD ssh:abc@xyz:1001
```

However, I'm encountering an issue where the numpy module does not seem to load correctly, resulting in an error with importing OpenGL.arrays.numpymodule.NumpyHandler. The specific error message is:

```
Original error was: DLL load failed while importing _multiarray_umath: The specified module could not be found.
```

The Python version being used is Python3.10, bundled with Xpra. The NumPy version is 1.24.3.

Additionally, I see warnings regarding an 'audio' option but I'm not sure if it's related to the numpy error.

To isolate the problem, I tried running the command below separately,
```
❯ .\Python_exec_cmd.exe "import numpy"
```
which also produced the same error.

Thank you

---

Here is the full log:

```
❯ .\Xpra_cmd.exe start --start=alacritty --clipboard=yes --clipboard-direction=both --remote-clipboard=CLIPBOARD ssh:abc@xyz:1001
Warning: invalid option: 'audio'

Warning: invalid option: 'audio'

2023-07-30 12:46:52,702 Xpra GTK3 client version 4.4.6-r29 64-bit
2023-07-30 12:46:52,745  running on Microsoft Windows 10
Warning: invalid option: 'audio'

2023-07-30 12:46:54,261 GStreamer version 1.22.3
2023-07-30 12:46:54,267 created named pipe 'Xpra\31252'
2023-07-30 12:46:54,326 keyboard layout 'United States - English' : 'us' (0x409)
2023-07-30 12:46:54,733 Unable to import OpenGL.arrays.numpymodule.NumpyHandler: No numpy module present:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "D:\apps\xpra\Xpra-Python3-x86_64_4.4.6-r29\Xpra_cmd.exe"
  * The NumPy version is: "1.24.3"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed while importing _multiarray_umath: The specified module could not be found.

2023-07-30 12:46:54,736 OpenGL enabled on 'NVIDIA GeForce RTX 2060/PCIe/SSE2'
2023-07-30 12:46:54,791 Connected (version 2.0, client OpenSSH_8.9p1)
```

```
❯ .\Python_exec_cmd.exe "import numpy"
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python3.10/site-packages/numpy/core/__init__.py", line 23, in <module>
  File "C:/msys64/mingw64/lib/python3.10/site-packages/numpy/core/multiarray.py", line 10, in <module>
  File "C:/msys64/mingw64/lib/python3.10/site-packages/numpy/core/overrides.py", line 6, in <module>
ImportError: DLL load failed while importing _multiarray_umath: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python3.10/site-packages/cx_Freeze/initscripts/__startup__.py", line 130, in run
  File "C:/msys64/mingw64/lib/python3.10/site-packages/cx_Freeze/initscripts/console.py", line 16, in run
  File "xpra/platform/win32/scripts/exec.py", line 20, in <module>
  File "<string>", line 1, in <module>
  File "C:/msys64/mingw64/lib/python3.10/site-packages/numpy/__init__.py", line 141, in <module>
  File "C:/msys64/mingw64/lib/python3.10/site-packages/numpy/core/__init__.py", line 49, in <module>
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "D:\apps\xpra\Xpra-Python3-x86_64_4.4.6-r29\Python_exec_cmd.exe"
  * The NumPy version is: "1.24.3"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed while importing _multiarray_umath: The specified module could not be found.

NativeCommandExitException: Program "Python_exec_cmd.exe" ended with non-zero exit code: 1.
```

**Comment by totaam** [comment]
> `-clipboard=yes --clipboard-direction=both --remote-clipboard=CLIPBOARD`

This does nothing as all these options use the default values.
> `ssh:abc@xyz:1001`

This form is deprecated.
Please use `ssh://abc@xyz/1001` instead.

> The NumPy version is 1.24.3.

Do you have numpy installed locally?
xpra is not designed to work with python modules installed outside its own installation directory.

> Warning: invalid option: 'audio'

This is a v5 option. Did you install xpra beta builds?
Did you clean everything afterwards?

Finally, does xpra run at all, even with these noisy numpy warnings?
ie:
`./Xpra_cmd.exe`
Does this show the GUI as expected?

**Comment by totaam** [comment]
Not heard back.
