### ISSUE TITLE
[Client, GL] `TypeError: object of type 'int' has no len()`

### ISSUE THREAD

**Issue by goekce** [Xpra-org/xpra#3959]
Client version: d11fa1b37
Server version: 31ffd107c
On ArchLinux with Intel OpenGL.

Xpra proxies a 3D program using VirtualGL. Sometimes the client throws this error:

```
TypeError: object of type 'int' has no len()
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/xpra/client/gl/gl_window_backing_base.py", line 1006, in set_cursor_data
    if not self.validate_cursor():
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xpra/client/gl/gl_window_backing_base.py", line 988, in validate_cursor
    if len(pixels)!=blen:
       ^^^^^^^^^^^
```

and sometimes this:
```
TypeError: object of type 'int' has no len()
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/xpra/client/base/client_base.py", line 1235, in call_handler
    handler(packet)
  File "/usr/lib/python3.11/site-packages/xpra/client/mixins/window_manager.py", line 586, in _process_cursor
    self.set_windows_cursor(self._id_to_window.values(), new_cursor)
  File "/usr/lib/python3.11/site-packages/xpra/client/gtk3/gtk_client_base.py", line 950, in set_windows_cursor
    w.set_cursor_data(cursor_data)
  File "/usr/lib/python3.11/site-packages/xpra/client/gtk3/gtk_client_window_base.py", line 798, in set_cursor_data
    self.when_realized("cursor", b.set_cursor_data, cursor_data)
  File "/usr/lib/python3.11/site-packages/xpra/client/gtk3/gtk_client_window_base.py", line 900, in when_realized
    callback(*args)
  File "/usr/lib/python3.11/site-packages/xpra/client/gl/gl_window_backing_base.py", line 1006, in set_cursor_data
    if not self.validate_cursor():
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xpra/client/gl/gl_window_backing_base.py", line 988, in validate_cursor
    if len(pixels)!=blen:
       ^^^^^^^^^^^
```

I can try with the latest version if needed. Currently I cannot pinpoint when this exactly occurs.

**Comment by totaam** [comment]
Can be reproduced using:
https://github.com/Xpra-org/xpra/blob/master/tests/xpra/test_apps/test_cursor_pixbuf.py
And the opengl renderer.

Fixed.
