### ISSUE TITLE
xpra client hangs when local monitor is turned off ("Exception: invalid window size")

### ISSUE THREAD

**Issue by luke-jr** [Xpra-org/xpra#3965]
**Describe the bug**
xpra client hangs when local monitor is turned off

**To Reproduce**
1. xpra start ...
2. open application
3. turn off monitor

**System Information (please complete the following information):**
 - Xpra Server Version 4.4
 - Xpra Client Version 4.4.5 (4.4.6 was too buggy to be usable)

**Additional context**

```
2023-08-18 18:29:17,835 window 1 has been moved to monitor 0: ACI HDMI-1 1920x1080 at 0,0
2023-08-18 18:29:17,835 configure event: current size=(1503, 1007), new size=(1503, 661), moved by=(0, 0), backing=gtk3.CairoBacking(ImageSurface(1503, 1007) : size=(1503, 1007), render_size=(1503, 1007)), iconified=False
2023-08-18 18:29:17,837 ['configure-window', 1, 208, 29, 1503, 661, {'encoding.render-size': (1503, 661)}, 0, {}, False, 1, (984, 632), []]
2023-08-18 18:29:17,837 configure event: queueing redraw
2023-08-18 18:29:17,837 configure event: current size=(1503, 661), new size=(1503, 661), moved by=(0, 0), backing=gtk3.CairoBacking(ImageSurface(1503, 661) : size=(1503, 661), render_size=(1503, 661)), iconified=False
2023-08-18 18:29:17,837 ['configure-window', 1, 208, 29, 1503, 661, {}, 0, {}, False, 1, (984, 632), []]
2023-08-18 18:29:17,837 configure event: queueing redraw
2023-08-18 18:29:17,838 configure event: current size=(1503, 661), new size=(1503, 65507), moved by=(0, 0), backing=gtk3.CairoBacking(ImageSurface(1503, 661) : size=(1503, 661), render_size=(1503, 661)), iconified=False
Traceback (most recent call last):
  File ".../xpra/client/gtk_base/gtk_client_window_base.py", line 2115, in do_configure_event
    self._set_backing_size(w, h)
  File ".../xpra/client/gtk_base/gtk_client_window_base.py", line 2155, in _set_backing_size
    raise Exception("invalid window size %ix%i" % (ww, wh))
Exception: invalid window size 1503x65507
```

**Comment by totaam** [comment]
> Xpra Server Version 4.4

This is not a supported version.

> Xpra Client Version 4.4.5 (4.4.6 was too buggy to be usable)

We're not aware of critical bugs in 4.4.6, 4.4.5 is not supported.

Missing DE, application specifics, etc

**Comment by luke-jr** [comment]
Modifying `do_configure_event` to return early if `h` is absurd (immediately after setting `h`) suppresses the exception, but doesn't prevent xpra from freezing.

**Comment by totaam** [comment]
Not heard back.
