### ISSUE TITLE
NameError: name 'avg' is not defined in session_info.py

### ISSUE THREAD

**Issue by allo-** [Xpra-org/xpra#3972]
**Describe the bug**

**To Reproduce**
1. xpra start
2. xpra connect
3. Choose Information -> Session Info in the tray menu

**System Information (please complete the following information):**
 - Server OS: Debian Bookworm
 - Client OS: Debian Trixie
 - Xpra Server Version xpra 5.0-r0-1
 - Xpra Client Version 5.0-r32900-1

**Additional context**
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xpra/client/gtk3/menu_helper.py", line 478, in show_session_info_cb
    self.show_session_info()
  File "/usr/lib/python3/dist-packages/xpra/client/gtk3/menu_helper.py", line 359, in show_session_info
    self.client.show_session_info(*args)
  File "/usr/lib/python3/dist-packages/xpra/client/gtk3/gtk_client_base.py", line 697, in show_session_info
    self.session_info = SessionInfo(self, self.session_name, conn)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/xpra/client/gtk3/session_info.py", line 491, in __init__
    self.populate_all()
  File "/usr/lib/python3/dist-packages/xpra/client/gtk3/session_info.py", line 582, in populate_all
    p_cb()
  File "/usr/lib/python3/dist-packages/xpra/client/gtk3/session_info.py", line 1049, in populate_statistics
    setall(self.quality_labels, self.all_values_from_info("quality", "encoding.quality"))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/xpra/client/gtk3/session_info.py", line 1009, in all_values_from_info
    return getv("cur", avg), getv("min", min), getv("avg", avg), getv("90p", avg), getv("max", max)
                       ^^^
NameError: name 'avg' is not defined
```

**Comment by totaam** [comment]
Already fixed in ad068ec9599c7d5f22a0762fb7d30d1edc7a51b2.

Your client is out of date because CUDA fails to build on Trixie: https://github.com/Xpra-org/xpra/issues/3808#issue-1642401991
