### ISSUE TITLE
run_mode error in /usr/lib64/python3.11/site-packages/xpra/scripts/main.py (Fedora 37)

### ISSUE THREAD

**Issue by angus73** [Xpra-org/xpra#3977]
**Describe the bug**
running "xpra info" outputs:

Warning: invalid compressor(s) specified: lzo
xpra main error:
Traceback (most recent call last):
  File "/usr/lib64/python3.11/site-packages/xpra/scripts/main.py", line 121, in main
    return run_mode(script_file, cmdline, err, options, args, mode, defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/xpra/scripts/main.py", line 421, in run_mode
    configure_network(options)
  File "/usr/lib64/python3.11/site-packages/xpra/scripts/main.py", line 226, in configure_network
    compression.init_compressors(*(list(options.compressors)+["none"]))
  File "/usr/lib64/python3.11/site-packages/xpra/net/compression.py", line 92, in init_compressors
    raise ValueError(f"{attr!r} is not callable")
ValueError: None is not callable

**System Information (please complete the following information):**
 - Server OS: Fedora 37
 - Client OS: error triggers even without trying to connect
 - Xpra Server Version: xpra v5.0-r0

**Additional context**
It used to work until the last upgrade. Thanks in advance for your help!

**Comment by totaam** [comment]
Your configuration is invalid.
`lzo` is not a valid compressor.

Use `xpra showsetting compressors` to see which file contains this invalid setting and fix it.
