### ISSUE TITLE
`ctypes.ArgumentError: argument 1: OverflowError: int too long to convert` + `failed to fixup window style: ctypes.ArgumentError: argument 3: TypeError: expected WinFunctionType instance instead of int`

### ISSUE THREAD

**Issue by stdedos** [Xpra-org/xpra#3988]
**Describe the bug**

```
"Xpra-x86_64_6.0-r34134\xpra_cmd" start ssh://user@ip/2 --ssh="plink -ssh -agent" --modal-windows=no --desktop-scaling=no --headerbar=off --source-start=gnome-keyring-daemon --start --title="@title@ on @@/@server-display@" --start="nohup systemd-inhibit --what=handle-lid-switch sleep 1d >/dev/null 2>&1 & inhibit_pid=$ ; xpra xwait ; kill -9 $inhibit_pid ; nohup systemd-inhibit --what=handle-lid-switch sleep 5m >/dev/null 2>&1 &" --border=#FF5733,5 --microphone=off --speaker=off --webcam=no --pulseaudio=no --start=gnome-terminal

XPRA_EXECUTABLE=Xpra-x86_64_6.0-r34134

Note: GDK_WIN32_DISABLE_HIDPI is ignored due to preset
      DPI awareness settings in user settings or application
      manifest, DPI awareness is still enabled.2023-09-05 00:45:29,520 Xpra GTK3 client version 6.0-r34134 (g1e3ef8977) beta
2023-09-05 00:45:29,538  running on Microsoft Windows
2023-09-05 00:45:29,539  cpython 3.11
2023-09-05 00:45:31,608 GStreamer version 1.22.5
2023-09-05 00:45:31,750 created named pipe 'Xpra\\30252'
2023-09-05 00:45:31,923 Error setting up the pipeline:
2023-09-05 00:45:31,924  gst_parse_error: could not link decoder to sink (3)
2023-09-05 00:45:31,924  GStreamer pipeline for:
2023-09-05 00:45:31,924   appsrc name=src emit-signals=1 block=0 is-live=1 do-timestamp=1 stream-type=0 format=2 caps=video/x-h264,width=128,height=128,profile=(string)main,stream-format=(string)byte-stream,alignment=(string)au ! \
2023-09-05 00:45:31,924   d3d11h264dec name=decoder ! \
2023-09-05 00:45:31,924   appsink name=sink emit-signals=1 max-buffers=10 drop=false sync=false async=true qos=false caps=video/x-raw,width=128,height=128,format=(string)I420
2023-09-05 00:45:31,924 Error creating context h264 128x128 YUV420P
2023-09-05 00:45:31,924 gstreamer: h264 decoding failed: failed to setup gstreamer pipeline
2023-09-05 00:45:31,929 keyboard layout 'United States - English' : 'us' (0x409)
2023-09-05 00:45:32,442 Unable to import OpenGL.arrays.numpymodule.NumpyHandler: No numpy module present:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.11 from "\xpra\Xpra-x86_64_6.0-r34134\Xpra_cmd.exe"
  * The NumPy version is: "1.25.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed while importing _multiarray_umath: Δεν ήταν δυνατό να εντοπιστεί η καθορισμένη λειτ. μονάδα.

2023-09-05 00:45:32,450 OpenGL enabled on 'NVIDIA GeForce RTX 2080 SUPER/PCIe/SSE2'
2023-09-05 00:45:32,532  keyboard settings: layout=us
2023-09-05 00:45:32,535  desktop size is 4480x1516:
2023-09-05 00:45:32,535   Default (1185x401 mm - DPI: 96x96) workarea: 4480x1476
2023-09-05 00:45:32,536     Samsung C32JG5x  2560x1440 at    0x0    (697x392 mm - DPI: 93x93) workarea: 2560x1400
2023-09-05 00:45:32,536     LG IPS234        1920x1080 at 2560x436  (510x290 mm - DPI: 96x95) workarea: 1920x1040 at 2560x436
2023-09-05 00:45:40,507 enabled remote logging
2023-09-05 00:45:40,508 Xpra X11 seamless server version 5.0
2023-09-05 00:45:40,521 running
Traceback (most recent call last):
  File "E:/xpra/xpra/client/gtk3/gtk_client_window_base.py", line 909, in on_realize
  File "E:/xpra/xpra/platform/win32/gui.py", line 566, in add_window_hooks
  File "E:/xpra/xpra/platform/win32/window_hooks.py", line 85, in setup
ctypes.ArgumentError: argument 1: OverflowError: int too long to convert
```

Also:

```
$ xpra toolbox
/usr/lib/python3/dist-packages/xpra/client/gtk3/../../gtk_common/gtk_view_keyboard.py:39: DeprecationWarning: Gtk.Widget.modify_font is deprecated
  label.modify_font(Pango.FontDescription("sans 13"))
do_keymap_changed: current keymap
do_keymap_changed: us, ['us'], , [], 
/usr/lib/python3/dist-packages/xpra/client/gtk3/../../gtk_common/gtk_view_keyboard.py:95: DeprecationWarning: Gtk.Widget.get_root_window is deprecated
  (x, y, current_mask) = self.window.get_root_window().get_pointer()[-3:]
/usr/lib/python3/dist-packages/xpra/client/gtk3/../../gtk_common/gtk_view_keyboard.py:95: DeprecationWarning: Gdk.Window.get_pointer is deprecated
  (x, y, current_mask) = self.window.get_root_window().get_pointer()[-3:]
```

**To Reproduce**
1. server command
2. client command
3. specific action to trigger the bug

**System Information (please complete the following information):**
- Server OS: Ubuntu 20.04.5 LTS
- Client OS: Microsoft Windows [Version 10.0.18363.836]
- Xpra Server Version (see above)
- Xpra Client Version (see above)

**Additional context**
Please see "reporting bugs" in the wiki section.

**Comment by totaam** [comment]
AFAICT, `ctypes.ArgumentError: argument 1: OverflowError: int too long to convert` comes from trying to add the window hooks, not from any key event.
I've never seen this but the commit above should fix that, and if not then we'll get more info from the message.

---

> `Unable to import OpenGL.arrays.numpymodule.NumpyHandler: No numpy module present:`
> `IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!`

I believe this is a non-cuda build, I should probably silence this scary warning since we don't even use the numpy format handler.

> `gtk_view_keyboard.py:39: DeprecationWarning: Gtk.Widget.modify_font is deprecated`
> `gtk_view_keyboard.py:95: DeprecationWarning: Gtk.Widget.get_root_window is deprecated`

Now silenced, the non deprecated API is a lot more work: [`gtk_widget_override_font` is deprecated](https://stackoverflow.com/questions/41831578/)

**Comment by totaam** [comment]
Please try r34203 or later.

**Comment by stdedos** [comment]
No luck

```
"Xpra-x86_64_6.0-r34204\xpra_cmd" start ssh://user@ip/2 --ssh="plink -ssh -agent" --modal-windows=no --desktop-scaling=no --headerbar=off --source-start=gnome-keyring-daemon --start --title="@title@ on @@/@server-display@" --start="nohup systemd-inhibit --what=handle-lid-switch sleep 1d >/dev/null 2>&1 & inhibit_pid=$ ; xpra xwait ; kill -9 $inhibit_pid ; nohup systemd-inhibit --what=handle-lid-switch sleep 5m >/dev/null 2>&1 &" --border=#FF5733,5 --microphone=off --speaker=off --webcam=no --pulseaudio=no --start=gnome-terminal

XPRA_EXECUTABLE=Xpra-x86_64_6.0-r34204

Note: GDK_WIN32_DISABLE_HIDPI is ignored due to preset
      DPI awareness settings in user settings or application
      manifest, DPI awareness is still enabled.2023-09-05 22:32:42,600 Xpra GTK3 client version 6.0-r34204 (g11a74ac93) beta
2023-09-05 22:32:42,618  running on Microsoft Windows
2023-09-05 22:32:42,619  cpython 3.11
2023-09-05 22:32:46,610 GStreamer version 1.22.5
2023-09-05 22:32:46,775 created named pipe 'Xpra\\24372'
2023-09-05 22:32:46,880 Error importing dec_avif (avif decoder)
2023-09-05 22:32:46,881  DLL load failed while importing decoder: Δεν ήταν δυνατό να εντοπιστεί η καθορισμένη λειτ. μονάδα.
2023-09-05 22:32:47,042 Error setting up the pipeline:
2023-09-05 22:32:47,042  gst_parse_error: could not link decoder to sink (3)
2023-09-05 22:32:47,042  GStreamer pipeline for:
2023-09-05 22:32:47,043   appsrc name=src emit-signals=1 block=0 is-live=1 do-timestamp=1 stream-type=0 format=2 caps=video/x-h264,width=128,height=128,profile=(string)main,stream-format=(string)byte-stream,alignment=(string)au ! \
2023-09-05 22:32:47,043   d3d11h264dec name=decoder ! \
2023-09-05 22:32:47,043   appsink name=sink emit-signals=1 max-buffers=10 drop=false sync=false async=true qos=false caps=video/x-raw,width=128,height=128,format=(string)I420
2023-09-05 22:32:47,043 Error creating context h264 128x128 YUV420P
2023-09-05 22:32:47,044 gstreamer: h264 decoding failed: failed to setup gstreamer pipeline
2023-09-05 22:32:47,049 keyboard layout 'United States - English' : 'us' (0x409)
2023-09-05 22:32:47,509 Unable to import OpenGL.arrays.numpymodule.NumpyHandler: No numpy module present:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.11 from "\xpra\Xpra-x86_64_6.0-r34204\Xpra_cmd.exe"
  * The NumPy version is: "1.25.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed while importing _multiarray_umath: Δεν ήταν δυνατό να εντοπιστεί η καθορισμένη λειτ. μονάδα.

2023-09-05 22:32:47,517 OpenGL enabled on 'NVIDIA GeForce RTX 2080 SUPER/PCIe/SSE2'
2023-09-05 22:32:47,611  keyboard settings: layout=us
2023-09-05 22:32:47,612  desktop size is 4480x1516:
2023-09-05 22:32:47,613   Default (1185x401 mm - DPI: 96x96) workarea: 4480x1476
2023-09-05 22:32:47,613     Samsung C32JG5x  2560x1440 at    0x0    (697x392 mm - DPI: 93x93) workarea: 2560x1400
2023-09-05 22:32:47,614     LG IPS234        1920x1080 at 2560x436  (510x290 mm - DPI: 96x95) workarea: 1920x1040 at 2560x436
2023-09-05 22:32:55,717 enabled remote logging
2023-09-05 22:32:55,718 Xpra X11 seamless server version 5.0
2023-09-05 22:32:55,739 running
2023-09-05 22:33:02,737 server is not responding, drawing spinners over the windows
2023-09-05 22:33:03,240 server is OK again
Traceback (most recent call last):
  File "E:/xpra/xpra/client/gl/gl_window_backing_base.py", line 1007, in set_cursor_data
  File "E:/xpra/xpra/client/gl/gl_window_backing_base.py", line 989, in validate_cursor
TypeError: object of type 'int' has no len()
Traceback (most recent call last):
  File "E:/xpra/xpra/client/base/client_base.py", line 1236, in call_handler
  File "E:/xpra/xpra/client/mixins/window_manager.py", line 587, in _process_cursor
  File "E:/xpra/xpra/client/gtk3/gtk_client_base.py", line 950, in set_windows_cursor
  File "E:/xpra/xpra/client/gtk3/gtk_client_window_base.py", line 801, in set_cursor_data
  File "E:/xpra/xpra/client/gtk3/gtk_client_window_base.py", line 903, in when_realized
  File "E:/xpra/xpra/client/gl/gl_window_backing_base.py", line 1007, in set_cursor_data
  File "E:/xpra/xpra/client/gl/gl_window_backing_base.py", line 989, in validate_cursor
TypeError: object of type 'int' has no len()
2023-09-05 22:46:04,634 window 9 has been moved to monitor 1: LG IPS234 1920x1080 at 2560,436
Traceback (most recent call last):
  File "E:/xpra/xpra/client/base/client_base.py", line 1236, in call_handler
  File "E:/xpra/xpra/client/mixins/window_manager.py", line 587, in _process_cursor
  File "E:/xpra/xpra/client/gtk3/gtk_client_base.py", line 950, in set_windows_cursor
  File "E:/xpra/xpra/client/gtk3/gtk_client_window_base.py", line 801, in set_cursor_data
  File "E:/xpra/xpra/client/gtk3/gtk_client_window_base.py", line 903, in when_realized
  File "E:/xpra/xpra/client/gl/gl_window_backing_base.py", line 1007, in set_cursor_data
  File "E:/xpra/xpra/client/gl/gl_window_backing_base.py", line 989, in validate_cursor
TypeError: object of type 'int' has no len()
Traceback (most recent call last):
  File "E:/xpra/xpra/client/base/client_base.py", line 1236, in call_handler
  File "E:/xpra/xpra/client/mixins/window_manager.py", line 587, in _process_cursor
  File "E:/xpra/xpra/client/gtk3/gtk_client_base.py", line 950, in set_windows_cursor
  File "E:/xpra/xpra/client/gtk3/gtk_client_window_base.py", line 801, in set_cursor_data
  File "E:/xpra/xpra/client/gtk3/gtk_client_window_base.py", line 903, in when_realized
  File "E:/xpra/xpra/client/gl/gl_window_backing_base.py", line 1007, in set_cursor_data
  File "E:/xpra/xpra/client/gl/gl_window_backing_base.py", line 989, in validate_cursor
TypeError: object of type 'int' has no len()
2023-09-05 22:46:26,169 failed to fixup window style
Traceback (most recent call last):
  File "E:/xpra/xpra/platform/win32/gui.py", line 413, in fixup_window_style
ctypes.ArgumentError: argument 3: TypeError: expected WinFunctionType instance instead of int
2023-09-05 22:46:48,005 failed to fixup window style
Traceback (most recent call last):
  File "E:/xpra/xpra/platform/win32/gui.py", line 413, in fixup_window_style
ctypes.ArgumentError: argument 3: TypeError: expected WinFunctionType instance instead of int
2023-09-05 22:46:48,007 failed to fixup window style
Traceback (most recent call last):
  File "E:/xpra/xpra/platform/win32/gui.py", line 413, in fixup_window_style
ctypes.ArgumentError: argument 3: TypeError: expected WinFunctionType instance instead of int
Traceback (most recent call last):
  File "E:/xpra/xpra/client/base/client_base.py", line 1236, in call_handler
  File "E:/xpra/xpra/client/mixins/window_manager.py", line 587, in _process_cursor
  File "E:/xpra/xpra/client/gtk3/gtk_client_base.py", line 950, in set_windows_cursor
  File "E:/xpra/xpra/client/gtk3/gtk_client_window_base.py", line 801, in set_cursor_data
  File "E:/xpra/xpra/client/gtk3/gtk_client_window_base.py", line 903, in when_realized
  File "E:/xpra/xpra/client/gl/gl_window_backing_base.py", line 1007, in set_cursor_data
  File "E:/xpra/xpra/client/gl/gl_window_backing_base.py", line 989, in validate_cursor
TypeError: object of type 'int' has no len()
2023-09-05 22:46:55,452 failed to fixup window style
Traceback (most recent call last):
  File "E:/xpra/xpra/platform/win32/gui.py", line 413, in fixup_window_style
ctypes.ArgumentError: argument 3: TypeError: expected WinFunctionType instance instead of int
2023-09-05 22:46:55,454 failed to fixup window style
Traceback (most recent call last):
  File "E:/xpra/xpra/platform/win32/gui.py", line 413, in fixup_window_style
ctypes.ArgumentError: argument 3: TypeError: expected WinFunctionType instance instead of int
Traceback (most recent call last):
  File "E:/xpra/xpra/client/base/client_base.py", line 1236, in call_handler
  File "E:/xpra/xpra/client/mixins/window_manager.py", line 587, in _process_cursor
  File "E:/xpra/xpra/client/gtk3/gtk_client_base.py", line 950, in set_windows_cursor
  File "E:/xpra/xpra/client/gtk3/gtk_client_window_base.py", line 801, in set_cursor_data
  File "E:/xpra/xpra/client/gtk3/gtk_client_window_base.py", line 903, in when_realized
  File "E:/xpra/xpra/client/gl/gl_window_backing_base.py", line 1007, in set_cursor_data
  File "E:/xpra/xpra/client/gl/gl_window_backing_base.py", line 989, in validate_cursor
TypeError: object of type 'int' has no len()
Traceback (most recent call last):
  File "E:/xpra/xpra/client/base/client_base.py", line 1236, in call_handler
  File "E:/xpra/xpra/client/mixins/window_manager.py", line 587, in _process_cursor
  File "E:/xpra/xpra/client/gtk3/gtk_client_base.py", line 950, in set_windows_cursor
  File "E:/xpra/xpra/client/gtk3/gtk_client_window_base.py", line 801, in set_cursor_data
  File "E:/xpra/xpra/client/gtk3/gtk_client_window_base.py", line 903, in when_realized
  File "E:/xpra/xpra/client/gl/gl_window_backing_base.py", line 1007, in set_cursor_data
  File "E:/xpra/xpra/client/gl/gl_window_backing_base.py", line 989, in validate_cursor
TypeError: object of type 'int' has no len()
Traceback (most recent call last):
  File "E:/xpra/xpra/client/base/client_base.py", line 1236, in call_handler
  File "E:/xpra/xpra/client/mixins/window_manager.py", line 587, in _process_cursor
  File "E:/xpra/xpra/client/gtk3/gtk_client_base.py", line 950, in set_windows_cursor
  File "E:/xpra/xpra/client/gtk3/gtk_client_window_base.py", line 801, in set_cursor_data
  File "E:/xpra/xpra/client/gtk3/gtk_client_window_base.py", line 903, in when_realized
  File "E:/xpra/xpra/client/gl/gl_window_backing_base.py", line 1007, in set_cursor_data
  File "E:/xpra/xpra/client/gl/gl_window_backing_base.py", line 989, in validate_cursor
TypeError: object of type 'int' has no len()
Traceback (most recent call last):
  File "E:/xpra/xpra/client/base/client_base.py", line 1236, in call_handler
  File "E:/xpra/xpra/client/mixins/window_manager.py", line 587, in _process_cursor
  File "E:/xpra/xpra/client/gtk3/gtk_client_base.py", line 950, in set_windows_cursor
  File "E:/xpra/xpra/client/gtk3/gtk_client_window_base.py", line 801, in set_cursor_data
  File "E:/xpra/xpra/client/gtk3/gtk_client_window_base.py", line 903, in when_realized
  File "E:/xpra/xpra/client/gl/gl_window_backing_base.py", line 1007, in set_cursor_data
  File "E:/xpra/xpra/client/gl/gl_window_backing_base.py", line 989, in validate_cursor
TypeError: object of type 'int' has no len()
Traceback (most recent call last):
  File "E:/xpra/xpra/client/base/client_base.py", line 1236, in call_handler
  File "E:/xpra/xpra/client/mixins/window_manager.py", line 587, in _process_cursor
  File "E:/xpra/xpra/client/gtk3/gtk_client_base.py", line 950, in set_windows_cursor
  File "E:/xpra/xpra/client/gtk3/gtk_client_window_base.py", line 801, in set_cursor_data
  File "E:/xpra/xpra/client/gtk3/gtk_client_window_base.py", line 903, in when_realized
  File "E:/xpra/xpra/client/gl/gl_window_backing_base.py", line 1007, in set_cursor_data
  File "E:/xpra/xpra/client/gl/gl_window_backing_base.py", line 989, in validate_cursor
TypeError: object of type 'int' has no len()
Traceback (most recent call last):
  File "E:/xpra/xpra/client/base/client_base.py", line 1236, in call_handler
  File "E:/xpra/xpra/client/mixins/window_manager.py", line 587, in _process_cursor
  File "E:/xpra/xpra/client/gtk3/gtk_client_base.py", line 950, in set_windows_cursor
  File "E:/xpra/xpra/client/gtk3/gtk_client_window_base.py", line 801, in set_cursor_data
  File "E:/xpra/xpra/client/gtk3/gtk_client_window_base.py", line 903, in when_realized
  File "E:/xpra/xpra/client/gl/gl_window_backing_base.py", line 1007, in set_cursor_data
  File "E:/xpra/xpra/client/gl/gl_window_backing_base.py", line 989, in validate_cursor
TypeError: object of type 'int' has no len()
Traceback (most recent call last):
  File "E:/xpra/xpra/client/base/client_base.py", line 1236, in call_handler
  File "E:/xpra/xpra/client/mixins/window_manager.py", line 587, in _process_cursor
  File "E:/xpra/xpra/client/gtk3/gtk_client_base.py", line 950, in set_windows_cursor
  File "E:/xpra/xpra/client/gtk3/gtk_client_window_base.py", line 801, in set_cursor_data
  File "E:/xpra/xpra/client/gtk3/gtk_client_window_base.py", line 903, in when_realized
  File "E:/xpra/xpra/client/gl/gl_window_backing_base.py", line 1007, in set_cursor_data
  File "E:/xpra/xpra/client/gl/gl_window_backing_base.py", line 989, in validate_cursor
TypeError: object of type 'int' has no len()
Traceback (most recent call last):
  File "E:/xpra/xpra/client/base/client_base.py", line 1236, in call_handler
  File "E:/xpra/xpra/client/mixins/window_manager.py", line 587, in _process_cursor
  File "E:/xpra/xpra/client/gtk3/gtk_client_base.py", line 950, in set_windows_cursor
  File "E:/xpra/xpra/client/gtk3/gtk_client_window_base.py", line 801, in set_cursor_data
  File "E:/xpra/xpra/client/gtk3/gtk_client_window_base.py", line 903, in when_realized
  File "E:/xpra/xpra/client/gl/gl_window_backing_base.py", line 1007, in set_cursor_data
  File "E:/xpra/xpra/client/gl/gl_window_backing_base.py", line 989, in validate_cursor
TypeError: object of type 'int' has no len()
Traceback (most recent call last):
  File "E:/xpra/xpra/client/base/client_base.py", line 1236, in call_handler
  File "E:/xpra/xpra/client/mixins/window_manager.py", line 587, in _process_cursor
  File "E:/xpra/xpra/client/gtk3/gtk_client_base.py", line 950, in set_windows_cursor
  File "E:/xpra/xpra/client/gtk3/gtk_client_window_base.py", line 801, in set_cursor_data
  File "E:/xpra/xpra/client/gtk3/gtk_client_window_base.py", line 903, in when_realized
  File "E:/xpra/xpra/client/gl/gl_window_backing_base.py", line 1007, in set_cursor_data
  File "E:/xpra/xpra/client/gl/gl_window_backing_base.py", line 989, in validate_cursor
TypeError: object of type 'int' has no len()
Traceback (most recent call last):
  File "E:/xpra/xpra/client/base/client_base.py", line 1236, in call_handler
  File "E:/xpra/xpra/client/mixins/window_manager.py", line 587, in _process_cursor
  File "E:/xpra/xpra/client/gtk3/gtk_client_base.py", line 950, in set_windows_cursor
  File "E:/xpra/xpra/client/gtk3/gtk_client_window_base.py", line 801, in set_cursor_data
  File "E:/xpra/xpra/client/gtk3/gtk_client_window_base.py", line 903, in when_realized
  File "E:/xpra/xpra/client/gl/gl_window_backing_base.py", line 1007, in set_cursor_data
  File "E:/xpra/xpra/client/gl/gl_window_backing_base.py", line 989, in validate_cursor
TypeError: object of type 'int' has no len()
```

However, I have to rename the ticket: `Ctrl + Shift + C` mishap was of my own doing

**Comment by stdedos** [comment]
No change on

```
$ xpra toolbox
/usr/lib/python3/dist-packages/xpra/client/gtk3/../../gtk_common/gtk_view_keyboard.py:39: DeprecationWarning: Gtk.Widget.modify_font is deprecated
  label.modify_font(Pango.FontDescription("sans 13"))
do_keymap_changed: current keymap
do_keymap_changed: us, ['us'], , [], 
/usr/lib/python3/dist-packages/xpra/client/gtk3/../../gtk_common/gtk_view_keyboard.py:95: DeprecationWarning: Gtk.Widget.get_root_window is deprecated
  (x, y, current_mask) = self.window.get_root_window().get_pointer()[-3:]
/usr/lib/python3/dist-packages/xpra/client/gtk3/../../gtk_common/gtk_view_keyboard.py:95: DeprecationWarning: Gdk.Window.get_pointer is deprecated
  (x, y, current_mask) = self.window.get_root_window().get_pointer()[-3:]
```

but those are old - let's ignore them I guess

**Comment by totaam** [comment]
> No luck

Indeed.
The original bug has been fixed.. but this broke the only other `SetWindowLong` caller we had! (same symptom)
Whac-a-mole time. Since I can't figure out how to handle polymorphic functions correctly with `ctypes`,  I resorted to wrapping the function twice!
Try 6.0-r34208 or later.

As for `TypeError: object of type 'int' has no len()`, this is already tracked in #3959 so I am going to change the ticket summary again, and I think we can close it?


> No change on

You're running that on the server, right?
Which has not been updated yet, has it?

**Comment by stdedos** [comment]
> You're running that on the server, right?
> Which has not been updated yet, has it?

Oops. Yes 😓 However, It has been updated 😕 

```console
$ xpra toolbox
/usr/lib/python3/dist-packages/xpra/client/gtk3/../../gtk_common/gtk_view_keyboard.py:39: DeprecationWarning: Gtk.Widget.modify_font is deprecated
  label.modify_font(Pango.FontDescription("sans 13"))
do_keymap_changed: current keymap
do_keymap_changed: us, ['us'], , [], 
/usr/lib/python3/dist-packages/xpra/client/gtk3/../../gtk_common/gtk_view_keyboard.py:95: DeprecationWarning: Gtk.Widget.get_root_window is deprecated
  (x, y, current_mask) = self.window.get_root_window().get_pointer()[-3:]
/usr/lib/python3/dist-packages/xpra/client/gtk3/../../gtk_common/gtk_view_keyboard.py:95: DeprecationWarning: Gdk.Window.get_pointer is deprecated
  (x, y, current_mask) = self.window.get_root_window().get_pointer()[-3:]
$ xpra version
5.0.1-r20
$ apt-cache madison xpra
      xpra | 5.0.1-r20-1 | https://xpra.org/beta focal/main amd64 Packages
      xpra | 5.0.1-r0-1 | https://xpra.org focal/main amd64 Packages
      xpra |   5.0-r0-1 | https://xpra.org focal/main amd64 Packages
      xpra | 4.4.6-r29-1 | https://xpra.org focal/main amd64 Packages
      xpra | 3.1.5-r0-1 | https://xpra.org focal/main amd64 Packages
      xpra | 3.0.6+dfsg1-1build1 | http://gr.archive.ubuntu.com/ubuntu focal/universe amd64 Packages
```

... but the versioning is weird 😅 

-----------

All `ctypes` are fixed 🎉 🎉 🎉 🎉 🎉

**Comment by totaam** [comment]
> but the versioning is weird 

Isn't it just showing all the versions you can install?

**Comment by stdedos** [comment]
Indeed. But the `r0`, `r29`, `r20` are not accurate? 😅

**Comment by totaam** [comment]
> Indeed. But the `r0`, `r29`, `r20` are not accurate? 😅 

They start counting from the last tag.
So stable releases should be `r0` or close to it.
Beta builds have higher numbers, which should not be a much of a problem as they're almost always one version ahead.
