### ISSUE TITLE
`Error: video helper modules have already been initialized`

### ISSUE THREAD

**Issue by stdedos** [Xpra-org/xpra#3996]
**Describe the bug**

```
"Xpra-x86_64_6.0-r34211\xpra_cmd" start ssh://user@ip/2 --ssh="plink -ssh -agent" --modal-windows=no --desktop-scaling=no --headerbar=off --source-start=gnome-keyring-daemon --title="@title@ on @@/@server-display@" --border=#FF5733,5 --microphone=off --speaker=off --webcam=no --pulseaudio=no --start=gnome-terminal
```

**To Reproduce**
```
$ cat server.log
Socket path '/tmp/.X11-unix/X2' not found
2023-09-10 21:58:53,228 no uinput module (not usually needed)
2023-09-10 21:58:54,446 pointer device emulation using XTest
2023-09-10 21:58:54,523 serving html content from '/usr/share/xpra/www'
2023-09-10 21:58:54,523 wrote pid 1449760 to '/run/user/1000/xpra/2/server.pid'
2023-09-10 21:58:54,543 created unix domain socket '/run/user/1000/xpra/h-2'
2023-09-10 21:58:54,544 cannot create group socket '/run/xpra/h-2'
2023-09-10 21:58:54,544  [Errno 13] Permission denied
2023-09-10 21:58:54,544 created unix domain socket '/home/u/.xpra/h-2'
2023-09-10 21:58:54,544 created unix domain socket '/run/user/1000/xpra/2/socket'
2023-09-10 21:58:54,544 xvfb pid=1449769
2023-09-10 21:58:54,561 python-zeroconf: '::' IPv6 loopback address is not supported
2023-09-10 21:58:54,569 D-Bus notification forwarding is available
2023-09-10 21:58:54,648 xpra is ready.
2023-09-10 21:58:54,648 xpra X11 seamless server version 5.0.1-r20
2023-09-10 21:58:54,649  uid=1000 (u), gid=1000 (u)
2023-09-10 21:58:54,649  running with pid 1449760 on Linux Ubuntu 20.04 focal
2023-09-10 21:58:54,736  connected to X11 display :2 with 24 bit colors
2023-09-10 21:58:54,740 watching for applications menu changes in:
2023-09-10 21:58:54,740  '/home/u/.local/share/flatpak/exports/share/applications'
2023-09-10 21:58:54,740  '/var/lib/flatpak/exports/share/applications'
2023-09-10 21:58:54,740  '/usr/share/applications'
2023-09-10 21:58:54,740  '/var/lib/snapd/desktop/applications'
2023-09-10 21:58:54,749 GStreamer version 1.16.3
2023-09-10 21:58:54,771 New socket connection received
2023-09-10 21:58:54,771  on '/run/user/1000/xpra/h-2'
2023-09-10 21:58:54,847 New socket connection received
2023-09-10 21:58:54,847  on '/run/user/1000/xpra/h-2'
2023-09-10 21:58:54,848 Handshake complete; enabling connection
2023-09-10 21:58:54,866 Python/GTK3 Microsoft Windows aero client version 6.0
2023-09-10 21:58:54,866  connected as 'u'
2023-09-10 21:58:54,866  OpenGL is enabled with NVIDIA GeForce RTX 2080 SUPER/PCIe/SSE2
2023-09-10 21:58:54,867 setting key repeat rate from client: 500ms delay / 33ms interval
2023-09-10 21:58:54,867 setting keyboard layout to 'us'
2023-09-10 21:58:54,880 Warning: client did not supply any modifier definitions
2023-09-10 21:58:54,969  client root window size is 4480x1516
2023-09-10 21:58:54,969   Default (1185x401 mm - DPI: 96x96) workarea: 4480x1476
2023-09-10 21:58:54,969     Samsung C32JG5x  2560x1440 at    0x0    (697x392 mm - DPI: 93x93) workarea: 2560x1400
2023-09-10 21:58:54,969     LG IPS234        1920x1080 at 2560x436  (510x290 mm - DPI: 96x95) workarea: 1920x1040 at 2560x436
2023-09-10 21:58:55,479 server virtual display now set to 4480x1516
2023-09-10 21:58:55,509 client   1 @08.781 Xpra X11 seamless server version 5.0
2023-09-10 21:58:55,527 client   1 @08.797 running
2023-09-10 21:58:55,535 DPI set to 96 x 96
2023-09-10 21:58:55,560 setting keyboard layout to 'us'
2023-09-10 21:58:56,719 loaded 76 start menu entries from 13 sub-menus in 2.0 seconds
2023-09-10 21:58:58,010 Warning: not adding duplicate printer 'PDFCreator'
2023-09-10 21:58:58,011 Warning: not adding duplicate printer 'OneNote (Desktop)'
2023-09-10 21:59:02,272 printer forwarding enabled using postscript and pdf
2023-09-10 21:59:02,272 Error: video helper modules have already been initialized
2023-09-10 21:59:02,272 from:
2023-09-10 21:59:02,272    File "/usr/bin/xpra", line 17, in <module>
    sys.exit(main(sys.argv[0], sys.argv))
2023-09-10 21:59:02,272    File "/usr/lib/python3/dist-packages/xpra/scripts/main.py", line 121, in main
    return run_mode(script_file, cmdline, err, options, args, mode, defaults)
2023-09-10 21:59:02,272    File "/usr/lib/python3/dist-packages/xpra/scripts/main.py", line 455, in run_mode
    return do_run_mode(script_file, cmdline, error_cb, options, args, mode, defaults)
2023-09-10 21:59:02,272    File "/usr/lib/python3/dist-packages/xpra/scripts/main.py", line 520, in do_run_mode
    return run_server(script_file, cmdline, error_cb, options, args, mode, defaults)
2023-09-10 21:59:02,273    File "/usr/lib/python3/dist-packages/xpra/scripts/main.py", line 1919, in run_server
    return do_run_server(script_file, cmdline, error_cb, options, args, mode, str(display or ""), defaults)
2023-09-10 21:59:02,273    File "/usr/lib/python3/dist-packages/xpra/scripts/server.py", line 724, in do_run_server
    return _do_run_server(script_file, cmdline,
2023-09-10 21:59:02,273    File "/usr/lib/python3/dist-packages/xpra/scripts/server.py", line 1533, in _do_run_server
    r = app.run()
2023-09-10 21:59:02,273    File "/usr/lib/python3/dist-packages/xpra/server/server_core.py", line 460, in run
    self.do_run()
2023-09-10 21:59:02,273    File "/usr/lib/python3/dist-packages/xpra/server/gtk_server_base.py", line 140, in do_run
    Gtk.main()
2023-09-10 21:59:02,273    File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 1632, in main
    return _Gtk_main(*args, **kwargs)
2023-09-10 21:59:02,273    File "/usr/lib/python3/dist-packages/xpra/server/server_core.py", line 2245, in call_hello_oked
    self.hello_oked(proto, c, auth_caps)
2023-09-10 21:59:02,273    File "/usr/lib/python3/dist-packages/xpra/server/server_base.py", line 406, in hello_oked
    ss = cc_class(proto, drop_client,
2023-09-10 21:59:02,273    File "/usr/lib/python3/dist-packages/xpra/server/source/client_connection_factory.py", line 108, in __init__
    c.init_state(self)
2023-09-10 21:59:02,273    File "/usr/lib/python3/dist-packages/xpra/server/source/encodings.py", line 69, in init_state
    self.video_helper = getVideoHelper().clone()
2023-09-10 21:59:02,273    File "/usr/lib/python3/dist-packages/xpra/codecs/video_helper.py", line 204, in clone
    self.init()
2023-09-10 21:59:02,273    File "/usr/lib/python3/dist-packages/xpra/codecs/video_helper.py", line 254, in init
    self._init_from.append(traceback.format_stack())
2023-09-10 21:59:02,274 Error during threaded setup of <class 'xpra.server.mixins.encoding.EncodingServer'>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xpra/server/server_base.py", line 190, in threaded_init
    c.threaded_setup(self)
  File "/usr/lib/python3/dist-packages/xpra/server/mixins/encoding.py", line 96, in threaded_setup
    getVideoHelper().set_modules(video_encoders=self.video_encoders, csc_modules=self.csc_modules)
  File "/usr/lib/python3/dist-packages/xpra/codecs/video_helper.py", line 173, in set_modules
    raise RuntimeError("too late to set modules, the helper is already initialized")
RuntimeError: too late to set modules, the helper is already initialized
2023-09-10 21:59:02,281 31.1GB of system memory
2023-09-10 21:59:02,380 some GStreamer elements are missing or unavailable on this system:
2023-09-10 21:59:02,380  vaapih264enc, vaapih265enc, amfh264enc, amfh265enc
2023-09-10 21:59:02,889 OpenGL is supported on display ':2'
2023-09-10 21:59:02,889  using 'llvmpipe (LLVM 12.0.0, 256 bits)' renderer
2023-09-10 21:59:02,901 started command `gnome-terminal` with pid 1450432
2023-09-10 21:59:02,901  automatic picture encoding enabled, also available:
2023-09-10 21:59:02,901   png, png/P, png/L, webp, rgb24, rgb32, jpeg, jpega, scroll
Failed to inhibit: Access denied
2023-09-10 21:59:02,905 started command `ibus-daemon` with pid 1450433
2023-09-10 21:59:47,158 New socket connection received
2023-09-10 21:59:47,158  on '/run/user/1000/xpra/h-2'
```

**System Information (please complete the following information):**
- Server OS: Ubuntu 20.04.5 LTS
- Client OS: Microsoft Windows [Version 10.0.18363.836]
- Xpra Server Version (see above)
- Xpra Client Version (see above)

**Additional context**
Please see "reporting bugs" in the wiki section.

**Comment by totaam** [comment]
Also saw this yesterday, already fixed: ff3e68a022ccc28b8a22c6f17b88813bf922dabe and improved: e8f23907a15c2ac51c86cd433b72d45161c7626d
