### ISSUE TITLE
html5 client can hang the server

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#3999]
Not sure yet what's wrong with the html5 client, but the server ends up consuming 100% CPU and not servicing new clients!
```
(..)
2023-09-11 21:08:17,469 peek_connection(tcp socket: 127.0.0.1:10000 <- 127.0.0.1:48994, 1000) failed
Traceback (most recent call last):
  File "/usr/lib64/python3.11/site-packages/xpra/net/socket_util.py", line 183, in peek_connection
    peek_data = conn.peek(size)
                ^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/xpra/net/bytestreams.py", line 344, in peek
    return self._socket.recv(n, socket.MSG_PEEK)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: timed out
2023-09-11 21:08:17,837 peek: elapsed=1373, timeout=1000
2023-09-11 21:08:17,842 socket tcp socket: 127.0.0.1:10000 <- 127.0.0.1:48994 peek: got 0 bytes
2023-09-11 21:08:17,848 socket peek=b''
2023-09-11 21:08:17,853 socket peek hex=
2023-09-11 21:08:17,853 socket peek line1=b''
2023-09-11 21:08:17,853 guess_packet_type(..)=
2023-09-11 21:08:17,868 log_new_connection(tcp socket: 127.0.0.1:10000 <- 127.0.0.1:48994, ('0.0.0.0', 10000)) type=<class 'xpra.net.bytestreams.SocketConnection'>, sock=<socket.socket fd=157, family=2, type=1, proto=0, laddr=('127.0.0.1', 10000), raddr=('127.0.0.1', 48994)>, sockname=('127.0.0.1', 10000), address=('127.0.0.1', 48994), peername=('127.0.0.1', 48994)
2023-09-11 21:08:17,873 New tcp connection received
2023-09-11 21:08:17,879  from '127.0.0.1:48994'
2023-09-11 21:08:17,884  on '0.0.0.0:10000'
2023-09-11 21:08:17,889 make_protocol('tcp', tcp socket: 127.0.0.1:10000 <- 127.0.0.1:48994, {}, <function ServerCore.make_protocol.<locals>.xpra_protocol_class at 0x7f1ede6b5440>, None)
2023-09-11 21:08:17,894 tcp: encryption=, keyfile=
2023-09-11 21:08:17,899 socktype=tcp, encryption=, keyfile=''
2023-09-11 21:08:21,823 untilConcludes(<bound method Connection.is_active of ws socket: 127.0.0.1:10000 <- 127.0.0.1:48998>, <bound method Connection.can_retry of ws socket: 127.0.0.1:10000 <- 127.0.0.1:48998>, <built-in method recv of socket object at 0x7f1eddfb7ca0>, (65536,), {}) timed out, retry=socket.timeout
2023-09-11 21:08:47,365 parse_ws_frame(6 bytes) total buffer is 6 bytes
2023-09-11 21:08:47,370 parse_ws_frame(6 bytes) payload=0 bytes, processed=6, remaining=0, opcode=CLOSE, fin=True
2023-09-11 21:08:47,375 _process_ws_close(<memory at 0x7f1f44176a40>)
2023-09-11 21:08:47,381 connection lost: unknown reason
2023-09-11 21:08:47,386 flush_then_close(None, b'\x88\x10\x03\xe8unknown reason', <function noop at 0x7f1f52466ac0>) closed=False
2023-09-11 21:08:47,386 flush_then_close: wait_for_write_lock()
2023-09-11 21:08:47,391 flush_then_close: acquired the write lock
2023-09-11 21:08:47,397 flush_then_close: queue is now empty, sending the last packet and closing
2023-09-11 21:08:47,397 raw_write for flush-then-close, starting write thread
2023-09-11 21:08:47,397 io_thread_loop(write, <bound method SocketProtocol._write of WebSocket(ws socket: 127.0.0.1:10000 <- 127.0.0.1:48998)>) loop starting
2023-09-11 21:08:47,397 Protocol.close(unknown reason) closed=False, connection=ws socket: 127.0.0.1:10000 <- 127.0.0.1:48998
2023-09-11 21:08:47,397 Protocol.close(unknown reason) calling <bound method SocketConnection.close of ws socket: 127.0.0.1:10000 <- 127.0.0.1:48998>
2023-09-11 21:08:47,397 ws socket: 127.0.0.1:10000 <- 127.0.0.1:48998.close() socket=<socket.socket fd=156, family=2, type=1, proto=0, laddr=('127.0.0.1', 10000), raddr=('127.0.0.1', 48998)>
2023-09-11 21:08:47,398 ws socket: 127.0.0.1:10000 <- 127.0.0.1:48998.close() done
2023-09-11 21:08:47,398 terminate_queue_threads()
2023-09-11 21:08:47,404 parse thread: empty marker, exiting
2023-09-11 21:08:47,404 can_retry: <class 'OSError'>, args=(9, 'Bad file descriptor'), errno=9, code=9, abort=9
2023-09-11 21:08:47,405 None closed in write loop
Traceback (most recent call last):
  File "/usr/lib64/python3.11/site-packages/xpra/net/protocol/socket_handler.py", line 666, in _io_thread_loop
    while not self._closed and callback():
                               ^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/xpra/net/protocol/socket_handler.py", line 693, in _write
    return self.write_items(*items)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/xpra/net/protocol/socket_handler.py", line 716, in write_items
    self.write_buffers(buf_data, packet_type, fail_cb, synchronous)
  File "/usr/lib64/python3.11/site-packages/xpra/net/protocol/socket_handler.py", line 740, in write_buffers
    written = self.con_write(con, buf, packet_type)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/xpra/net/protocol/socket_handler.py", line 751, in con_write
    return con.write(buf, packet_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/xpra/net/bytestreams.py", line 350, in write
    return self._write(self._socket.send, buf)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/xpra/net/bytestreams.py", line 158, in _write
    w = self.untilConcludes(*args)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/xpra/net/bytestreams.py", line 150, in untilConcludes
    return untilConcludes(self.is_active, self.can_retry, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/xpra/net/bytestreams.py", line 86, in untilConcludes
    retry = can_retry_cb(e)
            ^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/xpra/net/bytestreams.py", line 147, in can_retry
    return can_retry(e)
           ^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/xpra/net/bytestreams.py", line 76, in can_retry
    raise ConnectionClosedException(e) from None
xpra.net.common.ConnectionClosedException: [Errno 9] Bad file descriptor
2023-09-11 21:08:47,404 Protocol.close(unknown reason) done
2023-09-11 21:08:47,427 io_thread_loop(read, <bound method SocketProtocol._read of WebSocket(None)>) loop ended, closed=True
```

**Comment by totaam** [comment]
Found it, this goes into an infinite loop:
```
t=typedict({"platform" : {'': 'Linux', 'name': 'Linux', 'processor': 'unknown', 'platform': '5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36'}})
t.strtupleget("platform.linux_distribution")
```
