### ISSUE TITLE
Exception thrown in the underlying HTTP server

### ISSUE THREAD

**Issue by BruunAnd** [Xpra-org/xpra#4022]
Hi - big fan of the project! 

I'm working on a Dockerfile combining Xpra and the HTML5 client which I plan to open source and maintain soon. This has previously worked great, but I've been having some issues getting this image to work using the latest versions of Xpra.

The main components of the Dockerfile are listed below (permission details omitted for brevity):
```
FROM ubuntu:jammy

# Install Xpra and dependencies
RUN apt update \
 && DEBIAN_FRONTEND=noninteractive apt install -y git wget gnupg xvfb x11-xserver-utils \
 && echo "deb [arch=amd64] https://xpra.org/ jammy main" > /etc/apt/sources.list.d/xpra.list \
 && wget -q https://xpra.org/gpg.asc -O- | apt-key add - \
 && apt update \
 && DEBIAN_FRONTEND=noninteractive apt install -y xpra \
 && mkdir -p /run/user/0/xpra

(...)

# Install HTML5 client
RUN git clone https://github.com/Xpra-org/xpra-html5
RUN cd xpra-html5 && ./setup.py install

ENTRYPOINT ["xpra", ...]
```

The error I've been getting in more recent versions, leading me unable to connect, is:
```
2023-10-04 08:49:05,029 Error parsing bencode packet:
2023-10-04 08:49:05,029  invalid b'bencoded string' type identifier: 194 at position 0
2023-10-04 08:49:05,030 Disconnecting client ('192.168.65.1', 65192):
2023-10-04 08:49:05,030  failed to parse bencode packet
2023-10-04 08:49:05,226 Error: http GET request failure for client 192.168.65.1:65210:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xpra/server/server_core.py", line 1375, in start_http
    WebSocketRequestHandler(sock, frominfo, new_websocket_client,
  File "/usr/lib/python3/dist-packages/xpra/net/websockets/handler.py", line 30, in __init__
    HTTPRequestHandler.__init__(self, sock, addr, web_root, http_headers_dir, script_paths)
  File "/usr/lib/python3/dist-packages/xpra/server/http_handler.py", line 61, in __init__
    BaseHTTPRequestHandler.__init__(self, sock, addr, server)
  File "/usr/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/usr/lib/python3/dist-packages/xpra/net/websockets/handler.py", line 75, in do_GET
    HTTPRequestHandler.do_GET(self)
  File "/usr/lib/python3/dist-packages/xpra/server/http_handler.py", line 180, in do_GET
    self.handle_request()
  File "/usr/lib/python3/dist-packages/xpra/net/websockets/handler.py", line 87, in handle_request
    HTTPRequestHandler.handle_request(self)
  File "/usr/lib/python3/dist-packages/xpra/server/http_handler.py", line 185, in handle_request
    self.wfile.write(content)
TypeError: a bytes-like object is required, not 'str'
```

Any idea what could be causing this error?

**Comment by BruunAnd** [comment]
Closing, as the problem does not occur if I skip the manual upgrade of the HTML5 client.

**Comment by totaam** [comment]
>  if I skip the manual upgrade of the HTML5 client.

I don't know what that means.
My guess is that your server is too old for your html5 client.

You may want to use a release rather than git master.
