### ISSUE TITLE
`File "E:/xpra/xpra/scripts/main.py", line 2145, in run_remote_server: FileNotFoundError: [Errno 2] No such file or directory`

### ISSUE THREAD

**Issue by stdedos** [Xpra-org/xpra#4026]
I'm seeing again the same

```
"Xpra-x86_64_6.0-r34211\xpra_cmd" shadow ssh://user@ip/1 --ssh="plink -ssh -agent" --modal-windows=no --headerbar=off --source-start=gnome-keyring-daemon --title="@title@ on @@/@server-display@" --encodings=-webp --start="nohup systemd-inhibit --what=handle-lid-switch sleep 1d >/dev/null 2>&1 & inhibit_pid=\$! ; xpra xwait ; kill -9 \$inhibit_pid ; nohup systemd-inhibit --what=handle-lid-switch sleep 5m >/dev/null 2>&1 &" --microphone=off --speaker=off --webcam=no --pulseaudio=no --key-shortcut=Shift+F2:toggle_pointer_grab

...

2023-09-17 11:11:32,732  Actual log file name is now: '/run/user/1000/xpra/2/server.log'
CONNECTION_LOST, reconnecting
2023-09-17 11:11:33,252 xpra main error:
Traceback (most recent call last):
  File "E:/xpra/xpra/scripts/main.py", line 123, in main
  File "E:/xpra/xpra/scripts/main.py", line 457, in run_mode
  File "E:/xpra/xpra/scripts/main.py", line 497, in do_run_mode
  File "E:/xpra/xpra/scripts/main.py", line 2145, in run_remote_server
FileNotFoundError: [Errno 2] No such file or directory
```

Same cause or different issue?

_Originally posted by @stdedos in https://github.com/Xpra-org/xpra/issues/3381#issuecomment-1726531674_

**Comment by stdedos** [comment]
It seems that https://github.com/Xpra-org/xpra/commit/2cddeaa2ed1a90ddde5b5de6aeea3028e25734e8 is not helping:

```
CONNECTION_LOST, reconnecting
2023-10-06 02:16:14,382 xpra main error:
Traceback (most recent call last):
  File "E:/xpra/xpra/scripts/main.py", line 126, in main
  File "E:/xpra/xpra/scripts/main.py", line 457, in run_mode
  File "E:/xpra/xpra/scripts/main.py", line 508, in do_run_mode
  File "E:/xpra/xpra/scripts/main.py", line 2158, in run_remote_server
FileNotFoundError: [Errno 2] No such file or directory

"was: Xpra-x86_64_6.0-r34433\xpra_cmd" shadow ssh://user@ip/1 --ssh="plink -ssh -agent" --modal-windows=no --headerbar=off --source-start=gnome-keyring-daemon --title="@title@ on @@/@server-display@" --encodings=-webp --start="nohup systemd-inhibit --what=handle-lid-switch sleep 1d >/dev/null 2>&1 & inhibit_pid=\$! ; xpra xwait ; kill -9 \$inhibit_pid ; nohup systemd-inhibit --what=handle-lid-switch sleep 5m >/dev/null 2>&1 &" --microphone=off --speaker=off --webcam=no --pulseaudio=no --opengl=no --key-shortcut=Shift+F2:toggle_pointer_grab
```

**Comment by totaam** [comment]
Only just noticed that you're running from a relative path..
Hopefully the last commit above will fix that, if not then the other commit will at least show us what it's trying to run.

**Comment by totaam** [comment]
I assume that this is fixed. Please re-open if not.

**Comment by stdedos** [comment]
I haven't had access to a Windows computer yet to retry 😓 (and also be able to reliably connect/shutdown it)

I have this still open, looking at it

**Comment by stdedos** [comment]
```
ImportError: cannot import name 'InfoTimerClient' from 'xpra.client.base.gobject' (E:\Stdedos\Downloads\Archived\xpra\Xpra-x86_64_6.0-r34669M\lib\xpra\client\base\gobject.pyc)
2023-11-11 22:20:56,361 server requested disconnect:
2023-11-11 22:20:56,362  ConnectionMessage.SERVER_SHUTDOWN
2023-11-11 22:20:56,368 remote SSH stderr:
2023-11-11 22:20:56,368  Entering daemon mode; any further errors will be reported to:
2023-11-11 22:20:56,373    '/run/user/1000/xpra/1/server.log'

"was: Xpra-x86_64_6.0-r34669M\xpra_cmd" shadow ssh://user@ip/1 --ssh="plink -ssh -agent" --modal-windows=no --headerbar=off --source-start=gnome-keyring-daemon --title="@title@ on @@/@server-display@" --encodings=-webp --start="nohup systemd-inhibit --what=handle-lid-switch sleep 1d >/dev/null 2>&1 & inhibit_pid=\$! ; xpra xwait ; kill -9 \$inhibit_pid ; nohup systemd-inhibit --what=handle-lid-switch sleep 5m >/dev/null 2>&1 &" --microphone=off --speaker=off --webcam=no --pulseaudio=no --opengl=no --min-speed=70 --key-shortcut=Shift+F2:toggle_pointer_grab
```

but when loosing connectivity, I get:

```
(xpra_cmd:7252): Pango-WARNING **: 22:21:42.048: couldn't load font "URW Bookman L Not-Rotated 52.76171875", falling back to "Sans Not-Rotated 52.76171875", expect ugly output.
2023-11-11 22:21:49,622 server is not responding, drawing spinners over the windows
2023-11-11 22:22:11,231 remote SSH stderr:
2023-11-11 22:22:11,233  Entering daemon mode; any further errors will be reported to:
2023-11-11 22:22:11,234    '/run/user/1000/xpra/1/server.log'
CONNECTION_LOST, reconnecting
failed to re-connect using 'E:\\User\\Downloads\\Archived\\xpra\\Xpra-x86_64_6.0-r34669M\\Xpra-x86_64_6.0-r34669M\\xpra_cmd.exe'

"was: Xpra-x86_64_6.0-r34669M\xpra_cmd" shadow ssh://user@ip/1 --ssh="plink -ssh -agent" --modal-windows=no --headerbar=off --source-start=gnome-keyring-daemon --title="@title@ on @@/@server-display@" --encodings=-webp --start="nohup systemd-inhibit --what=handle-lid-switch sleep 1d >/dev/null 2>&1 & inhibit_pid=\$! ; xpra xwait ; kill -9 \$inhibit_pid ; nohup systemd-inhibit --what=handle-lid-switch sleep 5m >/dev/null 2>&1 &" --microphone=off --speaker=off --webcam=no --pulseaudio=no --opengl=no --min-speed=70 --key-shortcut=Shift+F2:toggle_pointer_grab
```

**Comment by totaam** [comment]
> `ImportError: cannot import name 'InfoTimerClient'`

Oops, fixed in 06def20f943bfb5faf5e45d4671701861634eaf3 - that's #4051

> `failed to re-connect using 'E:\\User\\Downloads\\Archived\\xpra\\Xpra-x86_64_6.0-r34669M\\Xpra-x86_64_6.0-r34669M\\xpra_cmd.exe'`

This path looks like it has the same directory twice? PITA.
I think that the exe wrapper changes directory before we get control.
8f510e44b62449e6ca03295a670dde66885d4da9 should work around that, this is for MS Windows only.

**Comment by totaam** [comment]
I believe this is fixed, please re-open if not.
