### ISSUE TITLE
Does not connect to xpra server, client failed to specify any supported encodings + ffmpeg: all the codecs have failed!

### ISSUE THREAD

**Issue by aurelg** [Xpra-org/xpra#4043]
**Describe the bug**
I'm trying to setup [xpra](https://github.com/Xpra-org/xpra) and [xpra-html5](https://github.com/Xpra-org/xpra-html5) to share my screen with other people using just their web browser.

My first attempt is to start `xterm` using `xpra` on localhost, and connect to it with a browser also running on localhost. 
The browser is immediately redirected to `http://127.0.0.1:10001/connect.html`, but can't proceed further.

**To Reproduce**
The server and client are running on the same machine:

```sh
# Server:
xpra start --daemon=no --mdns=no --bind-tcp=0.0.0.0:10001 --start=xterm
# Client: 
xdg-open http://localhost:10001
```

**System Information (please complete the following information):**
 - Server OS: Archlinux
 - Client OS: Archlinux
 - Xpra Server Version: 4.4.5-1
 - Xpra Client Version: xpra-html5-git 9.0.r14.g60cd4d0-1

**Additional context**

When the html5 client connects, the server issues there warnings/errors:

```
2023-10-27 11:11:35,467 New tcp connection received
2023-10-27 11:11:35,468  from '127.0.0.1:55148'
2023-10-27 11:11:35,468  on '0.0.0.0:10001'
2023-10-27 11:11:36,213 Handshake complete; enabling connection
2023-10-27 11:11:36,213 Warning: failed to convert dpi
2023-10-27 11:11:36,213  from <class 'dict'> using <class 'int'>: int() argument must be a string, a bytes-like object or a real number, not 'dict'
2023-10-27 11:11:36,223 listget('encodings', (), <class 'str'>, None)
2023-10-27 11:11:36,223 expected a list or tuple value for encodings but got <class 'dict'>
2023-10-27 11:11:36,229 listget('encodings', (), <class 'str'>, None)
2023-10-27 11:11:36,229 expected a list or tuple value for encodings but got <class 'dict'>
2023-10-27 11:11:36,230 Error setting up new connection for
2023-10-27 11:11:36,230  WebSocket(ws socket: 127.0.0.1:10001 <- 127.0.0.1:51432):
2023-10-27 11:11:36,230  client failed to specify any supported encodings
2023-10-27 11:11:36,232 Disconnecting client 127.0.0.1:51432:
2023-10-27 11:11:36,233  connection error (client failed to specify any supported encodings)
```

Maybe related: when the `xpra` sever starts, I see several paragraphs like this showing codecs are failing:

```
2023-10-27 11:49:32,609 enc_ffmpeg.Encoder.init_context(64, 32, YUV420P) self={'version': (60, 3, 100), 'encoding': 'h264+mp4', 'formats': ['YUV420P'], 'type': 'ffmpeg', 'frames': 0, 'width': 64, 'height': 32, 'muxer': 'mp4', 'video-codec': 'libx264', 'video-description': 'libx264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10', 'src_format': 'YUV420P', 'encoder_width': 64, 'encoder_height': 32}
2023-10-27 11:49:32,609 enc_ffmpeg.Encoder({'version': (60, 3, 100), 'encoding': 'h264+mp4', 'formats': ['YUV420P'], 'type': 'ffmpeg', 'frames': 0, 'width': 64, 'height': 32, 'muxer': 'mp4', 'video-codec': 'libx264', 'video-description': 'libx264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10', 'src_format': 'YUV420P', 'encoder_width': 64, 'encoder_height': 32}).clean_encoder()
2023-10-27 11:49:32,609 clean_encoder() freeing AVFrame: 0x7f8714197f80
2023-10-27 11:49:32,610 clean_encoder() freeing av format context 0x7f8714193140
2023-10-27 11:49:32,610 clean_encoder() freeing bitstream buffer 0x7f87149fdb80
2023-10-27 11:49:32,610 clean_encoder() freeing AVCodecContext: 0x7f871418fb40
2023-10-27 11:49:32,610 clean_encoder() done
2023-10-27 11:49:32,610 parse_event(..)=<X11:PropertyNotify {'send_event': '0', 'serial': '0x18b', 'delivered_to': '0x400009', 'window': '0x400009', 'atom': 'WM_ICON_NAME', 'time': '5659600'}>
2023-10-27 11:49:32,610 ffmpeg: h264+mp4 encoding failed
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/xpra/codecs/codec_checks.py", line 157, in testencoder
    testencoding(encoder_module, encoding, full)
  File "/usr/lib/python3.11/site-packages/xpra/codecs/codec_checks.py", line 174, in testencoding
    do_testencoding(encoder_module, encoding, W, H, full)
  File "/usr/lib/python3.11/site-packages/xpra/codecs/codec_checks.py", line 253, in do_testencoding
    v = e.compress_image(image)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "xpra/codecs/enc_ffmpeg/encoder.pyx", line 1703, in xpra.codecs.enc_ffmpeg.encoder.Encoder.compress_image
```

And later:

```
2023-10-27 11:49:32,635 ffmpeg: all the codecs have failed! (h264+mp4, mpeg4+mp4, mpeg1, mpeg2)
2023-10-27 11:49:32,635 xpra.codecs.enc_ffmpeg.encoder cleanup_module=<built-in function cleanup_module>
2023-10-27 11:49:32,635 enc_ffmpeg.cleanup_module()
```

I'd be happy to help!

**Comment by totaam** [comment]
Please do not open duplicate issues: https://github.com/Xpra-org/xpra-html5/issues/271
