### ISSUE TITLE
About / Session info cannot be opened

### ISSUE THREAD

**Issue by stdedos** [Xpra-org/xpra#4051]
**Describe the bug**

Tried to verify https://github.com/Xpra-org/xpra/issues/4023, but I saw instead

```
"Xpra-x86_64_6.0-r34669M\xpra_cmd" shadow ssh://user@ip/1 --ssh="plink -ssh -agent" --modal-windows=no --headerbar=off --source-start=gnome-keyring-daemon --title="@title@ on @@/@server-display@" --encodings=-webp --start="nohup systemd-inhibit --what=handle-lid-switch sleep 1d >/dev/null 2>&1 & inhibit_pid=\$! ; xpra xwait ; kill -9 \$inhibit_pid ; nohup systemd-inhibit --what=handle-lid-switch sleep 5m >/dev/null 2>&1 &" --microphone=off --speaker=off --webcam=no --pulseaudio=no --opengl=no --min-speed=70 --key-shortcut=Shift+F2:toggle_pointer_grab

XPRA_EXECUTABLE=Xpra-x86_64_6.0-r34669M

Note: GDK_WIN32_DISABLE_HIDPI is ignored due to preset
      DPI awareness settings in user settings or application
      manifest, DPI awareness is still enabled.
2023-11-11 22:15:38,370 Xpra GTK3 client version 6.0-r34669M (gabfb4684f) beta
2023-11-11 22:15:38,381  running on Microsoft Windows
2023-11-11 22:15:38,381  cpython 3.11
2023-11-11 22:15:40,271 GStreamer version 1.22.6
2023-11-11 22:15:40,443 created named pipe 'Xpra\\26268'
2023-11-11 22:15:40,676 Error setting up the pipeline:
2023-11-11 22:15:40,676  gst_parse_error: could not link decoder to sink (3)
2023-11-11 22:15:40,676  GStreamer pipeline for:
2023-11-11 22:15:40,676   appsrc name=src emit-signals=1 block=0 is-live=1 do-timestamp=1 stream-type=0 format=2 caps=video/x-h264,width=128,height=128,profile=(string)main,stream-format=(string)byte-stream,alignment=(string)au ! \
2023-11-11 22:15:40,677   d3d11h264dec name=decoder ! \
2023-11-11 22:15:40,677   appsink name=sink emit-signals=1 max-buffers=10 drop=false sync=false async=true qos=false caps=video/x-raw,width=128,height=128,format=(string)I420
2023-11-11 22:15:40,677 Error creating context h264 128x128 YUV420P
2023-11-11 22:15:40,677 gstreamer: h264 decoding failed: failed to setup gstreamer pipeline
2023-11-11 22:15:40,682 keyboard layout 'United States - English' : 'us' (0x409)
2023-11-11 22:15:40,854  keyboard settings: layout=us
2023-11-11 22:15:40,856  desktop size is 4480x1516:
2023-11-11 22:15:40,857   Default (1185x401 mm - DPI: 96x96) workarea: 4480x1476
2023-11-11 22:15:40,857     Samsung C32JG5x  2560x1440 at    0x0    (697x392 mm - DPI: 93x93) workarea: 2560x1400
2023-11-11 22:15:40,858     LG IPS234        1920x1080 at 2560x436  (510x290 mm - DPI: 96x95) workarea: 1920x1040 at 2560x436
2023-11-11 22:15:47,492 enabled remote logging
2023-11-11 22:15:47,493 Xpra shadow server version 5.0
2023-11-11 22:15:47,494  remote desktop size is 1920x1200
2023-11-11 22:15:47,494   :1.0 (508x318 mm - DPI: 96x96) workarea: 1848x1173 at   72x27
2023-11-11 22:15:47,494     LGD eDP-1        (336x210 mm - DPI: 145x145)
2023-11-11 22:15:47,873 running, 1 windows

(xpra_cmd:26268): Pango-WARNING **: 22:15:50.851: couldn't load font "Petyka - Retro Computer___SHORT Not-Rotated 17.98828125", falling back to "Sans Not-Rotated 17.98828125", expect ugly output.

(xpra_cmd:26268): Pango-WARNING **: 22:15:50.887: couldn't load font "DejaVu Serif Not-Rotated 59.796875", falling back to "Sans Not-Rotated 59.796875", expect ugly output.

(xpra_cmd:26268): Pango-WARNING **: 22:15:50.895: couldn't load font "URW Bookman L Not-Rotated 52.76171875", falling back to "Sans Not-Rotated 52.76171875", expect ugly output.

Traceback (most recent call last):
  File "E:/xpra/xpra/gtk/dialogs/about.py", line 70, in about
TypeError: second argument must be callable
Traceback (most recent call last):
  File "E:/xpra/xpra/client/gtk3/menu_helper.py", line 485, in show_session_info_cb
  File "E:/xpra/xpra/client/gtk3/menu_helper.py", line 364, in show_session_info
  File "E:/xpra/xpra/client/gtk3/client_base.py", line 698, in show_session_info
  File "E:/xpra/xpra/gtk/dialogs/session_info.py", line 25, in <module>
ImportError: cannot import name 'InfoTimerClient' from 'xpra.client.base.gobject' (E:\Stdedos\Downloads\Archived\xpra\Xpra-x86_64_6.0-r34669M\lib\xpra\client\base\gobject.pyc)
```

**To Reproduce**
1. server command
2. client command
3. specific action to trigger the bug

**System Information (please complete the following information):**
- Server OS: Ubuntu 20.04.6 LTS
- Client OS: Microsoft Windows [Version 10.0.18363.836]
- Xpra Server Version: (see above)
- Xpra Client Version: (see above)

**Additional context**
Please see "reporting bugs" in the wiki section.

**Comment by totaam** [comment]
Fixed in 06def20f943bfb5faf5e45d4671701861634eaf3
