### ISSUE TITLE
Failing to set encoding h264:  object has no attribute 'check_randr'

### ISSUE THREAD

**Issue by devrite** [Xpra-org/xpra#4103]
Hi everyone,

have not found any solution or info in the doc that helped and what previously worked does not seem to do now.

**Describe the bug**
Forcing the encoding (h264) fails although both instances and client and server report the encoding.

Produces failure to set resolution on server and common encoding (server empty, client h264):
```sh
File "/usr/lib/python3/dist-packages/xpra/x11/x11_server_core.py", line 779, in set_screen_size
    if RandR.check_randr():
AttributeError: 'xpra.x11.bindings.randr.RandRBindingsInstance' object has no attribute 'check_randr'
```

**To Reproduce**
On Ubuntu Jammy and Jammy on the client with the package version 5.0.4-r0-1 from official repos installed and all suggested and recommended packages.

1. xpra start :101--start=xterm --encodings=h264
2. xpra attach ssh://myhost/101 --encodings=h264

**System Information (please complete the following information):**
 - Server OS: Ubuntu 22.04
 - Client OS:  Ubuntu 22.04
 - Xpra Server Version v5.0.4-r0M
 - Xpra Client Version v5.0.4-r0M

**Additional context**

Server encodings and encoders:
```sh
 * h264        H.264 video codec
 * vp8         VP8 video codec
 * vp9         VP9 video codec
 * png         Portable Network Graphics (lossless, 24bpp or 32bpp for transparency)
 * png/P       Portable Network Graphics (lossy, 8bpp colour)
 * png/L       Portable Network Graphics (lossy, 8bpp grayscale)
 * webp        WebP compression (supports lossless and lossy modes)
 * avif        AVIF: AV1 Image File Format
 * rgb         Raw RGB pixels, lossless, may be compressed using lz4 or zlib (24bpp or 32bpp for transparency)
 * jpeg        JPEG lossy compression
 * jpega       JPEG lossy compression, with alpha channel
 * scroll      motion vectors, supplemented with picture codecs

the following video-encoders are defined: x264, openh264, vpx, nvenc, ffmpeg, nvjpeg, jpeg, webp, gstreamer
```

Client encodings and decoders:

```sh
GTK3 Wayland xpra client supports the following encodings:
 * auto        automatic mode (recommended)
 * stream      video stream
 * grayscale   same as 'auto' but in grayscale mode
 * h264        H.264 video codec
 * h265        H.265 (HEVC) video codec (not recommended)
 * av1         AV1: AOMedia Video 1
 * vp8         VP8 video codec
 * vp9         VP9 video codec
 * mpeg4       MPEG-4 video codec
 * png         Portable Network Graphics (lossless, 24bpp or 32bpp for transparency)
 * png/P       Portable Network Graphics (lossy, 8bpp colour)
 * png/L       Portable Network Graphics (lossy, 8bpp grayscale)
 * webp        WebP compression (supports lossless and lossy modes)
 * avif        AVIF: AV1 Image File Format
 * rgb         Raw RGB pixels, lossless, may be compressed using lz4 or zlib (24bpp or 32bpp for transparency)
 * jpeg        JPEG lossy compression
 * jpega       JPEG lossy compression, with alpha channel
 * scroll      motion vectors, supplemented with picture codecs
 
the following video-decoders are defined: avcodec2, openh264, vpx, gstreamer, nvdec
```
```sh
Socket path '/tmp/.X11-unix/X101' not found
2024-01-22 08:19:07,315 no uinput module (not usually needed)
2024-01-22 08:19:08,611 pointer device emulation using XTest
2024-01-22 08:19:08,688 serving html content from '/usr/share/xpra/www'
2024-01-22 08:19:08,688 wrote pid 784153 to '/run/user/1000/xpra/101/server.pid'
2024-01-22 08:19:08,702 created unix domain socket '/run/user/1000/xpra/myhost-101'
2024-01-22 08:19:08,702 cannot create group socket '/run/xpra/myhost-101'
2024-01-22 08:19:08,702  [Errno 13] Permission denied
2024-01-22 08:19:08,703 created unix domain socket '/home/user/.xpra/myhost-101'
2024-01-22 08:19:08,703 created unix domain socket '/run/user/1000/xpra/101/socket'
2024-01-22 08:19:08,703 xvfb pid=784160
2024-01-22 08:19:08,726 D-Bus notification forwarding is available
2024-01-22 08:19:08,750 pulseaudio server started with pid 784187
2024-01-22 08:19:08,750  private server socket path:
2024-01-22 08:19:08,750  '/run/user/1000/xpra/101/pulse/pulse/native'
2024-01-22 08:19:08,858 python-zeroconf: '::' IPv6 loopback address is not supported
2024-01-22 08:19:08,888 watching for applications menu changes in:
2024-01-22 08:19:08,888  '/usr/share/applications'
2024-01-22 08:19:08,889  '/var/lib/snapd/desktop/applications'
2024-01-22 08:19:08,916 Warning: webcam forwarding is disabled
2024-01-22 08:19:08,921  the virtual video directory '/sys/devices/virtual/video4linux' was not found
2024-01-22 08:19:08,922  make sure that the 'v4l2loopback' kernel module is installed and loaded
2024-01-22 08:19:08,922  or use the 'webcam=no' option
2024-01-22 08:19:08,922 found 0 virtual video devices for webcam forwarding
2024-01-22 08:19:09,024 GStreamer version 1.20.3
2024-01-22 08:19:09,039 xpra is ready.
2024-01-22 08:19:09,040 xpra X11 seamless server version 5.0.4-r0M
2024-01-22 08:19:09,041  uid=1000 (user), gid=1000 (user)
2024-01-22 08:19:09,041  running with pid 784153 on Linux Ubuntu 22.04 jammy
2024-01-22 08:19:09,151  connected to X11 display :101 with 24 bit colors
2024-01-22 08:19:10,297 loaded 66 start menu entries from 11 sub-menus in 1.3 seconds
2024-01-22 08:19:12,663 printer forwarding enabled using postscript and pdf
2024-01-22 08:19:12,783 some GStreamer elements are missing or unavailable on this system:
2024-01-22 08:19:12,783  vaapih264enc, vaapih265enc, amfh264enc, amfh265enc
2024-01-22 08:19:12,875 62.5GB of system memory
2024-01-22 08:19:13,303 OpenGL is supported on display ':101'
2024-01-22 08:19:13,304  using 'llvmpipe (LLVM 15.0.7, 256 bits)' renderer
2024-01-22 08:19:13,305 started command `xterm` with pid 784319
2024-01-22 08:19:13,308 started command `ibus-daemon` with pid 784320
2024-01-22 08:19:19,811 New socket connection received
2024-01-22 08:19:19,811  on '/run/user/1000/xpra/101/socket'
2024-01-22 08:19:19,816 Handshake complete; enabling connection
2024-01-22 08:19:19,839 Python/GTK3 Linux Ubuntu 22.04 jammy Wayland client version 5.0
2024-01-22 08:19:19,839  OpenGL is disabled
2024-01-22 08:19:19,841 setting keymap: layout=at
2024-01-22 08:19:19,874 Warning: client did not supply any modifier definitions
2024-01-22 08:19:19,907  client root window size is 1920x2280
2024-01-22 08:19:19,907   wayland-0 (520x490 mm - DPI: 94x118)
2024-01-22 08:19:19,908     DEL DELL U2412M  1920x1200 at    0x0    (520x320 mm - DPI: 94x95) workarea: 1920x1200
2024-01-22 08:19:19,908     AUO 0x243d       1920x1080 at    0x1200 (310x170 mm - DPI: 157x161) workarea: 1920x1080 at    0x1200
2024-01-22 08:19:20,412 ouch, failed to set new resolution: 'xpra.x11.bindings.randr.RandRBindingsInstance' object has no attribute 'check_randr'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xpra/x11/x11_server_core.py", line 779, in set_screen_size
    if RandR.check_randr():
AttributeError: 'xpra.x11.bindings.randr.RandRBindingsInstance' object has no attribute 'check_randr'
2024-01-22 08:19:20,418  automatic picture encoding enabled, also available:
2024-01-22 08:19:20,418   h264
2024-01-22 08:19:20,429 client   1 @02.760 Xpra X11 seamless server version 5.0
2024-01-22 08:19:20,438 Error: processing new connection from Protocol(socket socket:/run/user/1000/xpra/101/socket):
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xpra/server/server_base.py", line 460, in process_hello_ui
    self.send_initial_data(ss, c, send_ui, share_count)
  File "/usr/lib/python3/dist-packages/xpra/server/server_base.py", line 485, in send_initial_data
    bc.send_initial_data(self, ss, c, send_ui, share_count)
  File "/usr/lib/python3/dist-packages/xpra/server/mixins/window.py", line 141, in send_initial_data
    self.send_initial_windows(ss, share_count>0)
  File "/usr/lib/python3/dist-packages/xpra/x11/server.py", line 483, in send_initial_windows
    ss.new_window("new-window", wid, window, x, y, w, h, wprops)
  File "/usr/lib/python3/dist-packages/xpra/server/source/windows.py", line 441, in new_window
    self.send_window_icon(wid, window)
  File "/usr/lib/python3/dist-packages/xpra/server/source/windows.py", line 447, in send_window_icon
    ws = self.make_window_source(wid, window)
  File "/usr/lib/python3/dist-packages/xpra/server/source/windows.py", line 589, in make_window_source
    ws.init_encoders()
  File "/usr/lib/python3/dist-packages/xpra/server/window/window_source.py", line 373, in init_encoders
    self.do_init_encoders()
  File "/usr/lib/python3/dist-packages/xpra/server/window/window_video_source.py", line 207, in do_init_encoders
    super().do_init_encoders()
  File "/usr/lib/python3/dist-packages/xpra/server/window/window_source.py", line 416, in do_init_encoders
    self.update_encoding_selection(self.encoding, init=True)
  File "/usr/lib/python3/dist-packages/xpra/server/window/window_video_source.py", line 442, in update_encoding_selection
    super().update_encoding_selection(encoding, exclude, init)
  File "/usr/lib/python3/dist-packages/xpra/server/window/window_source.py", line 882, in update_encoding_selection
    raise ValueError("no common encodings found (server: %s vs client: %s, excluding: %s)" % (
ValueError: no common encodings found (server:  vs client: h264, excluding: )
2024-01-22 08:19:20,440 Disconnecting client /run/user/1000/xpra/101/socket:
2024-01-22 08:19:20,440  ConnectionMessage.CONNECTION_ERROR (error accepting new connection)
2024-01-22 08:19:20,442 Python/GTK3 client 1 disconnected.
```

**Comment by totaam** [comment]
> `AttributeError: 'xpra.x11.bindings.randr.RandRBindingsInstance' object has no attribute 'check_randr'`

This one is due for 5.0.5: 30c7cfa5a9f119aac300b5652d3d545f9ca799cf

> Forcing the encoding (h264)

Don't do that. Please see the documentation.

> `xpra start :101--start=xterm --encodings=h264`
> (..)
> `ValueError: no common encodings found (server:  vs client: h264, excluding: )`

Don't do that.

**Comment by devrite** [comment]
Was just to force it. It was not selectable either way.
