### ISSUE TITLE
_ctypes.COMError: (-2147467262, 'Such connection is not supported', (None, None, None, 0, None))

### ISSUE THREAD

**Issue by stdedos** [Xpra-org/xpra#4109]
**Describe the bug**

```py
"Xpra-x86_64_6.0-r35031\xpra_cmd" shadow ssh://user@ip/1 --ssh="plink -ssh -agent" --modal-windows=no --headerbar=off --source-start=gnome-keyring-daemon --title="@title@ on @@/@server-display@" --encodings=-webp --start="nohup systemd-inhibit --what=handle-lid-switch sleep 1d >/dev/null 2>&1 & inhibit_pid=\$! ; xpra xwait ; kill -9 \$inhibit_pid ; nohup systemd-inhibit --what=handle-lid-switch sleep 5m >/dev/null 2>&1 &" --microphone=off --speaker=off --webcam=no --pulseaudio=no --opengl=no --min-speed=70 --key-shortcut=Shift+F2:toggle_pointer_grab

XPRA_EXECUTABLE=Xpra-x86_64_6.0-r35031

Note: GDK_WIN32_DISABLE_HIDPI is ignored due to preset
      DPI awareness settings in user settings or application
      manifest, DPI awareness is still enabled.2024-01-29 21:43:51,309 xpra main error:
Traceback (most recent call last):
  File "E:/xpra/xpra/scripts/main.py", line 134, in main
  File "E:/xpra/xpra/scripts/main.py", line 507, in run_mode
  File "E:/xpra/xpra/scripts/main.py", line 564, in do_run_mode
  File "E:/xpra/xpra/scripts/main.py", line 2223, in run_remote_server
  File "E:/xpra/xpra/scripts/main.py", line 1904, in make_client
  File "E:/xpra/xpra/client/gtk3/client.py", line 10, in <module>
  File "E:/xpra/xpra/client/gtk3/client_base.py", line 79, in <module>
  File "E:/xpra/xpra/client/gtk3/window_base.py", line 125, in <module>
  File "C:/msys64/mingw64/lib/python3.11/site-packages/pyvda/__init__.py", line 58, in <module>
  File "C:/msys64/mingw64/lib/python3.11/site-packages/pyvda/pyvda.py", line 20, in <module>
  File "C:/msys64/mingw64/lib/python3.11/site-packages/pyvda/utils.py", line 61, in __init__
  File "C:/msys64/mingw64/lib/python3.11/site-packages/pyvda/utils.py", line 44, in get_vd_manager_internal2
  File "C:/msys64/mingw64/lib/python3.11/site-packages/pyvda/utils.py", line 30, in _get_object
_ctypes.COMError: (-2147467262, 'Δεν υποστηρίζεται τέτοια διασύνδεση', (None, None, None, 0, None))
```

**To Reproduce**
1. server command
2. client command
3. specific action to trigger the bug

**System Information (please complete the following information):**
- Server OS: Ubuntu 20.04.6 LTS
- Client OS: Microsoft Windows [Version 10.0.18363.836]
- Xpra Server Version: (see above)
- Xpra Client Version: (see above)

**Additional context**
Please see "reporting bugs" in the wiki section.

**Comment by totaam** [comment]
Ouch. Sorry.

Hopefully the commits above fix that - I'm obviously not hitting this issue here and I hope this doesn't prevent #1442 from working.

Please try 6.0-r35043 or later.

**Comment by totaam** [comment]
It is now a known issue with `pyvda`: https://github.com/mrob95/pyvda/issues/35
It seems to have been caused by a Windows update.

**Comment by totaam** [comment]
This has caused more serious breakage: #4429

**Comment by stdedos** [comment]
😢
