### ISSUE TITLE
conflict with builtin types

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#4163]
This stopped working:
```shell
$ python ./xpra/util/version.py

Traceback (most recent call last):
  File "E:/xpra/xpra/util/version.py", line 9, in <module>
    import socket
  File "C:/msys64/mingw64/lib/python3.11/socket.py", line 55, in <module>
    from enum import IntEnum, IntFlag
  File "C:/msys64/mingw64/lib/python3.11/enum.py", line 3, in <module>
    from types import MappingProxyType, DynamicClassAttribute
  File "E:/xpra/xpra/util/types.py", line 7, in <module>
    from typing import Any
  File "C:/msys64/mingw64/lib/python3.11/typing.py", line 26, in <module>
    import contextlib
  File "C:/msys64/mingw64/lib/python3.11/contextlib.py", line 7, in <module>
    from functools import wraps
  File "C:/msys64/mingw64/lib/python3.11/functools.py", line 22, in <module>
    from types import GenericAlias
ImportError: cannot import name 'GenericAlias' from partially initialized module 'types' (most likely due to a circular import) (E:/xpra/xpra/util/types.py)
```

**Comment by totaam** [comment]
Solved by the renaming in the commit above.
