### ISSUE TITLE
Can't attach session when Cisco AnyConnect VPN is enabled with openconnect

### ISSUE THREAD

**Issue by btasdelen** [Xpra-org/xpra#4165]
**Describe the bug**
Xpra can start and attach a session when the Cisco AnyConnect Secure Mobility Client is used, but gives the following exception only for the attach command, when I use the openconnect to connect to the same VPN network using KDE's network manager dialog:

```
2024-03-15 11:11:57,516 error preparing connection: 'int' object has no attribute 'get_vendor'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/xpra/client/base/client_base.py", line 391, in send_hello
    hello.update(self.make_hello())
                 ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xpra/client/gtk3/gtk_client_base.py", line 841, in make_hello
    capabilities = UIXpraClient.make_hello(self)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xpra/client/gui/ui_client_base.py", line 426, in make_hello
    caps.update(c.get_caps(self))
                ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xpra/client/mixins/network_state.py", line 232, in get_caps
    default_adapter_type = guess_adapter_type(get_NM_adapter_type(device_name) or device_name)
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xpra/client/mixins/network_state.py", line 71, in get_NM_adapter_type
    log(f"NM device {device_name!r}: {nmdevice.get_vendor()} {nmdevice.get_product()}")
                                      ^^^^^^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'get_vendor'
```
Starting a new session works, but I still can not attach the newly created session after detaching on openconnect VPN.

**To Reproduce**
1. Connect to VPN using openconnect.
2. Start a new session with `xpra start`. Then detach the session.
3. Try attaching the server with `xpra attach`.
 
**System Information (please complete the following information):**
 - Server OS: Ubuntu 20.04.6
 - Client OS: Arch Linux
 - Xpra Server Version v5.0-r33693
 - Xpra Client Version v5.0.7-r0

**Comment by totaam** [comment]
Sorry about that.
The trivial patch above should fix this problem.
You can easily apply it by hand or wait for the 5.0.8 release.

**Comment by btasdelen** [comment]
Thanks for the prompt patch! Works like a charm. Closing.

**Comment by totaam** [comment]
This broke things for other users: #4299
