### ISSUE TITLE
Paramiko does not work on Official Windows Installer Build

### ISSUE THREAD

**Issue by Simba98** [Xpra-org/xpra#4192]
**Describe the bug**
On Windows, the exe installer (EXE) version's paramiko will not work but the portable (ZIP) version works well.
This is a cryptography issue, which is referred by paramiko. See the following discussion:
https://github.com/paramiko/paramiko/issues/2360
https://github.com/pyca/cryptography/issues/10300

**To Reproduce**
1. server command: Any
2. client command: & 'C:\Program Files\Xpra\Xpra_cmd.exe' attach ssh://SOMETHING -d ssh
3. specific action to trigger the bug: You will see it in the log.

**System Information (please complete the following information):**
 - Client OS: e.g. Windows 11
 - Xpra Client Version: v5.0.8-r0, and also v5.0.7.

**Additional context**
The installer version:
```
& 'C:\Program Files\Xpra\Xpra_cmd.exe' attach ssh://SOMETHING -d ssh

2024-04-18 12:43:15,314 debug enabled for xpra.scripts.parsing / ('ssh',)
2024-04-18 12:43:15,314 parse_ssh_option(auto)
Traceback (most recent call last):
  File "E:/xpra/xpra/scripts/parsing.py", line 613, in parse_ssh_option
  File "C:/msys64/mingw64/lib/python3.11/site-packages/paramiko/__init__.py", line 22, in <module>
  File "C:/msys64/mingw64/lib/python3.11/site-packages/paramiko/transport.py", line 33, in <module>
  File "C:/msys64/mingw64/lib/python3.11/site-packages/cryptography/hazmat/primitives/ciphers/__init__.py", line 11, in <module>
  File "C:/msys64/mingw64/lib/python3.11/site-packages/cryptography/hazmat/primitives/ciphers/base.py", line 10, in <module>
  File "C:/msys64/mingw64/lib/python3.11/site-packages/cryptography/exceptions.py", line 9, in <module>
ImportError: DLL load failed while importing _rust: The specified procedure could not be found.
```

The portable version (Unzip from the zip):
cmd: 
```
&C:\PATH_TO_XPRA\Xpra-x86_64_5.0.8-r0\Xpra_cmd.exe attach ssh://SOMETHING -d ssh

2024-04-18 12:48:43,461 debug enabled for xpra.scripts.parsing / ('ssh',)
2024-04-18 12:48:43,461 using paramiko ssh backend
2024-04-18 12:48:43,461 debug enabled for xpra.scripts.parsing / ('ssh',)
2024-04-18 12:48:43,461 using paramiko ssh backend
2024-04-18 12:48:45,251 debug enabled for xpra.net.ssh.paramiko_client / ('network', 'ssh')
```

**Comment by totaam** [comment]
Could be a packaging issue. Or maybe a virus scanner issue.
The contents of the ZIP file and EXE should be identical, they are created from the exact same directory.

Does xpra correctly fall back to using plink?

**Comment by Simba98** [comment]
> Could be a packaging issue. Or maybe a virus scanner issue. The contents of the ZIP file and EXE should be identical, they are created from the exact same directory.
> 
> Does xpra correctly fall back to using plink?

Yes, the exe version fall back to plink correctly, as expected.
> 2024-04-19 11:44:34,311 paramiko not found, using plink.exe -ssh -agent
And TortoisePlink pops a window asking for password.

And I am using a Local Administrator group user, with UAC enabled.
So I tried to run it in an elevated mode, but the issue still here.

The only Anti-virus software installed is Windows Defender, with no warning from it.
The current system version is: 22631.3296.

Any ideas to debug from the packaged version? Since debug from source may not be helpful in this case.

**Comment by totaam** [comment]
I've just installed this package (`sha256sum`):
```
f0c7add576047c78b6784299649ffd5f2fe112bcdf1d4ec64edbf73284ea9489  Xpra-Light-x86_64_Setup_5.0.8-r0.exe
```
On a clean MS Windows 11 VM and paramiko worked out of the box on the first attempt.

Then got the same result with:
```
1a7b0b5490e66020118cd127d05624cd61106402a45d1d2d91155fbfb0c63940  Xpra-x86_64_Setup_5.0.8-r0.exe
```

So there is something wrong with your installation.
Typically, that's caused by:
* virus scanners putting files in quarantine
* bad environment variables (ie: `%PATH%`) causing some library conflicts
