### ISSUE TITLE
`AttributeError` and Cache Directory Issues with `comtypes`

### ISSUE THREAD

**Issue by stdedos** [Xpra-org/xpra#4200]
**Describe the bug**

```python
"Xpra-x86_64_6.0-r35620\xpra_cmd" shadow ssh://user@ip/0 --ssh="plink -ssh -agent" --modal-windows=no --headerbar=off --title="@title@ on @@/@server-display@" --encodings=-webp --microphone=off --speaker=off --webcam=no --pulseaudio=no --opengl=no --min-speed=70 --key-shortcut=Shift+F2:toggle_pointer_grab

XPRA_EXECUTABLE=Xpra-x86_64_6.0-r35620


2024-04-24 23:57:46,829 Xpra GTK3 client version 6.0-r35620 (g79036646b) beta
2024-04-24 23:57:47,093  running on Microsoft Windows Microsoft Windows 10 Enterprise
2024-04-24 23:57:47,093  cpython 3.11
2024-04-24 23:57:47,694 GStreamer version 1.24.1
2024-04-24 23:57:47,716 created named pipe 'Xpra\25596'
2024-04-24 23:57:47,952 Error setting up the pipeline:
2024-04-24 23:57:47,952  gst_parse_error: could not link decoder to sink (3)
2024-04-24 23:57:47,952  GStreamer pipeline for:
2024-04-24 23:57:47,952   appsrc name=src emit-signals=1 block=0 is-live=1 do-timestamp=1 stream-type=0 format=2 caps=video/x-h264,width=128,height=128,profile=(string)main,stream-format=(string)byte-stream,alignment=(string)au ! \
2024-04-24 23:57:47,952   d3d11h264dec name=decoder ! \
2024-04-24 23:57:47,952   appsink name=sink emit-signals=1 max-buffers=10 drop=False sync=False async=True qos=False caps=video/x-raw,width=128,height=128,format=(string)I420
2024-04-24 23:57:47,952 Error creating context h264 128x128 YUV420P
2024-04-24 23:57:47,953 gstreamer: h264 decoding failed: failed to setup gstreamer pipeline
2024-04-24 23:57:47,961 keyboard layout 'United States - English' : 'us' (0x409)
2024-04-24 23:57:48,063  keyboard settings: layout=us
2024-04-24 23:57:48,065  desktop size is 4480x1516:
2024-04-24 23:57:48,066   Default (1185x401 mm - DPI: 96x96) workarea: 4480x1476
2024-04-24 23:57:48,066     Samsung C32JG5x  2560x1440 at    0x0    (697x392 mm - DPI: 93x93) workarea: 2560x1400
2024-04-24 23:57:48,066     LG IPS234        1920x1080 at 2560x436  (510x290 mm - DPI: 96x95) workarea: 1920x1040 at 2560x436
2024-04-24 23:57:52,533 enabled remote logging
2024-04-24 23:57:52,535 Xpra shadow server version 5.0
2024-04-24 23:57:52,536  remote desktop size is 1920x1200
2024-04-24 23:57:52,537   :0.0 (508x317 mm - DPI: 96x96) workarea: 1851x1173 at   69x27
2024-04-24 23:57:52,537     LGD eDP-1        (336x210 mm - DPI: 145x145)
2024-04-24 23:57:52,852 running, 1 windows
2024-04-25 00:02:55,434 downloaded 51154 bytes to temporary file:
2024-04-25 00:02:55,436  '~\Downloads\my.txt'
2024-04-25 00:02:55,448 Could not import comtypes.gen, trying to create it.
2024-04-25 00:02:55,449 Creating comtypes.gen package failed: [WinError 3] Το σύστημα δεν είναι σε θέση να εντοπίσει την καθορισμένη διαδρομή δίσκου: '~\\Xpra-x86_64_6.0-r35620\\lib\\library.zip\\comtypes\\gen'
2024-04-25 00:02:55,450 Created a memory-only package.
2024-04-25 00:02:55,450 Creating writeable comtypes cache directory: 'AppData\Local\Temp\comtypes_cache\Xpra_cmd-311'
2024-04-25 00:02:55,451 Using writeable comtypes cache directory: 'AppData\Local\Temp\comtypes_cache\Xpra_cmd-311'
2024-04-25 00:02:56,877 UI thread is now blocked
Traceback (most recent call last):
  File "E:/xpra/xpra/gtk/dialogs/open_requests.py", line 303, in transfer_progress_update
  File "E:/xpra/xpra/platform/win32/gui.py", line 1043, in set_window_progress
  File "E:/xpra/xpra/platform/win32/gui.py", line 1035, in getTaskbar
AttributeError: module 'comtypes.gen.TaskbarLib' has no attribute 'ITaskbarlist3'. Did you mean: 'ITaskbarList3'?
2024-04-25 00:02:57,693 UI thread is running again, resuming
```

**To Reproduce**
1. server command
2. client command
3. specific action to trigger the bug

**System Information (please complete the following information):**
- Server OS: Ubuntu 20.04.6 LTS
- Client OS: Microsoft Windows [Version 10.0.18363.836]
- Xpra Server Version: (see above)
- Xpra Client Version: (see above)

**Additional context**
Please see "reporting bugs" in the wiki section.

**Comment by totaam** [comment]
This had been broken for 8 months!?

Thanks!
