### ISSUE TITLE
Cannot work on windows

### ISSUE THREAD

**Issue by cadem** [Xpra-org/xpra#4206]
I cannot use xpra on windows.
```
"C:\Program Files\Xpra\Xpra_cmd.exe" attach ssh://ubuntu@127.0.0.1:34021/100

2024-05-01 00:17:40,504 Xpra GTK3 client version 6.0-r0
2024-05-01 00:17:40,982  running on Microsoft Windows Microsoft Windows 11 家庭中文版
2024-05-01 00:17:40,984  cpython 3.11
2024-05-01 00:17:46,225 GStreamer version 1.24.2
2024-05-01 00:17:46,244 created named pipe 'Xpra\16344'
2024-05-01 00:17:46,607 Error setting up the pipeline:
2024-05-01 00:17:46,607  gst_parse_error: could not link decoder to sink (3)
2024-05-01 00:17:46,607  GStreamer pipeline for:
2024-05-01 00:17:46,608   appsrc name=src emit-signals=1 block=0 is-live=1 do-timestamp=1 stream-type=0 format=2 caps=video/x-h264,width=128,height=128,profile=(string)main,stream-format=(string)byte-stream,alignment=(string)au ! \
2024-05-01 00:17:46,608   d3d11h264dec name=decoder ! \
2024-05-01 00:17:46,608   appsink name=sink emit-signals=1 max-buffers=10 drop=False sync=False async=True qos=False caps=video/x-raw,width=128,height=128,format=(string)I420
2024-05-01 00:17:46,608 Error creating context h264 128x128 YUV420P
2024-05-01 00:17:46,609 gstreamer: h264 decoding failed: failed to setup gstreamer pipeline
2024-05-01 00:17:46,619 keyboard layout 'Chinese (Simplified) - US Keyboard' : 'cn' (0x804)
2024-05-01 00:17:47,639 OpenGL accelerate missing: numpy_formathandler
2024-05-01 00:17:47,670 OpenGL enabled on 'AMD Radeon(TM) Vega 8 Graphics'
2024-05-01 00:17:47,955 Connected (version 2.0, client OpenSSH_8.9p1)
2024-05-01 00:17:48,200 Authentication (publickey) successful!
2024-05-01 00:17:48,492 ssh server OS is 'linux-gnu'
2024-05-01 00:17:48,850 paramiko SSH agent forwarding enabled
2024-05-01 00:17:48,873  keyboard settings: layout=cn
2024-05-01 00:17:48,875  desktop size is 3840x1080:
2024-05-01 00:17:48,876   Default (1016x285 mm - DPI: 96x96) workarea: 3840x1032
2024-05-01 00:17:48,876     Philips 234CL    1920x1080 at    0x0    (509x286 mm - DPI: 96x96) workarea: 1920x1032
2024-05-01 00:17:48,877     Huawei Huawei PnP Monitor 1920x1080 at 1920x0    (309x173 mm - DPI: 158x159) workarea: 1920x1032 at 1920x0
2024-05-01 00:18:18,869 connection timed out
2024-05-01 00:18:18,873 SSH EOF on stderr of run-xpra
```
Before running xpra, I have already set up tunnel at port 34021, I can connect 34021 via ssh.

**Comment by totaam** [comment]
Run with `-d ssh` to get more ssh debug messages.
Or if the problem comes from `paramiko`, try with `--ssh=ssh`

**Comment by cadem** [comment]
C:\Users\Administrator>"C:\Program Files\Xpra\Xpra_cmd.exe" -d ssh --ssh=ssh attach ssh://ubuntu@127.0.0.1:34021/100

2024-05-01 13:46:47,358 Xpra GTK3 client version 5.0.8-r0
2024-05-01 13:46:47,382  running on Microsoft Windows 10
2024-05-01 13:46:50,227 GStreamer version 1.24.1
2024-05-01 13:46:50,392 created named pipe 'Xpra\\5228'
2024-05-01 13:46:51,414 keyboard layout 'Chinese (Simplified) - US Keyboard' : 'cn' (0x804)
2024-05-01 13:46:51,537 debug enabled for xpra.net.ssh.exec_client / ('network', 'ssh')
2024-05-01 13:46:51,537 executing ssh command: "ssh" "-l" "ubuntu" "-p" "34021" "-T" "127.0.0.1" "sh -c 'if command -v "xpra" > /dev/null 2>&1; then xpra _proxy "100";elif [ -x $XDG_RUNTIME_DIR/xpra/run-xpra ]; then $XDG_RUNTIME_DIR/xpra/run-xpra _proxy "100";elif [ -x /usr/local/bin/xpra ]; then /usr/local/bin/xpra _proxy "100";elif [ -x ~/.xpra/run-xpra ]; then ~/.xpra/run-xpra _proxy "100";elif [ -x Xpra_cmd.exe ]; then Xpra_cmd.exe _proxy "100";else echo "no run-xpra command found"; exit 1; fi'"
2024-05-01 13:46:51,600  keyboard settings: layout=cn
2024-05-01 13:46:51,600  desktop size is 1920x973:
2024-05-01 13:46:51,612   Default (508x257 mm - DPI: 96x96) workarea: 1920x933
2024-05-01 13:46:51,612     通用非即插即用监视器
2024-05-01 13:46:54,037 SSH EOF on stderr of ['ssh', '-l', 'ubuntu', '-p', '34021', '-T', '127.0.0.1', 'sh -c \'if command -v "xpra" > /dev/null 2>&1; then xpra _proxy "100";elif [ -x $XDG_RUNTIME_DIR/xpra/run-xpra ]; then $XDG_RUNTIME_DIR/xpra/run-xpra _proxy "100";elif [ -x /usr/local/bin/xpra ]; then /usr/local/bin/xpra _proxy "100";elif [ -x ~/.xpra/run-xpra ]; then ~/.xpra/run-xpra _proxy "100";elif [ -x Xpra_cmd.exe ]; then Xpra_cmd.exe _proxy "100";else echo "no run-xpra command found"; exit 1; fi\'']
2024-05-01 13:46:54,052 Error: failed to receive anything, not an xpra server?
2024-05-01 13:46:54,052 remote SSH stderr:
2024-05-01 13:46:54,052   could also be the wrong protocol, username, password or port
2024-05-01 13:46:54,052  Host key verification failed.
2024-05-01 13:46:54,052   or the session was not found
2024-05-01 13:46:54,052 Connection failed

But I can connect via ssh directly.

**Comment by totaam** [comment]
How about without `--ssh=ssh`? What's the output then?

Are you sure there is an active xpra server on  `:100`?
(try `xpra version :100` on the server, or just `xpra list`)

> `Host key verification failed.`

That's not right. This log output looks messed up.
This message comes from the `paramiko` (default) backend, yet you're using `--ssh=ssh`. Very odd.
https://github.com/Xpra-org/xpra/blob/006b7775999a3f72ceb5886d0b4fd4a4dceb624f/xpra/net/ssh/paramiko_client.py#L526

Then there's also the question of the double tunnel.
Why use ssh over a tunnel? Isn't that redundant?
Why not use plain tcp then?

**Comment by cadem** [comment]
Very odd, I run xpra_cmd.exe at same machine, but I got error
![image](https://github.com/Xpra-org/xpra/assets/3262235/03ab8aa3-a9bb-43ca-b346-701d940c9cf5)
xpra_cmd.exe can run at this machine before.

**Comment by totaam** [comment]
Maybe an anti-virus has quarantined a file, or system permissions prevent you from running it.

**Comment by cadem** [comment]
I can not run at my machine, I move to a virtual machine(which is windows server), run "C:\Program Files\Xpra\Xpra_cmd.exe" -d ssh attach ssh://ubuntu@127.0.0.1:34021/100

I got the following log:
Microsoft Windows [版本 10.0.20348.169]
(c) Microsoft Corporation。保留所有权利。

C:\Users\Administrator>"C:\Program Files\Xpra\Xpra_cmd.exe" -d ssh attach ssh://ubuntu@127.0.0.1:34021/100

2024-05-01 15:54:45,582 Xpra GTK3 client version 5.0.8-r0
2024-05-01 15:54:45,589  running on Microsoft Windows 10
2024-05-01 15:54:48,109 GStreamer version 1.24.1
2024-05-01 15:54:48,411 created named pipe 'Xpra\\844'
2024-05-01 15:54:49,463 keyboard layout 'Chinese (Simplified) - US Keyboard' : 'cn' (0x804)
2024-05-01 15:54:49,479 debug enabled for xpra.scripts.parsing / ('ssh',)
2024-05-01 15:54:49,479 using paramiko ssh backend
2024-05-01 15:54:49,479 debug enabled for xpra.scripts.parsing / ('ssh',)
2024-05-01 15:54:49,479 using paramiko ssh backend
2024-05-01 15:54:49,594 debug enabled for xpra.net.ssh.paramiko_client / ('network', 'ssh')
2024-05-01 15:54:49,594 connect_to({'display_name': 'ssh://ubuntu@127.0.0.1:34021/100', 'cmdline': ['C:\\Program Files\\Xpra\\Xpra_cmd.exe', '-d', 'ssh', 'attach', 'ssh://ubuntu@127.0.0.1:34021/100'], 'type': 'ssh', 'proxy_command': ['_proxy'], 'exit_ssh': True, 'remote_xpra': ['xpra', '$XDG_RUNTIME_DIR/xpra/run-xpra', '/usr/local/bin/xpra', '~/.xpra/run-xpra', 'Xpra_cmd.exe'], 'username': 'ubuntu', 'host': '127.0.0.1', 'local': True, 'port': 34021, 'display': '100', 'display_as_args': ['100', '--env=SSH_AGENT_UUID=737ff26eab3bf56b4905fe3f1e74b8025c4fb836359b40542b47008b0a4b6f22'], 'is_paramiko': True, 'agent': True, 'ssh-agent-uuid': '737ff26eab3bf56b4905fe3f1e74b8025c4fb836359b40542b47008b0a4b6f22', 'full_ssh': ['paramiko']})
2024-05-01 15:54:49,594 parsed user config 'C:\\Users\\Administrator/.ssh/config'
2024-05-01 15:54:49,594 1 hosts found
2024-05-01 15:54:49,594 got host config for '127.0.0.1': {'stricthostkeychecking': 'no', 'include': 'configs/taos/myvir/myvir_vb.conf', 'forwardagent': 'yes', 'hostname': '127.0.0.1'}
2024-05-01 15:54:49,594 authentication modes=['none', 'agent', 'key', 'password']
2024-05-01 15:54:49,627 paramiko socket_connect: sockname=('127.0.0.1', 59850), peername=('127.0.0.1', 34021)
2024-05-01 15:54:49,627 SSH transport <paramiko.Transport at 0x8c4b5750 (unconnected)>
2024-05-01 15:54:49,627 starting thread (client mode): 0x8c4b5750
2024-05-01 15:54:49,627 Local version/idstring: SSH-2.0-paramiko_3.4.0
2024-05-01 15:54:49,627 Remote version/idstring: SSH-2.0-OpenSSH_8.9p1 Ubuntu-3ubuntu0.4
2024-05-01 15:54:49,627 Connected (version 2.0, client OpenSSH_8.9p1)
2024-05-01 15:54:49,627 === Key exchange possibilities ===
2024-05-01 15:54:49,627 kex algos: curve25519-sha256, curve25519-sha256@libssh.org, ecdh-sha2-nistp256, ecdh-sha2-nistp384, ecdh-sha2-nistp521, sntrup761x25519-sha512@openssh.com, diffie-hellman-group-exchange-sha256, diffie-hellman-group16-sha512, diffie-hellman-group18-sha512, diffie-hellman-group14-sha256
2024-05-01 15:54:49,627 server key: rsa-sha2-512, rsa-sha2-256, ecdsa-sha2-nistp256, ssh-ed25519
2024-05-01 15:54:49,627 client encrypt: chacha20-poly1305@openssh.com, aes128-ctr, aes192-ctr, aes256-ctr, aes128-gcm@openssh.com, aes256-gcm@openssh.com
2024-05-01 15:54:49,627 server encrypt: chacha20-poly1305@openssh.com, aes128-ctr, aes192-ctr, aes256-ctr, aes128-gcm@openssh.com, aes256-gcm@openssh.com
2024-05-01 15:54:49,627 client mac: umac-64-etm@openssh.com, umac-128-etm@openssh.com, hmac-sha2-256-etm@openssh.com, hmac-sha2-512-etm@openssh.com, hmac-sha1-etm@openssh.com, umac-64@openssh.com, umac-128@openssh.com, hmac-sha2-256, hmac-sha2-512, hmac-sha1
2024-05-01 15:54:49,627 server mac: umac-64-etm@openssh.com, umac-128-etm@openssh.com, hmac-sha2-256-etm@openssh.com, hmac-sha2-512-etm@openssh.com, hmac-sha1-etm@openssh.com, umac-64@openssh.com, umac-128@openssh.com, hmac-sha2-256, hmac-sha2-512, hmac-sha1
2024-05-01 15:54:49,627 client compress: none, zlib@openssh.com
2024-05-01 15:54:49,627 server compress: none, zlib@openssh.com
2024-05-01 15:54:49,627 client lang: <none>
2024-05-01 15:54:49,627 server lang: <none>
2024-05-01 15:54:49,627 kex follows: False
2024-05-01 15:54:49,627 === Key exchange agreements ===
2024-05-01 15:54:49,627 Kex: curve25519-sha256@libssh.org
2024-05-01 15:54:49,627 HostKey: ssh-ed25519
2024-05-01 15:54:49,627 Cipher: aes128-ctr
2024-05-01 15:54:49,627 MAC: hmac-sha2-256
2024-05-01 15:54:49,627 Compression: none
2024-05-01 15:54:49,627 === End of kex handshake ===
2024-05-01 15:54:49,658 kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
2024-05-01 15:54:49,658 Switch to new keys ...
2024-05-01 15:54:49,658 Got EXT_INFO: {'server-sig-algs': b'ssh-ed25519,sk-ssh-ed25519@openssh.com,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ecdsa-sha2-nistp256@openssh.com,webauthn-sk-ecdsa-sha2-nistp256@openssh.com', 'publickey-hostbound@openssh.com': b'0'}
2024-05-01 15:54:49,658 do_connect_to(<paramiko.Transport at 0x8c4b5750 (cipher aes128-ctr, 128 bits) (connected; awaiting auth)>, '127.0.0.1', 'ubuntu', None, {'stricthostkeychecking': 'no', 'include': 'configs/taos/myvir/myvir_vb.conf', 'forwardagent': 'yes', 'hostname': '127.0.0.1'}, ['C:\\Users\\Administrator/.ssh\\id_ed25519', 'C:\\Users\\Administrator/.ssh\\id_ecdsa', 'C:\\Users\\Administrator/.ssh\\id_rsa', 'C:\\Users\\Administrator/.ssh\\id_dsa'], {'display_name': 'ssh://ubuntu@127.0.0.1:34021/100', 'cmdline': ['C:\\Program Files\\Xpra\\Xpra_cmd.exe', '-d', 'ssh', 'attach', 'ssh://ubuntu@127.0.0.1:34021/100'], 'type': 'ssh', 'proxy_command': ['_proxy'], 'exit_ssh': True, 'remote_xpra': ['xpra', '$XDG_RUNTIME_DIR/xpra/run-xpra', '/usr/local/bin/xpra', '~/.xpra/run-xpra', 'Xpra_cmd.exe'], 'username': 'ubuntu', 'host': '127.0.0.1', 'local': True, 'port': 34021, 'display': '100', 'display_as_args': ['100', '--env=SSH_AGENT_UUID=737ff26eab3bf56b4905fe3f1e74b8025c4fb836359b40542b47008b0a4b6f22'], 'is_paramiko': True, 'agent': True, 'ssh-agent-uuid': '737ff26eab3bf56b4905fe3f1e74b8025c4fb836359b40542b47008b0a4b6f22', 'full_ssh': ['paramiko']})
2024-05-01 15:54:49,658 remote_server_key=MD5:9d:62:7a:7e:6d:3d:da:68:fb:06:65:1c:4d:c2:50:21
2024-05-01 15:54:49,676 HostKeys.load(C:\Users\Administrator/.ssh/known_hosts) successful
2024-05-01 15:54:49,676 host keys=<paramiko.hostkeys.HostKeys object at 0x000001fb1026c5d0>
2024-05-01 15:54:49,676 ed25519 host key 'MD5:9d:62:7a:7e:6d:3d:da:68:fb:06:65:1c:4d:c2:50:21' OK for host '127.0.0.1'
2024-05-01 15:54:49,676 starting authentication, authentication methods: ['none', 'agent', 'key', 'password']
2024-05-01 15:54:49,676 auth=none
2024-05-01 15:54:49,676 trying none authentication
2024-05-01 15:54:49,676 userauth is OK
2024-05-01 15:54:49,691 Authentication type (none) not permitted.
2024-05-01 15:54:49,691 Allowed methods: ['publickey', 'password']
2024-05-01 15:54:49,691 auth_none()
Traceback (most recent call last):
  File "E:/xpra/xpra/net/ssh/paramiko_client.py", line 675, in auth_none
  File "C:/msys64/mingw64/lib/python3.11/site-packages/paramiko/transport.py", line 1540, in auth_none
  File "C:/msys64/mingw64/lib/python3.11/site-packages/paramiko/auth_handler.py", line 263, in wait_for_response
paramiko.ssh_exception.BadAuthenticationType: Bad authentication type; allowed types: ['publickey', 'password']
2024-05-01 15:54:49,691 auth=agent
2024-05-01 15:54:49,724 agent keys: (PKey(alg=RSA, bits=4096, fp=SHA256:8SjnOY1o5JZQHXD7eQe/hlhiscOhsgX67mfL0dO8ees, comment='cadem@HOME-LAPTOP-HUAWEI'),)
2024-05-01 15:54:49,724 trying ssh-agent key 'MD5:87:3c:b8:93:c4:67:38:b6:39:35:a3:41:66:8f:8a:4c'
2024-05-01 15:54:49,724 userauth is OK
2024-05-01 15:54:49,724 Finalizing pubkey algorithm for key of type 'ssh-rsa'
2024-05-01 15:54:49,724 Our pubkey algorithm list: ['rsa-sha2-512', 'rsa-sha2-256', 'ssh-rsa']
2024-05-01 15:54:49,724 Server-side algorithm list: ['ssh-ed25519', 'sk-ssh-ed25519@openssh.com', 'ssh-rsa', 'rsa-sha2-256', 'rsa-sha2-512', 'ssh-dss', 'ecdsa-sha2-nistp256', 'ecdsa-sha2-nistp384', 'ecdsa-sha2-nistp521', 'sk-ecdsa-sha2-nistp256@openssh.com', 'webauthn-sk-ecdsa-sha2-nistp256@openssh.com']
2024-05-01 15:54:49,724 Agreed upon 'rsa-sha2-512' pubkey algorithm
2024-05-01 15:54:49,864 Authentication (publickey) successful!
2024-05-01 15:54:49,864 authenticated using agent and key 'MD5:87:3c:b8:93:c4:67:38:b6:39:35:a3:41:66:8f:8a:4c'
2024-05-01 15:54:49,864 run_remote_xpra(<paramiko.Transport at 0x8c4b5750 (cipher aes128-ctr, 128 bits) (active; 0 openchannel(s))>, ['_proxy'], ['xpra', '$XDG_RUNTIME_DIR/xpra/run-xpra', '/usr/local/bin/xpra', '~/.xpra/run-xpra', 'Xpra_cmd.exe'], None, ['100', '--env=SSH_AGENT_UUID=737ff26eab3bf56b4905fe3f1e74b8025c4fb836359b40542b47008b0a4b6f22'], {'display_name': 'ssh://ubuntu@127.0.0.1:34021/100', 'cmdline': ['C:\\Program Files\\Xpra\\Xpra_cmd.exe', '-d', 'ssh', 'attach', 'ssh://ubuntu@127.0.0.1:34021/100'], 'type': 'ssh', 'proxy_command': ['_proxy'], 'exit_ssh': True, 'remote_xpra': ['xpra', '$XDG_RUNTIME_DIR/xpra/run-xpra', '/usr/local/bin/xpra', '~/.xpra/run-xpra', 'Xpra_cmd.exe'], 'username': 'ubuntu', 'host': '127.0.0.1', 'local': True, 'port': 34021, 'display': '100', 'display_as_args': ['100', '--env=SSH_AGENT_UUID=737ff26eab3bf56b4905fe3f1e74b8025c4fb836359b40542b47008b0a4b6f22'], 'is_paramiko': True, 'agent': True, 'ssh-agent-uuid': '737ff26eab3bf56b4905fe3f1e74b8025c4fb836359b40542b47008b0a4b6f22', 'full_ssh': ['paramiko']})
2024-05-01 15:54:49,864 will try to run xpra from: ['xpra', '$XDG_RUNTIME_DIR/xpra/run-xpra', '/usr/local/bin/xpra', '~/.xpra/run-xpra', 'Xpra_cmd.exe']
2024-05-01 15:54:49,864 run_test_command(transport, echo %OS%)
2024-05-01 15:54:49,864 [chan 0] Max packet in: 4096 bytes
2024-05-01 15:54:49,938 Received global request "hostkeys-00@openssh.com"
2024-05-01 15:54:49,938 Rejecting "hostkeys-00@openssh.com" global request from server.
2024-05-01 15:54:49,938 Debug msg: b'/home/ubuntu/.ssh/authorized_keys:1: key options: agent-forwarding port-forwardingpty user-rc x11-forwarding'
2024-05-01 15:54:49,955 [chan 0] Max packet out: 32768 bytes
2024-05-01 15:54:49,955 Secsh channel 0 opened.
2024-05-01 15:54:49,957 [chan run-test:echo %OS%] Sesch channel 0 request ok
2024-05-01 15:54:49,957 exec_command('echo %OS%') returned
2024-05-01 15:54:49,957 exit status is not ready yet, sleeping
2024-05-01 15:54:49,972 [chan run-test:echo %OS%] EOF received (run-test:echo %OS%)
2024-05-01 15:54:49,974 [chan run-test:echo %OS%] EOF sent (run-test:echo %OS%)
2024-05-01 15:54:49,975 exec_command('echo %OS%')=0
2024-05-01 15:54:49,975 exec_command out=['%OS%\n']
2024-05-01 15:54:49,975 exec_command err=[]
2024-05-01 15:54:49,975 echo %OS%='%OS%'
2024-05-01 15:54:49,975 run_test_command(transport, echo $OSTYPE)
2024-05-01 15:54:49,975 [chan 1] Max packet in: 4096 bytes
2024-05-01 15:54:49,975 [chan 1] Max packet out: 32768 bytes
2024-05-01 15:54:49,975 Secsh channel 1 opened.
2024-05-01 15:54:49,975 [chan run-test:echo $OSTYPE] Sesch channel 1 request ok
2024-05-01 15:54:49,975 exec_command('echo $OSTYPE') returned
2024-05-01 15:54:49,975 exit status is not ready yet, sleeping
2024-05-01 15:54:49,999 exit status is not ready yet, sleeping
2024-05-01 15:54:50,004 [chan run-test:echo $OSTYPE] EOF received (run-test:echo $OSTYPE)
2024-05-01 15:54:50,004 [chan run-test:echo $OSTYPE] EOF sent (run-test:echo $OSTYPE)
2024-05-01 15:54:50,011 exec_command('echo $OSTYPE')=0
2024-05-01 15:54:50,011 exec_command out=['linux-gnu\n']
2024-05-01 15:54:50,011 exec_command err=[]
2024-05-01 15:54:50,011 OSTYPE='linux-gnu'
2024-05-01 15:54:50,011 ssh server OS is 'linux-gnu'
2024-05-01 15:54:50,011 run_test_command(transport, command)
2024-05-01 15:54:50,011 [chan 2] Max packet in: 4096 bytes
2024-05-01 15:54:50,011 [chan 2] Max packet out: 32768 bytes
2024-05-01 15:54:50,011 Secsh channel 2 opened.
2024-05-01 15:54:50,020 [chan run-test:command] Sesch channel 2 request ok
2024-05-01 15:54:50,020 exec_command('command') returned
2024-05-01 15:54:50,020 exit status is not ready yet, sleeping
2024-05-01 15:54:50,038 exit status is not ready yet, sleeping
2024-05-01 15:54:50,038 [chan run-test:command] EOF received (run-test:command)
2024-05-01 15:54:50,039 [chan run-test:command] EOF sent (run-test:command)
2024-05-01 15:54:50,049 exec_command('command')=0
2024-05-01 15:54:50,049 exec_command out=[]
2024-05-01 15:54:50,049 exec_command err=[]
2024-05-01 15:54:50,051 run_test_command(transport, command -v xpra)
2024-05-01 15:54:50,051 [chan 3] Max packet in: 4096 bytes
2024-05-01 15:54:50,053 [chan 3] Max packet out: 32768 bytes
2024-05-01 15:54:50,053 Secsh channel 3 opened.
2024-05-01 15:54:50,053 [chan run-test:command -v xpra] Sesch channel 3 request ok
2024-05-01 15:54:50,053 exec_command('command -v xpra') returned
2024-05-01 15:54:50,053 exit status is not ready yet, sleeping
2024-05-01 15:54:50,070 [chan run-test:command -v xpra] EOF received (run-test:command -v xpra)
2024-05-01 15:54:50,072 exit status is not ready yet, sleeping
2024-05-01 15:54:50,072 [chan run-test:command -v xpra] EOF sent (run-test:command -v xpra)
2024-05-01 15:54:50,084 exec_command('command -v xpra')=0
2024-05-01 15:54:50,084 exec_command out=['/usr/bin/xpra\n']
2024-05-01 15:54:50,086 exec_command err=[]
2024-05-01 15:54:50,086 adding xpra_cmd='/usr/bin/xpra'
2024-05-01 15:54:50,086 cmd(['_proxy'], ['100', '--env=SSH_AGENT_UUID=737ff26eab3bf56b4905fe3f1e74b8025c4fb836359b40542b47008b0a4b6f22'])="/usr/bin/xpra" "_proxy" "100" "--env=SSH_AGENT_UUID=737ff26eab3bf56b4905fe3f1e74b8025c4fb836359b40542b47008b0a4b6f22"
2024-05-01 15:54:50,086 trying to open SSH session, window-size=134217727, timeout=60
2024-05-01 15:54:50,086 [chan 4] Max packet in: 4096 bytes
2024-05-01 15:54:50,086 [chan 4] Max packet out: 32768 bytes
2024-05-01 15:54:50,086 Secsh channel 4 opened.
2024-05-01 15:54:50,086 paramiko agent_option=True
2024-05-01 15:54:50,086 paramiko SSH agent forwarding enabled
2024-05-01 15:54:50,086 channel exec_command('"/usr/bin/xpra" "_proxy" "100" "--env=SSH_AGENT_UUID=737ff26eab3bf56b4905fe3f1e74b8025c4fb836359b40542b47008b0a4b6f22"')
2024-05-01 15:54:50,086 [chan run-xpra] Sesch channel 4 request ok
2024-05-01 15:54:50,103  keyboard settings: layout=cn
2024-05-01 15:54:50,113  desktop size is 1910x1000:
2024-05-01 15:54:50,113   Default (505x264 mm - DPI: 96x96) workarea: 1910x960
2024-05-01 15:54:50,113     通用非即插即用监视器       (505x265 mm)
2024-05-01 15:55:20,113 connection timed out
2024-05-01 15:55:20,113 [chan run-xpra] EOF sent (run-xpra)
2024-05-01 15:55:20,113 SSH EOF on stderr of run-xpra

C:\Users\Administrator>

And I got another popup error message: opengl acceleration fature.

I am sure I have sesion on server, run xpra list, I got:
❯ xpra list
Found the following xpra sessions:
/home/ubuntu/.xpra:
        LIVE session at :100

**Comment by totaam** [comment]
> `LIVE session at :100`

OK, good.

> `ssh server OS is 'linux-gnu'`

The client correctly detects that the server runs Linux.

> `adding xpra_cmd='/usr/bin/xpra'

And it finds `xpra` in `/usr/bin`.

But for some reason, this command never returns:
> `channel exec_command('"/usr/bin/xpra" "_proxy" "100" "--env=SSH_AGENT_UUID=737ff26eab3bf56b4905fe3f1e74b8025c4fb836359b40542b47008b0a4b6f22"')`
> (...)
> `connection timed out`

That's odd seeing that `:100` is `LIVE`.
You could try running it by hand from an ssh session on the server: `xpra _proxy 100`.
Then press enter a few times and the command should exit with an error message:
```
$ xpra _proxy :100

disconnect: invalid packet header byte: 0x0a
```

My guess is that perhaps your server version is too old? You haven't specified it.
Be aware that the one from the Ubuntu repositories do not work: https://github.com/Xpra-org/xpra/wiki/Distribution-Packages-Ubuntu

**Comment by cadem** [comment]
❯ xpra _proxy 100

disconnect: invalid packet format, character 0xa, not an xpra client?

❯ xpra _proxy :100

disconnect: invalid packet format, character 0xa, not an xpra client?

❯ xpra -V
xpra initialization error:
 no such option: -V
❯ xpra --version
xpra v3.1

**Comment by totaam** [comment]
> xpra v3.1

Not a supported version, please see: https://github.com/Xpra-org/xpra/wiki/Versions
