### ISSUE TITLE
xpra client v6 can not attach to the v5 server 

### ISSUE THREAD

**Issue by btasdelen** [Xpra-org/xpra#4229]
**Describe the bug**
After updating client to v6.0, xpra can not attach the session with following error:

```
2024-05-14 13:35:16,324 Warning: server connection failure:
2024-05-14 13:35:16,325  Connection failed: disconnected before the session could be established
2024-05-14 13:35:16,325  ConnectionMessage.CONNECTION_ERROR
2024-05-14 13:35:16,325  client failed to specify any supported encodings
```
Here is the command `xpra start --ssh='ssh' ssh://serveraddr/12 --exit-with-children --start-child='konsole -e byobu' -d encoding`

```
2024-05-14 13:35:30,187 debug enabled for ['xpra.client.mixins.encodings', 'client', 'encoding']
2024-05-14 13:35:30,205 debug enabled for ['xpra.client.gtk3.window_base', 'encoding']

2024-05-14 13:35:30,213 Xpra GTK3 client version 6.0-r0
2024-05-14 13:35:30,224  running on Linux Arch rolling
2024-05-14 13:35:30,224  cpython 3.12
2024-05-14 13:35:30,225  window manager is 'KWin'
2024-05-14 13:35:30,932 GStreamer version 1.24.3
2024-05-14 13:35:30,957 created unix domain sockets:
2024-05-14 13:35:30,957  '/run/user/1000/xpra/clients/bilal-pc-14651'
2024-05-14 13:35:30,980 debug enabled for ['xpra.codecs.checks', 'encoding']
2024-05-14 13:35:31,018 test_csc(<module 'xpra.codecs.csc_cython.converter' from '/usr/lib/python3.12/site-packages/xpra/codecs/csc_cython/converter.cpython-312-x86_64-linux-gnu.so'>, False, None, None)
2024-05-14 13:35:31,018 do_testcsc(<module 'xpra.codecs.csc_cython.converter' from '/usr/lib/python3.12/site-packages/xpra/codecs/csc_cython/converter.cpython-312-x86_64-linux-gnu.so'>, 48, 32, 48, 32, False, None, None, 8192, 8192)
2024-05-14 13:35:31,018 cython: testing BGRX -> YUV420P
2024-05-14 13:35:31,019 cython: testing RGBX -> YUV420P
2024-05-14 13:35:31,019 cython: testing BGR -> YUV420P
2024-05-14 13:35:31,019 cython: testing RGB -> YUV420P
2024-05-14 13:35:31,019 cython: testing YUV420P -> RGB
2024-05-14 13:35:31,019 cython: testing YUV420P -> BGR
2024-05-14 13:35:31,019 cython: testing YUV420P -> RGBX
2024-05-14 13:35:31,019 cython: testing YUV420P -> BGRX
2024-05-14 13:35:31,019 cython: testing GBRP -> RGBX
2024-05-14 13:35:31,020 cython: testing GBRP -> BGRX
2024-05-14 13:35:31,020 cython: testing r210 -> YUV420P
2024-05-14 13:35:31,020 cython: testing r210 -> BGR48
2024-05-14 13:35:31,020 cython: testing r210 -> YUV444P10
2024-05-14 13:35:31,020 cython: testing YUV444P10 -> r210
2024-05-14 13:35:31,020 cython: testing YUV444P -> BGRX
2024-05-14 13:35:31,020 cython: testing GBRP10 -> r210
2024-05-14 13:35:31,021 vpx: testing vp8 / YUV420P with 1 frames of size 24x16
2024-05-14 13:35:31,021 frame 1 is    64 bytes
2024-05-14 13:35:31,021  test passed for 24x16 vp8 - YUV420P
2024-05-14 13:35:31,021 vpx: testing vp8 / YUV420P with 5 frames of size 320x240
2024-05-14 13:35:31,021 frame 1 is   160 bytes
2024-05-14 13:35:31,022  test passed for 320x240 vp8 - YUV420P
2024-05-14 13:35:31,022 frame 2 is    26 bytes
2024-05-14 13:35:31,022  test passed for 320x240 vp8 - YUV420P
2024-05-14 13:35:31,022 frame 3 is    26 bytes
2024-05-14 13:35:31,022  test passed for 320x240 vp8 - YUV420P
2024-05-14 13:35:31,022 frame 4 is    26 bytes
2024-05-14 13:35:31,022  test passed for 320x240 vp8 - YUV420P
2024-05-14 13:35:31,022 frame 5 is    26 bytes
2024-05-14 13:35:31,022  test passed for 320x240 vp8 - YUV420P
2024-05-14 13:35:31,023 vpx: testing vp9 / YUV420P with 1 frames of size 24x16
2024-05-14 13:35:31,023 frame 1 is    45 bytes
2024-05-14 13:35:31,023  test passed for 24x16 vp9 - YUV420P
2024-05-14 13:35:31,023 vpx: testing vp9 / YUV420P with 5 frames of size 128x128
2024-05-14 13:35:31,023 frame 1 is    87 bytes
2024-05-14 13:35:31,023  test passed for 128x128 vp9 - YUV420P
2024-05-14 13:35:31,023 frame 2 is    16 bytes
2024-05-14 13:35:31,023  test passed for 128x128 vp9 - YUV420P
2024-05-14 13:35:31,023 frame 3 is    16 bytes
2024-05-14 13:35:31,023  test passed for 128x128 vp9 - YUV420P
2024-05-14 13:35:31,023 frame 4 is    16 bytes
2024-05-14 13:35:31,023  test passed for 128x128 vp9 - YUV420P
2024-05-14 13:35:31,023 frame 5 is    16 bytes
2024-05-14 13:35:31,023  test passed for 128x128 vp9 - YUV420P
2024-05-14 13:35:31,023 vpx: testing vp9 / YUV444P with 1 frames of size 24x16
2024-05-14 13:35:31,023 frame 1 is    46 bytes
2024-05-14 13:35:31,024  test passed for 24x16 vp9 - YUV444P
2024-05-14 13:35:31,024 vpx: testing vp9 / YUV444P with 5 frames of size 128x128
2024-05-14 13:35:31,024 frame 1 is    88 bytes
2024-05-14 13:35:31,024  test passed for 128x128 vp9 - YUV444P
2024-05-14 13:35:31,024 frame 2 is    16 bytes
2024-05-14 13:35:31,024  test passed for 128x128 vp9 - YUV444P
2024-05-14 13:35:31,024 frame 3 is    16 bytes
2024-05-14 13:35:31,024  test passed for 128x128 vp9 - YUV444P
2024-05-14 13:35:31,024 frame 4 is    16 bytes
2024-05-14 13:35:31,024  test passed for 128x128 vp9 - YUV444P
2024-05-14 13:35:31,024 frame 5 is    16 bytes
2024-05-14 13:35:31,024  test passed for 128x128 vp9 - YUV444P
2024-05-14 13:35:31,024 skipped vp8 decoding test at 24x16 for <module 'xpra.codecs.gstreamer.decoder' from '/usr/lib/python3.12/site-packages/xpra/codecs/gstreamer/decoder.py'> (min size is 48x16)
2024-05-14 13:35:31,027 gstreamer: testing vp8 / YUV420P with 5 frames of size 320x240
2024-05-14 13:35:31,027 frame 1 is   160 bytes
2024-05-14 13:35:31,028  test passed for 320x240 vp8 - YUV420P
2024-05-14 13:35:31,029 frame 2 is    26 bytes
2024-05-14 13:35:31,029  test passed for 320x240 vp8 - YUV420P
2024-05-14 13:35:31,029 frame 3 is    26 bytes
2024-05-14 13:35:31,029  test passed for 320x240 vp8 - YUV420P
2024-05-14 13:35:31,029 frame 4 is    26 bytes
2024-05-14 13:35:31,029  test passed for 320x240 vp8 - YUV420P
2024-05-14 13:35:31,029 frame 5 is    26 bytes
2024-05-14 13:35:31,030  test passed for 320x240 vp8 - YUV420P
2024-05-14 13:35:31,031 skipped vp9 decoding test at 24x16 for <module 'xpra.codecs.gstreamer.decoder' from '/usr/lib/python3.12/site-packages/xpra/codecs/gstreamer/decoder.py'> (min size is 48x16)
2024-05-14 13:35:31,031 gstreamer: testing vp9 / YUV420P with 5 frames of size 128x128
2024-05-14 13:35:31,031 frame 1 is    87 bytes
2024-05-14 13:35:31,032  test passed for 128x128 vp9 - YUV420P
2024-05-14 13:35:31,032 frame 2 is    16 bytes
2024-05-14 13:35:31,032  test passed for 128x128 vp9 - YUV420P
2024-05-14 13:35:31,032 frame 3 is    16 bytes
2024-05-14 13:35:31,032  test passed for 128x128 vp9 - YUV420P
2024-05-14 13:35:31,032 frame 4 is    16 bytes
2024-05-14 13:35:31,032  test passed for 128x128 vp9 - YUV420P
2024-05-14 13:35:31,032 frame 5 is    16 bytes
2024-05-14 13:35:31,032  test passed for 128x128 vp9 - YUV420P
2024-05-14 13:35:31,034 gstreamer: testing av1 / YUV420P with 1 frames of size 64x64
2024-05-14 13:35:31,034 frame 1 is    42 bytes
2024-05-14 13:35:31,035  test passed for 64x64 av1 - YUV420P
2024-05-14 13:35:31,035 skipped h264 decoding test at 24x16 for <module 'xpra.codecs.gstreamer.decoder' from '/usr/lib/python3.12/site-packages/xpra/codecs/gstreamer/decoder.py'> (min size is 48x16)
2024-05-14 13:35:32,288 gstreamer: testing h264 / YUV420P with 5 frames of size 128x128
2024-05-14 13:35:32,288 frame 1 is   820 bytes
2024-05-14 13:35:35,288 Error: frame queue timeout after 3000s
2024-05-14 13:35:35,289  on 'buffer' of size 820
2024-05-14 13:35:35,289  of gstreamer-nvh264dec(YUV420P - 128x128)
2024-05-14 13:35:35,289  version         : (5, 0)
2024-05-14 13:35:35,289  frames          : 0
2024-05-14 13:35:35,289  width           : 128
2024-05-14 13:35:35,289  height          : 128
2024-05-14 13:35:35,289  encoding        : h264
2024-05-14 13:35:35,290  colorspace      : YUV420P
2024-05-14 13:35:35,290 Error on h264 128x128 test YUV420P frame 0
2024-05-14 13:35:35,312 gstreamer: h264 decoding failed
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/xpra/codecs/checks.py", line 307, in testdecoder
    testdecoding(decoder_module, encoding, full)
  File "/usr/lib/python3.12/site-packages/xpra/codecs/checks.py", line 349, in testdecoding
    raise RuntimeError(f"failed to decode test data for encoding {encoding!r} with colorspace {cs!r}")
RuntimeError: failed to decode test data for encoding 'h264' with colorspace 'YUV420P'
2024-05-14 13:35:35,312 gstreamer: h264 decoding failed: failed to decode test data for encoding 'h264' with colorspace 'YUV420P'
2024-05-14 13:35:35,644 OpenGL enabled on 'Mesa Intel(R) UHD Graphics 630 (CFL GT2)'
2024-05-14 13:35:35,654  keyboard settings: rules=evdev, model=pc105, layout=tr,us
2024-05-14 13:35:35,749  desktop size is 3840x1080:
2024-05-14 13:35:35,750   :0.0 (1013x285 mm - DPI: 96x96) workarea: 3840x1036
2024-05-14 13:35:35,750     ACR HDMI-1-0     1920x1080 at    0x0    (598x336 mm - DPI: 82x82) workarea: 1920x1036
2024-05-14 13:35:35,750     LGD eDP-1        1920x1080 at 1920x0    (344x194 mm - DPI: 142x141) workarea: 1920x1080 at 1920x0
2024-05-14 13:35:35,842 dec_pillow.get_encodings()=('png', 'png/L', 'png/P', 'jpeg', 'webp')
2024-05-14 13:35:35,842 dec_webp.get_encodings()=('webp',)
2024-05-14 13:35:35,842 dec_jpeg.get_encodings()=('jpeg', 'jpega')
2024-05-14 13:35:35,842 video_decodings=('vp8', 'vp9', 'av1')
2024-05-14 13:35:35,842 get_core_encodings()=['vp9', 'vp8', 'png', 'png/P', 'png/L', 'webp', 'rgb24', 'rgb32', 'jpeg', 'jpega', 'av1', 'scroll'] (core=('vp9', 'vp8', 'png', 'png/P', 'png/L', 'webp', 'rgb24', 'rgb32', 'jpeg', 'jpega', 'av1', 'scroll'), allowed=('h264', 'vp9', 'vp8', 'mpeg4', 'mpeg4+mp4', 'h264+mp4', 'vp8+webm', 'vp9+webm', 'png', 'png/P', 'png/L', 'webp', 'avif', 'rgb', 'rgb24', 'rgb32', 'jpeg', 'jpega', 'h265', 'av1', 'scroll', 'grayscale', 'stream'))
2024-05-14 13:35:35,843 dec_pillow.get_encodings()=('png', 'png/L', 'png/P', 'jpeg', 'webp')
2024-05-14 13:35:35,843 dec_webp.get_encodings()=('webp',)
2024-05-14 13:35:35,843 dec_jpeg.get_encodings()=('jpeg', 'jpega')
2024-05-14 13:35:35,843 video_decodings=('vp8', 'vp9', 'av1')
2024-05-14 13:35:35,843 get_core_encodings()=['vp9', 'vp8', 'png', 'png/P', 'png/L', 'webp', 'rgb24', 'rgb32', 'jpeg', 'jpega', 'av1', 'scroll'] (core=('vp9', 'vp8', 'png', 'png/P', 'png/L', 'webp', 'rgb24', 'rgb32', 'jpeg', 'jpega', 'av1', 'scroll'), allowed=('h264', 'vp9', 'vp8', 'mpeg4', 'mpeg4+mp4', 'h264+mp4', 'vp8+webm', 'vp9+webm', 'png', 'png/P', 'png/L', 'webp', 'avif', 'rgb', 'rgb24', 'rgb32', 'jpeg', 'jpega', 'h265', 'av1', 'scroll', 'grayscale', 'stream'))
2024-05-14 13:35:35,843 dec_pillow.get_encodings()=('png', 'png/L', 'png/P', 'jpeg', 'webp')
2024-05-14 13:35:35,843 dec_webp.get_encodings()=('webp',)
2024-05-14 13:35:35,843 dec_jpeg.get_encodings()=('jpeg', 'jpega')
2024-05-14 13:35:35,843 video_decodings=('vp8', 'vp9', 'av1')
2024-05-14 13:35:35,843 get_core_encodings()=['vp9', 'vp8', 'png', 'png/P', 'png/L', 'webp', 'rgb24', 'rgb32', 'jpeg', 'jpega', 'av1', 'scroll'] (core=('vp9', 'vp8', 'png', 'png/P', 'png/L', 'webp', 'rgb24', 'rgb32', 'jpeg', 'jpega', 'av1', 'scroll'), allowed=('h264', 'vp9', 'vp8', 'mpeg4', 'mpeg4+mp4', 'h264+mp4', 'vp8+webm', 'vp9+webm', 'png', 'png/P', 'png/L', 'webp', 'avif', 'rgb', 'rgb24', 'rgb32', 'jpeg', 'jpega', 'h265', 'av1', 'scroll', 'grayscale', 'stream'))
2024-05-14 13:35:35,843 dec_pillow.get_encodings()=('png', 'png/L', 'png/P', 'jpeg', 'webp')
2024-05-14 13:35:35,843 dec_webp.get_encodings()=('webp',)
2024-05-14 13:35:35,843 dec_jpeg.get_encodings()=('jpeg', 'jpega')
2024-05-14 13:35:35,843 video_decodings=('vp8', 'vp9', 'av1')
2024-05-14 13:35:35,844 get_core_encodings()=['vp9', 'vp8', 'png', 'png/P', 'png/L', 'webp', 'rgb24', 'rgb32', 'jpeg', 'jpega', 'av1', 'scroll'] (core=('vp9', 'vp8', 'png', 'png/P', 'png/L', 'webp', 'rgb24', 'rgb32', 'jpeg', 'jpega', 'av1', 'scroll'), allowed=('h264', 'vp9', 'vp8', 'mpeg4', 'mpeg4+mp4', 'h264+mp4', 'vp8+webm', 'vp9+webm', 'png', 'png/P', 'png/L', 'webp', 'avif', 'rgb', 'rgb24', 'rgb32', 'jpeg', 'jpega', 'h265', 'av1', 'scroll', 'grayscale', 'stream'))
2024-05-14 13:35:35,844 dec_pillow.get_encodings()=('png', 'png/L', 'png/P', 'jpeg', 'webp')
2024-05-14 13:35:35,844 dec_webp.get_encodings()=('webp',)
2024-05-14 13:35:35,844 dec_jpeg.get_encodings()=('jpeg', 'jpega')
2024-05-14 13:35:35,844 video_decodings=('vp8', 'vp9', 'av1')
2024-05-14 13:35:35,844 get_core_encodings()=['vp9', 'vp8', 'png', 'png/P', 'png/L', 'webp', 'rgb24', 'rgb32', 'jpeg', 'jpega', 'av1', 'scroll'] (core=('vp9', 'vp8', 'png', 'png/P', 'png/L', 'webp', 'rgb24', 'rgb32', 'jpeg', 'jpega', 'av1', 'scroll'), allowed=('h264', 'vp9', 'vp8', 'mpeg4', 'mpeg4+mp4', 'h264+mp4', 'vp8+webm', 'vp9+webm', 'png', 'png/P', 'png/L', 'webp', 'avif', 'rgb', 'rgb24', 'rgb32', 'jpeg', 'jpega', 'h265', 'av1', 'scroll', 'grayscale', 'stream'))
2024-05-14 13:35:35,844 get_batch_caps()={}
2024-05-14 13:35:35,844 supported full csc_modes={'vp8': ['YUV420P'], 'vp9': ['YUV420P'], 'av1': ['YUV420P'], 'webp': ['BGRX', 'BGRA', 'RGBX', 'RGBA'], 'jpeg': ['BGRX', 'BGRA', 'YUV420P'], 'jpega': ['BGRA', 'RGBA']}
2024-05-14 13:35:35,844 dec_pillow.get_encodings()=('png', 'png/L', 'png/P', 'jpeg', 'webp')
2024-05-14 13:35:35,844 dec_webp.get_encodings()=('webp',)
2024-05-14 13:35:35,844 dec_jpeg.get_encodings()=('jpeg', 'jpega')
2024-05-14 13:35:35,845 video_decodings=('vp8', 'vp9', 'av1')
2024-05-14 13:35:35,845 get_core_encodings()=['vp9', 'vp8', 'png', 'png/P', 'png/L', 'webp', 'rgb24', 'rgb32', 'jpeg', 'jpega', 'av1', 'scroll'] (core=('vp9', 'vp8', 'png', 'png/P', 'png/L', 'webp', 'rgb24', 'rgb32', 'jpeg', 'jpega', 'av1', 'scroll'), allowed=('h264', 'vp9', 'vp8', 'mpeg4', 'mpeg4+mp4', 'h264+mp4', 'vp8+webm', 'vp9+webm', 'png', 'png/P', 'png/L', 'webp', 'avif', 'rgb', 'rgb24', 'rgb32', 'jpeg', 'jpega', 'h265', 'av1', 'scroll', 'grayscale', 'stream'))
2024-05-14 13:35:35,845 encoding capabilities: {'video_b_frames': ['h264'], 'video_max_size': (8192, 8192), 'max-soft-expired': 5, 'send-timestamps': False, '': 'auto', 'min-quality': 1, 'speed': 0, 'min-speed': 1, 'rgb_lz4': True, 'rgb_formats': ['RGB', 'RGBX', 'RGBA'], 'full_csc_modes': {'vp8': ['YUV420P'], 'vp9': ['YUV420P'], 'av1': ['YUV420P'], 'webp': ['BGRX', 'BGRA', 'RGBX', 'RGBA'], 'jpeg': ['BGRX', 'BGRA', 'YUV420P'], 'jpega': ['BGRA', 'RGBA']}}
found existing display 12 : LIVE

2024-05-14 13:35:37,162 removing unix domain socket '/run/user/1000/xpra/clients/bilal-pc-14651'
2024-05-14 13:35:39,152 Warning: server connection failure:
2024-05-14 13:35:39,152  Connection failed: disconnected before the session could be established
2024-05-14 13:35:39,152  ConnectionMessage.CONNECTION_ERROR
2024-05-14 13:35:39,152  client failed to specify any supported encodings
```

**System Information (please complete the following information):**
 - Server OS: Ubuntu 20.04
 - Client OS: Arch Linux
 - Xpra Server Version v5.0-r33693 (g2a908f54b)
 - Xpra Client Version v6.0-r0

**Additional context**
Please see "reporting bugs" in the wiki section.

**Comment by totaam** [comment]
Update your server.
Even if you wish to stay on the LTS 5.x branch, you should be running 5.0.8 or later (at time of writing).

**Comment by btasdelen** [comment]
@totaam That did the trick, thank you.
