### ISSUE TITLE
--without-http broken in 6.0.1

### ISSUE THREAD

**Issue by luke-jr** [Xpra-org/xpra#4251]
**Describe the bug**
The xpra server fails to start with --without-http configuration

**System Information (please complete the following information):**
 - Server OS: Gentoo
 - Client OS: Gentoo
 - Xpra Server Version 6.0.1
 - Xpra Client Version 4.4.5

**Additional context**
Even if I use --with-http, connecting still fails later on. Didn't try 6.0.1 on the client yet (hoping to see server functional first)

**Comment by totaam** [comment]
What is the error in the server log?

**Comment by luke-jr** [comment]
```
xpra main error:
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/xpra/scripts/main.py", line 138, in main
    return run_mode(script_file, cmdline, err, options, args, mode, defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/xpra/scripts/main.py", line 521, in run_mode
    return do_run_mode(script_file, cmdline, error_cb, options, args, full_mode, defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/xpra/scripts/main.py", line 604, in do_run_mode
    return run_server(script_file, cmdline, error_cb, options, args, full_mode, defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/xpra/scripts/main.py", line 2096, in run_server
    return do_run_server(script_file, cmdline, error_cb, options, args, full_mode, str(display or ""), defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/xpra/scripts/server.py", line 778, in do_run_server
    return _do_run_server(script_file, cmdline,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/xpra/scripts/server.py", line 1534, in _do_run_server
    app = make_seamless_server(clobber)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/xpra/scripts/server.py", line 337, in make_seamless_server
    from xpra.x11.server.seamless import SeamlessServer
  File "/usr/lib/python3.12/site-packages/xpra/x11/server/seamless.py", line 35, in <module>
    from xpra.x11.server.base import X11ServerBase
  File "/usr/lib/python3.12/site-packages/xpra/x11/server/base.py", line 19, in <module>
    from xpra.x11.server.core import X11ServerCore, XTestPointerDevice
  File "/usr/lib/python3.12/site-packages/xpra/x11/server/core.py", line 30, in <module>
    from xpra.server.gtk_server import GTKServerBase
  File "/usr/lib/python3.12/site-packages/xpra/server/gtk_server.py", line 22, in <module>
    from xpra.server.base import ServerBase
  File "/usr/lib/python3.12/site-packages/xpra/server/base.py", line 13, in <module>
    from xpra.server.core import ServerCore
  File "/usr/lib/python3.12/site-packages/xpra/server/core.py", line 23, in <module>
    from xpra.net.http.common import HTTP_UNSUPORTED
ModuleNotFoundError: No module named 'xpra.net.http'
```
