### ISSUE TITLE
[v5.0.9-r0] TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by MaxGyver83** [Xpra-org/xpra#4262]
**Describe the bug**

When I start the xpra server, I get this error:

```shell
$ xpra start :100
xpra main error:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xpra/scripts/main.py", line 111, in main
    options, args = do_parse_cmdline(cmdline, defaults)
  File "/usr/lib/python3/dist-packages/xpra/scripts/parsing.py", line 1783, in do_parse_cmdline
    fixup_options(options)
  File "/usr/lib/python3/dist-packages/xpra/scripts/config.py", line 1581, in fixup_options
    fixup_encodings(options)
  File "/usr/lib/python3/dist-packages/xpra/scripts/config.py", line 1432, in fixup_encodings
    from xpra.codecs.codec_constants import PREFERRED_ENCODING_ORDER
  File "/usr/lib/python3/dist-packages/xpra/codecs/codec_constants.py", line 29, in <module>
    PREFERRED_REFRESH_ENCODING_ORDER: tuple[str, ...] = (
TypeError: 'type' object is not subscriptable
```

**To Reproduce**
1. xpra start :100

**System Information (please complete the following information):**
 - Server OS: Ubuntu 20.04
 - Xpra Server Version: xpra v5.0.9-r0

**Additional context**

I think this error started after the upgrade to version `v5.0.9-r0`.

**Comment by totaam** [comment]
Thanks, fixed by the commit above.
This only affects distributions with older python versions.

**Comment by MaxGyver83** [comment]
Wow, this was quick. Thank you!
