### ISSUE TITLE
AttributeError: 'ClientConnectionMuxer' object has no attribute 'encodings_packet'

### ISSUE THREAD

**Issue by 821760408-sp** [Xpra-org/xpra#4272]
**Describe the bug**
Installed xpra server on CentOS 9: `dnf install xpra`
Started xpra server: `xpra start`
Trying to connect from my Mac by: `xpra attach --ssh "ssh -6" ssh:myserver`
Got "error accepting new connection", server log:
```
2024-07-01 10:17:42,189 New unix-domain connection received
2024-07-01 10:17:42,189  on '/run/user/386550/xpra/0/socket'
2024-07-01 10:17:42,191 Handshake complete; enabling connection
2024-07-01 10:17:42,191 Warning: failed to convert dpi
2024-07-01 10:17:42,191  from <class 'dict'> using <class 'int'>: int() argument must be a string, a bytes-like object or a number, not 'dict'
2024-07-01 10:17:42,193 listget('encodings', (), <class 'str'>, None)
2024-07-01 10:17:42,193 expected a list or tuple value for encodings but got <class 'dict'>
2024-07-01 10:17:42,194 Python/GTK3 {'': 'darwin', 'name': 'Mac OS X 14.5', 'machine': 'arm64'} client version 6.0
2024-07-01 10:17:42,194  OpenGL is disabled
2024-07-01 10:17:42,195 keyboard mapping already configured (skipped)
2024-07-01 10:17:42,195  client root window size is 2056x1329
2024-07-01 10:17:42,195   yuangaobk-mbp (544x352 mm - DPI: 96x96) workarea: 2056x1285 at    0x44
2024-07-01 10:17:42,195     monitor 1        (344x222 mm - DPI: 152x152)
2024-07-01 10:17:42,199 Error: failed to set new screen size
2024-07-01 10:17:42,200 Warning: tried to set resolution to 2056x1329
2024-07-01 10:17:42,200  and ended up with 8192x4096
2024-07-01 10:17:42,202 Error: processing new connection from Protocol(unix-domain socket:/run/user/386550/xpra/0/socket):
Traceback (most recent call last):
  File "/usr/lib64/python3.9/site-packages/xpra/server/server_base.py", line 441, in _process_hello_ui
    self.send_hello(ss, root_w, root_h, auth_caps)
  File "/usr/lib64/python3.9/site-packages/xpra/server/server_base.py", line 552, in send_hello
    if server_source.encodings_packet:
AttributeError: 'ClientConnectionMuxer' object has no attribute 'encodings_packet'
2024-07-01 10:17:42,202 Disconnecting client /run/user/386550/xpra/0/socket:
2024-07-01 10:17:42,202  connection error (error accepting new connection)
2024-07-01 10:17:42,203 Python/GTK3 client 4 disconnected.
2024-07-01 10:17:42,208 DPI set to 68 x 62 (wanted 96 x 96)
2024-07-01 10:17:42,209  you may experience scaling problems, such as huge or small fonts, etc
2024-07-01 10:17:42,209  to fix this issue, try the dpi switch, or use a patched Xorg dummy driver
```

**System Information (please complete the following information):**
 - Server OS: CentOS 9
 - Client OS: Mac OS X 14.5
 - Xpra Server Version: 4.4.3
 - Xpra Client Version: Xpra GTK3 client version 6.0.1-r3

**Additional context**
Please see "reporting bugs" in the wiki section.

**Comment by totaam** [comment]
4.4.3 is not a supported version.
