### ISSUE TITLE
`shadow` does not work on windows

### ISSUE THREAD

**Issue by stdedos** [Xpra-org/xpra#4287]
**Describe the bug**

Executing `xpra\Xpra-x86_64_6.1-r35869\Xpra-Shadow.exe` gives

![image](https://github.com/Xpra-org/xpra/assets/133706/c19b40f3-f2a8-4a12-9d88-c1b6ec09dd7e)

```
xpra\Xpra-x86_64_6.1-r35869>Xpra_cmd.exe shadow
2024-07-06 10:17:10,996 xpra main error:
Traceback (most recent call last):
  File "E:/xpra/xpra/scripts/main.py", line 139, in main
  File "E:/xpra/xpra/scripts/main.py", line 522, in run_mode
  File "E:/xpra/xpra/scripts/main.py", line 605, in do_run_mode
  File "E:/xpra/xpra/scripts/main.py", line 2115, in run_server
  File "E:/xpra/xpra/scripts/server.py", line 779, in do_run_server
  File "E:/xpra/xpra/scripts/server.py", line 1185, in _do_run_server
ModuleNotFoundError: No module named 'xpra.x11'
```

* `xpra\Xpra-x86_64_6.1-r35715` is also affected
* `xpra\Xpra-x86_64_6.0-r35620` is working

**To Reproduce**
1. server command
2. client command
3. specific action to trigger the bug

**System Information (please complete the following information):**
- Server OS: Ubuntu 20.04.6 LTS
- Client OS: Microsoft Windows [Version 10.0.18363.836]
- Xpra Server Version: (see above)
- Xpra Client Version: (see above)

**Additional context**
Please see "reporting bugs" in the wiki section.

**Comment by totaam** [comment]
Already fixed, is this the latest build available?

**Comment by stdedos** [comment]
```
xpra\Xpra-x86_64_6.1-r35982>Xpra_cmd.exe shadow --bind-ws=0.0.0.0:10000 --no-audio
2024-07-06 10:59:53,359 created ws socket '0.0.0.0:10000'
2024-07-06 10:59:53,361 xpra main error:
Traceback (most recent call last):
  File "E:/xpra/xpra/scripts/main.py", line 139, in main
  File "E:/xpra/xpra/scripts/main.py", line 522, in run_mode
  File "E:/xpra/xpra/scripts/main.py", line 605, in do_run_mode
  File "E:/xpra/xpra/scripts/main.py", line 2115, in run_server
  File "E:/xpra/xpra/scripts/server.py", line 779, in do_run_server
  File "E:/xpra/xpra/scripts/server.py", line 1185, in _do_run_server
ModuleNotFoundError: No module named 'xpra.x11'
```

**Comment by stdedos** [comment]
Is this

```
2024-07-06 11:03:20,637 CUDA initialization (this may take a few seconds)
2024-07-06 11:03:20,760 CUDA 12.3.0 / PyCUDA 2024.1, found 1 devices:
2024-07-06 11:03:20,760   + NVIDIA GeForce RTX 2080 SUPER @ 0000:01:00.0 (memory: 82% free, compute: 7.5)
2024-07-06 11:03:20,775 NVidia driver version 466.77
2024-07-06 11:03:20,775 Warning: NVidia driver version 466.77 is untested with NVENC
2024-07-06 11:03:20,775  (this encoder has been tested with versions 466.x and later only)
2024-07-06 11:03:20,822  disabling YUV444P and lossless mode
2024-07-06 11:03:20,822  use XPRA_NVENC_YUV444P=1 to force enable
2024-07-06 11:03:20,883  device NVIDIA GeForce RTX 2080 SUPER is not supported: cannot open encoding session: This indicates that an invalid struct version was used by the client., 0 contexts are in use
2024-07-06 11:03:20,884 no valid NVENC devices found
2024-07-06 11:03:21,466 Warning: NvFBC screen capture initialization failed:
2024-07-06 11:03:21,467  NvFBC_GetStatusEx - returned INVALID_TARGET
```

fixed on the latest version?

(`this encoder has been tested with versions 466.x and later only` and `NVidia driver version 466.77`)

**Comment by totaam** [comment]
> `AssertionError: pixel buffer is too small: expected at least 27166720 bytes but got 14745600`

Let me try to reproduce this one.
`27166720/14745600 = 1.842361111`
Could be 24-bit vs 32-bit capture issue, padded to the wrong rowstride.
Does your full shadow log not print the capture backed in use? (it would narrow it down a bit so I don't have to try them all)
Add `-d shadow` if it doesn't print it.

> `(this encoder has been tested with versions 466.x and later only and NVidia driver version 466.77)`

Derp! c676e358c0a2277464afbdbd8f4f002b125d65aa

> `RuntimeError: the numpy import lock is already held by CUDA in thread 91700!`

That's #3483
From now on, the message will be more helpful and should help us figure out which threads are competing for the lock.

> `Error: failed to create SSL socket`

That was already fixed: a9f422e92e1a7a684906140499f19a558b4baf32

**Comment by stdedos** [comment]
> Does your full shadow log not print the capture backed in use? (it would narrow it down a bit so I don't have to try them all)

Do you mean

```
2024-07-06 12:16:27,463 capture using d3d11screencapturesrc
```

?

**Comment by stdedos** [comment]
Did you miss something

```
(Xpra_cmd.exe:18984): Gtk-WARNING **: 12:18:19.889: Could not find the icon 'xpra-ms windows-color'. The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
        http://icon-theme.freedesktop.org/releases
```

or is it "one of those errors"?

**Comment by totaam** [comment]
> Do you mean
> `d3d11screencapturesrc`

Yes.
Thanks.
Problem is, this one requires real hardware - doesn't work in VirtualBox.
Maybe I can force enable it and still trigger the bug.

**Comment by stdedos** [comment]
... Or you need 

```
2024-07-06 12:28:05,860 xpra shadow server version 6.0-r35620 (g79036646b) beta
2024-07-06 12:28:05,861  running with pid 39680 on Microsoft Windows Microsoft Windows 10
2024-07-06 12:28:05,862  cpython 3.11
2024-07-06 12:28:05,862  on display 'Default' of size 4480x1516
2024-07-06 12:28:05,863  with 2 monitors:
2024-07-06 12:28:05,863   DISPLAY23        2560x1440 at    0,0
2024-07-06 12:28:05,863   DISPLAY24        1920x1080 at 2560,436
```

?

**Comment by totaam** [comment]
> `Could not find the icon 'xpra-ms windows-color'.`
> `The 'hicolor' theme was not found either, perhaps you need to install it.`
> or is it "one of those errors"?

You guessed well.
The strings `xpra-ms` and `window-color` don't exist in the xpra source.
So somewhere GTK is deciding that it really needs those things for something... (and I have absolutely no idea what that could be)

See [Gtk-3.0.gir](https://raw.githubusercontent.com/gtk-rs/gir-files/master/Gtk-3.0.gir):
`set_search_path` : _Sets the search path for the icon theme object. When looking for an icon theme, GTK+ will search for a subdirectory of one or more of the directories in @path with the same name as the icon theme containing an `index.theme` file. (Themes from multiple of the path elements are combined to allow themes to be extended by adding icons in the user's home directory.)_
_In addition if an icon found isn't found either in the current icon theme or the default icon theme, and an image file with the right name is found directly in one of the elements of @path, then that image will be used for the icon name._
_(This is legacy feature, and new icons should be put into the fallback icon theme, which is called hicolor, rather than directly on the icon path.)_

We have `Adwaita` in `Xpra/share/icons/`.
I would rather not bundle `hicolor` as we used to. It's not huge at 500KB, but that's 38 files in 707 directories...

**Comment by stdedos** [comment]
> I would rather not bundle `hicolor` as we used to. It's not huge at 500KB, but that's 38 files in 707 directories...

... I don't have any concrete sensible reasons, but I tend to share that sentiment 😓 

Idk why it could not be "one big zip-file", load it into memory, and "read it from there"

**Comment by aaron26122** [comment]
Having the same SSL bug with you must  you must specify an 'ssl-cert' file to use ssl sockets, even though I have given a ssl key and certificate on the server but on windows its a big bug. hope this can be resolved

**Comment by totaam** [comment]
@aaron26122 I have no idea what you are talking about, this ticket is not about ssl.

**Comment by aaron26122** [comment]
He mentioned something about ticking a box that isn't shown in the client side only the html side, thats for ssl

**Comment by totaam** [comment]
@aaron26122 @stdedos 's issue (which was already fixed when reported) is that attempting to connect with SSL enabled to a server which is not configured for SSL triggers the same warning multiple times.
You said "I have given a ssl key..." so this is extremely unlikely to be related.

**Comment by aaron26122** [comment]
ok thx

**Comment by totaam** [comment]
@stdedos can you help me figure out what still needs doing in this ticket?
(or can we close it?)
