### ISSUE TITLE
nvenc is now padding video frames

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#4345]
First reported in https://github.com/orgs/Xpra-org/discussions/4343#discussioncomment-10526895

Error with v5 and ffmpeg decoder:
```
2024-09-04 17:11:30,402 Error drawing on window 4
Traceback (most recent call last):
  File "/usr/lib64/python3.11/site-packages/xpra/client/mixins/window_manager.py", line 1592, in _do_draw
    window.draw_region(x, y, width, height, coding, data, rowstride,
  File "/usr/lib64/python3.11/site-packages/xpra/client/gui/client_window_base.py", line 838, in draw_region
    backing.draw_region(x, y, width, height, coding, img_data, rowstride, options, callbacks)
  File "/usr/lib64/python3.11/site-packages/xpra/client/gui/window_backing_base.py", line 923, in draw_region
    self.paint_with_video_decoder(VIDEO_DECODERS.get(coding),
  File "/usr/lib64/python3.11/site-packages/xpra/client/gui/window_backing_base.py", line 804, in paint_with_video_decoder
    img = vd.decompress_image(img_data, options)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "xpra/codecs/ffmpeg/decoder.pyx", line 1016, in xpra.codecs.ffmpeg.decoder.Decoder.decompress_image
    raise RuntimeError("%s context dimension %ix%i is smaller than the codec's expected size of %ix%i for frame %i" % (
```

Warning with `openh264` decoder:
```
Warning: image bigger than expected
2024-09-04 17:13:17,607  1248x928 instead of 1240x900
```

**Comment by totaam** [comment]
See also caf91e2b05e12a8f4ef2e66b92d43e167ea29d14
