### ISSUE TITLE
debain 12 No module named 'xpra.x11'

### ISSUE THREAD

**Issue by klein-de** [Xpra-org/xpra#4361]
**Describe the bug**
2024-09-18 11:14:28,200 error preparing connection: No module named 'xpra.x11'

**To Reproduce**
1. server command == xpra start-desktop :10 --start-child=openbox-session --exit-with-children
2. client command  == xpra shadow ssh:"192.168.1.193":10
3. specific action to trigger the bug
starting xpra on client 
**System Information (please complete the following information):**
 - Server OS: [e.g. RHEL 8.x] == arcoplinux/arch
 - Client OS: [e.g. Windows 10]
 - Xpra Server Version [e.g. 4.2.3] == xpra v6.1.2-r1
 - Xpra Client Version [e.g. 4.3] == xpra v6.1.2-r1

**Additional context**
```
xpra shadow ssh:"192.168.1.193":10
2024-09-18 11:14:27,802 Warning: missing audio module

2024-09-18 11:14:27,921 Xpra GTK3 client version 6.1.2-r1
2024-09-18 11:14:27,931  running on Linux Debian 12 bookworm
2024-09-18 11:14:27,931  cpython 3.11
2024-09-18 11:14:27,931  window manager is 'icewm'
2024-09-18 11:14:28,131 Warning: failed to instantiate the dbus notification handler
2024-09-18 11:14:28,131  you may need to start a notification service for 'org.freedesktop.Notifications'
2024-09-18 11:14:28,131  disable notifications to avoid this warning
2024-09-18 11:14:28,133 created unix domain sockets:
2024-09-18 11:14:28,133  '/tmp/1000/.run/xpra/clients/antix-8570p-15347'
2024-09-18 11:14:28,196  using default keyboard settings
2024-09-18 11:14:28,199  desktop size is 1600x900:
2024-09-18 11:14:28,199   :0.0 (423x238 mm - DPI: 96x96)
2024-09-18 11:14:28,199     LGD LVDS         (345x194 mm - DPI: 118x118) workarea: 1600x867
2024-09-18 11:14:28,200 error preparing connection: No module named 'xpra.x11'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xpra/client/base/client.py", line 412, in send_hello
    hello.update(self.make_hello())
                 ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/xpra/client/gtk3/client_base.py", line 873, in make_hello
    capabilities = UIXpraClient.make_hello(self)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/xpra/client/gui/ui_client_base.py", line 410, in make_hello
    caps.update(c.get_caps(self))
                ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/xpra/client/mixins/windows.py", line 399, in get_caps
    "time": get_double_click_time(),
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/xpra/platform/posix/gui.py", line 343, in get_double_click_time
    return _get_xsettings_int("Net/DoubleClickTime", -1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/xpra/platform/posix/gui.py", line 332, in _get_xsettings_int
    d = _get_xsettings_dict()
        ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/xpra/platform/posix/gui.py", line 175, in _get_xsettings_dict
    from xpra.x11.common import xsettings_to_dict
ModuleNotFoundError: No module named 'xpra.x11'
ssh: connect to host 192.168.1.193 port 10: Connection refused
2024-09-18 11:14:28,311 removing unix domain socket '/tmp/1000/.run/xpra/clients/antix-8570p-15347'
2024-09-18 11:14:28,312 Error: failed to listen on socket socket /tmp/1000/.run/xpra/clients/antix-8570p-15347:
2024-09-18 11:14:28,313  [Errno 9] Bad file descriptor'
```
first error when starting
`2024-09-18 11:14:28,200 error preparing connection: No module named 'xpra.x11'`

second error witch i believe is cause by the first: 
`ssh: connect to host 192.168.1.193 port 10: Connection refused`

System:
```
  Host: antix-8570p Kernel: 6.1.60-antix.1-amd64-smp arch: x86_64 bits: 64
  Desktop: IceWM v: 3.6.0 Distro: antiX-23.1-runit_x64 bookworm September 08 2024
```
Device-1: AMD Thames [Radeon HD 7550M/7570M/7650M] driver: radeon v: kernel

Display: server: X.Org v: 1.21.1.7 driver: X: loaded: radeon
    unloaded: fbdev,modesetting,vesa dri: r600 gpu: radeon
    resolution: 1600x900~60Hz

API: EGL v: 1.4,1.5 drivers: kms_swrast,r600,swrast platforms: gbm,x11,surfaceless,device

API: OpenGL v: 4.5 vendor: x.org mesa v: 22.3.6 renderer: AMD TURKS (DRM 2.50.0 / 6.1.60-antix.1-amd64-smp LLVM 15.0.6)

Memory: total: 8 GiB available: 7.69 GiB used: 1.26 GiB (16.4%)
Shell: Bash inxi: 3.3.34

os = antix 23.1 full 64bit (runit)

from the debian repos:
```
$ xpra --version
xpra v3.1.3
```
updated adding xpra repos https://github.com/Xpra-org/xpra/wiki/Download#-for-debian-based-distributions
```
$ xpra --version
xpra v6.1.2-r1
```
```
$ python3 --version
Python 3.11.2
```

**Comment by totaam** [comment]
Install `xpra-x11` which should have been pulled in automatically as a recommends dependency for `xpra-server`.

> Server OS: [e.g. RHEL 8.x] == arcoplinux/arch
> updated adding xpra repos https://github.com/Xpra-org/xpra/wiki/Download#-for-debian-based-distributions

Which is it? arch or debian?

**Comment by klein-de** [comment]
the server i'm using is arcopro/arch 
the client witch i'm having problems antix 23.1 64bit runit full 
xpra shadow ssh:"192.168.1.193":10 is run on antix/debian and in the terminal out put is the two errors.

**Comment by klein-de** [comment]
xpra shadow ssh:"192.168.1.193":10
2024-09-18 18:21:13,536 Warning: missing audio module

2024-09-18 18:21:13,673 Xpra GTK3 client version 6.1.2-r1
2024-09-18 18:21:13,683  running on Linux Debian 12 bookworm
2024-09-18 18:21:13,684  cpython 3.11
2024-09-18 18:21:13,685  window manager is 'IceWM 3.6.0 (Linux/x86_64)'
2024-09-18 18:21:13,899 Warning: failed to instantiate the dbus notification handler
2024-09-18 18:21:13,900  you may need to start a notification service for 'org.freedesktop.Notifications'
2024-09-18 18:21:13,900  disable notifications to avoid this warning
2024-09-18 18:21:13,901 created unix domain sockets:
2024-09-18 18:21:13,901  '/tmp/1000/.run/xpra/clients/antix-8570p-13270'
ssh: connect to host 192.168.1.193 port 10: Connection refused
2024-09-18 18:21:14,278  keyboard settings: rules=evdev, model=pc105, layout=us
2024-09-18 18:21:14,637  desktop size is 1600x900:
2024-09-18 18:21:14,638   :0.0 (423x238 mm - DPI: 96x96) workarea: 1600x867 
2024-09-18 18:21:14,639     LGD LVDS         (345x194 mm - DPI: 118x118)
2024-09-18 18:21:14,828 Error: SSH connection to the xpra server failed
2024-09-18 18:21:14,828  check your username, hostname, display number, firewall, etc
2024-09-18 18:21:14,828  for server: ssh://192.168.1.193:10
2024-09-18 18:21:14,828  the command line used was:
2024-09-18 18:21:14,829  ssh -x -p 10 -T 192.168.1.193
2024-09-18 18:21:14,830 Error: failed to receive anything, not an xpra server?
2024-09-18 18:21:14,830   could also be the wrong protocol, username, password or port
2024-09-18 18:21:14,830   or the session was not found
2024-09-18 18:21:14,830 Connection failed
2024-09-18 18:21:14,941 removing unix domain socket '/tmp/1000/.run/xpra/clients


ssh: connect to host 192.168.1.193 port 10: Connection refused

so xpra is interrupting 
xpra shadow ssh:"192.168.1.193":10 
wrong instead of using as a display number it thinks it is a port 

server arcopro/arch 
ssh -V
OpenSSH_9.8p1, OpenSSL 3.3.2 3 Sep 2024

client antix 23.1 
ssh -V
OpenSSH_9.2p1 Debian-2.0nosystemd2, OpenSSL 3.0.14 4 Jun 2024

and it wont let me update it :
openssh-server is already the newest version (1:9.2p1-2.0nosystemd2).

**Comment by totaam** [comment]
Your syntax is invalid and should have triggered a deprecation warning.

`xpra shadow ssh://host:port/DISPLAY` is the correct syntax
(and in most cases the display is optional - with ssh connections, the default port 22 is also optional)
Which leaves:
`xpra shadow ssh://host/`

**Comment by klein-de** [comment]
@totaam
https://github.com/Xpra-org/xpra/issues/4361 [don't require xpra.x11 in the client](https://github.com/Xpra-org/xpra/commit/8e67bd904c95193d1a45e1e2791677aaba4491d1)

and yet is still com planes :
2024-09-18 11:14:28,200 error preparing connection: No module named 'xpra.x11'
being i installed it, it doesn't through that message any more.

xpra shadow ssh://host/  (was the fix this works)

where is the latest information for xpra listed and where can it be found ?

is there a way to control the actual server desktop ?

**Comment by klein-de** [comment]
note: xpra following install from this page, xpra installed and workeds 
note: after install when updating system or doing a search, i get this in my terminal so after renaming xpra.sources to xpra.list and updating, well deb didn't like that, so i moved xpra.sources to ~/ and deb was happy. kinda defeats having a repo. i'm sure there is a way around this but i'm not sure.


N: Ignoring file 'xpra.sources' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension
N: Skipping acquire of configured file 'main/binary-riscv64/Packages' as repository 'https://xpra.org bookworm InRelease' doesn't support architecture 'riscv64'
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
N: Ignoring file 'xpra.sources' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension


is there a way to fix this? on your end ?

**Comment by totaam** [comment]
I struggle to understand your last 2 comments. Please try again, more clearly.

**Comment by klein-de** [comment]
from this page:
https://github.com/Xpra-org/xpra/wiki/Download#-for-debian-based-distributions

Debian Bookworm Stable Repository file
wget https://raw.githubusercontent.com/Xpra-org/xpra/master/packaging/repos/bookworm/xpra.sources

nano /etc/apt/sources.list.d/xpra.sources and you get the below:
Types: deb
URIs: https://xpra.org
Suites: bookworm
Components: main
Signed-By: /usr/share/keyrings/xpra.asc
Architectures: amd64 arm64 riscv64

with this Debian apt complains:
N: Skipping acquire of configured file 'main/binary-riscv64/Packages' as repository
 'https://xpra.org bookworm InRelease' doesn't support architecture 'riscv64'
 
nano /etc/apt/sources.list.d/xpra.sources and you take out riscv64 as below:
Types: deb
URIs: https://xpra.org
Suites: bookworm
Components: main
Signed-By: /usr/share/keyrings/xpra.asc
Architectures: amd64 arm64

now Debian apt doesn't complain.

all i was saying, is why is this in there if Debian isn't using it and complaining.
there need to be posted somewhere, if this happens do this.

good news is, it works with your guidance.
antix 23.1 64bit runit  full

**Comment by totaam** [comment]
OK thanks.
Now I understand. Done: 3bcf513429eca8a8981c137cfd70f655b5f61a1f
