### ISSUE TITLE
Couldn't kill "xpra attach" after emacs locked up

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#9]
*Issue migrated from trac ticket # 9*

**component:** client | **priority:** major | **resolution:** worksforme

#### 2011-08-18 02:27:40: FredSRichardson created the issue

___
> 
> I think some combination of keys causes this problem.  Emacs wasn't responding, but the odd thing is that I couldn't kill the process with Ctrl-C!
> 
> This is what I got in the console:
> 
> 
> ```
> ^C^CShutting down main-loop
> Traceback (most recent call last):
>   File "/usr/local/lib/python/xpra/protocol.py", line 67, in cb
>     fn(*args, **kwargs)
>   File "/usr/local/lib/python/xpra/protocol.py", line 179, in _handle_read
>     self._read_decoder.add(buf)
>   File "/usr/local/lib/python/xpra/bencode.py", line 35, in add
>     self._buf += bytes
> KeyboardInterrupt
> Ignoring stray packet read after connection allegedly closed ([<object object at 0xb77f04d0>, 'l4:drawi1ei0ei65ei2540ei1360e5:rgb2410363200:geoge'...])
> Ignoring stray packet read after connection allegedly closed ([<object object at 0xb77f04d0>, 'l4:drawi1ei0ei65ei2540ei1360e5:rgb2410363200:geoge'...])
> Ignoring stray packet read after connection allegedly closed ([<object object at 0xb77f04d0>, 'l4:drawi1ei0ei65ei2540ei1360e5:rgb2410363200:geoge'...])
> Ignoring stray packet read after connection allegedly closed ([<object object at 0xb77f04d0>, 'l4:drawi1ei0ei65ei2540ei1360e5:rgb2410363200:geoge'...])
> Ignoring stray packet read after connection allegedly closed ([<object object at 0xb77f04d0>, 'l4:drawi1ei0ei65ei2540ei1360e5:rgb2410363200:geoge'...])
> Ignoring stray packet read after connection allegedly closed ([<object object at 0xb77f04d0>, 'l4:drawi1ei0ei65ei2540ei1360e5:rgb2410363200:geoge'...])
> Ignoring stray packet read after connection allegedly closed ([<object object at 0xb77f04d0>, 'l4:drawi1ei0ei65ei2540ei1360e5:rgb2410363200:geoge'...])
> Ignoring stray packet read after connection allegedly closed ([<object object at 0xb77f04d0>, 'l4:drawi1ei0ei65ei2540ei1360e5:rgb2410363200:geoge'...])
> Ignoring stray packet read after connection allegedly closed ([<object object at 0xb77f04d0>, 'l4:drawi1ei0ei65ei2540ei1360e5:rgb2410363200:geoge'...])
> Ignoring stray packet read after connection allegedly closed ([<object object at 0xb77f04d0>, 'l4:drawi1ei0ei65ei2540ei1360e5:rgb2410363200:geoge'...])
> Ignoring stray packet read after connection allegedly closed ([<object object at 0xb77f04d0>, 'l4:drawi1ei0ei65ei2540ei1360e5:rgb2410363200:geoge'...])
> Ignoring stray packet read after connection allegedly closed ([<object object at 0xb77f04d0>, 'l4:drawi1ei0ei65ei2540ei1360e5:rgb2410363200:geoge'...])
> Ignoring stray packet read after connection allegedly closed ([<object object at 0xb77f04d0>, 'l4:drawi1ei0ei65ei2540ei1360e5:rgb2410363200:geoge'...])
> ```
> 
> 
> Here's what I saw at the end of the log:
> 
> 
> 
> ```
> xkbcomp successfully applied new keymap
> Uh-oh, our size doesn't fit window sizing constraints!
> Uh-oh, our size doesn't fit window sizing constraints!
> Uh-oh, our size doesn't fit window sizing constraints!
> Error parsing property WM_TRANSIENT_FOR (type window); this may be a
>   misbehaving application, or bug in Wimpiggy
>   Data: '\x01\x00\x00\x00'[...?]
> Error parsing property WM_TRANSIENT_FOR (type window); this may be a
>   misbehaving application, or bug in Wimpiggy
>   Data: '\x01\x00\x00\x00'[...?]
> Error reading from connection: [Errno 104] Connection reset by peer
> Error writing to connection: [Errno 32] Broken pipe
> Connection lost
> xpra client disconnected.
> New connection received
> Connection lost
> 
> ```
>

**Comment by totaam** [comment]
Looks like `gtk_main_quit_really()` is called whilst the network queues are still active, I think we should trap `KeyboardInterrupt` and first stop the network thread. However, I am reluctant to make any changes until I can reproduce this issue.

Can you re-produce it easily? (also, I don't think this really matters, but which svn version are you using?)

**Comment by totaam** [comment]
I have moved the 'alt gets stuck' to #13 - I'll try to take a look at this asap, please add details there.

**Comment by totaam** [comment]
Assuming that I am not enough of a monkey to trigger this bug (this would surprise many - nonetheless...), please try running xpra with:
```
-d all
```
and/or stracing it when the next lockup occurs so I can get an idea of what it is doing.

**Comment by totaam** [comment]
No updates, closing.
