### ISSUE TITLE
AF_VSOCK support

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#983]
When using the ProxyServer, or just when connecting to/from a virtual machine in general, it would be very nice to support VSOCK.
One could also envisage running virtual machines without any networking whatsoever (or even the host, and let the VM have the NIC instead), only the VSOCK would be used for display forwarding.

Links:
* [virtio-vsock @ kvm forum 2015](http://events.linuxfoundation.org/sites/events/files/slides/stefanha-kvm-forum-2015.pdf)
* [Add virtio transport for AF_VSOCK](https://lwn.net/Articles/646365/)

Usage:
```
qemu ... -device vhost-vsock-pci,id=vhost-vsock-pci0
```
```
.svm_family = AF_VSOCK,
.svm_cid = VMADDR_CID_HOST,
.svm_port = 1234,
```

Not sure about the kernel + python support.
```
/usr/include/bits/socket.h:#define PF_VSOCK	40	/* vSockets.  */
/usr/include/bits/socket.h:#define AF_VSOCK	PF_VSOCK
```

This may require cythonizing:
```python
>>> s=socket.socket(40)
>>> s.bind((1234, ))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: getsockaddrarg: bad family
>>> 
```

**Comment by totaam** [comment]
Got the answer from the 2.8 release notes [*New device vhost-vsock*](http://wiki.qemu.org/ChangeLog/2.8#virtio)

You should be able to test with the 2.8 RC.
